JetBrains/kotlin

idea/src/org/jetbrains/kotlin/idea/coverage/KotlinCoverageExtension.kt

Always get the .class files corresponding to a source file by looking at the output directory, not by analyzing the source file.

Improve code coverage performance

---

ReadMe.md

I wanted to fix [#KT-6729](https://youtrack.jetbrains.com/issue/KT-6729) "Kotlin Gradle Plugin v0.10.195 + Android Gradle Plugin v1.1.0-rc1 -> build error"
And spent ~1 hour on figuring out build problem of Project Kotlin, finally I decided to go to your TeamCity CI and there I ~~found~~ investigated that it uses JDK 1.6 and when I switched to JDK 1.6 I was able to build Project Kotlin.
So.. I decided to make a notice about it in ReadMe.md.
Here is stacktrace of `ant -f build.xml` with **JDK 1.8**:
````
BUILD FAILED
/Users/artem/projects/open-source/kotlin/build.xml:732: The following error occurred while executing this line:
/Users/artem/projects/open-source/kotlin/build.xml:689: Java returned: 1
at org.apache.tools.ant.taskdefs.Java.execute(Java.java:111)
at …
```

Added info about JDK 1.6 into "Building" section of ReadMe.md

---

compiler/frontend/src/org/jetbrains/kotlin/parsing/JetExpressionParsing.java
grammar/src/expressions.grm
grammar/src/lexical.grm

add some missing elements to Kotlin grammar

---

libraries/build-docs.xml

fix source links in generated API docs

---

idea/src/org/jetbrains/kotlin/idea/findUsages/JetElementDescriptionProvider.kt

provide element description for HighlightUsagesDescriptionLocation

---

idea/src/org/jetbrains/kotlin/idea/KotlinFoldingBuilder.kt
idea/testData/folding/checkCollapse/customRegions.kt
idea/tests/org/jetbrains/kotlin/idea/folding/KotlinFoldingTestGenerated.java

support custom folding regions for Kotlin

---

js/js.libraries/src/generated/org.khronos.webgl.kt
js/js.libraries/src/generated/org.w3c.dom.css.kt
js/js.libraries/src/generated/org.w3c.dom.events.kt
js/js.libraries/src/generated/org.w3c.dom.kt
js/js.libraries/src/generated/org.w3c.dom.svg.kt
js/js.libraries/src/generated/org.w3c.dom.url.kt
js/js.libraries/src/generated/org.w3c.fetch.kt
js/js.libraries/src/generated/org.w3c.files.kt
js/js.libraries/src/generated/org.w3c.notifications.kt
js/js.libraries/src/generated/org.w3c.performance.kt
js/js.libraries/src/generated/org.w3c.workers.kt
js/js.libraries/src/generated/org.w3c.xhr.kt
libraries/tools/idl2k/src/main/kotlin/config.kt
libraries/tools/idl2k/src/main/kotlin/gen.kt
libraries/tools/idl2k/src/main/kotlin/idl.kt
libraries/tools/idl2k/src/main/kotlin/main.kt
libraries/tools/idl2k/src/main/kotlin/model.kt
libraries/tools/idl2k/src/main/kotlin/render.kt
libraries/tools/idl2k/src/main/kotlin/typeMappings.kt
libraries/tools/idl2k/src/main/kotlin/types.kt

First commit to get everything sorted alphabetically to avoid members and classes place change.
The second one is to support static members: both attributes and functions

Idl2k static members

---

ReadMe.md

Fix broken link in README.md

---

compiler/frontend/src/org/jetbrains/kotlin/diagnostics/Errors.java
compiler/frontend/src/org/jetbrains/kotlin/diagnostics/rendering/DefaultErrorMessages.java
compiler/frontend/src/org/jetbrains/kotlin/psi/KtMultiDeclaration.java
compiler/frontend/src/org/jetbrains/kotlin/psi/KtParameter.java
compiler/frontend/src/org/jetbrains/kotlin/psi/KtValVarKeywordProvider.java
compiler/frontend/src/org/jetbrains/kotlin/resolve/ModifiersChecker.java
compiler/frontend/src/org/jetbrains/kotlin/types/expressions/ControlStructureTypingVisitor.java
compiler/testData/diagnostics/tests/controlStructures/valVarLoopParameter.kt
compiler/testData/diagnostics/tests/controlStructures/valVarLoopParameter.txt
compiler/testData/diagnostics/tests/declarationChecks/DataFlowInMultiDeclInFor.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/RemoveValVarFromParameterFix.java
idea/src/org/jetbrains/kotlin/idea/refactoring/rename/AutomaticVariableRenamer.kt
idea/testData/quickfix/variables/removeValVarFromParameter/loopMultiParameter.kt
idea/testData/quickfix/variables/removeValVarFromParameter/loopMultiParameter.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

Add VAL_OR_VAR_ON_LOOP_MULTI_PARAMETER error
Add KtValVarKeywordProvider interface for those who have getValOrVarKeyword method

#KT-6274 Fixed

---

compiler/frontend/src/org/jetbrains/kotlin/psi/KtPsiFactory.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/ConvertExtensionPropertyInitializerToGetterFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/testData/quickfix/properties/extensionPropertyInitializerToGetter/baseCase.kt
idea/testData/quickfix/properties/extensionPropertyInitializerToGetter/baseCase.kt.after
idea/testData/quickfix/properties/extensionPropertyInitializerToGetter/baseCaseWithoutTypeAnnotation.kt
idea/testData/quickfix/properties/extensionPropertyInitializerToGetter/baseCaseWithoutTypeAnnotation.kt.after
idea/testData/quickfix/properties/extensionPropertyInitializerToGetter/dontShowQuickfixOnExistingAccessors.kt
idea/testData/quickfix/properties/extensionPropertyInitializerToGetter/insertGetterBeforeExistingSetter.kt
idea/testData/quickfix/properties/extensionPropertyInitializerToGetter/insertGetterBeforeExistingSetter.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-5115

#KT-5115 Fixed

---

compiler/frontend/src/org/jetbrains/kotlin/parsing/KotlinExpressionParsing.java
compiler/testData/psi/When.kt
compiler/testData/psi/When.txt

https://youtrack.jetbrains.com/issue/KT-1396

#KT-1396 Fixed

---

idea/src/org/jetbrains/kotlin/idea/editor/KotlinSmartEnterHandler.kt
idea/src/org/jetbrains/kotlin/idea/editor/fixers/KotlinCatchBodyFixer.kt
idea/src/org/jetbrains/kotlin/idea/editor/fixers/KotlinCatchParameterFixer.kt
idea/src/org/jetbrains/kotlin/idea/editor/fixers/KotlinFinallyBodyFixer.kt
idea/src/org/jetbrains/kotlin/idea/editor/fixers/KotlinMissingIfBranchFixer.kt
idea/src/org/jetbrains/kotlin/idea/editor/fixers/KotlinTryBodyFixer.kt
idea/tests/org/jetbrains/kotlin/idea/codeInsight/smartEnter/SmartEnterTest.kt

Implement smart enter processors for try, catch (parameters and body) and finally

---

idea/src/org/jetbrains/kotlin/idea/editor/KotlinSmartEnterHandler.kt
idea/src/org/jetbrains/kotlin/idea/editor/fixers/KotlinLastLambdaParameterFixer.kt
idea/tests/org/jetbrains/kotlin/idea/codeInsight/smartEnter/SmartEnterTest.kt

Implement Smart Enter Processor for adding a lambda block

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertToForEachFunctionCallIntention.kt
idea/testData/intentions/convertToForEachFunctionCall/continueToReturnWithLabel.kt
idea/testData/intentions/convertToForEachFunctionCall/continueToReturnWithLabel.kt.after
idea/testData/intentions/convertToForEachFunctionCall/continueToReturnWithoutLabel.kt
idea/testData/intentions/convertToForEachFunctionCall/continueToReturnWithoutLabel.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

ConvertToForEachFunctionCallIntention: convert 'continue' to 'return@forEach'

---

idea/src/org/jetbrains/kotlin/idea/quickfix/LetImplementInterfaceFix.kt
idea/testData/quickfix/typeMismatch/letObjectImplementAdditionalInterface.kt
idea/testData/quickfix/typeMismatch/letObjectImplementAdditionalInterface.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

Fix let implement quickfix label for object expressions

---

idea/src/org/jetbrains/kotlin/idea/quickfix/LetImplementInterfaceFix.kt

Let Implement Quickfix: Launch "Implement Members" dialog after applying

---

idea/src/org/jetbrains/kotlin/idea/quickfix/AddCrossinlineFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/testData/quickfix/addCrossinline/basic.kt
idea/testData/quickfix/addCrossinline/basic.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

Add QuickFix to add 'crossinline' to parameter

---

core/descriptors/src/org/jetbrains/kotlin/builtins/KotlinBuiltIns.java
idea/src/org/jetbrains/kotlin/idea/quickfix/AddToStringFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixFactoryForTypeMismatchError.kt
idea/testData/quickfix/toString/notNullableExpectedNullable.kt
idea/testData/quickfix/toString/notNullableExpectedNullable.kt.after
idea/testData/quickfix/toString/nullableExpectedNotNullable.kt
idea/testData/quickfix/toString/nullableExpectedNotNullable.kt.after
idea/testData/quickfix/toString/nullableExpectedNullable.kt
idea/testData/quickfix/toString/nullableExpectedNullable.kt.after
idea/testData/quickfix/toString/simple.kt
idea/testData/quickfix/toString/simple.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

Add quickfix to add 'toString'

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ConvertExtensionToFunctionTypeFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/testData/quickfix/superTypeIsExtensionType/typeWith1Argument.kt
idea/testData/quickfix/superTypeIsExtensionType/typeWith1Argument.kt.after
idea/testData/quickfix/superTypeIsExtensionType/typeWithNoArgument.kt
idea/testData/quickfix/superTypeIsExtensionType/typeWithNoArgument.kt.after
idea/testData/quickfix/superTypeIsExtensionType/typeWithTypeArgument.kt
idea/testData/quickfix/superTypeIsExtensionType/typeWithTypeArgument.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

Quick fix for SUPERTYPE_IS_EXTENSION_FUNCTION_TYPE

---

idea/src/org/jetbrains/kotlin/idea/quickfix/AddRunToLambdaFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/testData/quickfix/addRunBeforeLambda/basic.kt
idea/testData/quickfix/addRunBeforeLambda/basic.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

Add quickfix for UNUSED_LAMBDA_EXPRESSION

---

compiler/frontend/src/org/jetbrains/kotlin/psi/KtPsiUtil.java
idea/resources/inspectionDescriptions/RedundantlIf.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/inspections/RedundantIfInspection.kt
idea/testData/inspections/redundantIf/inspectionData/expected.xml
idea/testData/inspections/redundantIf/inspectionData/inspections.test
idea/testData/inspections/redundantIf/redundantIf.kt
idea/testData/quickfix/redundantIf/.inspection
idea/testData/quickfix/redundantIf/simple.kt
idea/testData/quickfix/redundantIf/simplet.kt.after
idea/tests/org/jetbrains/kotlin/idea/codeInsight/InspectionTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

KT-12019 Highlighting of redundant 'if' statements

---

idea/src/org/jetbrains/kotlin/idea/quickfix/AddCrossinlineFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/testData/quickfix/addNoinline/basic.kt
idea/testData/quickfix/addNoinline/basic.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

Add quickfix for "Illegal usage of inline parameter"

---

idea/src/org/jetbrains/kotlin/idea/KotlinQuickDocumentationProvider.kt
idea/testData/editor/quickDoc/AtImplicitLambdaParameter.kt
idea/tests/org/jetbrains/kotlin/idea/editor/quickDoc/QuickDocProviderTestGenerated.java

Show quick doc for implicit lambda parameter 'it'

---

idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/WrongLongSuffixFix.kt
idea/testData/quickfix/wrongLongSuffix/simple.kt
idea/testData/quickfix/wrongLongSuffix/simple.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

Implement quickfix for wrong long suffix

---

idea/resources/fileTemplates/code/New Kotlin Function Body.kt.ft

Signed-off-by: Laszlo Hornyak <laszlo.hornyak@gmail.com>

new function body changed to call the shorter TODO() function

---

idea/src/org/jetbrains/kotlin/idea/quickfix/AddConstModifierFix.kt
idea/testData/intentions/addConstModifier/inapplicableToConst.kt
idea/testData/intentions/addConstModifier/inapplicableToOverride.kt
idea/testData/intentions/addConstModifier/removeJvmField.kt
idea/testData/intentions/addConstModifier/removeJvmField.kt.after
idea/testData/intentions/addConstModifier/removeJvmStatic.kt
idea/testData/intentions/addConstModifier/removeJvmStatic.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

AddConstModifierIntention: handle more edge cases

---

idea/idea-completion/src/org/jetbrains/kotlin/idea/completion/KeywordCompletion.kt
idea/idea-completion/testData/keywords/AfterClassProperty.kt
idea/idea-completion/testData/keywords/AfterClasses.kt
idea/idea-completion/testData/keywords/AfterFuns.kt
idea/idea-completion/testData/keywords/AfterTryCatch.kt
idea/idea-completion/testData/keywords/AfterTryFinally.kt
idea/idea-completion/testData/keywords/GlobalPropertyAccessors.kt
idea/idea-completion/testData/keywords/InAnnotationClassScope.kt
idea/idea-completion/testData/keywords/InClassBeforeFun.kt
idea/idea-completion/testData/keywords/InClassScope.kt
idea/idea-completion/testData/keywords/InCodeBlock.kt
idea/idea-completion/testData/keywords/InEnumScope2.kt
idea/idea-completion/testData/keywords/InInterfaceScope.kt
idea/idea-completion/testData/keywords/InObjectScope.kt
idea/idea-completion/testData/keywords/InTopScopeAfterPackage.kt
idea/idea-completion/testData/keywords/PropertyAccessors.kt
idea/idea-completion/testData/keywords/PropertyAccessors2.kt
idea/idea-completion/testData/keywords/PropertySetter.kt
idea/idea-completion/testData/keywords/TopScope.kt

Fix Completion: keyword 'typealias' is not suggested

---

idea/resources/inspectionDescriptions/RemoveSingleExpressionStringTemplate.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/intentions/RemoveSingleExpressionStringTemplateIntention.kt
idea/testData/intentions/removeSingleExpressionStringTemplate/.intention
idea/testData/intentions/removeSingleExpressionStringTemplate/emptyString.kt
idea/testData/intentions/removeSingleExpressionStringTemplate/multipleStringTemplate.kt
idea/testData/intentions/removeSingleExpressionStringTemplate/singleExpressionStringTemplate.kt
idea/testData/intentions/removeSingleExpressionStringTemplate/singleExpressionStringTemplate.kt.after
idea/testData/intentions/removeSingleExpressionStringTemplate/singleExpressionStringTemplateWithMethodCall.kt
idea/testData/intentions/removeSingleExpressionStringTemplate/singleExpressionStringTemplateWithMethodCall.kt.after
idea/testData/intentions/removeSingleExpressionStringTemplate/singleExpressionStringTemplateWithNonStringType.kt
idea/testData/intentions/removeSingleExpressionStringTemplate/singleExpressionStringTemplateWithNonStringType.kt.after
idea/testData/intentions/removeSingleExpressionStringTemplate/stringTemplateWithText.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

KT-13113 Add inspection to detect single-expression string template

---

idea/resources/inspectionDescriptions/RemoveToStringInStringTemplate.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/inspections/RemoveToStringInStringTemplateInspection.kt
idea/testData/inspections/removeToStringInStringTemplate/inspectionData/expected.xml
idea/testData/inspections/removeToStringInStringTemplate/inspectionData/inspections.test
idea/testData/inspections/removeToStringInStringTemplate/test.kt
idea/testData/quickfix/removeToStringInStringTemplate/.inspection
idea/testData/quickfix/removeToStringInStringTemplate/simple.kt
idea/testData/quickfix/removeToStringInStringTemplate/simple.kt.after
idea/tests/org/jetbrains/kotlin/idea/codeInsight/InspectionTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

Highlight use of toString() inside string interpolation as redundant

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertToStringTemplateIntention.kt
idea/testData/intentions/convertToStringTemplate/appendsLiteralToVariableOmittingBraces.kt
idea/testData/intentions/convertToStringTemplate/appendsLiteralToVariableOmittingBraces.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

KT-13336 Fix problem with appending literal to variable omitting braces

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertFunctionToPropertyIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPropertyInitializerToGetterIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPropertyToFunctionIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/CreateKotlinSubClassIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/IntroduceBackingPropertyIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/ReplaceSubstringWithSubstringBeforeAfterIntentions.kt
idea/src/org/jetbrains/kotlin/idea/intentions/ReplaceSubstringWithTakeIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/SimplifyForIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/SpecifyTypeExplicitlyIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/Utils.kt
idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/IfToWhenIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/conventionNameCalls/ReplaceCallWithBinaryOperatorIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/conventionNameCalls/ReplaceContainsIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/loopToCallChain/matchAndConvert.kt
idea/src/org/jetbrains/kotlin/idea/intentions/loopToCallChain/utils.kt
idea/testData/intentions/conventionNameCalls/replaceCallWithBinaryOperator/equalsExtensionFunction.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

Fix "Can be replaced with comparison" false positive if extension method called 'equals' is used

---

idea/resources/inspectionDescriptions/RemoveEmptyParenthesesFromLambdaCall.html
idea/resources/intentionDescriptions/RemoveEmptyParenthesesFromLambdaCallIntention/after.kt.template
idea/resources/intentionDescriptions/RemoveEmptyParenthesesFromLambdaCallIntention/before.kt.template
idea/resources/intentionDescriptions/RemoveEmptyParenthesesFromLambdaCallIntention/description.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/intentions/RemoveEmptyParenthesesFromLambdaCallIntention.kt
idea/testData/intentions/removeEmptyParenthesesFromLambdaCall/.intention
idea/testData/intentions/removeEmptyParenthesesFromLambdaCall/simple.kt
idea/testData/intentions/removeEmptyParenthesesFromLambdaCall/simple.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

Add intention+inspection to remove empty parentheses from method call with single lambda parameter

---

idea/resources/inspectionDescriptions/ReplaceArrayEqualityOpWithArraysEquals.html
idea/resources/intentionDescriptions/ReplaceArrayEqualityOpWithArraysEqualsIntention/after.kt.template
idea/resources/intentionDescriptions/ReplaceArrayEqualityOpWithArraysEqualsIntention/before.kt.template
idea/resources/intentionDescriptions/ReplaceArrayEqualityOpWithArraysEqualsIntention/description.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/intentions/ReplaceArrayEqualityOpWithArraysEqualsIntention.kt
idea/testData/inspections/replaceArrayEqualityOpWithArraysEquals/inspectionData/expected.xml
idea/testData/inspections/replaceArrayEqualityOpWithArraysEquals/inspectionData/inspections.test
idea/testData/inspections/replaceArrayEqualityOpWithArraysEquals/test.kt
idea/testData/intentions/replaceArrayEqualityOpWithArraysEquals/.intention
idea/testData/intentions/replaceArrayEqualityOpWithArraysEquals/arrayAndOtherTypeEQEQ.kt
idea/testData/intentions/replaceArrayEqualityOpWithArraysEquals/arrayEQEQ.kt
idea/testData/intentions/replaceArrayEqualityOpWithArraysEquals/arrayEQEQ.kt.after
idea/tests/org/jetbrains/kotlin/idea/codeInsight/InspectionTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

KT-13384 Inspection to warn on using == with array types

---

idea/src/org/jetbrains/kotlin/idea/KotlinFoldingBuilder.kt
idea/testData/folding/checkCollapse/headerKDoc.kt
idea/testData/folding/checkCollapse/headerMultilineComment.kt
idea/testData/folding/noCollapse/kdocComments.kt
idea/testData/folding/noCollapse/multilineComments.kt

#KT-4519 Fixed
https://youtrack.jetbrains.com/issue/KT-4519

KT-4519 Show first line with content of block comment when collapsed

---

compiler/frontend/src/org/jetbrains/kotlin/diagnostics/Errors.java
compiler/frontend/src/org/jetbrains/kotlin/diagnostics/rendering/DefaultErrorMessages.java
compiler/frontend/src/org/jetbrains/kotlin/types/expressions/BasicExpressionTypingVisitor.java
compiler/testData/diagnostics/tests/platformTypes/nullabilityWarnings/uselessElvisRightIsNull.kt
compiler/testData/diagnostics/tests/platformTypes/nullabilityWarnings/uselessElvisRightIsNull.txt
compiler/tests/org/jetbrains/kotlin/checkers/DiagnosticsTestGenerated.java
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt

#KT-13521 Fixed
https://youtrack.jetbrains.com/issue/KT-13521

KT-13521 Warning right part of "expression ?: null" is useless

---

idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/editor/wordSelection/KotlinBracketsSelectioner.kt
idea/testData/wordSelection/ArrayBrackets/0.kt
idea/testData/wordSelection/ArrayBrackets/1.kt
idea/testData/wordSelection/ArrayBrackets/2.kt
idea/testData/wordSelection/ArrayBrackets/3.kt
idea/tests/org/jetbrains/kotlin/idea/WordSelectionTest.java

#KT-13693 Fixed
https://youtrack.jetbrains.com/issue/KT-13693

KT-13693 Expand selection for array brackets

---

idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/RemoveFinalUpperBoundFix.kt
idea/testData/quickfix/removeFinalUpperBound/basic.kt
idea/testData/quickfix/removeFinalUpperBound/basic.kt.after
idea/testData/quickfix/removeFinalUpperBound/function.kt
idea/testData/quickfix/removeFinalUpperBound/function.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

#KT-13674 Fixed
https://youtrack.jetbrains.com/issue/KT-13674

KT-13674 Add quickfix to remove the final upper bound

---

j2k/src/org/jetbrains/kotlin/j2k/ClassBodyConverter.kt
j2k/src/org/jetbrains/kotlin/j2k/Converter.kt
j2k/src/org/jetbrains/kotlin/j2k/ast/Modifier.kt
j2k/src/org/jetbrains/kotlin/j2k/propertyDetection.kt
j2k/testData/fileOrElement/function/nativeMethods.java
j2k/testData/fileOrElement/function/nativeMethods.kt
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterForWebDemoTestGenerated.java
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterSingleFileTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-11990

KT-11990 J2K `native` to `external` conversion

---

j2k/src/org/jetbrains/kotlin/j2k/ExpressionConverter.kt
j2k/testData/fileOrElement/anonymousClass/kt-13146.java
j2k/testData/fileOrElement/anonymousClass/kt-13146.kt
j2k/testData/fileOrElement/anonymousClass/localSelfReference.java
j2k/testData/fileOrElement/anonymousClass/localSelfReference.kt
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterForWebDemoTestGenerated.java
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterSingleFileTestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/TypeAliasesTestsGenerated.java

https://youtrack.jetbrains.com/issue/KT-13146
This fix is only small workaround of a big problem

KT-13146 J2K recursion while converting self-referenced anonymous functions

---

idea/resources/inspectionDescriptions/RemoveEmptyClassBody.html
idea/resources/intentionDescriptions/RemoveEmptyClassBodyIntention/after.kt.template
idea/resources/intentionDescriptions/RemoveEmptyClassBodyIntention/before.kt.template
idea/resources/intentionDescriptions/RemoveEmptyClassBodyIntention/description.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/intentions/RemoveEmptyClassBodyIntention.kt
idea/testData/intentions/removeEmptyClassBody/.intention
idea/testData/intentions/removeEmptyClassBody/emptyClass.kt
idea/testData/intentions/removeEmptyClassBody/emptyClass.kt.after
idea/testData/intentions/removeEmptyClassBody/emptyDataClass.kt
idea/testData/intentions/removeEmptyClassBody/emptyDataClass.kt.after
idea/testData/intentions/removeEmptyClassBody/emptyInterface.kt
idea/testData/intentions/removeEmptyClassBody/emptyInterface.kt.after
idea/testData/intentions/removeEmptyClassBody/noneEmptyClass.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

#KT-14241
https://youtrack.jetbrains.com/issue/KT-14241

KT-14241 Add Intention + Inspection to remove empty class body

---

j2k/src/org/jetbrains/kotlin/j2k/ExpressionConverter.kt
j2k/testData/fileOrElement/classExpression/complexExample.java
j2k/testData/fileOrElement/classExpression/complexExample.kt
j2k/testData/fileOrElement/classExpression/primitivesAndArrays.java
j2k/testData/fileOrElement/classExpression/primitivesAndArrays.kt

#KT-13550 Fixed
https://youtrack.jetbrains.com/issue/KT-13550

KT-13550  Fix Boolean.TYPE does not compile

---

idea/src/org/jetbrains/kotlin/idea/intentions/RemoveEmptyClassBodyIntention.kt
idea/testData/intentions/removeEmptyClassBody/anonymousInterfaceObject.kt
idea/testData/intentions/removeEmptyClassBody/anonymousObject.kt
idea/testData/intentions/removeEmptyClassBody/innerClass.kt
idea/testData/intentions/removeEmptyClassBody/innerClass.kt.after
idea/testData/intentions/removeEmptyClassBody/nestedAnonymous.kt
idea/testData/intentions/removeEmptyClassBody/object.kt
idea/testData/intentions/removeEmptyClassBody/object.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

#KT-14329 Fixed
https://youtrack.jetbrains.com/issue/KT-14329

KT-14329  Do not report inspection "Remove empty class body" for anonymous objects

---

js/js.translator/testData/maps.js

KT-14194 JS: HashMap.putAll shouldn't call getKey/getValue

---

idea/formatter/src/org/jetbrains/kotlin/idea/formatter/kotlinSpacingRules.kt
idea/testData/formatter/By.after.kt
idea/testData/formatter/By.kt
idea/tests/org/jetbrains/kotlin/formatter/FormatterTestGenerated.java

Format spaces around by keyword

---

idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createCallable/CreateBinaryOperationActionFactory.kt
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/greaterOrEqualOnUserType.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/inOnUserType.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/lessOnUserType.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/notInOnUserType.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/plusAssignOnUserType.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/plusExtraArgs.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/plusForAssignmentOnUserType.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/plusMissingArgs.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/plusOnLibType.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/plusOnUserType.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/plusOnUserTypeWithTypeParams.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/typeMismatch.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/whenInOnUserType.kt.after
idea/testData/quickfix/createFromUsage/createFunction/binaryOperations/whenNotInOnUserType.kt.after

Fix Quickfix for missing operator adds infix modifier to created function

---

compiler/frontend/src/org/jetbrains/kotlin/psi/KtClass.kt
compiler/frontend/src/org/jetbrains/kotlin/psi/KtPsiFactory.kt
idea/idea-android/src/org/jetbrains/kotlin/android/quickfix/AndroidQuickFixRegistrar.kt
idea/idea-android/src/org/jetbrains/kotlin/android/quickfix/KotlinAndroidViewConstructorFix.kt
idea/idea-android/tests/org/jetbrains/kotlin/android/quickfixes/AndroidQuickFixMultiFileTestGenerated.java
idea/src/META-INF/android.xml
idea/testData/android/quickfix/viewConstructor/indirect.after.kt
idea/testData/android/quickfix/viewConstructor/indirect.before.Dependency1.kt
idea/testData/android/quickfix/viewConstructor/indirect.before.Dependency2.kt
idea/testData/android/quickfix/viewConstructor/indirect.before.Dependency3.kt
idea/testData/android/quickfix/viewConstructor/indirect.before.Main.kt
idea/testData/android/quickfix/viewConstructor/simple.after.kt
idea/testData/android/quickfix/viewConstructor/simple.before.Dependency1.kt
idea/testData/android/quickfix/viewConstructor/simple.before.Dependency2.kt
idea/testData/android/quickfix/viewConstructor/simple.before.Dependency3.kt
idea/testData/android/quickfix/viewConstructor/simple.before.Main.kt

Fixes #KT-15150
https://youtrack.jetbrains.com/issue/KT-15150

Android: Add intention to generate View constructor convention

---

idea/src/org/jetbrains/kotlin/idea/editor/KotlinSmartEnterHandler.kt
idea/src/org/jetbrains/kotlin/idea/editor/fixers/KotlinClassBodyFixer.kt
idea/tests/org/jetbrains/kotlin/idea/codeInsight/smartEnter/SmartEnterTest.kt

Implement Smart Enter handler for class body

---

idea/resources/intentionDescriptions/MergeIfsIntention/after.kt.template
idea/resources/intentionDescriptions/MergeIfsIntention/before.kt.template
idea/resources/intentionDescriptions/MergeIfsIntention/description.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/intentions/MergeIfsIntention.kt
idea/src/org/jetbrains/kotlin/idea/joinLines/JoinBlockIntoSingleStatementHandler.kt
idea/testData/intentions/mergeIfs/.intention
idea/testData/intentions/mergeIfs/comments.kt
idea/testData/intentions/mergeIfs/comments.kt.after
idea/testData/intentions/mergeIfs/else1.kt
idea/testData/intentions/mergeIfs/else2.kt
idea/testData/intentions/mergeIfs/expression.kt
idea/testData/intentions/mergeIfs/expression.kt.after
idea/testData/intentions/mergeIfs/simple.kt
idea/testData/intentions/mergeIfs/simple.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-9912

Add Merge ifs intention

---

idea/src/org/jetbrains/kotlin/idea/refactoring/introduce/extractionEngine/extractableAnalysisUtil.kt
idea/src/org/jetbrains/kotlin/idea/refactoring/introduce/extractionEngine/inferParameterInfo.kt
idea/testData/refactoring/extractFunction/controlFlow/outputValues/outputValueWithReturn.kt
idea/testData/refactoring/extractFunction/controlFlow/outputValues/outputValueWithReturn.kt.after
idea/testData/refactoring/extractFunction/controlFlow/outputValues/outputValueWithSingleLineExpression.kt
idea/testData/refactoring/extractFunction/controlFlow/outputValues/outputValueWithSingleLineExpression.kt.after
idea/testData/refactoring/extractFunction/controlFlow/outputValues/pair.kt
idea/testData/refactoring/extractFunction/controlFlow/outputValues/pair.kt.after
idea/testData/refactoring/extractFunction/controlFlow/outputValues/pairWithNameClash.kt
idea/testData/refactoring/extractFunction/controlFlow/outputValues/pairWithNameClash.kt.after
idea/testData/refactoring/extractFunction/controlFlow/outputValues/singleOutputValue.kt
idea/testData/refactoring/extractFunction/controlFlow/outputValues/singleOutputValue.kt.after
idea/testData/refactoring/extractFunction/controlFlow/outputValues/tooManyOutputValuesAsList.kt
idea/testData/refactoring/extractFunction/controlFlow/outputValues/tooManyOutputValuesAsList.kt.after
idea/testData/refactoring/extractFunction/controlFlow/outputValues/triple.kt
idea/testData/refactoring/extractFunction/controlFlow/outputValues/triple.kt.after
idea/testData/refactoring/extractFunction/controlFlow/outputValues/usedAndUnusedOutputValues.kt
idea/testData/refactoring/extractFunction/controlFlow/outputValues/usedAndUnusedOutputValues.kt.after
idea/testData/refactoring/extractFunction/parameters/candidateTypes/nonNullableTypes.kt
idea/testData/refactoring/extractFunction/parameters/candidateTypes/nonNullableTypes.kt.after
idea/testData/refactoring/extractFunction/parameters/candidateTypes/nullableTypes.kt
idea/testData/refactoring/extractFunction/parameters/candidateTypes/nullableTypes.kt.after
idea/testData/refactoring/extractFunction/parameters/capturedFunctions/localExtensionFun.kt
idea/testData/refactoring/extractFunction/parameters/capturedFunctions/localExtensionFun.kt.after
idea/testData/refactoring/extractFunction/parameters/capturedFunctions/localExtensionFunChainedCalls.kt
idea/testData/refactoring/extractFunction/parameters/capturedFunctions/localExtensionFunChainedCalls.kt.after
idea/testData/refactoring/extractFunction/parameters/capturedFunctions/localExtensionFunInfixCall.kt
idea/testData/refactoring/extractFunction/parameters/capturedFunctions/localExtensionFunInfixCall.kt.after
idea/testData/refactoring/extractFunction/parameters/misc/usagesInCallArgs.kt
idea/testData/refactoring/extractFunction/parameters/misc/usagesInCallArgs.kt.after

Extract method refactoring should order parameters by first usage

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantSemicolonInspection.kt
idea/testData/inspections/redundantSemicolon/BeforeEmptyImports.kt
idea/testData/inspections/redundantSemicolon/inspectionData/expected.xml

Detect redundant semicolon before empty import list

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPrimaryConstructorToSecondaryIntention.kt
idea/testData/intentions/convertPrimaryConstructorToSecondary/dataClass.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

Convert to secondary constructor is not applicable to data classes

---

idea/resources/intentionDescriptions/ValToObjectIntention/after.kt.template
idea/resources/intentionDescriptions/ValToObjectIntention/before.kt.template
idea/resources/intentionDescriptions/ValToObjectIntention/description.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/intentions/ValToObjectIntention.kt
idea/testData/intentions/valToObject/.intention
idea/testData/intentions/valToObject/annotations.kt
idea/testData/intentions/valToObject/callableReference.kt
idea/testData/intentions/valToObject/getter.kt
idea/testData/intentions/valToObject/nonTopLevel.kt
idea/testData/intentions/valToObject/simple.kt
idea/testData/intentions/valToObject/simple.kt.after
idea/testData/intentions/valToObject/var.kt
idea/testData/intentions/valToObject/withJavaUsage.1.java
idea/testData/intentions/valToObject/withJavaUsage.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-14137

Add intention to convert top level val with object expression to object declaration

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertTwoComparisonsToRangeCheckIntention.kt
idea/testData/intentions/convertTwoComparisonsToRangeCheck/charInt.kt
idea/testData/intentions/convertTwoComparisonsToRangeCheck/compareToComparableSameType.kt
idea/testData/intentions/convertTwoComparisonsToRangeCheck/compareToComparableSameType.kt.after
idea/testData/intentions/convertTwoComparisonsToRangeCheck/compareToDifferentTypes.kt
idea/testData/intentions/convertTwoComparisonsToRangeCheck/compareToSameType.kt
idea/testData/intentions/convertTwoComparisonsToRangeCheck/doubleToInt1.kt
idea/testData/intentions/convertTwoComparisonsToRangeCheck/doubleToInt1.kt.after
idea/testData/intentions/convertTwoComparisonsToRangeCheck/doubleToInt2.kt
idea/testData/intentions/convertTwoComparisonsToRangeCheck/doubleToInt2.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

Stricter type checks in 'convert to range' intention

---

idea/src/org/jetbrains/kotlin/idea/editor/fixers/KotlinClassBodyFixer.kt
idea/tests/org/jetbrains/kotlin/idea/codeInsight/smartEnter/SmartEnterTest.kt

Add Smart Enter processor for object expessions

---

j2k/src/org/jetbrains/kotlin/j2k/ExpressionConverter.kt
j2k/testData/fileOrElement/strings/escapedBackslash.java
j2k/testData/fileOrElement/strings/escapedBackslash.kt
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterForWebDemoTestGenerated.java
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterSingleFileTestGenerated.java

Detect escaped backslashes

---

j2k/src/org/jetbrains/kotlin/j2k/SwitchConverter.kt
j2k/testData/fileOrElement/switch/nestedIf.java
j2k/testData/fileOrElement/switch/nestedIf.kt
j2k/testData/fileOrElement/switch/nestedIfFallback.java
j2k/testData/fileOrElement/switch/nestedIfFallback.kt
j2k/testData/fileOrElement/switch/nestedSwitch.java
j2k/testData/fileOrElement/switch/nestedSwitch.kt
j2k/testData/fileOrElement/switch/nestedSwitchFallback.java
j2k/testData/fileOrElement/switch/nestedSwitchFallback.kt
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterForWebDemoTestGenerated.java
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterSingleFileTestGenerated.java

Take control flow into account for checking fall-through switch branches

---

idea/src/org/jetbrains/kotlin/idea/intentions/DeprecatedCallableAddReplaceWithIntention.kt
idea/testData/intentions/deprecatedCallableAddReplaceWith/DeprecationLevelHidden.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

Don't suggest adding replaceWith in DeprecationLevel.HIDDEN

---

spec-docs/NameResolution.adoc
spec-docs/annotation-arguments.md
spec-docs/enums.md
spec-docs/function-types.md
spec-docs/secondary-constructors.md

I've made few minor typo and grammatical corrections in spec-docs.

Minor corrections in spec-docs

---

compiler/compiler-runner/src/org/jetbrains/kotlin/compilerRunner/CompilerOutputParser.kt

Fixed a minor spelling mistake in a comment

Fixed a typo in a comment

---

idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/intentions/KotlinCommonIntentionActionsFactory.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/CommonIntentionActionsTest.kt

`createAddMethodAction` and `createAddBeanPropertyActions` common intention actions added

KotlinCommonIntentionActionsFactory extensions for IDEA-85507 and KT-11906

---

ReadMe.md

Fix Git CLI typo.

---

ultimate/src/org/jetbrains/kotlin/idea/spring/generate/GenerateKotlinAutowiredDependencyAction.kt
ultimate/src/org/jetbrains/kotlin/idea/spring/generate/GenerateKotlinSpringBeanXmlDependencyAction.kt
ultimate/src/org/jetbrains/kotlin/idea/spring/generate/generateAutowiredDependenciesUtils.kt
ultimate/src/org/jetbrains/kotlin/idea/spring/generate/generateDependenciesUtils.kt

Spring dependency-generations actions: `runWriteAction` moved to the proper place

---

compiler/cli/src/org/jetbrains/kotlin/cli/jvm/K2JVMCompiler.kt
compiler/testData/cli/jvm/jdkPathDoesNotExist.args
compiler/testData/cli/jvm/jdkPathDoesNotExist.out
compiler/tests/org/jetbrains/kotlin/cli/CliTestGenerated.java

Fix https://youtrack.jetbrains.com/issue/KT-18794

Improve a reported message if -jdk-home path does not exist.

---

compiler/frontend/src/org/jetbrains/kotlin/psi/FindDocComment.kt
idea/testData/kdoc/finder/Annotated.kt
idea/tests/org/jetbrains/kotlin/idea/kdoc/KDocFinderTest.kt

https://youtrack.jetbrains.com/issue/KT-18501

KT-18501: Fix to find KDoc even if KDoc is in ModifierList

---

.idea/libraries/intellij_core.xml
compiler/tests-common/tests-common.iml

Add missing dependencies

---

idea/src/org/jetbrains/kotlin/idea/intentions/AddValVarToConstructorParameterAction.kt
idea/testData/quickfix/addValVar/addValAfterVarArg.kt
idea/testData/quickfix/addValVar/addValAfterVarArg.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

Fix of https://youtrack.jetbrains.com/issue/KT-18979

KT-18979 Add val to proper place for 'Add val/var' intent

---

idea/resources/intentionDescriptions/ConvertSealedClassToEnumIntention/before.kt.template

https://youtrack.jetbrains.com/issue/KT-18722

KT-18722 Correct "before" sample in description for intention Convert to enum class

---

idea/src/org/jetbrains/kotlin/idea/intentions/KotlinCommonIntentionActionsFactory.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/CommonIntentionActionsTest.kt

`KotlinCommonIntentionActionsFactory` is able to remove constructors parameters

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeToPropertyAccessFix.kt
idea/testData/quickfix/variables/changeToPropertyAccess/enumEntryCall.kt
idea/testData/quickfix/variables/changeToPropertyAccess/enumEntryCall.kt.after
idea/testData/quickfix/variables/changeToPropertyAccess/objectCall.kt
idea/testData/quickfix/variables/changeToPropertyAccess/objectCall.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-13870

KT-13870 Wrong caption "Change to property access" for Quick Fix to convert class instantiation to object reference

---

idea/resources/intentionDescriptions/ConvertClassToSealedClassIntention/after.kt.template
idea/resources/intentionDescriptions/ConvertClassToSealedClassIntention/before.kt.template
idea/resources/intentionDescriptions/ConvertClassToSealedClassIntention/description.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/intentions/ConvertClassToSealedClassIntention.kt
idea/testData/intentions/convertClassToSealedClass/.intention
idea/testData/intentions/convertClassToSealedClass/abstract.kt
idea/testData/intentions/convertClassToSealedClass/abstract.kt.after
idea/testData/intentions/convertClassToSealedClass/noConstructor.kt
idea/testData/intentions/convertClassToSealedClass/notOpenAndAbstract.kt
idea/testData/intentions/convertClassToSealedClass/notPrivatePrimaryConstructor.kt
idea/testData/intentions/convertClassToSealedClass/notPrivateSecondaryConstructor.kt
idea/testData/intentions/convertClassToSealedClass/onlySecondaryConstructor.kt
idea/testData/intentions/convertClassToSealedClass/onlySecondaryConstructor.kt.after
idea/testData/intentions/convertClassToSealedClass/primaryConstructor.kt
idea/testData/intentions/convertClassToSealedClass/primaryConstructor.kt.after
idea/testData/intentions/convertClassToSealedClass/primaryConstructorWithAnnotation.kt
idea/testData/intentions/convertClassToSealedClass/primaryConstructorWithValueParameter.kt
idea/testData/intentions/convertClassToSealedClass/primaryConstructorWithValueParameter.kt.after
idea/testData/intentions/convertClassToSealedClass/secondaryConstructor.kt
idea/testData/intentions/convertClassToSealedClass/secondaryConstructor.kt.after
idea/testData/intentions/convertClassToSealedClass/secondaryConstructorWithAnnotation.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-12504

KT-12504 Intention to make open class with only private constructors sealed

---

compiler/frontend/src/org/jetbrains/kotlin/idea/MainFunctionDetector.kt
idea/resources/intentionDescriptions/AddJvmStaticIntention/after.kt.template
idea/resources/intentionDescriptions/AddJvmStaticIntention/before.kt.template
idea/resources/intentionDescriptions/AddJvmStaticIntention/description.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/intentions/AddJvmStaticIntention.kt
idea/testData/intentions/addJvmStatic/.intention
idea/testData/intentions/addJvmStatic/hasJvmStatic.kt
idea/testData/intentions/addJvmStatic/inAnonymousObject.kt
idea/testData/intentions/addJvmStatic/inClass.kt
idea/testData/intentions/addJvmStatic/inCompanionObject.kt
idea/testData/intentions/addJvmStatic/inCompanionObject.kt.after
idea/testData/intentions/addJvmStatic/inObjedct.kt
idea/testData/intentions/addJvmStatic/inObjedct.kt.after
idea/testData/intentions/addJvmStatic/inTopLevel.kt
idea/testData/intentions/addJvmStatic/mainJvmName.kt
idea/testData/intentions/addJvmStatic/mainJvmName.kt.after
idea/testData/intentions/addJvmStatic/notMainJvmName.kt
idea/testData/intentions/addJvmStatic/notMainMethod.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-12195

KT-12195 Quickfix @JvmStatic on main() method in an object

---

idea/resources/inspectionDescriptions/WhenWithOnlyElse.html
idea/src/META-INF/plugin.xml
idea/src/org/jetbrains/kotlin/idea/inspections/ConstantConditionIfInspection.kt
idea/src/org/jetbrains/kotlin/idea/inspections/WhenWithOnlyElseInspection.kt
idea/testData/inspectionsLocal/whenWithOnlyElse/.inspection
idea/testData/inspectionsLocal/whenWithOnlyElse/complexExpression.kt
idea/testData/inspectionsLocal/whenWithOnlyElse/complexExpression.kt.after
idea/testData/inspectionsLocal/whenWithOnlyElse/hasOtherBranches.kt
idea/testData/inspectionsLocal/whenWithOnlyElse/notExpression.kt
idea/testData/inspectionsLocal/whenWithOnlyElse/notExpression.kt.after
idea/testData/inspectionsLocal/whenWithOnlyElse/simpleExpression.kt
idea/testData/inspectionsLocal/whenWithOnlyElse/simpleExpression.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

Add inspection for when with only else

---

compiler/frontend/src/org/jetbrains/kotlin/idea/MainFunctionDetector.kt
idea/src/org/jetbrains/kotlin/idea/inspections/UnusedReceiverParameterInspection.kt

KT-18083: Detect valid extension main functions

---

compiler/frontend/src/org/jetbrains/kotlin/psi/KtPsiFactory.kt
idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPropertyInitializerToGetterIntention.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/testData/quickfix/convertPropertyInitializerToGetter/val.kt
idea/testData/quickfix/convertPropertyInitializerToGetter/val.kt.after
idea/testData/quickfix/convertPropertyInitializerToGetter/var.kt
idea/testData/quickfix/convertPropertyInitializerToGetter/var.kt.after
idea/testData/quickfix/convertPropertyInitializerToGetter/varWithSetter.kt
idea/testData/quickfix/convertPropertyInitializerToGetter/varWithSetter.kt.after
idea/testData/quickfix/properties/extensionPropertyInitializerToGetter/baseCaseVar.kt
idea/testData/quickfix/properties/extensionPropertyInitializerToGetter/baseCaseVar.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-19126

KT-19126 Add replace property initializer with getter in interfaces

---

libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinProperties.kt

Ensure that the properties file is closed after reading in KotlinProperties.kt

Close the local.properties file after reading

---

j2k/src/org/jetbrains/kotlin/j2k/CodeConverter.kt
j2k/testData/fileOrElement/literalExpression/long.java
j2k/testData/fileOrElement/literalExpression/long.kt

https://youtrack.jetbrains.com/issue/KT-19393

KT-19393 long == <int_literal> in Java converted to red code in Kotlin

---

j2k/src/org/jetbrains/kotlin/j2k/AnnotationConverter.kt
j2k/testData/fileOrElement/docComments/deprecatedDocTagWithAnnotation.java
j2k/testData/fileOrElement/docComments/deprecatedDocTagWithAnnotation.kt
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterForWebDemoTestGenerated.java
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterSingleFileTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-19351

KT-19351 Repeated annotation @Deprecated after J2K for method with annotation and javadoc

---

ultimate/testData/quickFixes/spring/addQualifierAnnotation/ambiguousBean.kt.after

A simple fix for falling [test](https://teamcity.jetbrains.com/project.html?projectId=Kotlin&testNameId=299917331009863911&tab=testDetails)

Spring `testAmbiguousBean` formatting fix

---

idea/src/org/jetbrains/kotlin/idea/inspections/RemoveSetterParameterTypeInspection.kt
idea/src/org/jetbrains/kotlin/idea/intentions/RemoveExplicitTypeIntention.kt
idea/testData/intentions/removeExplicitType/notOnSetterParameter.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-19648

KT-19648 "Redundant setter parameter type" range includes whole parameter declaration

---

idea/tests/org/jetbrains/kotlin/idea/quickfix/LanguageFeatureQuickFixTest.kt
ultimate/src/org/jetbrains/kotlin/idea/spring/generate/generateDependenciesUtils.kt
ultimate/src/org/jetbrains/kotlin/idea/spring/inspections/SpringKotlinAutowiredMembersInspection.kt
ultimate/src/org/jetbrains/kotlin/idea/spring/inspections/SpringKotlinAutowiringInspection.kt
ultimate/src/org/jetbrains/kotlin/idea/spring/references/KtSpringQualifierReference.kt

Should fix the 173-branch build starting from 29.08.17. But who knows...

Fixes for 173 after 28.08.17 changes in IDEA

---

idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/RemovePartsFromPropertyFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/RemoveRedundantInitializerFix.kt
idea/testData/quickfix/removeRedundantInitializer/simple.kt
idea/testData/quickfix/removeRedundantInitializer/simple.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-5878

KT-5878 Quickfix for "variable initializer is redundant" (VARIABLE_WITH_REDUNDANT_INITIALIZER)

---

j2k/src/org/jetbrains/kotlin/j2k/CodeConverter.kt
j2k/src/org/jetbrains/kotlin/j2k/Converter.kt
j2k/src/org/jetbrains/kotlin/j2k/propertyDetection.kt
j2k/testData/fileOrElement/class/utilityClass4.java
j2k/testData/fileOrElement/class/utilityClass4.kt
j2k/testData/fileOrElement/class/utilityClass5.java
j2k/testData/fileOrElement/class/utilityClass5.kt
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterForWebDemoTestGenerated.java
j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterSingleFileTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-19651

KT-19651 Java class with static-only methods can contain 'protected' members

---

idea/src/org/jetbrains/kotlin/idea/joinLines/JoinBlockIntoSingleStatementHandler.kt
idea/testData/joinLines/removeBraces/FunctionWithOneLineReturn.kt
idea/testData/joinLines/removeBraces/FunctionWithOneLineReturn.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/declarations/JoinLinesTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-15769

KT-15769 Join lines could "convert to expression body"

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertObjectLiteralToClassIntention.kt
idea/testData/intentions/convertObjectLiteralToClass/inClass.kt
idea/testData/intentions/convertObjectLiteralToClass/inClass.kt.after
idea/testData/intentions/convertObjectLiteralToClass/inClassHasMethodReference.kt
idea/testData/intentions/convertObjectLiteralToClass/inClassHasMethodReference.kt.after
idea/testData/intentions/convertObjectLiteralToClass/inClassHasPropertyReference.kt
idea/testData/intentions/convertObjectLiteralToClass/inClassHasPropertyReference.kt.after
idea/testData/intentions/convertObjectLiteralToClass/inFunction.kt
idea/testData/intentions/convertObjectLiteralToClass/inFunction.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-20091

KT-20091 "Convert object literal to class" should create inner class if necessary

---

idea/resources/intentionDescriptions/MoveMemberToTopLevelIntention/after.kt.template
idea/resources/intentionDescriptions/MoveMemberToTopLevelIntention/before.kt.template
idea/resources/intentionDescriptions/MoveMemberToTopLevelIntention/description.html

@asedunov I didn't add description for MoveMemberToTopLevelIntention. See #1355

Add description for MoveMemberToTopLevelIntention

---

libraries/stdlib/src/kotlin/text/StringsJVM.kt

Fixes https://youtrack.jetbrains.com/issue/KT-20968

Fix the doc for String.Companion.format

---

idea/src/org/jetbrains/kotlin/idea/parameterInfo/KotlinFunctionParameterInfoHandler.kt
idea/testData/parameterInfo/annotations/ConstructorCall.kt
idea/testData/parameterInfo/annotations/ConstructorCallWithUseSite.kt
idea/testData/parameterInfo/annotations/FunctionCall.kt
idea/testData/parameterInfo/functionCall/NoAnnotations.kt
idea/tests/org/jetbrains/kotlin/idea/parameterInfo/ParameterInfoTestGenerated.java

#KT-20591 Fixed
https://youtrack.jetbrains.com/issue/KT-20591

KT-20591 Show annotations in parameter info

---

idea/src/org/jetbrains/kotlin/idea/intentions/JoinDeclarationAndAssignmentIntention.kt
idea/testData/intentions/joinDeclarationAndAssignment/hasLateinit.kt
idea/testData/intentions/joinDeclarationAndAssignment/hasLateinit.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-21603

KT-21603 "Join declaration and assignment" should remove 'lateinit' for 'var'

---

idea/src/org/jetbrains/kotlin/idea/KotlinFoldingBuilder.kt
idea/testData/folding/checkCollapse/primaryConstructor.kt
idea/tests/org/jetbrains/kotlin/idea/folding/KotlinFoldingTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-17928

KT-17928 Support code folding for primary constructors

---

idea/src/org/jetbrains/kotlin/idea/editor/KotlinLiteralCopyPasteProcessor.kt
idea/testData/copyPaste/literal/DontEscapeThis.expected.kt
idea/testData/copyPaste/literal/DontEscapeThis.kt
idea/testData/copyPaste/literal/DontEscapeThis.to.kt
idea/tests/org/jetbrains/kotlin/idea/conversion/copy/LiteralKotlinToKotlinCopyPasteTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-21770

KT-21770 Pasting $this into an interpolated string shouldn't escape $

---

idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createClass/CreateClassFromUsageFix.kt
idea/testData/quickfix/createFromUsage/createClass/delegationSpecifier/traitDelegatorToSuperclass2.kt
idea/testData/quickfix/createFromUsage/createClass/delegationSpecifier/traitDelegatorToSuperclass2.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-21698

KT-21698 `Create interface` shouldn't suggest to declare it inside a class which implements it

---

idea/idea-live-templates/src/org/jetbrains/kotlin/idea/liveTemplates/macro/KotlinClassNameMacro.kt
idea/idea-live-templates/testData/soutf.exp.kt
idea/idea-live-templates/testData/soutf.kt
idea/idea-live-templates/testData/soutf_InCompanion.exp.kt
idea/idea-live-templates/testData/soutf_InCompanion.kt
idea/idea-live-templates/tests/org/jetbrains/kotlin/idea/liveTemplates/LiveTemplatesTest.kt

https://youtrack.jetbrains.com/issue/KT-15320

KT-15320 Live templates: please add function which returns the "outer" class name

---

idea/idea-live-templates/src/org/jetbrains/kotlin/idea/liveTemplates/macro/KotlinPackageNameMacro.kt
idea/src/META-INF/plugin.xml

https://youtrack.jetbrains.com/issue/KT-14670

KT-14670 Support kotlinPackageName() macro in live templates

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantSetterInspection.kt
idea/testData/inspectionsLocal/redundantSetter/override.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-21780

KT-21780 Wrong redundant setter inspection

---

idea/src/org/jetbrains/kotlin/idea/quickfix/MakeVisibleFactory.kt
idea/testData/quickfix/increaseVisibility/invalidSealedClassInheritance.kt
idea/testData/quickfix/increaseVisibility/privateSealedClassInheritance.kt
idea/testData/quickfix/increaseVisibility/privateSealedClassInheritance.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-21929

KT-21929 Inappropriate quick fix for a sealed class instantiation

---

idea/src/org/jetbrains/kotlin/idea/kdoc/KDocRenderer.kt
idea/testData/editor/quickDoc/OnMethodUsageWithMultilineParam.kt
idea/tests/org/jetbrains/kotlin/idea/editor/quickDoc/QuickDocProviderTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-21213

KT-21213 multiline kdoc - intellij joins lines together without space

---

idea/idea-analysis/src/org/jetbrains/kotlin/idea/KotlinBundle.properties
idea/idea-analysis/src/org/jetbrains/kotlin/idea/highlighter/KotlinHighlightingColors.java
idea/idea-analysis/src/org/jetbrains/kotlin/idea/highlighter/PropertiesHighlightingVisitor.kt
idea/src/org/jetbrains/kotlin/idea/highlighter/KotlinColorSettingsPage.kt
idea/testData/highlighter/SyntheticExtensionProperty.kt
idea/tests/org/jetbrains/kotlin/idea/highlighter/HighlightingTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-21949

KT-21949 Please add a separate Color Scheme settings for properties synthesized from Java accessors

---

js/js.libraries/src/core/numberConversions.kt
libraries/stdlib/common/src/kotlin/TextH.kt
libraries/stdlib/test/text/StringNumberConversionTest.kt

Implement String.toBoolean() for JS.

---

idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createTypeAlias/CreateTypeAliasFromTypeReferenceActionFactory.kt
idea/testData/quickfix/createFromUsage/createTypeAlias/typeReference/javaUserTypeReceiver.test
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-15176

KT-15176 Remove "Create type alias" intention when called on java class

---

idea/src/org/jetbrains/kotlin/idea/quickfix/AddAnnotationTargetFix.kt
idea/testData/quickfix/addAnnotationTarget/expression.kt
idea/testData/quickfix/addAnnotationTarget/expression.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-22167

KT-22167 "Add annotation target" quick fix does nothing and disappears from menu

---

ReadMe.md
js/js.libraries/src/core/generated/_SequencesJs.kt
libraries/stdlib/common/src/generated/_Sequences.kt
libraries/stdlib/src/generated/_Sequences.kt
libraries/tools/kotlin-stdlib-gen/src/templates/Aggregates.kt

- In the main ReadMe.md
- In onEach template's doc

Fix a couple of typos

---

compiler/backend/src/org/jetbrains/kotlin/codegen/intrinsics/CompareTo.kt
compiler/testData/codegen/bytecodeText/intrinsicsCompare/longSmartCast.kt

Fix of https://youtrack.jetbrains.com/issue/KT-10057

KT-10057 Use lcmp instead of Intrinsics.compare

---

idea/idea-android/src/org/jetbrains/kotlin/android/ResourceReferenceAnnotatorUtil.java

Change-Id: I5dc44306eb315bc9463aaf3d55ad1a75c1e12015

Android framework resource refactoring fixes

---

idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createCallable/CreateCallableFromUsageFix.kt
idea/testData/quickfix/createFromUsage/createFunction/call/typeArguments/classMemberInFunctionLiteralWithReceiver.kt
idea/testData/quickfix/createFromUsage/createFunction/call/typeArguments/classMemberInFunctionLiteralWithReceiver.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-22428

KT-22428 Create member function from usage shouldn't present type parameters as options

---

idea/idea-android/src/org/jetbrains/kotlin/android/quickfix/AddTargetApiQuickFix.kt
idea/idea-android/src/org/jetbrains/kotlin/android/quickfix/KotlinAndroidQuickFixProvider.kt

Change-Id: If2148ab8cefcc124a72f63458b7dbddf1a6cfe04

Fix uses of AndroidxName from SdkConstants

---

ReadMe.md

Fix typo in README

---

grammar/src/class_members.grm
grammar/src/enum.grm
grammar/src/expressions.grm
grammar/src/lexical.grm
grammar/src/notation.grm
grammar/src/toplevel.grm
grammar/src/types.grm

https://youtrack.jetbrains.com/issue/KT-22676
Feel free to squash any/all commits.

Fix various bugs in generated Kotlin grammar

---

compiler/frontend/src/org/jetbrains/kotlin/parsing/KotlinExpressionParsing.java
grammar/src/expressions.grm
grammar/src/lexical.grm

Add missing long literal suffix
Add binary integer literals
Introduce IntegerLiteral lexer rule, which is closer to the actual lexer
Issue #KT-22713 Fixed

Update literals in the grammar reference

---

idea/idea-android/src/org/jetbrains/kotlin/android/intention/KotlinAndroidAddStringResource.kt
plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/AndroidConst.kt
plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/codegen/AbstractAndroidExtensionsExpressionCodegenExtension.kt
plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/codegen/AndroidContainerType.kt
plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/codegen/ResourcePropertyStackValue.kt
plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/descriptors/LazySyntheticElementResolveContext.kt
plugins/android-extensions/android-extensions-compiler/test/org/jetbrains/kotlin/android/synthetic/test/AndroidBytecodeShapeTestGenerated.java
plugins/android-extensions/android-extensions-compiler/testData/codegen/bytecodeShape/supportExtensionFunctionsFragmentAndroidx/res/layout/layout.xml
plugins/android-extensions/android-extensions-compiler/testData/codegen/bytecodeShape/supportExtensionFunctionsFragmentAndroidx/supportExtensionFunctionsFragmentAndroidx.kt
plugins/android-extensions/android-extensions-compiler/testData/codegen/bytecodeShape/supportSimpleFragmentAndroidx/res/layout/layout.xml
plugins/android-extensions/android-extensions-compiler/testData/codegen/bytecodeShape/supportSimpleFragmentAndroidx/supportSimpleFragmentAndroidx.kt
plugins/android-extensions/android-extensions-compiler/testData/codegen/bytecodeShape/supportSimpleFragmentPropertyAndroidx/res/layout/layout.xml
plugins/android-extensions/android-extensions-compiler/testData/codegen/bytecodeShape/supportSimpleFragmentPropertyAndroidx/supportSimpleFragmentPropertyAndroidx.kt

... in the IDE plugin and the Android extensions compiler.
Change-Id: Iffd58351b0592e12ffc937c06d871d26958fe161

Support androidx packages

---

compiler/frontend/src/org/jetbrains/kotlin/psi/synthetics/SyntheticClassOrObjectDescriptor.kt
compiler/frontend/src/org/jetbrains/kotlin/resolve/lazy/descriptors/LazyClassDescriptor.java

Needed by kapt due to https://github.com/Kotlin/kotlinx.serialization/issues/76

Add correct type parameter information to synthetic declarations

---

libraries/stdlib/common/src/kotlin/TextH.kt
libraries/stdlib/js/src/kotlin/numberConversions.kt
libraries/stdlib/jvm/src/kotlin/text/StringNumberConversionsJVM.kt
libraries/stdlib/jvm/test/text/StringNumberConversionJVMTest.kt
libraries/stdlib/test/text/StringNumberConversionTest.kt

JS implementation of [KT-10456](https://youtrack.jetbrains.com/issue/KT-10456). Was #1650 before I broke my branch.

[KT-10456] [JS] Common Int.toString(radix: Int) method

---

plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/resolve/KSerializerDescriptorResolver.kt

Create a version that actually passes a type parameter in write$Self

Fix for Kotlin/kotlinx.serialization/136

---

compiler/light-classes/src/org/jetbrains/kotlin/asJava/elements/KtLightAnnotationsValues.kt
compiler/light-classes/src/org/jetbrains/kotlin/asJava/elements/KtLightAnnotationsValues.kt.173
compiler/light-classes/src/org/jetbrains/kotlin/asJava/elements/lightAnnotations.kt
compiler/light-classes/src/org/jetbrains/kotlin/asJava/elements/lightAnnotations.kt.173
idea/tests/org/jetbrains/kotlin/asJava/KtLightAnnotationTest.kt
idea/tests/org/jetbrains/kotlin/asJava/KtLightAnnotationTest.kt.173
plugins/uast-kotlin/src/org/jetbrains/uast/kotlin/declarations/KotlinUVariable.kt
plugins/uast-kotlin/src/org/jetbrains/uast/kotlin/declarations/KotlinUVariable.kt.173

Many thanks for your contribution, we genuinely appreciate it. 
Make sure that you can say "YES" to each point in this short checklist:
- You do not have merge commits in PR
- You made a few changes
- You provided the link to related issue from YouTrack
- You can describe changes made in PR
- You made changes related to only one issue
- You are ready to defend your changes on code review
- You didn't touch what you don't understand
- You ran the build locally, and verified new functionality
- You ran related tests locally, and it passed
Thank you for your contribution!

Fixes for new light-annotations

---

libraries/tools/idl2k/src/main/kotlin/build.kt
libraries/tools/idl2k/src/main/kotlin/generator.kt
libraries/tools/idl2k/src/main/kotlin/main.kt

This PR just separates the idl2k front end and back end invocations.
So that Kotlin/Native could provide their own back end.

Separated idl2k frontend and backend invocations.

---

plugins/scripting/scripting-cli/src/org/jetbrains/kotlin/scripting/compiler/plugin/asmBasedAnnotationsLoading.kt

Tentative fix for [KT-24926](https://youtrack.jetbrains.com/issue/KT-24926).

Only collect annotations with a name starting with `KotlinScript`

---

idea/src/org/jetbrains/kotlin/idea/refactoring/introduce/extractFunction/ui/KotlinExtractFunctionDialog.java

Many thanks for your contribution, we genuinely appreciate it. 
Make sure that you can say "YES" to each point in this short checklist:
- You do not have merge commits in PR
- You made a few changes
- You provided the link to related issue from YouTrack
- You can describe changes made in PR
- You made changes related to only one issue
- You are ready to defend your changes on code review
- You didn't touch what you don't understand
- You ran the build locally, and verified new functionality
- You ran related tests locally, and it passed
Thank you for your contribution!

KT-22333 Extract function: make name editor focused once again

---

js/js.translator/src/org/jetbrains/kotlin/js/translate/expression/LoopTranslator.kt
js/js.translator/testData/box/expression/for/forIteratesOverLiteralRange.kt

https://youtrack.jetbrains.com/issue/KT-22376

KT-22376 JS: TranslationRuntimeException on 'for (x in ("a"))'

---

js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/BoxJsTestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/IrBoxJsTestGenerated.java
js/js.translator/src/org/jetbrains/kotlin/js/translate/callTranslator/CallTranslator.kt
js/js.translator/testData/box/expression/when/whenWithMapRangeClause.kt

https://youtrack.jetbrains.com/issue/KT-23458

KT-23458 ClassCastException when compiling when statements to JS

---

ReadMe.md

This is to provide some guidance for PRs like #1769

Some notes on contributing language features

---

libraries/stdlib/common/src/kotlin/TextH.kt
libraries/stdlib/js/src/kotlin/string.kt
libraries/stdlib/jvm/src/kotlin/text/StringsJVM.kt
libraries/stdlib/samples/test/samples/text/strings.kt

Create sample to String.toLowerCase

---

idea/resources/postfixTemplates/KtSpreadPostfixTemplate/after.kt.template
idea/resources/postfixTemplates/KtSpreadPostfixTemplate/before.kt.template
idea/resources/postfixTemplates/KtSpreadPostfixTemplate/description.html
idea/src/org/jetbrains/kotlin/idea/codeInsight/postfix/KtPostfixTemplateProvider.kt
idea/src/org/jetbrains/kotlin/idea/codeInsight/postfix/stringBasedPostfixTemplates.kt
idea/testData/codeInsight/postfix/spread.kt
idea/testData/codeInsight/postfix/spread.kt.after
idea/testData/codeInsight/postfix/spreadIntArray.kt
idea/testData/codeInsight/postfix/spreadIntArray.kt.after
idea/tests/org/jetbrains/kotlin/idea/codeInsight/postfix/PostfixTemplateProviderTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26249

KT-26249 Postfix template for the spread operator

---

idea/src/org/jetbrains/kotlin/idea/intentions/RemoveExplicitTypeIntention.kt
idea/testData/intentions/removeExplicitType/needTypeArgument.kt
idea/testData/intentions/removeExplicitType/needTypeArgument.kt.after
idea/testData/intentions/removeExplicitType/needTypeArgument2.kt
idea/testData/intentions/removeExplicitType/needTypeArgument2.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-13343

KT-13343 Remove explicit type specification breaks code if initializer omits generics

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantSemicolonInspection.kt
idea/testData/inspectionsLocal/redundantSemicolon/ifElse.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26185

KT-26185 False positive "redundant semicolon" with if-else

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/IfThenUtils.kt
idea/testData/intentions/branched/ifWhen/ifToWhen/lambdaExpression.kt
idea/testData/intentions/branched/ifWhen/ifToWhen/lambdaExpression.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/lambdaExpression2.kt
idea/testData/intentions/branched/ifWhen/ifToWhen/lambdaExpression2.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26187

KT-26187 "Cascade if can be replaced with when" loses lambda curly braces

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/IfThenUtils.kt
idea/testData/intentions/branched/ifThenToElvis/extensionFunctionInClass.kt
idea/testData/intentions/branched/ifThenToElvis/extensionFunctionInClass.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26343

KT-26343 "Replace 'if' expression with elvis expression" produces wrong code in extension function with not null type parameter

---

idea/src/org/jetbrains/kotlin/idea/intentions/SimplifyBooleanWithConstantsIntention.kt
idea/testData/intentions/simplifyBooleanWithConstants/notReduceableBinary.kt
idea/testData/intentions/simplifyBooleanWithConstants/notReduceableBinary.kt.after
idea/testData/intentions/simplifyBooleanWithConstants/notReduceableBinary2.kt
idea/testData/intentions/simplifyBooleanWithConstants/notReduceableBinary2.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26179

KT-26179 False negative "Boolean expression that can be simplified" for `!true`

---

idea/src/org/jetbrains/kotlin/idea/intentions/FoldInitializerAndIfToElvisIntention.kt
idea/testData/intentions/foldInitializerAndIfToElvis/NotIsNullableType.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-25886

KT-25886 False positive "Replace 'if' with elvis operator" for nullable type

---

idea/src/org/jetbrains/kotlin/idea/intentions/ReplaceSingleLineLetIntention.kt
idea/testData/inspectionsLocal/replaceSingleLineLet/.inspection
idea/testData/inspectionsLocal/replaceSingleLineLet/callChain.kt
idea/testData/inspectionsLocal/replaceSingleLineLet/callChain.kt.after
idea/testData/inspectionsLocal/replaceSingleLineLet/callChain2.kt
idea/testData/inspectionsLocal/replaceSingleLineLet/callChain2.kt.after
idea/testData/inspectionsLocal/replaceSingleLineLet/callChain3.kt
idea/testData/inspectionsLocal/replaceSingleLineLet/callChain3.kt.after
idea/testData/inspectionsLocal/replaceSingleLineLet/callChainWithLineBreak.kt
idea/testData/inspectionsLocal/replaceSingleLineLet/longCallChain.kt
idea/testData/inspectionsLocal/replaceSingleLineLet/noReceiver.kt
idea/testData/inspectionsLocal/replaceSingleLineLet/noReceiver.kt.after
idea/testData/inspectionsLocal/replaceSingleLineLet/simple.kt
idea/testData/inspectionsLocal/replaceSingleLineLet/simple.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26289

KT-26289 Redundant let with call expression: don't report for long call chains

---

idea/src/org/jetbrains/kotlin/idea/quickfix/AddAnnotationTargetFix.kt
idea/testData/quickfix/addAnnotationTarget/expression2.kt
idea/testData/quickfix/addAnnotationTarget/expression2.kt.after
idea/testData/quickfix/addAnnotationTarget/expression3.kt
idea/testData/quickfix/addAnnotationTarget/expression3.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26306

KT-26306 "Add annotation target" quick fix adds EXPRESSION annotation, but not SOURCE retention

---

idea/idea-core/src/org/jetbrains/kotlin/idea/core/script/dependencies/ScriptDependenciesLoader.kt

In 4f3f4dd, launch(EDT(project)) was replaced with TransactionGuard.submitTransaction to fix write in write-unsafe context.
Unfortunately submitTransaction will call action immediately if we are already on EDT. This causes IDE freeze.
By replacing submitTransaction with submitTransactionLater we are postponing work to the end of events queue (as it was before 4f3f4dd).
Also in isUnitTestMode we need to call action immediately as it was before 4f3f4dd.
#KT-25958 Fixed

ScriptDependenciesLoader: Fix freeze on notifyRootsChanged

---

idea/src/META-INF/plugin.xml
idea/src/META-INF/plugin.xml.173
idea/src/META-INF/plugin.xml.181
idea/src/META-INF/plugin.xml.183
idea/src/META-INF/plugin.xml.as31
idea/src/META-INF/plugin.xml.as32
idea/src/META-INF/plugin.xml.as33
idea/src/org/jetbrains/kotlin/idea/inspections/NestedLambdaShadowedImplicitParameterInspection.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/explicit.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/explicitParent.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicit.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicit.kt.after
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicit2.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicit2.kt.after
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicit3.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicit3.kt.after
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicitGrandParent.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicitGrandParent.kt.after
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/notUseParameter.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/receiver.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/receiverParent.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26268

KT-26268 Inspection "Nested lambda has shadowed implicit parameter" should only warn if parameter is used

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantLambdaArrowInspection.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/underscore.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/underscore.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-24728

KT-24728 Add quickfix to remove single explicit & unused lambda parameter

---

idea/src/org/jetbrains/kotlin/idea/refactoring/introduce/extractFunction/ui/KotlinExtractFunctionDialog.java

https://youtrack.jetbrains.com/issue/KT-25454

KT-25454 Extract function: make default visibility private

---

idea/src/org/jetbrains/kotlin/idea/inspections/ScopeFunctionConversionInspection.kt
idea/testData/inspectionsLocal/scopeFunctions/applyToAlso/methodWithThis.kt
idea/testData/inspectionsLocal/scopeFunctions/applyToAlso/methodWithThis.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26009

KT-26009 "Convert to 'also'" intention adds an extra `it` expression

---

libraries/tools/kotlin-gradle-plugin-api/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinTarget.kt
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/NewMultiplatformIT.kt
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/new-mpp-lib-and-app/sample-lib/build.gradle
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/KotlinMultiplatformPlugin.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/kotlinTargets.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/tasks/KotlinNativeTasks.kt

Provide a DSL for publication settings

---

idea/src/org/jetbrains/kotlin/idea/inspections/collections/RenameUselessCallFix.kt
idea/testData/inspectionsLocal/collections/uselessCallOnNotNull/NullOrBlankSafe.kt
idea/testData/inspectionsLocal/collections/uselessCallOnNotNull/NullOrBlankSafe.kt.after

https://youtrack.jetbrains.com/issue/KT-26902

Bad quickfix name for "Call on non-null type may be reduced"

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/IfThenUtils.kt
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/conditionInParentheses.kt
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/conditionInParentheses.kt.after
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/implicitReceiver2.kt
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/implicitReceiver2.kt.after
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/implicitReceiver3.kt
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/implicitReceiver3.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26662

KT-26662 Corner cases around 'this' inside "replace if with safe access"

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantSamConstructorInspection.kt
idea/testData/inspectionsLocal/redundantSamConstructor/simple.1.java
idea/testData/inspectionsLocal/redundantSamConstructor/simple.kt
idea/testData/inspectionsLocal/redundantSamConstructor/simple.kt.after
idea/testData/inspectionsLocal/redundantSamConstructor/simple2.1.java
idea/testData/inspectionsLocal/redundantSamConstructor/simple2.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27034

KT-27034 "Redundant SAM constructor" inspection shouldn't make all lambda gray (too much highlighting)

---

idea/src/org/jetbrains/kotlin/idea/intentions/AddBracesIntention.kt
idea/testData/intentions/addBraces/addBracesForIfWithIndent.kt
idea/testData/intentions/addBraces/addBracesForIfWithIndent.kt.after
idea/testData/intentions/addBraces/addBracesForIfWithIndent2.kt
idea/testData/intentions/addBraces/addBracesForIfWithIndent2.kt.after
idea/testData/intentions/addBraces/addBracesForIfWithIndent3.kt
idea/testData/intentions/addBraces/addBracesForIfWithIndent3.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26839

KT-26839 Add braces to if statement produces code that is not formatted according to style

---

idea/src/org/jetbrains/kotlin/idea/inspections/LeakingThisInspection.kt
idea/testData/inspectionsLocal/leakingThis/inClassLiteral.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-16338

KT-16338 "Leaking 'this' in constructor" of non-final class when using 'this::class.java'

---

idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/testData/quickfix/redundantInline/function.kt
idea/testData/quickfix/redundantInline/function.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-5187

KT-5187 Quick Fix to remove inline keyword on warning about performance benefits

---

libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/kotlinTargetPresets.kt

[K/N] Friendly displaying of Kotlin/Native default libraries in IDEA

---

libraries/stdlib/samples/test/samples/collections/maps.kt
libraries/stdlib/src/kotlin/collections/Maps.kt

KT-20357 Add sample for orEmpty method in collections/Maps.kt

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPrimaryConstructorToSecondaryIntention.kt
idea/testData/intentions/convertPrimaryConstructorToSecondary/delegation.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27061

KT-27061 False positive "Convert to secondary constructor" with delegation

---

idea/src/org/jetbrains/kotlin/idea/quickfix/DeclarationCantBeInlinedFactory.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/testData/quickfix/declarationCantBeInlined/inClass.kt
idea/testData/quickfix/declarationCantBeInlined/inClass.kt.after
idea/testData/quickfix/declarationCantBeInlined/inInterface.kt
idea/testData/quickfix/declarationCantBeInlined/inInterface.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-9983

KT-9983 "'inline'' modifier is not allowed on virtual members." should have quickfix

---

idea/src/org/jetbrains/kotlin/idea/intentions/ObjectLiteralToLambdaIntention.kt
idea/testData/intentions/objectLiteralToLambda/inspectionData/expected.xml

https://youtrack.jetbrains.com/issue/KT-27116

KT-27116 "Object literal can be converted to lambda" produces code littered with "return@label"

---

idea/src/org/jetbrains/kotlin/idea/inspections/UnlabeledReturnInsideLambdaInspection.kt
idea/testData/inspectionsLocal/unlabeledReturnInsideLambda/labeledReturn.kt
idea/testData/inspectionsLocal/unlabeledReturnInsideLambda/notInlineFunction.kt
idea/testData/inspectionsLocal/unlabeledReturnInsideLambda/return.kt.after
idea/testData/inspectionsLocal/unlabeledReturnInsideLambda/returnInFunction.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27007

KT-27007 Intention: add label to return if scope is visually ambiguous

---

idea/src/org/jetbrains/kotlin/idea/inspections/collections/ConvertCallChainIntoSequenceInspection.kt
idea/testData/inspectionsLocal/collections/convertCallChainIntoSequence/flatten.kt
idea/testData/inspectionsLocal/collections/convertCallChainIntoSequence/flatten.kt.after
idea/testData/inspectionsLocal/collections/convertCallChainIntoSequence/flatten2.kt
idea/testData/inspectionsLocal/collections/convertCallChainIntoSequence/flatten2.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26969

KT-26969 ConvertCallChainIntoSequence quick fix doesn't use sequences all the way

---

idea/src/org/jetbrains/kotlin/idea/inspections/collections/ConvertCallChainIntoSequenceInspection.kt
idea/testData/inspectionsLocal/collections/convertCallChainIntoSequence/termination/unzip.kt
idea/testData/inspectionsLocal/collections/convertCallChainIntoSequence/termination/unzip.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27486

KT-27486 ConvertCallChainIntoSequence quick fix doesn't convert 'unzip' into 'Sequence'

---

idea/src/org/jetbrains/kotlin/idea/intentions/AddAccessorIntentions.kt
idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPropertyInitializerToGetterIntention.kt
idea/testData/intentions/addPropertyAccessors/both/jvmField.kt
idea/testData/intentions/addPropertyAccessors/getter/jvmField.kt
idea/testData/intentions/addPropertyAccessors/setter/jvmField.kt
idea/testData/intentions/convertPropertyInitializerToGetter/jvmField.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27139

KT-27139 Add getter intention is suggested for properties marked with @JvmField

---

idea/src/org/jetbrains/kotlin/idea/intentions/IntroduceBackingPropertyIntention.kt
idea/testData/intentions/introduceBackingProperty/jvmField.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27156

KT-27156 Introduce backing property intention is suggested for property marked with @JvmField

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPropertyToFunctionIntention.kt
idea/testData/intentions/convertPropertyToFunction/jvmField.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27157

KT-27157 Convert property to function intention is suggested for property marked with @JvmField

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/BranchedFoldingUtils.kt
idea/testData/inspectionsLocal/liftOut/ifToAssignment/nullableMutableList.kt
idea/testData/inspectionsLocal/liftOut/ifToAssignment/nullableMutableList.kt.after
idea/testData/inspectionsLocal/liftOut/ifToAssignment/typeMismatch.kt
idea/testData/inspectionsLocal/liftOut/ifToAssignment/typeMismatch2.kt
idea/testData/inspectionsLocal/liftOut/ifToAssignment/typeMismatch3.kt
idea/testData/inspectionsLocal/liftOut/ifToAssignment/typeMismatchMutableList.kt
idea/testData/inspectionsLocal/liftOut/ifToAssignment/typeMismatchMutableList2.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-21520

KT-21520 'Assignment can be lifted out of if' in cases where argument are of different types

---

idea/src/org/jetbrains/kotlin/idea/intentions/RemoveEmptyParenthesesFromLambdaCallIntention.kt
idea/testData/intentions/removeEmptyParenthesesFromLambdaCall/afterLambda4.kt
idea/testData/intentions/removeEmptyParenthesesFromLambdaCall/afterLambda5.kt
idea/testData/intentions/removeEmptyParenthesesFromLambdaCall/afterLambda6.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26669

KT-26669 "Remove unnecessary parentheses" reports parens of function returned from extension function

---

idea/src/org/jetbrains/kotlin/idea/inspections/SafeCastWithReturnInspection.kt
idea/testData/inspectionsLocal/safeCastWithReturn/lambdaLastStatement.kt
idea/testData/inspectionsLocal/safeCastWithReturn/lambdaLastStatement2.kt
idea/testData/inspectionsLocal/safeCastWithReturn/lambdaLastStatement2.kt.after
idea/testData/inspectionsLocal/safeCastWithReturn/lambdaLastStatement3.kt
idea/testData/inspectionsLocal/safeCastWithReturn/lambdaLastStatement3.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27906

KT-27906 SafeCastAndReturn is not reported on code block with unqualified return

---

libraries/stdlib/common/src/generated/_Arrays.kt
libraries/stdlib/common/src/generated/_Collections.kt
libraries/stdlib/common/src/generated/_Maps.kt
libraries/stdlib/common/src/generated/_Sequences.kt
libraries/stdlib/common/src/generated/_Strings.kt
libraries/stdlib/samples/test/samples/collections/collections.kt
libraries/tools/kotlin-stdlib-gen/src/templates/Aggregates.kt

See https://youtrack.jetbrains.com/issue/KT-20357

KT-20357 Add samples for maxBy and minBy

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantCompanionReferenceInspection.kt
idea/testData/inspectionsLocal/redundantCompanionReference/inEnum.kt
idea/testData/inspectionsLocal/redundantCompanionReference/inEnum.kt.after
idea/testData/inspectionsLocal/redundantCompanionReference/inEnumEntry.kt
idea/testData/inspectionsLocal/redundantCompanionReference/inEnumEntry2.kt
idea/testData/inspectionsLocal/redundantCompanionReference/inEnumEntry2.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27861

KT-27861 RedundantCompanionReference false positive for nested class with name "Companion"

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertToStringTemplateIntention.kt
idea/testData/intentions/convertToStringTemplate/this.kt
idea/testData/intentions/convertToStringTemplate/this.kt.after
idea/testData/intentions/convertToStringTemplate/this2.kt
idea/testData/intentions/convertToStringTemplate/this2.kt.after
idea/testData/intentions/convertToStringTemplate/this3.kt
idea/testData/intentions/convertToStringTemplate/this3.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-7555

KT-7555 Omit braces when converting 'this' in 'Convert concatenation to template'

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/IfToWhenIntention.kt
idea/testData/intentions/branched/ifWhen/ifToWhen/onElseIf.kt
idea/testData/intentions/branched/ifWhen/ifToWhen/onElseIf.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/onElseIf2.kt
idea/testData/intentions/branched/ifWhen/ifToWhen/onElseIf2.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/onElseIf3.kt
idea/testData/intentions/branched/ifWhen/ifToWhen/onElseIf3.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-4645

KT-4645 Unexpected behevior of "Replace 'if' with 'when'" intention when called on second or third 'if'

---

idea/src/org/jetbrains/kotlin/idea/inspections/ProtectedInFinalInspection.kt
idea/testData/inspections/protectedInFinal/finalize.kt

https://youtrack.jetbrains.com/issue/KT-13311

KT-13311 IDE marks fun finalize() as unused and says that its effective visibility is private

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantLambdaArrowInspection.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/inIfElse.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/inIfElse2.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/inIfElse2.kt.after
idea/testData/inspectionsLocal/redundantLambdaArrow/inIfThen.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/inIfThen2.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/inIfThen2.kt.after
idea/testData/inspectionsLocal/redundantLambdaArrow/inIfWhenEntry.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/inIfWhenEntry2.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/inIfWhenEntry2.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-28047

KT-28047 False positive "Redundant lambda arrow" for lambda returned from `when` branch

---

idea/src/org/jetbrains/kotlin/idea/actions/generate/KotlinGenerateToStringAction.kt
idea/testData/codeInsight/generate/toString/multipeTemplates/arrays.kt.after
idea/testData/codeInsight/generate/toString/multipeTemplates/customAccessors.kt.after
idea/testData/codeInsight/generate/toString/multipeTemplates/dataClass.kt.after
idea/testData/codeInsight/generate/toString/multipeTemplates/keepQuotes.kt.after
idea/testData/codeInsight/generate/toString/multipeTemplates/multipleVars.kt.after
idea/testData/codeInsight/generate/toString/multipeTemplates/multipleVarsWithSuperClass.kt.after

https://youtrack.jetbrains.com/issue/KT-27954

Multiple templates with concatenation generator should add spaces after commas (KT-27954)

---

idea/src/org/jetbrains/kotlin/idea/actions/generate/KotlinGenerateEqualsAndHashcodeAction.kt
idea/testData/codeInsight/generate/equalsWithHashCode/dataClass.kt
idea/testData/codeInsight/generate/equalsWithHashCode/dataClass.kt.after

https://youtrack.jetbrains.com/issue/KT-17502

KT-17502 Do not disable "Generate equals and hashCode" actions for data classes

---

idea/ide-common/src/org/jetbrains/kotlin/idea/core/quickfix/QuickFixUtil.java
idea/testData/quickfix/typeMismatch/when.kt
idea/testData/quickfix/typeMismatch/when.kt.after
idea/testData/quickfix/typeMismatch/when2.kt
idea/testData/quickfix/typeMismatch/when2.kt.after
idea/testData/quickfix/typeMismatch/when3.kt
idea/testData/quickfix/typeMismatch/when3.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-8820

KT-8820 No "Change type" quick fix inside when

---

idea/src/org/jetbrains/kotlin/idea/inspections/LeakingThisInspection.kt
idea/testData/inspectionsLocal/leakingThis/enum.kt
idea/testData/inspectionsLocal/leakingThis/enumEntryHasOverriddenMember.kt
idea/testData/inspectionsLocal/leakingThis/enumEntryHasOverriddenMember2.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-15835

KT-15835 "Leaking 'this' in constructor" for enum class

---

idea/src/org/jetbrains/kotlin/idea/inspections/RemoveRedundantSpreadOperatorInspection.kt
idea/testData/inspectionsLocal/removeRedundantSpreadOperator/spredOperatorArgument.kt
idea/testData/inspectionsLocal/removeRedundantSpreadOperator/spredOperatorArgument.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27699

KT-27699 "Remove redundant spread operator" produces incorrect code

---

idea/src/org/jetbrains/kotlin/idea/inspections/collections/ConvertCallChainIntoSequenceInspection.kt

https://youtrack.jetbrains.com/issue/KT-28231

KT-28231 Exception: Tool #ConvertCallChainIntoSequence registers INFORMATION level problem in batch mode

---

idea/src/org/jetbrains/kotlin/idea/quickfix/AddModifierFix.kt
idea/testData/quickfix/abstract/makeInlineClassAbstract.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-28268

KT-28268 Don't suggest "make abstract" quick fix for inline classes

---

idea/idea-completion/src/org/jetbrains/kotlin/idea/completion/KeywordCompletion.kt
idea/idea-completion/testData/keywords/AfterClassProperty.kt
idea/idea-completion/testData/keywords/AfterClasses.kt
idea/idea-completion/testData/keywords/AfterClasses_LangLevel10.kt
idea/idea-completion/testData/keywords/AfterClasses_LangLevel11.kt
idea/idea-completion/testData/keywords/AfterFuns.kt
idea/idea-completion/testData/keywords/GlobalPropertyAccessors.kt
idea/idea-completion/testData/keywords/InAnnotationClassScope.kt
idea/idea-completion/testData/keywords/InClassBeforeFun.kt
idea/idea-completion/testData/keywords/InClassScope.kt
idea/idea-completion/testData/keywords/InEnumScope2.kt
idea/idea-completion/testData/keywords/InInterfaceScope.kt
idea/idea-completion/testData/keywords/InObjectScope.kt
idea/idea-completion/testData/keywords/InPrimaryConstructorParametersList.kt
idea/idea-completion/testData/keywords/InTopScopeAfterPackage.kt
idea/idea-completion/testData/keywords/PropertyAccessors.kt
idea/idea-completion/testData/keywords/PropertyAccessors2.kt
idea/idea-completion/testData/keywords/PropertySetter.kt
idea/idea-completion/testData/keywords/TopScope.kt

https://youtrack.jetbrains.com/issue/KT-27916

KT-27916 Autocomplete val when auto-completing const

---

idea/src/org/jetbrains/kotlin/idea/inspections/describeDeclaration.kt
idea/testData/inspections/unusedSymbol/class/inspectionData/expected.xml
idea/testData/inspections/unusedSymbol/class/interface.kt

https://youtrack.jetbrains.com/issue/KT-28286

KT-28286 "Unused symbol" inspection: Interface is reported as "class"

---

idea/src/org/jetbrains/kotlin/idea/inspections/UnusedSymbolInspection.kt
idea/testData/inspections/unusedSymbol/typeParameter/inspectionData/expected.xml
idea/testData/inspections/unusedSymbol/typeParameter/openClassTypeParameter.kt

https://youtrack.jetbrains.com/issue/KT-23639

KT-23639 False positive "Unused symbol" for sealed class type parameters

---

idea/src/org/jetbrains/kotlin/idea/intentions/IntroduceBackingPropertyIntention.kt
idea/testData/intentions/introduceBackingProperty/const.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-28341

KT-28341 False positive "Introduce backing property" intention for `const` values

---

idea/src/org/jetbrains/kotlin/idea/inspections/RemoveToStringInStringTemplateInspection.kt
idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceToStringWithStringTemplateInspection.kt
idea/src/org/jetbrains/kotlin/idea/intentions/ConvertToStringTemplateIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/Utils.kt
idea/testData/intentions/convertToStringTemplate/toString.kt
idea/testData/intentions/convertToStringTemplate/toString.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-6025

KT-6025 Auto-remove toString() call in "Convert concatenation to template"

---

idea/idea-core/src/org/jetbrains/kotlin/idea/core/psiModificationUtils.kt
idea/testData/intentions/changeVisibility/internal/hasJvmFieldInInterface.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27138#focus=streamItem-27-3179248-0-0

KT-27138 Change visibility intentions are suggested on properties marked with @JvmField

---

idea/src/org/jetbrains/kotlin/idea/refactoring/introduce/extractClass/ui/KotlinExtractInterfaceDialog.kt

https://youtrack.jetbrains.com/issue/KT-28408

KT-28408 "Extract interface" action should not show private properties

---

idea/idea-completion/src/org/jetbrains/kotlin/idea/completion/KeywordCompletion.kt
idea/idea-completion/testData/keywords/AfterClassProperty.kt
idea/idea-completion/testData/keywords/AfterClasses.kt
idea/idea-completion/testData/keywords/AfterClasses_LangLevel10.kt
idea/idea-completion/testData/keywords/AfterClasses_LangLevel11.kt
idea/idea-completion/testData/keywords/AfterFuns.kt
idea/idea-completion/testData/keywords/GlobalPropertyAccessors.kt
idea/idea-completion/testData/keywords/InAnnotationClassScope.kt
idea/idea-completion/testData/keywords/InClassBeforeFun.kt
idea/idea-completion/testData/keywords/InClassScope.kt
idea/idea-completion/testData/keywords/InEnumScope2.kt
idea/idea-completion/testData/keywords/InInterfaceScope.kt
idea/idea-completion/testData/keywords/InObjectScope.kt
idea/idea-completion/testData/keywords/InTopScopeAfterPackage.kt
idea/idea-completion/testData/keywords/PropertyAccessors.kt
idea/idea-completion/testData/keywords/PropertyAccessors2.kt
idea/idea-completion/testData/keywords/PropertySetter.kt
idea/idea-completion/testData/keywords/TopScope.kt

https://youtrack.jetbrains.com/issue/KT-26632

KT-26632 Completion: "data class" instead of "data"

---

compiler/psi/src/org/jetbrains/kotlin/psi/VisitorWrappers.kt
idea/resources/inspectionDescriptions/MapGetWithNotNullAssertionOperator.html
idea/src/META-INF/plugin-common.xml
idea/src/org/jetbrains/kotlin/idea/inspections/MapGetWithNotNullAssertionOperatorInspection.kt
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/.inspection
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/get.kt
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/get.kt.after
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/getValue.kt
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/indexedAccess.kt
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/indexedAccess.kt.after
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/list.kt
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/noNotNullAssersion.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-25171

KT-25171 Inspection: Change indexed access operator on maps to `Map.getValue`

---

idea/src/org/jetbrains/kotlin/idea/inspections/SetterBackingFieldAssignmentInspection.kt
idea/testData/inspectionsLocal/setterBackingFieldAssignment/noAssignment3.kt
idea/testData/inspectionsLocal/setterBackingFieldAssignment/noAssignment3.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-28694

KT-28694 "Assign backing field" quick fix adds empty line before created assignment

---

idea/src/org/jetbrains/kotlin/idea/inspections/conventionNameCalls/ReplaceCallWithBinaryOperatorInspection.kt
idea/src/org/jetbrains/kotlin/idea/intentions/Utils.kt
idea/src/org/jetbrains/kotlin/idea/intentions/conventionNameCalls/ReplaceContainsIntention.kt
idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/compareToFromJava.1.java
idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/compareToFromJava.1.java.after
idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/compareToFromJava.kt
idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/compareToFromJava.kt.after
idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/notOperatorCompareTo.kt
idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/notOperatorPlus.kt
idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/plusFromJava.1.java
idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/plusFromJava.1.java.after
idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/plusFromJava.kt
idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/plusFromJava.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-12273

KT-12273 "Replace with operator" intention is suggested for some non-operator functions and produces invalid code

---

idea/resources/META-INF/plugin-common.xml

It was deleted by 0439536.
https://youtrack.jetbrains.com/issue/KT-28699

Add ConvertToAlsoIntention to plugin-common.xml

---

idea/src/org/jetbrains/kotlin/idea/inspections/RemoveRedundantBackticksInspection.kt
idea/testData/inspectionsLocal/removeRedundantBackticks/underscore.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-28592

KT-28592 False positive "Remove redundant backticks" for underscore variable name

---

compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/checkers/SuspensionPointInsideMutexLockChecker.kt
compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/diagnostics/DefaultErrorMessagesJvm.java
compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/diagnostics/ErrorsJvm.java
compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/platform/JvmPlatformConfigurator.kt
compiler/testData/cli/jvm/suspensionPointInMonitor.out
compiler/testData/diagnostics/testsWithStdLib/coroutines/suspensionPointInMonitor.kt
compiler/testData/diagnostics/testsWithStdLib/coroutines/suspensionPointInMonitorNewInf.kt

See SuspensionPointInsideCriticalSectionChecker

Error on calling suspend functions inside Lock.withLock body

---

compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/CommonBackendContext.kt
compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/IrUtils.kt
compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/StringConcatenationLowering.kt
compiler/ir/backend.common/src/org/jetbrains/kotlin/ir/util/IrTypeUtils.kt
compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/lower/inline/DeepCopyIrTreeWithDescriptors.kt
compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/Psi2IrTranslator.kt
compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ModuleGenerator.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/builders/Scope.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/types/irTypes.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DeclarationStubGenerator.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DeepCopyIrTreeWithSymbols.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DeepCopySymbolRemapper.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DescriptorsRemapper.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DumpIrTree.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/ExternalDependenciesGenerator.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/SymbolTable.kt

mostly dealing with less descriptors, and more IR. 
The (null for now) deserializer plumbing in place.

Several changes in preparation for IR deserialization

---

idea/src/org/jetbrains/kotlin/idea/intentions/ObjectLiteralToLambdaIntention.kt
idea/testData/inspectionsLocal/objectLiteralToLambda/.inspection
idea/testData/inspectionsLocal/objectLiteralToLambda/notMatchFunctionParameterType.1.java
idea/testData/inspectionsLocal/objectLiteralToLambda/notMatchFunctionParameterType.1.java.after
idea/testData/inspectionsLocal/objectLiteralToLambda/notMatchFunctionParameterType.kt
idea/testData/inspectionsLocal/objectLiteralToLambda/notMatchFunctionParameterType.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-28081

KT-28081 "Convert to lambda" changes expression type for interface with multiple supertypes

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantLambdaArrowInspection.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/typeParameter.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/typeParameter2.kt
idea/testData/inspectionsLocal/redundantLambdaArrow/typeParameter3.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-28131

KT-28131 False positive "Redundant lambda arrow" with a functional type argument

---

idea/src/org/jetbrains/kotlin/idea/actions/JavaToKotlinAction.kt
idea/src/org/jetbrains/kotlin/idea/actions/JavaToKotlinAction.kt.181
idea/src/org/jetbrains/kotlin/idea/actions/JavaToKotlinAction.kt.as31
idea/src/org/jetbrains/kotlin/idea/actions/JavaToKotlinAction.kt.as32

https://youtrack.jetbrains.com/issue/KT-27869

KT-27869: Convert Java to Kotlin dialog ask yes/no question but shows OK/Cancel buttons

---

idea/src/org/jetbrains/kotlin/idea/intentions/RemoveEmptyClassBodyIntention.kt

https://youtrack.jetbrains.com/issue/KT-29567

KT-29567 "Remove empty class body" is a poor name for inspection text

---

idea/resources/META-INF/plugin-common.xml
idea/resources/inspectionDescriptions/RedundantEnumConstructorInvocation.html
idea/src/org/jetbrains/kotlin/idea/inspections/RedundantEnumConstructorInvocationInspection.kt
idea/testData/inspectionsLocal/redundantEnumConstructorInvocation/.inspection
idea/testData/inspectionsLocal/redundantEnumConstructorInvocation/basic.kt
idea/testData/inspectionsLocal/redundantEnumConstructorInvocation/basic.kt.after
idea/testData/inspectionsLocal/redundantEnumConstructorInvocation/basic2.kt
idea/testData/inspectionsLocal/redundantEnumConstructorInvocation/basic2.kt.after
idea/testData/inspectionsLocal/redundantEnumConstructorInvocation/hasArgument.kt
idea/testData/inspectionsLocal/redundantEnumConstructorInvocation/hasError.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-29321

KT-29321 "Remove empty primary constructor": apply for enum entries

---

idea/src/org/jetbrains/kotlin/idea/intentions/declarations/ConvertMemberToExtensionIntention.kt
idea/testData/intentions/declarations/convertMemberToExtension/privateInInternalClass.kt
idea/testData/intentions/declarations/convertMemberToExtension/privateInInternalClass.kt.after
idea/testData/intentions/declarations/convertMemberToExtension/publicInInternalClass.kt
idea/testData/intentions/declarations/convertMemberToExtension/publicInInternalClass.kt.after
idea/testData/intentions/declarations/convertMemberToExtension/publicInPrivateClass.kt
idea/testData/intentions/declarations/convertMemberToExtension/publicInPrivateClass.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-29248

KT-29248 "Convert member to extension" doesn't preserve visibility

---

idea/resources/META-INF/plugin-common.xml
idea/resources/inspectionDescriptions/RedundantRequireNotNullCall.html
idea/src/org/jetbrains/kotlin/idea/inspections/RedundantRequireNotNullCallInspection.kt
idea/testData/inspectionsLocal/redundantRequireNotNullCall/.inspection
idea/testData/inspectionsLocal/redundantRequireNotNullCall/checkNotNull.kt
idea/testData/inspectionsLocal/redundantRequireNotNullCall/checkNotNull.kt.after
idea/testData/inspectionsLocal/redundantRequireNotNullCall/notNull.kt
idea/testData/inspectionsLocal/redundantRequireNotNullCall/notNull.kt.after
idea/testData/inspectionsLocal/redundantRequireNotNullCall/notNull2.kt
idea/testData/inspectionsLocal/redundantRequireNotNullCall/notNull2.kt.after
idea/testData/inspectionsLocal/redundantRequireNotNullCall/notNull3.kt
idea/testData/inspectionsLocal/redundantRequireNotNullCall/notNull3.kt.after
idea/testData/inspectionsLocal/redundantRequireNotNullCall/nullable.kt
idea/testData/inspectionsLocal/redundantRequireNotNullCall/nullable2.kt
idea/testData/inspectionsLocal/redundantRequireNotNullCall/require.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-29113

KT-29113 Warn about  redundant requireNotNull and checkNotNull usages

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPrimaryConstructorToSecondaryIntention.kt
idea/testData/intentions/convertPrimaryConstructorToSecondary/noArgNameVal.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-29056

KT-29056 KNPE in ConvertPrimaryConstructorToSecondary with missing property identifier

---

idea/idea-gradle/src/org/jetbrains/kotlin/idea/configuration/KotlinGradleAbstractMultiplatformModuleBuilder.kt

#KT-28522 supposed to be fixed with this

Bump gradle version in template projects

---

idea/src/org/jetbrains/kotlin/idea/intentions/ObjectLiteralToLambdaIntention.kt
idea/testData/intentions/objectLiteralToLambda/inspectionData/expected.xml

https://youtrack.jetbrains.com/issue/KT-29763

KT-29763 False negative "Object literal can be converted to lambda" for block body function with explicit return

---

libraries/stdlib/common/src/kotlin/TextH.kt
libraries/stdlib/js/src/kotlin/regex.kt
libraries/stdlib/jvm/src/kotlin/text/regex/Regex.kt
libraries/stdlib/samples/test/samples/text/regex.kt

KT-20357 - add sample for Regex.findAll()

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertToScopeIntention.kt
idea/testData/intentions/convertToScope/convertToAlso/callExpression5.kt.after
idea/testData/intentions/convertToScope/convertToAlso/singleCall.kt
idea/testData/intentions/convertToScope/convertToAlso/singleCall.kt.after
idea/testData/intentions/convertToScope/convertToApply/callExpression5.kt.after
idea/testData/intentions/convertToScope/convertToApply/singleCall.kt
idea/testData/intentions/convertToScope/convertToApply/singleCall.kt.after
idea/testData/intentions/convertToScope/convertToRun/methodChainWithThisParameter.kt.after
idea/testData/intentions/convertToScope/convertToRun/singleCall.kt
idea/testData/intentions/convertToScope/convertToRun/singleCall.kt.after
idea/testData/intentions/convertToScope/convertToWith/methodChainWithThisParameter.kt
idea/testData/intentions/convertToScope/convertToWith/methodChainWithThisParameter.kt.after
idea/testData/intentions/convertToScope/convertToWith/singleCall.kt
idea/testData/intentions/convertToScope/convertToWith/singleCall.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-29099

KT-29099 "Convert to apply" intention is not available for a single function call

---

compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
compiler/tests/org/jetbrains/kotlin/generators/tests/GenerateCompilerTests.kt

as BytecodeTextTestGenerated is only available to JVM.

Set target backend of BytecodeTextTestGenerated to JVM

---

idea/resources/inspectionDescriptions/MapGetWithNotNullAssertionOperator.html
idea/src/org/jetbrains/kotlin/idea/inspections/MapGetWithNotNullAssertionOperatorInspection.kt
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/get.kt
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/get.kt.after
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/indexedAccess.kt.after
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/replaceWithElvisError.kt
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/replaceWithElvisError.kt.after
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/replaceWithGetOrElse.kt
idea/testData/inspectionsLocal/mapGetWithNotNullAssertionOperator/replaceWithGetOrElse.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30010

KT-30010 Introduce alternative quick-fixes for `map[key]!!`

---

idea/resources/META-INF/plugin-common.xml
idea/resources/inspectionDescriptions/KotlinThrowableNotThrown.html
idea/src/org/jetbrains/kotlin/idea/inspections/KotlinThrowableNotThrownInspection.kt
idea/testData/inspectionsLocal/throwableNotThrown/.inspection
idea/testData/inspectionsLocal/throwableNotThrown/basic.kt
idea/testData/inspectionsLocal/throwableNotThrown/basic2.kt
idea/testData/inspectionsLocal/throwableNotThrown/basic3.kt
idea/testData/inspectionsLocal/throwableNotThrown/field.kt
idea/testData/inspectionsLocal/throwableNotThrown/if.kt
idea/testData/inspectionsLocal/throwableNotThrown/if2.kt
idea/testData/inspectionsLocal/throwableNotThrown/if3.kt
idea/testData/inspectionsLocal/throwableNotThrown/if4.kt
idea/testData/inspectionsLocal/throwableNotThrown/if5.kt
idea/testData/inspectionsLocal/throwableNotThrown/nullable.kt
idea/testData/inspectionsLocal/throwableNotThrown/property.kt
idea/testData/inspectionsLocal/throwableNotThrown/property2.kt
idea/testData/inspectionsLocal/throwableNotThrown/property3.kt
idea/testData/inspectionsLocal/throwableNotThrown/property4.kt
idea/testData/inspectionsLocal/throwableNotThrown/property5.kt
idea/testData/inspectionsLocal/throwableNotThrown/return.kt
idea/testData/inspectionsLocal/throwableNotThrown/return2.kt
idea/testData/inspectionsLocal/throwableNotThrown/throw.kt
idea/testData/inspectionsLocal/throwableNotThrown/when.kt
idea/testData/inspectionsLocal/throwableNotThrown/when2.kt
idea/testData/inspectionsLocal/throwableNotThrown/when3.kt
idea/testData/inspectionsLocal/throwableNotThrown/when4.kt
idea/testData/inspectionsLocal/throwableNotThrown/when5.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-11629

KT-11629 Inspection: creating Throwable without throwing it

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPropertyInitializerToGetterIntention.kt
idea/testData/intentions/convertPropertyInitializerToGetter/onPropertyName.kt
idea/testData/intentions/convertPropertyInitializerToGetter/onPropertyName.kt.after
idea/testData/quickfix/removeUnused/usedVarAsAlias.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-29344

KT-29344 Add "convert to getter" intention

---

idea/src/org/jetbrains/kotlin/idea/quickfix/SurroundWithNullCheckFix.kt
idea/testData/quickfix/surroundWithNullCheck/assignment.kt
idea/testData/quickfix/surroundWithNullCheck/assignment.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30215

KT-30215 No "surround with null" check is suggested for an assignment

---

idea/src/org/jetbrains/kotlin/idea/intentions/ImportAllMembersIntention.kt
idea/testData/intentions/importAllMembers/TypeReference.1.kt
idea/testData/intentions/importAllMembers/TypeReference.1.kt.after
idea/testData/intentions/importAllMembers/TypeReference.kt
idea/testData/intentions/importAllMembers/TypeReference.kt.after
idea/testData/intentions/importAllMembers/TypeReference2.1.kt
idea/testData/intentions/importAllMembers/TypeReference2.1.kt.after
idea/testData/intentions/importAllMembers/TypeReference2.kt
idea/testData/intentions/importAllMembers/TypeReference2.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-29927

KT-29927 Missing "Import members from" intention with type check operator in `when` branch

---

idea/resources/inspectionDescriptions/ReplaceNegatedIsEmptyWithIsNotEmpty.html
idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceNegatedIsEmptyWithIsNotEmptyInspection.kt
idea/testData/inspectionsLocal/replaceNegatedIsEmptyWithIsNotEmpty/notNegate.kt
idea/testData/inspectionsLocal/replaceNegatedIsEmptyWithIsNotEmpty/stringIsEmpty.kt
idea/testData/inspectionsLocal/replaceNegatedIsEmptyWithIsNotEmpty/stringIsEmpty.kt.after
idea/testData/inspectionsLocal/replaceNegatedIsEmptyWithIsNotEmpty/stringIsNotEmpty.kt
idea/testData/inspectionsLocal/replaceNegatedIsEmptyWithIsNotEmpty/stringIsNotEmpty.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30123

KT-30123 Add intention to replace isEmpty/isNotEmpty method negation

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
compiler/testData/codegen/box/controlStructures/kt12908.kt
compiler/testData/codegen/box/controlStructures/kt12908_2.kt

...since they confuse the Java verifier.
The fix already exists for while loops, this is the same thing for do...while loops.

Avoid true condition generation for do while loops

---

idea/src/org/jetbrains/kotlin/idea/intentions/SpecifyTypeExplicitlyIntention.kt
idea/testData/inspections/hasPlatformType/extensionOnDynamic.kt

https://youtrack.jetbrains.com/issue/KT-29812

KT-29812 False positive for HasPlatformType with member extension on 'dynamic'

---

idea/resources/META-INF/plugin-common.xml

https://youtrack.jetbrains.com/issue/KT-29869

KT-29869 Disable `WhenWithOnlyElse` by default.

---

compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/serialization/DeserializeDescriptorReference.kt

This is a port of kotlin-native fix
* commit 575cbf48c3d839a963c3cdbe28d8fe41c85fe866
| Author: SvyatoslavScherbina <Svyatoslav.Scherbina@jetbrains.com>
| Date:   Thu Mar 14 14:25:10 2019 +0300
|
|     Optimize DescriptorReferenceDeserializer again (#2755)
to common ir deserializer.

Copy of kotlin-native fix "Optimize DescriptorReferenceDeserializer again (#2755)"

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/UnfoldReturnToIfIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/UnfoldReturnToWhenIntention.kt
idea/testData/intentions/branched/unfolding/returnToIf/labeledReturn.kt
idea/testData/intentions/branched/unfolding/returnToIf/labeledReturn.kt.after
idea/testData/intentions/branched/unfolding/returnToWhen/labeledReturn.kt
idea/testData/intentions/branched/unfolding/returnToWhen/labeledReturn.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30414

KT-30414 "Replace return with 'if' expression" drops return label

---

idea/resources/META-INF/plugin-common.xml
idea/resources/intentionDescriptions/RenameClassToContainingFileNameIntention/after.kt.template
idea/resources/intentionDescriptions/RenameClassToContainingFileNameIntention/before.kt.template
idea/resources/intentionDescriptions/RenameClassToContainingFileNameIntention/description.html
idea/src/org/jetbrains/kotlin/idea/intentions/RenameClassToContainingFileNameIntention.kt
idea/testData/intentions/renameClassToContainingFileName/.intention
idea/testData/intentions/renameClassToContainingFileName/Basic.kt
idea/testData/intentions/renameClassToContainingFileName/Basic.kt.after
idea/testData/intentions/renameClassToContainingFileName/Basic2.kt
idea/testData/intentions/renameClassToContainingFileName/Basic2.kt.after
idea/testData/intentions/renameClassToContainingFileName/HasSameNameClass.kt
idea/testData/intentions/renameClassToContainingFileName/HasSameNameObject.kt
idea/testData/intentions/renameClassToContainingFileName/SameName.kt
idea/testData/intentions/renameClassToContainingFileName/startWithLowerCase.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-25262

KT-25262 Intention: Rename class to containing file name

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertToScopeIntention.kt
idea/testData/intentions/convertToScope/convertToApply/binaryExpression.kt
idea/testData/intentions/convertToScope/convertToApply/binaryExpression.kt.after
idea/testData/intentions/convertToScope/convertToApply/binaryExpression2.kt
idea/testData/intentions/convertToScope/convertToApply/binaryExpression2.kt.after
idea/testData/intentions/convertToScope/convertToApply/binaryExpression3.kt
idea/testData/intentions/convertToScope/convertToApply/binaryExpression4.kt
idea/testData/intentions/convertToScope/convertToApply/binaryExpression5.kt
idea/testData/intentions/convertToScope/convertToRun/binaryExpression.kt
idea/testData/intentions/convertToScope/convertToRun/binaryExpression.kt.after
idea/testData/intentions/convertToScope/convertToRun/binaryExpression2.kt
idea/testData/intentions/convertToScope/convertToRun/binaryExpression2.kt.after
idea/testData/intentions/convertToScope/convertToRun/binaryExpression3.kt
idea/testData/intentions/convertToScope/convertToRun/binaryExpression3.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30228

KT-30228 'Convert to also/apply/run/with' intention behaves differently depending on the position of infix function call

---

idea/src/org/jetbrains/kotlin/idea/inspections/NestedLambdaShadowedImplicitParameterInspection.kt
idea/src/org/jetbrains/kotlin/idea/inspections/collections/FunctionUtils.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/scopeFunction.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/scopeFunction2.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/scopeFunction3.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/scopeFunction4.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/scopeFunction5.kt
idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/scopeFunction5.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30173

KT-30173 "Nested lambda has shadowed implicit parameter" is suggested when both parameters are logically the same

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeToStarProjectionFix.kt
idea/testData/quickfix/addStarProjections/cast/extensionReceiver.kt
idea/testData/quickfix/addStarProjections/cast/extensionReceiver2.kt
idea/testData/quickfix/addStarProjections/cast/extensionReceiver3.kt
idea/testData/quickfix/addStarProjections/cast/extensionReceiver3.kt.after
idea/testData/quickfix/addStarProjections/cast/extensionReceiver4.kt
idea/testData/quickfix/addStarProjections/cast/extensionReceiver4.kt.after
idea/testData/quickfix/addStarProjections/cast/extensionReceiver5.kt
idea/testData/quickfix/addStarProjections/cast/extensionReceiver5.kt.after
idea/testData/quickfix/addStarProjections/cast/valueArgument.kt
idea/testData/quickfix/addStarProjections/cast/valueArgument2.kt
idea/testData/quickfix/addStarProjections/cast/valueArgument3.kt
idea/testData/quickfix/addStarProjections/cast/valueArgument3.kt.after
idea/testData/quickfix/addStarProjections/cast/valueArgument4.kt
idea/testData/quickfix/addStarProjections/cast/valueArgument4.kt.after
idea/testData/quickfix/addStarProjections/cast/valueArgument5.kt
idea/testData/quickfix/addStarProjections/cast/valueArgument5.kt.after
idea/testData/quickfix/addStarProjections/cast/valueArgument6.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-23259

KT-23259 False positive unchecked cast warning/quickfix result in good code turning red

---

idea/src/org/jetbrains/kotlin/idea/quickfix/AddWhenRemainingBranchesFix.kt
idea/testData/quickfix/when/addRemainingBranchesBlankLine.kt
idea/testData/quickfix/when/addRemainingBranchesBlankLine.kt.after
idea/testData/quickfix/when/addRemainingBranchesBlankLineWithComment.kt
idea/testData/quickfix/when/addRemainingBranchesBlankLineWithComment.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30426

KT-30426 Don't preserve extra line when adding remaining branches for when

---

idea/resources/META-INF/gradle-groovy.xml
idea/resources/META-INF/gradle-java.xml
idea/resources/META-INF/gradle-java.xml.191
idea/resources/META-INF/gradle-java.xml.as33
idea/resources/META-INF/gradle-java.xml.as34

otherwise, a user who disables Groovy support gets NoClassDefFound errors
Fixes https://youtrack.jetbrains.com/issue/KT-30579

only load inspections when groovy plugin is present KT-30579

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantGetterInspection.kt
idea/src/org/jetbrains/kotlin/idea/inspections/RedundantSetterInspection.kt
idea/testData/inspectionsLocal/redundantSetter/lowerVisibility1.kt
idea/testData/inspectionsLocal/redundantSetter/lowerVisibility2.kt
idea/testData/inspectionsLocal/redundantSetter/lowerVisibility3.kt
idea/testData/inspectionsLocal/redundantSetter/sameVisibility1.kt
idea/testData/inspectionsLocal/redundantSetter/sameVisibility2.kt
idea/testData/inspectionsLocal/redundantSetter/sameVisibility3.kt

https://youtrack.jetbrains.com/issue/KT-30559

KT-30559 Redundant Getter, Redundant Setter: reduce range to getter/setter header

---

build.gradle.kts
compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/parseCommandLineArguments.kt
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/NewMultiplatformIT.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/tasks/KotlinNativeTasks.kt

This is same fix https://github.com/JetBrains/kotlin/pull/2206 but based on version of kotlin which works fine for kotlin-native.

Fix parser for linkerOpts/compilerOpts (KT-29970)

---

libraries/stdlib/common/src/generated/_Arrays.kt
libraries/stdlib/common/src/generated/_Collections.kt
libraries/stdlib/common/src/generated/_Sequences.kt
libraries/stdlib/common/src/generated/_Strings.kt
libraries/stdlib/common/src/generated/_UArrays.kt
libraries/tools/kotlin-stdlib-gen/src/templates/Aggregates.kt

https://youtrack.jetbrains.com/issue/KT-30451

KT-30451 Redundant call of selector in maxBy&minBy

---

idea/resources/META-INF/plugin-common.xml

https://youtrack.jetbrains.com/issue/KT-30876

KT-30876 SimplifyNotNullAssert inspection changes semantics

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrSourceCompilerForInline.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/PromisedValue.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/SwitchGenerator.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/ArrayConstructor.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/CompareTo.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/Concat.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/Equals.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IntrinsicMethod.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/JavaClassProperty.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/KClassJavaProperty.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/Not.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/RangeTo.kt
compiler/testData/codegen/box/primitiveTypes/kt2269NotOptimizable.kt
compiler/testData/codegen/bytecodeText/coercionToUnitOptimization/largeMethodWithCoercionToUnit.kt
compiler/testData/codegen/bytecodeText/intrinsicsCompare/charSmartCast.kt
compiler/testData/codegen/bytecodeText/intrinsicsCompare/longSmartCast.kt

JVM_IR: remove most uses of StackValue from ExpressionCodegen

---

idea/idea-core/src/org/jetbrains/kotlin/idea/core/psiModificationUtils.kt
idea/testData/intentions/lambdaToAnonymousFunction/javaMethod.1.java
idea/testData/intentions/lambdaToAnonymousFunction/javaMethod.1.java.after
idea/testData/intentions/lambdaToAnonymousFunction/javaMethod.kt
idea/testData/intentions/lambdaToAnonymousFunction/javaMethod.kt.after
idea/testData/intentions/moveLambdaInsideParentheses/javaMethod.1.java
idea/testData/intentions/moveLambdaInsideParentheses/javaMethod.1.java.after
idea/testData/intentions/moveLambdaInsideParentheses/javaMethod.kt
idea/testData/intentions/moveLambdaInsideParentheses/javaMethod.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30613

KT-30613 "Convert to anonymous function" should not insert named argument when interoping with Java functions

---

idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceAssertBooleanWithAssertEqualityInspection.kt
idea/testData/inspectionsLocal/replaceAssertBooleanWithAssertEquality/notSubtype.kt
idea/testData/inspectionsLocal/replaceAssertBooleanWithAssertEquality/notSubtype2.kt
idea/testData/inspectionsLocal/replaceAssertBooleanWithAssertEquality/subtype.kt
idea/testData/inspectionsLocal/replaceAssertBooleanWithAssertEquality/subtype.kt.after
idea/testData/inspectionsLocal/replaceAssertBooleanWithAssertEquality/subtype2.kt
idea/testData/inspectionsLocal/replaceAssertBooleanWithAssertEquality/subtype2.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30761

KT-30761 Replace assert boolean with assert equality produces uncompilable code when compared arguments type are different

---

libraries/kotlin.test/js/it/js/qunit-reporter.js
libraries/kotlin.test/js/src/main/kotlin/kotlin/test/FrameworkAdapter.kt
libraries/kotlin.test/js/src/main/kotlin/kotlin/test/adapters/BareAdapter.kt
libraries/kotlin.test/js/src/main/kotlin/kotlin/test/adapters/Externals.kt
libraries/kotlin.test/js/src/main/kotlin/kotlin/test/adapters/JasmineLikeAdapter.kt
libraries/kotlin.test/js/src/main/kotlin/kotlin/test/adapters/QUnitAdapter.kt

https://youtrack.jetbrains.com/issue/KT-22807

KT-22807: allow asynchronous testing in Kotlin/JS with QUnit

---

idea/src/org/jetbrains/kotlin/idea/intentions/InvertIfConditionIntention.kt
idea/testData/intentions/invertIfCondition/notBlock4.kt
idea/testData/intentions/invertIfCondition/notBlock4.kt.after
idea/testData/intentions/invertIfCondition/notBlock5.kt
idea/testData/intentions/invertIfCondition/notBlock5.kt.after
idea/testData/intentions/invertIfCondition/notBlock6.kt
idea/testData/intentions/invertIfCondition/notBlock6.kt.after
idea/testData/intentions/invertIfCondition/notBlock7.kt
idea/testData/intentions/invertIfCondition/notBlock7.kt.after
idea/testData/intentions/invertIfCondition/notBlock8.kt
idea/testData/intentions/invertIfCondition/notBlock8.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30900

KT-30900 Invert 'if' condition respects neither code formatting nor inline comments

---

idea/src/org/jetbrains/kotlin/idea/intentions/LambdaToAnonymousFunctionIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/SamConversionToAnonymousObjectIntention.kt
idea/testData/intentions/samConversionToAnonymousObject/typeArgument.1.java
idea/testData/intentions/samConversionToAnonymousObject/typeArgument.1.java.after
idea/testData/intentions/samConversionToAnonymousObject/typeArgument.kt
idea/testData/intentions/samConversionToAnonymousObject/typeArgument.kt.after
idea/testData/quickfix/convertToAnonymousObject/typeArgument.kt
idea/testData/quickfix/convertToAnonymousObject/typeArgument.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30208

KT-30208 Convert to anonymous object: lambda generic type argument is lost

---

idea/src/org/jetbrains/kotlin/idea/quickfix/AddFunctionToSupertypeFix.kt
idea/testData/quickfix/override/nothingToOverride/addFunctionSealedClass.kt
idea/testData/quickfix/override/nothingToOverride/addFunctionSealedClass.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30769

KT-30769 Override quickfix creates "sealed fun"

---

idea/idea-analysis/src/org/jetbrains/kotlin/idea/inspections/IntentionBasedInspection.kt
idea/src/org/jetbrains/kotlin/idea/intentions/UsePropertyAccessSyntaxIntention.kt
idea/testData/inspectionsLocal/usePropertyAccessSyntax/.inspection
idea/testData/inspectionsLocal/usePropertyAccessSyntax/caretOnValueArgumentList.kt
idea/testData/inspectionsLocal/usePropertyAccessSyntax/get.kt
idea/testData/inspectionsLocal/usePropertyAccessSyntax/get.kt.after
idea/testData/inspectionsLocal/usePropertyAccessSyntax/set.kt
idea/testData/inspectionsLocal/usePropertyAccessSyntax/set.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30910

KT-30910 "Use property access syntax" is not suitable as text for inspection problem text

---

libraries/kotlinx-metadata/src/kotlinx/metadata/visitors.kt

https://youtrack.jetbrains.com/issue/KT-31138

Fix a typo

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/ToArrayLowering.kt

by not running DFS from every node visited during another DFS.

JVM_IR: make ToArrayLowering linear in complexity

---

build.gradle.kts
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/tasks/KotlinNativeTasks.kt

I'll change compiler version when it is built.
Connected review - https://github.com/JetBrains/kotlin-native/pull/2915

Unify compiler and cinterop flags names

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/branchedTransformationUtils.kt
idea/testData/inspectionsLocal/branched/introduceWhenSubject/this.kt
idea/testData/inspectionsLocal/branched/introduceWhenSubject/this.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-12567

KT-12567 "Introduce 'when' subject" intention does not work for "this" in extension function

---

idea/src/org/jetbrains/kotlin/idea/intentions/RemoveBracesIntention.kt
idea/testData/intentions/removeBraces/elseInDotQualifiedExpression.kt.after
idea/testData/intentions/removeBraces/elseInPlusAssignExpression.kt
idea/testData/intentions/removeBraces/elseInPlusAssignExpression.kt.after
idea/testData/intentions/removeBraces/for.kt.after
idea/testData/intentions/removeBraces/forWithLocalVariable.kt
idea/testData/intentions/removeBraces/if.kt.after

https://youtrack.jetbrains.com/issue/KT-31443

KT-31443 Remove braces intention places caret in a wrong place

---

idea/src/org/jetbrains/kotlin/idea/highlighter/KotlinSuspendCallLineMarkerProvider.kt
idea/testData/inspections/redundantSuspendModifier/operators.kt

https://youtrack.jetbrains.com/issue/KT-25465

KT-25465 "Redundant 'suspend' modifier" with suspend operator invoke

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPropertyToFunctionIntention.kt
idea/testData/intentions/convertPropertyToFunction/expressionBodyWithGenericType.kt
idea/testData/intentions/convertPropertyToFunction/expressionBodyWithGenericType.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-29192

KT-29192 "Convert property to function" with explicit generic type loses getter body

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/ElvisToIfThenIntention.kt
idea/testData/intentions/branched/elvisToIfThen/assignmentAndBreak.kt
idea/testData/intentions/branched/elvisToIfThen/assignmentAndBreak.kt.after
idea/testData/intentions/branched/elvisToIfThen/assignmentAndContinue.kt
idea/testData/intentions/branched/elvisToIfThen/assignmentAndContinue.kt.after
idea/testData/intentions/branched/elvisToIfThen/assignmentAndReturn.kt
idea/testData/intentions/branched/elvisToIfThen/assignmentAndReturn.kt.after
idea/testData/intentions/branched/elvisToIfThen/assignmentAndThrow.kt
idea/testData/intentions/branched/elvisToIfThen/assignmentAndThrow.kt.after
idea/testData/intentions/branched/elvisToIfThen/safeCastAndReturn.kt
idea/testData/intentions/branched/elvisToIfThen/safeCastAndReturn.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-14369

KT-14369 "Replace elvis expression with 'if" intention produces boilerplate code for 'return' in RHS

---

libraries/stdlib/common/src/generated/_Arrays.kt
libraries/stdlib/common/src/generated/_Collections.kt
libraries/stdlib/common/src/generated/_Maps.kt
libraries/stdlib/common/src/generated/_Sequences.kt
libraries/stdlib/common/src/generated/_Strings.kt
libraries/stdlib/common/src/generated/_UArrays.kt
libraries/stdlib/samples/test/samples/collections/collections.kt
libraries/stdlib/samples/test/samples/collections/maps.kt
libraries/stdlib/samples/test/samples/text/strings.kt
libraries/tools/kotlin-stdlib-gen/src/templates/Mapping.kt

Small code sample for the collections.map() function

Add map() documentation sample

---

compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/FlattenStringConcatenationLowering.kt

This makes the check more precise, in case there are future extensions to the standard library, as discussed [here](https://github.com/JetBrains/kotlin/pull/2244#discussion_r284272433).

Use FQ names for string plus intrinsic in FlattenStringConcatenationLowering

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IrIntrinsicMethods.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/OrOr.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmBuiltinOptimizationLowering.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/descriptors/IrBuiltIns.kt
compiler/testData/codegen/bytecodeText/conditions/disjunction.kt
compiler/testData/codegen/bytecodeText/conditions/negatedDisjunction.kt

This is a follow up for [conjunction optimization](https://github.com/JetBrains/kotlin/pull/2283)

JVM_IR: Optimize disjunction condition with intrinsic function call.

---

libraries/tools/kotlin-bom/pom.xml

build: add kotlin-compiler-embeddable to BOM

---

idea/src/org/jetbrains/kotlin/idea/quickfix/replaceWith/DeprecatedSymbolUsageFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/replaceWith/DeprecatedSymbolUsageFixBase.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/replaceWith/DeprecatedSymbolUsageInWholeProjectFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/replaceWith/ReplaceWithAnnotationAnalyzer.kt
idea/testData/quickfix/deprecatedSymbolUsage/classUsages/innerType.kt
idea/testData/quickfix/deprecatedSymbolUsage/classUsages/innerType.kt.after
idea/testData/quickfix/deprecatedSymbolUsage/typeAliases/withTypeArgument.kt
idea/testData/quickfix/deprecatedSymbolUsage/typeAliases/withTypeArgument.kt.after
idea/testData/quickfix/deprecatedSymbolUsage/typeArguments/classLiteral.kt
idea/testData/quickfix/deprecatedSymbolUsage/typeArguments/classLiteral.kt.after
idea/testData/quickfix/deprecatedSymbolUsage/typeArguments/classLiteral2.kt
idea/testData/quickfix/deprecatedSymbolUsage/typeArguments/classLiteral2.kt.after
idea/testData/quickfix/deprecatedSymbolUsage/typeArguments/explicitTypeArg2.kt
idea/testData/quickfix/deprecatedSymbolUsage/typeArguments/explicitTypeArg2.kt.after
idea/testData/quickfix/deprecatedSymbolUsage/typeArguments/typeReference.kt
idea/testData/quickfix/deprecatedSymbolUsage/typeArguments/typeReference.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/DeprecatedSymbolUsageFixSpecialTest.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-8958

KT-8958 ReplaceWith intention message could be more helpful in case of generic substitution

---

idea/src/org/jetbrains/kotlin/idea/inspections/ExplicitThisInspection.kt
idea/testData/inspectionsLocal/explicitThis/differentReceiverInstanceExtension2.kt
idea/testData/inspectionsLocal/explicitThis/differentReceiverInstanceExtension3.kt
idea/testData/inspectionsLocal/explicitThis/differentReceiverInstanceExtension4.kt
idea/testData/inspectionsLocal/explicitThis/differentReceiverInstanceExtension4.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-27550

KT-27550 "Redundant explicit this" false positive with subclass and extension lambda

---

idea/src/org/jetbrains/kotlin/idea/actions/KotlinAddImportAction.kt

https://youtrack.jetbrains.com/issue/KT-17916
Currently, the `KotlinAddImportAction` doesn't highlight deprecated Psi elements. At the moment I just copy-pasted the java implementation from `AddImportAction.java`.
|Before|After|
|-----|------|
|![class_before](https://user-images.githubusercontent.com/930370/59795637-f789b100-92db-11e9-9bb7-6d6803a8115c.png)|![class_kt](https://user-images.githubusercontent.com/930370/59795649-fce6fb80-92db-11e9-869b-7cb167564996.png)|
|![function_before](https://user-images.githubusercontent.com/930370/59795749-37509880-92dc-11e9-831d-e77d5a1e0aa5.png)|![function_kt](https://user-images.githubusercontent.com/930370/59795755-3c154c80-92dc-11e9-8178-08f7ae09d113.png)|
Something to consider: feels like common logic from `KotlinAddImportAction.kt`, …

KT-17916: Import popup does not indicate deprecated classes

---

compiler/ir/serialization.common/src/org/jetbrains/kotlin/backend/common/serialization/IrModuleDeserializer.kt

Bind WrappedVariableDescriptorWithAccessors in IR deserializer

---

idea/src/org/jetbrains/kotlin/idea/intentions/RemoveArgumentNameIntention.kt
idea/testData/intentions/removeArgumentName/arrayLiteral.kt
idea/testData/intentions/removeArgumentName/arrayLiteral.kt.after
idea/testData/intentions/removeArgumentName/arrayLiteralForVararg.kt
idea/testData/intentions/removeArgumentName/arrayLiteralForVararg.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-32318

KT-32318 "Remove argument name" intention does not remove square braces for annotation vararg argument

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantVisibilityModifierInspection.kt
idea/testData/quickfix/redundantVisibilityModifier/getter.kt
idea/testData/quickfix/redundantVisibilityModifier/getter.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-32347

KT-32347 Duplicative "Remove redundant 'public' modifier" suggestion for getter

---

libraries/stdlib/samples/test/samples/collections/maps.kt
libraries/stdlib/src/kotlin/collections/Maps.kt

KT-20357 Add sample code for hashMapOf

---

idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceGuardClauseWithFunctionCallInspection.kt
idea/testData/inspectionsLocal/replaceGuardClauseWithFunctionCall/require/hasElse.kt
idea/testData/inspectionsLocal/replaceGuardClauseWithFunctionCall/require/hasElse.kt.after
idea/testData/inspectionsLocal/replaceGuardClauseWithFunctionCall/require/hasElse2.kt
idea/testData/inspectionsLocal/replaceGuardClauseWithFunctionCall/require/hasElse2.kt.after
idea/testData/inspectionsLocal/replaceGuardClauseWithFunctionCall/require/hasElse3.kt
idea/testData/inspectionsLocal/replaceGuardClauseWithFunctionCall/require/hasElse3.kt.after
idea/testData/inspectionsLocal/replaceGuardClauseWithFunctionCall/requireNotNull/hasElse.kt
idea/testData/inspectionsLocal/replaceGuardClauseWithFunctionCall/requireNotNull/hasElse.kt.after
idea/testData/inspectionsLocal/replaceGuardClauseWithFunctionCall/usedAsExpression.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-32797

KT-32797 Guard clause (check/require/...) inspection: handle case with if/else correctly

---

compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/ArrayConstructorLowering.kt

This is a minor performance fix. Currently, `ArrayConstructorLowering` always looks at the declarations contained in the array classes (`Array<T>`, `IntArray`, ...), which leads to some unnecessary deserialization.

Avoid eager deserialization of array classes in ArrayConstructorLowering

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeToStarProjectionFix.kt
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter.kt
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter2.kt
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter3.kt
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter3.kt.after
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter4.kt
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter4.kt.after
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter5.kt
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter6.kt
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter6.kt.after
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter7.kt
idea/testData/quickfix/addStarProjections/cast/genericTypeParameter7.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30794

KT-30794 Quickfix for unchecked cast produces invalid code

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/IfToWhenIntention.kt
idea/testData/inspectionsLocal/cascadeIf/insideOtherIf.kt.after
idea/testData/inspectionsLocal/cascadeIf/normal.kt
idea/testData/inspectionsLocal/cascadeIf/normal.kt.after
idea/testData/inspectionsLocal/cascadeIf/withAnnotation.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/ifElseSwallowTail.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/multipleIfFake.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/multipleIfWithReturns.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/onElseIf2.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/withAnnotation.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/withInternalLoop.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/withInternalLoopOnly.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/withLoopDeep.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/withLoopDeepAndComments.kt.after
idea/testData/intentions/branched/ifWhen/ifToWhen/withLoopThen.kt.after

https://youtrack.jetbrains.com/issue/KT-32650

KT-32650 "Replace 'if' with 'when'" removes braces from 'if' statement

---

idea/src/org/jetbrains/kotlin/idea/inspections/UnusedSymbolInspection.kt
idea/testData/inspectionsLocal/unusedSymbol/usedEnumFunction.kt
idea/testData/inspectionsLocal/unusedSymbol/usedEnumFunction2.kt
idea/testData/inspectionsLocal/unusedSymbol/usedEnumFunction3.kt
idea/testData/inspectionsLocal/unusedSymbol/usedEnumFunction4.kt
idea/testData/inspectionsLocal/unusedSymbol/usedEnumFunction5.kt
idea/testData/inspectionsLocal/unusedSymbol/usedEnumFunction6.kt
idea/testData/inspectionsLocal/unusedSymbol/usedEnumFunction7.kt
idea/testData/inspectionsLocal/unusedSymbol/usedEnumFunction8.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-31133

KT-31133 Liveness analysis on enum does not take into account calls to 'values'

---

idea/resources/META-INF/plugin-common.xml
idea/resources/intentionDescriptions/ReplaceMapGetOrDefaultIntention/after.kt.template
idea/resources/intentionDescriptions/ReplaceMapGetOrDefaultIntention/before.kt.template
idea/resources/intentionDescriptions/ReplaceMapGetOrDefaultIntention/description.html
idea/src/org/jetbrains/kotlin/idea/intentions/ReplaceMapGetOrDefaultIntention.kt
idea/testData/intentions/replaceMapGetOrDefault/.intention
idea/testData/intentions/replaceMapGetOrDefault/inExpression.kt
idea/testData/intentions/replaceMapGetOrDefault/inExpression.kt.after
idea/testData/intentions/replaceMapGetOrDefault/nullableValue.kt
idea/testData/intentions/replaceMapGetOrDefault/simple.kt
idea/testData/intentions/replaceMapGetOrDefault/simple.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
nj2k/nj2k-services/src/org/jetbrains/kotlin/nj2k/postProcessing/J2kPostProcessor.kt
nj2k/testData/newJ2k/postProcessing/MapGetOrDefault.java
nj2k/testData/newJ2k/postProcessing/MapGetOrDefault.kt
nj2k/tests/org/jetbrains/kotlin/nj2k/NewJavaToKotlinConverterSingleFileTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-21503

KT-21503 J2K: Intention to replace getOrDefault

---

nj2k/nj2k-services/src/org/jetbrains/kotlin/nj2k/postProcessing/J2kPostProcessor.kt
nj2k/testData/newJ2k/postProcessing/GuardClause.java
nj2k/testData/newJ2k/postProcessing/GuardClause.kt
nj2k/tests/org/jetbrains/kotlin/nj2k/NewJavaToKotlinConverterSingleFileTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-22412

KT-22412 J2K: Intention to replace if(...) throw IAE with require

---

nj2k/src/org/jetbrains/kotlin/nj2k/conversions/BuiltinMembersConversion.kt
nj2k/testData/newJ2k/methodCallExpression/specialBuiltinMembers.java
nj2k/testData/newJ2k/methodCallExpression/specialBuiltinMembers.kt

https://youtrack.jetbrains.com/issue/KT-21504

KT-21504 J2K: Convert Long.parseLong(s) to s.toLong()

---

idea/src/org/jetbrains/kotlin/idea/inspections/collections/SimplifiableCallInspection.kt
idea/testData/inspectionsLocal/collections/simplifiableCall/arrayFlatMap.kt
idea/testData/inspectionsLocal/collections/simplifiableCall/arrayFlatMap2.kt
idea/testData/inspectionsLocal/collections/simplifiableCall/arrayFlatMap3.kt
idea/testData/inspectionsLocal/collections/simplifiableCall/arrayFlatMap3.kt.after
idea/testData/inspectionsLocal/collections/simplifiableCall/primitiveArrayFlatMap.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33204

KT-33204 False positive "flatMap call could be simplified to flatten()" with Array

---

idea/idea-core/src/org/jetbrains/kotlin/idea/core/psiModificationUtils.kt
idea/testData/inspectionsLocal/removeCurlyBracesFromTemplate/necessaryBrackets7.kt
idea/testData/inspectionsLocal/removeCurlyBracesFromTemplate/unnecessaryBrackets9.kt
idea/testData/inspectionsLocal/removeCurlyBracesFromTemplate/unnecessaryBrackets9.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-32972

KT-32972 No "remove braces" inspection for ${this}

---

idea/src/org/jetbrains/kotlin/idea/refactoring/pullUp/KotlinPullUpHelper.kt
idea/testData/refactoring/pullUp/k2k/fromClassToClassMakeAbstractWithCommentAndAnotherIndent.kt
idea/testData/refactoring/pullUp/k2k/fromClassToClassMakeAbstractWithCommentAndAnotherIndent.kt.after
idea/testData/refactoring/pullUp/k2k/fromClassToClassMakeAbstractWithCommentAndAnotherIndent2.kt
idea/testData/refactoring/pullUp/k2k/fromClassToClassMakeAbstractWithCommentAndAnotherIndent2.kt.after
idea/tests/org/jetbrains/kotlin/idea/refactoring/pullUp/PullUpTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-32426

KT-32426 Invalid code format after "Pull Members Up" on function with comment and another indent

---

idea/src/org/jetbrains/kotlin/idea/inspections/ExplicitThisInspection.kt
idea/testData/inspectionsLocal/explicitThis/functionWithSameNameInvocableVariable.kt
idea/testData/inspectionsLocal/explicitThis/functionWithSameNameVariable.kt
idea/testData/inspectionsLocal/explicitThis/functionWithSameNameVariable.kt.after
idea/testData/inspectionsLocal/explicitThis/variableWithSameNameFunction.kt
idea/testData/inspectionsLocal/explicitThis/variableWithSameNameFunction.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30136

KT-30136 False negative "Redundant explicit 'this'" with local variable

---

konan/utils/src/org/jetbrains/kotlin/konan/target/KonanTarget.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/dsl/KotlinTargetContainerWithPresetFunctions.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/NativeBinaryTypes.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/cocoapods/KotlinCocoapodsPlugin.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/tasks/FatFrameworkTask.kt

Android x86 and 32-bit watchOS.

A bit more native targets

---

compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/HeaderInfo.kt
compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/ProgressionHandlers.kt
compiler/testData/codegen/bytecodeText/forLoop/forInIndices/forInCollectionImplicitReceiverIndices.kt
compiler/testData/codegen/bytecodeText/forLoop/forInIndices/forInCollectionIndices.kt
compiler/testData/codegen/bytecodeText/forLoop/forInRangeSpecializedToUntil.kt

Additionally unmute a couple of tests that are working as intended.

[IR] Support Collection<*>.indices in for loop lowering.

---

idea/src/org/jetbrains/kotlin/idea/inspections/KotlinRedundantOverrideInspection.kt
idea/testData/inspectionsLocal/redundantOverride/javaPackagePrivate.1.java
idea/testData/inspectionsLocal/redundantOverride/javaPackagePrivate.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33153

KT-33153 False positive "Redundant overriding method" when overriding package private method

---

idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/callableBuilder/CallableBuilder.kt
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/enumEntryAddComma.kt.after
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/enumEntryHasComma.kt.after
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/enumEntryHasNoLineBreak.kt
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/enumEntryHasNoLineBreak.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-32981

KT-32981 "Create enum constant" quick fix adds redundant empty line

---

idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createTypeParameter/CreateTypeParameterFromUsageFix.kt
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/backticks.kt
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/backticks.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33299

KT-33299 "Create type parameter from usage" should work with backticks

---

idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createTypeParameter/CreateTypeParameterByUnresolvedRefActionFactory.kt
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/inExtensionProperty.kt
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/inExtensionProperty.kt.after
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/inExtensionProperty2.kt
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/inExtensionProperty2.kt.after
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/inExtensionProperty3.kt
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/inExtensionProperty3.kt.after
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/inProperty.kt
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/inProperty2.kt
idea/testData/quickfix/createFromUsage/createTypeParameter/inContainingDeclaration/inProperty3.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33300

KT-33300 "Create type parameter from usage" suggests for top level property

---

idea/src/org/jetbrains/kotlin/idea/formatter/KotlinPreFormatProcessor.kt
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/enumEntryHasSemicolon.kt
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/enumEntryHasSemicolon.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33718

KT-33718 "Create enum constant" quick fix adds after semicolon

---

idea/src/org/jetbrains/kotlin/idea/formatter/KotlinPreFormatProcessor.kt
idea/testData/codeInsight/overrideImplement/enumClass.kt
idea/testData/codeInsight/overrideImplement/enumClass.kt.after
idea/testData/codeInsight/overrideImplement/enumClass2.kt
idea/testData/codeInsight/overrideImplement/enumClass2.kt.after
idea/testData/codeInsight/overrideImplement/enumClass3.kt
idea/testData/codeInsight/overrideImplement/enumClass3.kt.after
idea/testData/codeInsight/overrideImplement/enumClass4.kt
idea/testData/codeInsight/overrideImplement/enumClass4.kt.after
idea/tests/org/jetbrains/kotlin/idea/codeInsight/OverrideImplementTest.kt

https://youtrack.jetbrains.com/issue/KT-31139

KT-31139 "Override members" on enum inserts semicolon before enum body

---

idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceRangeToWithUntilInspection.kt
idea/src/org/jetbrains/kotlin/idea/intentions/ConvertTwoComparisonsToRangeCheckIntention.kt
idea/testData/intentions/convertTwoComparisonsToRangeCheck/nonConstants.kt
idea/testData/intentions/convertTwoComparisonsToRangeCheck/nonConstants.kt.after
idea/testData/intentions/convertTwoComparisonsToRangeCheck/until.kt
idea/testData/intentions/convertTwoComparisonsToRangeCheck/until.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33880

KT-33880 "Convert to range check" produces code that is subject to ReplaceRangeToWithUntil for range with exclusive upper bound

---

idea/src/org/jetbrains/kotlin/idea/codeInsight/upDownMover/KotlinExpressionMover.java
idea/testData/codeInsight/moveUpDown/parametersAndArguments/callArgs7.kt
idea/testData/codeInsight/moveUpDown/parametersAndArguments/callArgs7.kt.after
idea/testData/codeInsight/moveUpDown/parametersAndArguments/callArgs8.kt
idea/testData/codeInsight/moveUpDown/parametersAndArguments/callArgs8.kt.after
idea/testData/codeInsight/moveUpDown/parametersAndArguments/classParams7.kt
idea/testData/codeInsight/moveUpDown/parametersAndArguments/classParams7.kt.after
idea/testData/codeInsight/moveUpDown/parametersAndArguments/classParams8.kt
idea/testData/codeInsight/moveUpDown/parametersAndArguments/classParams8.kt.after
idea/testData/codeInsight/moveUpDown/parametersAndArguments/funParams7.kt
idea/testData/codeInsight/moveUpDown/parametersAndArguments/funParams7.kt.after
idea/testData/codeInsight/moveUpDown/parametersAndArguments/funParams8.kt
idea/testData/codeInsight/moveUpDown/parametersAndArguments/funParams8.kt.after
idea/tests/org/jetbrains/kotlin/idea/codeInsight/moveUpDown/MoveStatementTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-14756

KT-14756 Move statement down breaks code in argument list

---

idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/RemoveRedundantLabelFix.kt
idea/testData/quickfix/removeRedundantLabel/simple.kt
idea/testData/quickfix/removeRedundantLabel/simple.kt.after
idea/testData/quickfix/removeRedundantLabel/simple2.kt
idea/testData/quickfix/removeRedundantLabel/simple2.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26431

KT-26431 Quickfix to remove redundant label

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeParameterTypeFix.kt
idea/testData/quickfix/typeMismatch/fixOverloadedOperator/changeTimesFunctionParameterType.kt
idea/testData/quickfix/typeMismatch/fixOverloadedOperator/changeTimesFunctionParameterType.kt.after
idea/testData/quickfix/typeMismatch/letClassImplementGenericInterfaceTwice.kt
idea/testData/quickfix/typeMismatch/letClassImplementGenericStarInterface.kt
idea/testData/quickfix/typeMismatch/letClassImplementIndirectlyInheritedInterface.kt
idea/testData/quickfix/typeMismatch/letStringImplementInterface.kt
idea/testData/quickfix/typeMismatch/parameterTypeMismatch/changeFunctionParameterType1.kt
idea/testData/quickfix/typeMismatch/parameterTypeMismatch/changeFunctionParameterType1.kt.after
idea/testData/quickfix/typeMismatch/parameterTypeMismatch/changeParameterTypeLongNameRuntime.kt
idea/testData/quickfix/typeMismatch/parameterTypeMismatch/changeParameterTypeLongNameRuntime.kt.after

https://youtrack.jetbrains.com/issue/KT-32012

KT-32012 Change parameter type quick fix: Don't use qualified name

---

idea/src/org/jetbrains/kotlin/idea/intentions/SamConversionToAnonymousObjectIntention.kt
idea/testData/intentions/samConversionToAnonymousObject/nestedClass.1.java
idea/testData/intentions/samConversionToAnonymousObject/nestedClass.1.java.after
idea/testData/intentions/samConversionToAnonymousObject/nestedClass.kt
idea/testData/intentions/samConversionToAnonymousObject/nestedClass.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33660

KT-33660 "Convert to anonymous object" with nested SAM interface inserts `object` keyword in the wrong place

---

gradle/versions.properties.193
idea/src/org/jetbrains/kotlin/idea/actions/internal/benchmark/AbstractCompletionBenchmarkAction.kt.193

Affected method was removed in https://jetbrains.team/p/idea/code/intellij/revision/f516dc41608a4ed7c08f560cb078c3059f96cc8c

Advance 193 bunch

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmStaticAnnotationLowering.kt

Update for commit https://github.com/JetBrains/kotlin/commit/4920d71d70bb08e9b08daa06dadd2ec9ff30d7b1

JVM_IR: use correct descriptor type in JvmStaticAnnotationLowering

---

nj2k/src/org/jetbrains/kotlin/nj2k/conversions/BuiltinMembersConversion.kt
nj2k/testData/newJ2k/issues/kt-19357.kt
nj2k/testData/newJ2k/methodCallExpression/specialBuiltinMembers.java
nj2k/testData/newJ2k/methodCallExpression/specialBuiltinMembers.kt

https://youtrack.jetbrains.com/issue/KT-7940

KT-7940 J2K: convert Integer.MAX_VALUE to Int.MAX_VALUE

---

j2k/testData/JavaApi.java
nj2k/src/org/jetbrains/kotlin/nj2k/JavaToJKTreeBuilder.kt
nj2k/src/org/jetbrains/kotlin/nj2k/printing/JKCodeBuilder.kt
nj2k/src/org/jetbrains/kotlin/nj2k/tree/elements.kt
nj2k/src/org/jetbrains/kotlin/nj2k/types/typesUtils.kt
nj2k/testData/newJ2k/annotations/typeUseAnnotation.java
nj2k/testData/newJ2k/annotations/typeUseAnnotation.kt
nj2k/tests/org/jetbrains/kotlin/nj2k/NewJavaToKotlinConverterSingleFileTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-30643

KT-30643 J2K: wrong position of TYPE_USE annotation

---

idea/src/org/jetbrains/kotlin/idea/inspections/ControlFlowWithEmptyBodyInspection.kt
idea/testData/inspectionsLocal/controlFlowWithEmptyBody/if/blockHasCommentWithElse.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34325

KT-34325 "Control flow with empty body" inspection should not report ifs with comments

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ReplaceCallFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/ReplaceCallFixUtils.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/ReplaceInfixOrOperatorCallFix.kt
idea/testData/quickfix/replaceInfixOrOperatorCall/hasElvis.kt
idea/testData/quickfix/replaceInfixOrOperatorCall/hasElvis.kt.after
idea/testData/quickfix/replaceWithSafeCall/hasElvis.kt
idea/testData/quickfix/replaceWithSafeCall/hasElvis.kt.after
idea/testData/quickfix/replaceWithSafeCall/hasElvis2.kt
idea/testData/quickfix/replaceWithSafeCall/hasElvis2.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34432

KT-34432 Replace with safe call intention inserts redundant elvis operator

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantVisibilityModifierInspection.kt
idea/testData/inspectionsLocal/redundantVisibilityModifier/publicOverrideProtectedSetter.kt
idea/testData/inspectionsLocal/redundantVisibilityModifier/publicOverrideProtectedSetter2.kt
idea/testData/inspectionsLocal/redundantVisibilityModifier/publicOverrideProtectedSetter3.kt
idea/testData/inspectionsLocal/redundantVisibilityModifier/publicOverrideProtectedSetter3.kt.after
idea/testData/inspectionsLocal/redundantVisibilityModifier/publicOverrideProtectedSetter4.kt
idea/testData/inspectionsLocal/redundantVisibilityModifier/publicOverrideProtectedSetter5.kt
idea/testData/inspectionsLocal/redundantVisibilityModifier/publicOverrideProtectedSetter6.kt
idea/testData/inspectionsLocal/redundantVisibilityModifier/publicOverrideProtectedSetter6.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33580

KT-33580 False positive "Redundant visibility modifier" overriding property with protected set visibility

---

libraries/tools/kotlin-main-kts-test/test/org/jetbrains/kotlin/mainKts/test/mainKtsTest.kt
libraries/tools/kotlin-main-kts-test/testData/compile-java6.main.kts
libraries/tools/kotlin-main-kts/src/org/jetbrains/kotlin/mainKts/scriptDef.kt
libraries/tools/kotlin-script-util/src/main/kotlin/org/jetbrains/kotlin/script/util/annotations.kt

https://youtrack.jetbrains.com/issue/KT-34274

Add support for @CompilerOptions script annotation.

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt

Fixes to IrTypes in `AddContinuationLowering`

JVM IR: Minor coroutine fixes

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ImportFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/testData/quickfix/autoImports/iteratorOperator.after.kt
idea/testData/quickfix/autoImports/iteratorOperator.before.Dependency.kt
idea/testData/quickfix/autoImports/iteratorOperator.before.Main.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34303

KT-34303 IDE should suggest to import an extension iterator function when using for loop with a range

---

idea/src/org/jetbrains/kotlin/idea/intentions/IndentRawStringIntention.kt
idea/testData/intentions/indentRawString/annotationEntry.kt
idea/testData/intentions/indentRawString/const.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34784

KT-34784 "Indent raw string" intention: do not suggest in const

---

compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/HeaderProcessor.kt
compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/ProgressionHandlers.kt
compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/Utils.kt
compiler/testData/codegen/box/ranges/forInCharSequenceWithMultipleGetFunctions.kt
compiler/testData/codegen/box/ranges/forInIndices/forInCharSequenceTypeParameterIndices.kt
compiler/testData/codegen/box/ranges/forInIndices/forInCollectionTypeParameterIndices.kt
compiler/testData/codegen/bytecodeText/forLoop/forInCharSequenceTypeParameter.kt
compiler/testData/codegen/bytecodeText/forLoop/forInIndices/forInCharSequenceTypeParameterIndices.kt
compiler/testData/codegen/bytecodeText/forLoop/forInIndices/forInCollectionTypeParameterIndices.kt
compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java

Ensure the correct properties and functions are used in ForLoopsLowering

---

compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LateinitLowering.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt

On the JVM backend the `throwUninitializedPropertyAccessException` function is implemented in Java and has a return type of `Unit` (as far as Kotlin is concerned) instead of `Nothing`. In order to make the types match up we have to wrap its call in a block with an additional `IrThrow`.

JVM IR: Fix types in LateInitLowering

---

idea/src/org/jetbrains/kotlin/idea/refactoring/elementSelectionUtils.kt
idea/testData/smartSelection/beforeComment.kt
idea/testData/smartSelection/beforeKDocComment.kt
idea/testData/smartSelection/beforeRightParenthesis.kt
idea/testData/smartSelection/beforeRightParenthesis2.kt
idea/testData/smartSelection/beforeRightParenthesis3.kt
idea/tests/org/jetbrains/kotlin/idea/SmartSelectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-28607

KT-28607 Extract/Introduce variable fails if caret is just after expression

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/ResolveInlineCalls.kt
compiler/testData/codegen/box/jvm8/kt29242.kt
compiler/testData/codegen/box/jvm8/kt33054.kt
compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java

JVM_IR: resolve inline fake overrides before codegen

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeVariableMutabilityFix.kt
idea/testData/quickfix/variables/changeMutability/const.kt
idea/testData/quickfix/variables/changeMutability/const.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35022

KT-35022 Quickfix "change to var" doesn't remove `const` modifier

---

idea/src/org/jetbrains/kotlin/idea/editor/KotlinLiteralCopyPasteProcessor.kt
idea/testData/copyPaste/plainTextLiteral/TrimIndent3.expected.kt
idea/testData/copyPaste/plainTextLiteral/TrimIndent3.kt
idea/testData/copyPaste/plainTextLiteral/TrimIndent3.txt
idea/tests/org/jetbrains/kotlin/idea/conversion/copy/LiteralTextToKotlinCopyPasteTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33888

KT-33888 Bad indentation when copy-paste to trimIndent()

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/BodyGenerator.kt
compiler/testData/debug/stepping/conjunction.kt
compiler/testData/debug/stepping/functionInAnotherFile.kt
compiler/testData/debug/stepping/throwException.kt
compiler/testData/ir/sourceRanges/augmentedAssignmentWithExpression.txt
compiler/testData/ir/sourceRanges/comments.txt
compiler/testData/ir/sourceRanges/declarations/classProperties.txt
compiler/testData/ir/sourceRanges/declarations/topLevelProperties.txt
compiler/tests-common/tests/org/jetbrains/kotlin/codegen/debugInformation/AbstractSteppingTest.kt

Several minor changes to fix line number mismatch between current backend and JVM_IR backend for existing test cases.

Several line number fix for JVM_IR backend

---

plugins/uast-kotlin/src/org/jetbrains/uast/kotlin/expressions/KotlinUBinaryExpression.kt
plugins/uast-kotlin/testData/Bitwise.kt
plugins/uast-kotlin/testData/Bitwise.log.txt
plugins/uast-kotlin/testData/Bitwise.render.txt
plugins/uast-kotlin/tests/SimpleKotlinRenderLogTest.kt

Proposed fix for https://youtrack.jetbrains.com/issue/KT-35071

UAST: handle kotlin shifts like bitwise binary ops

---

nj2k/src/org/jetbrains/kotlin/nj2k/conversions/DefaultArgumentsConversion.kt
nj2k/testData/newJ2k/overloads/ConflictParameterName.java
nj2k/testData/newJ2k/overloads/ConflictParameterName.kt
nj2k/tests/org/jetbrains/kotlin/nj2k/NewJavaToKotlinConverterSingleFileTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-19574

KT-19574 Code with inferred default parameters and parameter vs property name clashes

---

libraries/stdlib/common/src/generated/_Arrays.kt
libraries/stdlib/common/src/generated/_Collections.kt
libraries/stdlib/common/src/generated/_Sequences.kt
libraries/stdlib/common/src/generated/_Strings.kt
libraries/stdlib/samples/test/samples/collections/arrays.kt
libraries/stdlib/samples/test/samples/collections/collections.kt
libraries/stdlib/samples/test/samples/text/strings.kt
libraries/tools/kotlin-stdlib-gen/src/templates/Snapshots.kt

KT-20357: Add samples for functions related to associate

---

idea/src/org/jetbrains/kotlin/idea/quickfix/SuperClassNotInitialized.kt
idea/testData/quickfix/supertypeInitialization/addImport.kt.after
idea/testData/quickfix/supertypeInitialization/addParameters.kt.after
idea/testData/quickfix/supertypeInitialization/multipleConstructors.kt.after
idea/testData/quickfix/supertypeInitialization/vararg4.kt
idea/testData/quickfix/supertypeInitialization/vararg4.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33109

KT-33109 "Add constructor parameters" quick fix should add default parameters from super class

---

compiler/light-classes/src/org/jetbrains/kotlin/asJava/classes/ultraLightField.kt

See https://youtrack.jetbrains.com/issue/KT-35454

KT-35454 Weird implementation of KtUltraLightFieldImpl.isEquivalentTo

---

idea/src/org/jetbrains/kotlin/idea/quickfix/AddConstructorParameterFromSuperTypeCallFix.kt
idea/testData/quickfix/addConstructorParameterFromSuperTypeCall/generics.kt
idea/testData/quickfix/addConstructorParameterFromSuperTypeCall/generics.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34203

KT-34203 'Add constructor parameter' fix does not add generics

---

idea/src/org/jetbrains/kotlin/idea/inspections/DeprecatedCallableAddReplaceWithInspection.kt
idea/testData/inspectionsLocal/deprecatedCallableAddReplaceWith/ReplaceWithHasNamedArgument.kt
idea/testData/inspectionsLocal/deprecatedCallableAddReplaceWith/ReplaceWithHasNamedArgument.kt.after
idea/testData/inspectionsLocal/deprecatedCallableAddReplaceWith/inspectionData/expected.xml
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34297

KT-34297 "Add 'replaceWith' argument" inserts positional instead of named argument

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeFunctionSignatureFix.kt
idea/testData/quickfix/changeSignature/addForItParameter.kt
idea/testData/quickfix/changeSignature/addForItParameter.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33297

KT-33297 Improve parameter name in `Add parameter to constructor` quick fix

---

idea/src/org/jetbrains/kotlin/idea/intentions/RemoveBracesIntention.kt
idea/testData/intentions/removeBraces/whenLambda2.kt
idea/testData/intentions/removeBraces/whenLambda3.kt
idea/testData/intentions/removeBraces/whenLambda3.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35288

KT-35288 False positive "Remove braces from 'when' entry" in 'when' expression which returns lambda

---

idea/resources/postfixTemplates/KtArgumentPostfixTemplate/after.kt.template
idea/resources/postfixTemplates/KtArgumentPostfixTemplate/before.kt.template

https://youtrack.jetbrains.com/issue/KT-34386

KT-34386 Typo in Kotlin arg postfix completion

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertLambdaToReferenceIntention.kt
idea/testData/intentions/convertLambdaToReference/constructor2.kt
idea/testData/intentions/convertLambdaToReference/constructor2.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34690

KT-34690 Support intention `Convert lambda to reference` for qualified references

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/WhenToIfIntention.kt
idea/src/org/jetbrains/kotlin/idea/intentions/declarations/SplitPropertyDeclarationIntention.kt
idea/testData/intentions/branched/ifWhen/whenToIf/variableSubject.kt
idea/testData/intentions/declarations/split/whenSubject.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35528

KT-35528 Intention `Replace 'when' with 'if'` produces wrong code if expression subject is a variable declaration

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantVisibilityModifierInspection.kt
idea/testData/inspectionsLocal/redundantVisibilityModifier/internalInPrivateClass.kt
idea/testData/inspectionsLocal/redundantVisibilityModifier/internalInPrivateClass.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35639

KT-35639 Inspection about internal member inside private type

---

idea/idea-gradle-native/src/org/jetbrains/kotlin/ide/konan/gradle/KotlinGradleNativeMultiplatformModuleBuilder.kt

It's been bugging me for a while. Here's a PR.

Fix template indentation

---

idea/src/org/jetbrains/kotlin/idea/codeInliner/UsageReplacementStrategy.kt
idea/testData/refactoring/inline/function/ReferenceReceiver.kt
idea/testData/refactoring/inline/function/ReferenceReceiver.kt.after
idea/tests/org/jetbrains/kotlin/idea/refactoring/inline/InlineTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26248

KT-26248 "Refactor -> Inline variable" breaks callable references

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/irCodegenUtils.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/BridgeLowering.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InheritedDefaultMethodsOnClassesLowering.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/IrUtils.kt

Rename and refactor interface delegation phase. It didn't actually do
what was said on the box. It should be more in line with the
intentions of the phase now.

[JVM IR] Refactor InterfaceDelegationPhase

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSymbols.kt
compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/dataClass.kt
compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/extensionComponents.kt
compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/generic.kt
compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/inline.kt
compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/otherParameters.kt
compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/parameters.kt
compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/underscoreNames.kt

@dnpetrov @ilmirus This commit was in #2961 but not in #2966 which was the one merged. Creating a separate PR just to keep it cleaner.

[JVM IR] Fix `checkLocalVariablesTableTest/parametersInSuspendLambda`

---

libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/nodejs/NodeJsSetupTask.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/yarn/YarnSetupTask.kt

Please have a look at the individual commit messages for the details.

Fix nodejs setup task check

---

libraries/stdlib/jvm/src/kotlin/system/Timing.kt

https://youtrack.jetbrains.net/issue/KT-27856

KT-27856 Add contracts to Timing.kt lambdas

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertLambdaToReferenceIntention.kt
idea/testData/intentions/convertLambdaToReference/suspendFunctionParameter.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-16907

KT-16907 "Convert to lambda reference" intention is erroneously shown for suspending lambda parameters, producing bad code

---

compiler/cli/src/org/jetbrains/kotlin/cli/metadata/K2MetadataKlibSerializer.kt
compiler/ir/serialization.js/src/org/jetbrains/kotlin/ir/backend/js/JsLibraryResolver.kt
compiler/ir/serialization.js/src/org/jetbrains/kotlin/ir/backend/js/klib.kt
compiler/util-klib/src/org/jetbrains/kotlin/library/KotlinLibrary.kt
compiler/util-klib/src/org/jetbrains/kotlin/library/KotlinLibraryLayout.kt
compiler/util-klib/src/org/jetbrains/kotlin/library/SearchPathResolver.kt
compiler/util-klib/src/org/jetbrains/kotlin/library/impl/KotlinLibraryImpl.kt
compiler/util-klib/src/org/jetbrains/kotlin/library/impl/KotlinLibraryLayoutImpl.kt
compiler/util-klib/src/org/jetbrains/kotlin/library/impl/KotlinLibraryWriterImpl.kt
idea/idea-native/src/org/jetbrains/kotlin/ide/konan/NativePlatformKindResolution.kt
konan/commonizer/src/org/jetbrains/kotlin/descriptors/commonizer/konan/NativeDistributionCommonizer.kt
konan/utils/src/org/jetbrains/kotlin/konan/target/Distribution.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/tasks/KotlinNativeTasks.kt

afb2e9f38def4de8d58feaf5341e125eeae06012.
8c4fa6446d2bd16d721806bac716beb089bf48f4.
f3bc533073c3488cc4219d00ef0c0ac3df232bc1.
ccf084b1a55cf383feb6dbba12c1c982cfac5762.

This reverts commits

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmBuiltinOptimizationLowering.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/PropertiesToFieldsLowering.kt
compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/transformations/InsertImplicitCasts.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/IrUtils.kt
compiler/testData/codegen/bytecodeText/accessorForOverridenVal.kt
compiler/testData/codegen/bytecodeText/constants/noInlineNonConst.kt
compiler/testData/codegen/bytecodeText/kt3845.kt

Reverts JetBrains/kotlin#3023 cause FIR related problems

Revert "JVM_IR: Use direct field access instead of calling certain accessors."

---

compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/HeaderProcessor.kt
compiler/testData/codegen/box/controlStructures/forInArrayWithIndex/forInArrayWithIndexBreakAndContinue.kt
compiler/testData/codegen/box/controlStructures/forInCharSequenceWithIndex/forInCharSequenceWithIndexBreakAndContinue.kt
compiler/testData/codegen/box/controlStructures/forInIterableWithIndex/forInListWithIndexBreakAndContinue.kt
compiler/testData/codegen/box/controlStructures/forInSequenceWithIndex/forInSequenceWithIndexBreakAndContinue.kt
compiler/testData/codegen/box/ranges/forInProgressionWithIndex/forInWithIndexBreakAndContinue.kt
compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java

@max-kammerer Thanks for notifying me of this issue, here is the fix.

ForLoopsLowering: Fix issue with break/continue in loop over withIndex

---

idea/src/org/jetbrains/kotlin/idea/refactoring/introduce/extractionEngine/extractorUtil.kt
idea/testData/refactoring/introduceProperty/kt24615.kt
idea/testData/refactoring/introduceProperty/kt24615.kt.after
idea/tests/org/jetbrains/kotlin/idea/refactoring/introduce/ExtractionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-24615

KT-24615 "Extract property" generates useless extension property

---

idea/src/org/jetbrains/kotlin/idea/refactoring/inline/inlineUtils.kt
idea/testData/refactoring/inline/function/returnAtEnd/InnerFunction.kt
idea/testData/refactoring/inline/function/returnAtEnd/InnerFunction.kt.after
idea/testData/refactoring/inline/function/returnAtEnd/InnerFunction2.kt
idea/testData/refactoring/inline/function/returnAtEnd/InnerFunction2.kt.after
idea/tests/org/jetbrains/kotlin/idea/refactoring/inline/InlineTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34190

KT-34190 Inline Function: False positive error "not at the end of the body" with anonymous object

---

idea/src/org/jetbrains/kotlin/idea/intentions/ToRawStringLiteralIntention.kt
idea/testData/intentions/toRawStringLiteral/trailingSpace3.kt
idea/testData/intentions/toRawStringLiteral/trailingSpace3.kt.after

https://youtrack.jetbrains.com/issue/KT-36369

KT-36369 "To raw string literal" intention is not available if string content starts with newline symbol \n

---

idea/src/org/jetbrains/kotlin/idea/inspections/LiftReturnOrAssignmentInspection.kt
idea/testData/inspectionsLocal/liftOut/ifToAssignment/usedAsExpression.kt
idea/testData/inspectionsLocal/liftOut/tryToAssignment/usedAsExpression.kt
idea/testData/inspectionsLocal/liftOut/whenToAssignment/usedAsExpression.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-36357

KT-36357 "Lift assignment out of 'if'" breaks code for oneliner function

---

compiler/ir/serialization.common/src/org/jetbrains/kotlin/backend/common/serialization/IrModuleSerializer.kt

This change is required for Native interop libraries.
For enums and structs we generate full-blown IR classes that should not
be serialized because they will be generated anew.

[IR][Serialization] Allow backends to skip files

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantCompanionReferenceInspection.kt
idea/testData/inspectionsLocal/redundantCompanionReference/namedWithSameNameFunction.kt
idea/testData/inspectionsLocal/redundantCompanionReference/namedWithSameNameFunction2.kt
idea/testData/inspectionsLocal/redundantCompanionReference/namedWithSameNameFunction2.kt.after
idea/testData/inspectionsLocal/redundantCompanionReference/namedWithSameNameProperty.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-36707

KT-36707 False positive redundant companion object on calling companion object members

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeVariableMutabilityFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/testData/quickfix/variables/changeMutability/canBeVal/uninitializedWithGetter.kt
idea/testData/quickfix/variables/changeMutability/canBeVal/uninitializedWithGetter.kt.after
idea/testData/quickfix/variables/changeMutability/canBeVal/uninitializedWithGetter2.kt
idea/testData/quickfix/variables/changeMutability/canBeVal/uninitializedWithGetter2.kt.after
idea/testData/quickfix/variables/changeMutability/canBeVal/uninitializedWithGetter3.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-15723

KT-15723 Add 'Convert to value' quickfix for property containing only getter

---

compiler/psi/src/org/jetbrains/kotlin/psi/KtNamedDeclarationStub.java
idea/testData/findUsages/kotlin/findFunctionUsages/objectExpressionMemberInCompanion.0.kt
idea/testData/findUsages/kotlin/findFunctionUsages/objectExpressionMemberInCompanion.results.txt
idea/testData/findUsages/kotlin/findFunctionUsages/objectExpressionMemberInTopLevel.0.kt
idea/testData/findUsages/kotlin/findFunctionUsages/objectExpressionMemberInTopLevel.results.txt
idea/testData/inspectionsLocal/unusedSymbol/inAnonymousDeeplyInTopLevel.kt
idea/testData/inspectionsLocal/unusedSymbol/inAnonymousInCompanion.kt
idea/testData/inspectionsLocal/unusedSymbol/inAnonymousInTopLovel.kt
idea/tests/org/jetbrains/kotlin/findUsages/FindUsagesTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-31800
https://youtrack.jetbrains.com/issue/KT-20868

KT-31800 False positive "never used" with function in private val object expression

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertFunctionToPropertyIntention.kt
idea/testData/intentions/convertFunctionToProperty/onFunKeyword.kt
idea/testData/intentions/convertFunctionToProperty/onFunKeyword.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34450

KT-34450 `Convert function to property` intention should be also displayed on `fun` keyword

---

idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceNegatedIsEmptyWithIsNotEmptyInspection.kt
idea/src/org/jetbrains/kotlin/idea/intentions/InvertIfConditionIntention.kt
idea/testData/intentions/invertIfCondition/isEmpty.kt
idea/testData/intentions/invertIfCondition/isEmpty.kt.after
idea/testData/intentions/invertIfCondition/isNotEmpty.kt
idea/testData/intentions/invertIfCondition/isNotEmpty.kt.after
idea/testData/intentions/invertIfCondition/negatedIsEmpty.kt
idea/testData/intentions/invertIfCondition/negatedIsEmpty.kt.after
idea/testData/intentions/invertIfCondition/negatedIsNotEmpty.kt
idea/testData/intentions/invertIfCondition/negatedIsNotEmpty.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34593

KT-34593 Invert 'if' condition: Invert `String.isNotEmpty` should be `String.isEmpty`

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPropertyToFunctionIntention.kt
idea/testData/intentions/convertPropertyToFunction/annotationUseSiteTarget.kt
idea/testData/intentions/convertPropertyToFunction/annotationUseSiteTarget.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-36834

KT-36834 Convert use-site targets and usages with convert property to fun intention

---

idea/src/org/jetbrains/kotlin/idea/refactoring/inline/KotlinInlineCallableProcessor.kt
idea/src/org/jetbrains/kotlin/idea/refactoring/inline/KotlinInlineValDialog.kt
idea/testData/inspectionsLocal/unnecessaryVariable/whenSubject.kt
idea/testData/inspectionsLocal/unnecessaryVariable/whenSubject.kt.after
idea/testData/refactoring/inline/inlineVariableOrProperty/whenSubject.kt
idea/testData/refactoring/inline/inlineVariableOrProperty/whenSubject.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/refactoring/inline/InlineTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-29870

KT-29870 Inline variable doesn't handle 'when' subject val correctly

---

idea/idea-analysis/src/org/jetbrains/kotlin/idea/references/referenceUtil.kt
idea/testData/editor/optimizeImports/jvm/KDocReference.kt
idea/testData/editor/optimizeImports/jvm/KDocReference.kt.after
idea/testData/inspections/unusedImport/kDocReferences.kt

https://youtrack.jetbrains.com/issue/KT-27601

KT-27601 keep imports for extension functions used in kdoc

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/IfToWhenIntention.kt
idea/testData/intentions/branched/ifWhen/ifToWhen/doNotSwallowComment.kt
idea/testData/intentions/branched/ifWhen/ifToWhen/doNotSwallowComment.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34640

KT-34640 Replace 'if' with 'when' leads to copy comment line above when from another if

---

compiler/util-io/src/org/jetbrains/kotlin/konan/CompilerVersion.kt

(cherry picked from commit 98ce49ba73dd972fc7a98f32642da4178698d095)

[build][native] version with milestone clause

---

idea/resources/META-INF/extensions/ide.xml
idea/src/org/jetbrains/kotlin/idea/refactoring/introduce/extractionEngine/AdditionalExtractableAnalyser.kt
idea/src/org/jetbrains/kotlin/idea/refactoring/introduce/extractionEngine/ExtractableCodeDescriptor.kt
idea/src/org/jetbrains/kotlin/idea/refactoring/introduce/extractionEngine/extractableAnalysisUtil.kt
idea/src/org/jetbrains/kotlin/idea/refactoring/introduce/extractionEngine/extractorUtil.kt

Adds annotations to ExtractableCodeDescriptor.
Adds functionality of adding annotations to KtPsiFactory.CallableBuilder

Adds AdditionalExtractableAnalyser EP.

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/BridgeLowering.kt

The problem is that in code such as:
```kotlin
abstract class C : MutableCollection<Int>
```
we need to generate an abstract method stub with signature `remove(Ljava/lang/Integer)Z` instead of `remove(I)Z`, in order to avoid clashes with a different method with the same signature in `java.util.List` which could be implemented by a subclass.
I didn't add a test, since this is already tested for in some bytecode listing tests, which are still failing because of differences in nullability annotations and `toArray` methods.

JVM IR: Box arguments in abstract method stubs for "remove" bridges

---

idea/src/org/jetbrains/kotlin/idea/intentions/MoveMemberOutOfObjectIntention.kt
idea/testData/multiFileIntentions/moveMemberToTopLevel/function/after/a/A.kt
idea/testData/multiFileIntentions/moveMemberToTopLevel/function/after/b/B.kt
idea/testData/multiFileIntentions/moveMemberToTopLevel/function/before/a/A.kt
idea/testData/multiFileIntentions/moveMemberToTopLevel/function/before/b/B.kt
idea/testData/multiFileIntentions/moveMemberToTopLevel/function/function.test
idea/tests/org/jetbrains/kotlin/idea/intentions/MultiFileIntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-37213

KT-37213 "Move to top level" intention does not update imports for extension functions

---

libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/Kapt3IT.kt
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/kt19179/api/build.gradle
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/internal/kapt/KaptGenerateStubsTask.kt

Filter kapt generate stubs classpath for non-existent entries (KT-37241)

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrSourceCompilerForInline.kt
compiler/testData/codegen/boxInline/reified/nonCapturingObjectInLambda_ir.txt
compiler/testData/codegen/bytecodeText/kt10259.kt
compiler/testData/codegen/bytecodeText/kt10259_3.kt

JVM_IR: restore InnerClasses for objects in lambdas

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendContext.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/CoroutineCodegen.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrSourceCompilerForInline.kt
compiler/testData/codegen/box/coroutines/varSpilling/refinedIntTypesAnalysis.kt

Non-behavior-affecting parts of #3056 and #3164. Depends on #3204.

JVM_IR: refactor ClassCodegen and FunctionCodegen

---

idea/src/org/jetbrains/kotlin/idea/refactoring/kotlinRefactoringUtil.kt

https://youtrack.jetbrains.com/issue/KT-37260

KT-37260: Several ReplaceWith expressions in kotlinRefactoringUtil missing parameter

---

libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/yarn/YarnBasics.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/yarn/YarnLock.kt

Support GitHub version format
Example:
```JSON
"escodegen": "github:yworks/escodegen#v1.11.2"
```

KT-34468 Yarn. Dependency GitHub package version support

---

compiler/backend/src/org/jetbrains/kotlin/codegen/AbstractClassBuilder.java
compiler/backend/src/org/jetbrains/kotlin/codegen/ClassBuilder.java
compiler/backend/src/org/jetbrains/kotlin/codegen/DelegatingClassBuilder.java
compiler/backend/src/org/jetbrains/kotlin/codegen/MemberCodegen.java
compiler/backend/src/org/jetbrains/kotlin/codegen/inline/AnonymousObjectTransformer.kt
compiler/backend/src/org/jetbrains/kotlin/codegen/inline/SMAP.kt
compiler/backend/src/org/jetbrains/kotlin/codegen/inline/SMAPParser.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrSourceCompilerForInline.kt
compiler/testData/codegen/boxInline/smap/smapWithNewSyntax.kt
compiler/testData/codegen/boxInline/smap/smapWithOldSyntax.kt
compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
compiler/util/src/org/jetbrains/kotlin/config/LanguageVersionSettings.kt
js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java

JVM: add a language feature to omit *E between SMAP strata

---

idea/src/org/jetbrains/kotlin/idea/intentions/SamConversionToAnonymousObjectIntention.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/ConvertToAnonymousObjectFix.kt
idea/testData/quickfix/convertToAnonymousObject/lambdaInParentheses.kt
idea/testData/quickfix/convertToAnonymousObject/lambdaInParentheses.kt.after
idea/testData/quickfix/convertToAnonymousObject/noLambda.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-31912

KT-31912 QF “Convert to anonymous object” do nothing on SAM-interfaces

---

ReadMe.md

README Update 'Gradle properties' link

---

idea/src/org/jetbrains/kotlin/idea/intentions/AddMissingDestructuringIntention.kt
idea/testData/intentions/addMissingDestructuring/empty.kt
idea/testData/intentions/addMissingDestructuring/empty.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-36094

KT-36094 "Add missing component" intention adds extra comma to an empty destructuring declaration

---

idea/src/org/jetbrains/kotlin/idea/inspections/RemoveRedundantBackticksInspection.kt
idea/testData/inspectionsLocal/removeRedundantBackticks/underscores.kt
idea/testData/inspectionsLocal/removeRedundantBackticks/underscores2.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-37496

KT-37496 False positive "Remove redundant backticks" for multiple underscores variable name

---

idea/idea-core/src/org/jetbrains/kotlin/idea/core/overrideImplement/OverrideImplementMembersHandler.kt
idea/testData/quickfix/implement/hasImplementedInPrimaryConstructor.kt
idea/testData/quickfix/implement/hasImplementedInPrimaryConstructor.kt.after
idea/testData/quickfix/implement/hasImplementedInPrimaryConstructor2.kt
idea/testData/quickfix/implement/hasImplementedInPrimaryConstructor2.kt.after
idea/testData/quickfix/implement/hasImplementedInPrimaryConstructor3.kt
idea/testData/quickfix/implement/hasImplementedInPrimaryConstructor3.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-37312

KT-37312 "Implement members" intention put function in the primary constructor if there are unused brackets in class

---

idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/RemoveModifierFix.kt
idea/testData/quickfix/redundantFun/simple.kt
idea/testData/quickfix/redundantFun/simple.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-37539

KT-37539 IDE: Introduce "Remove fun modifier" quick fix for FUN_INTERFACE_WRONG_COUNT_OF_ABSTRACT_MEMBERS error

---

idea/src/org/jetbrains/kotlin/idea/refactoring/changeSignature/KotlinChangeSignatureUsageProcessor.kt
idea/src/org/jetbrains/kotlin/idea/refactoring/changeSignature/usages/KotlinFunctionCallUsage.kt
idea/testData/intentions/convertParameterToReceiver/explicitThis.kt
idea/testData/intentions/convertParameterToReceiver/explicitThis.kt.after
idea/testData/intentions/convertParameterToReceiver/explicitThisForAnonymousObject.kt
idea/testData/intentions/convertParameterToReceiver/explicitThisForAnonymousObject.kt.after
idea/testData/intentions/convertParameterToReceiver/explicitThisForExtension.kt
idea/testData/intentions/convertParameterToReceiver/explicitThisForExtension.kt.after
idea/testData/intentions/convertParameterToReceiver/explicitThisForExtension2.kt
idea/testData/intentions/convertParameterToReceiver/explicitThisForExtension2.kt.after
idea/testData/intentions/convertReceiverToParameter/explicitThisForExtension.kt
idea/testData/intentions/convertReceiverToParameter/explicitThisForExtension.kt.after
idea/testData/intentions/convertReceiverToParameter/usedInAnonymousObject.kt
idea/testData/intentions/convertReceiverToParameter/usedInAnonymousObject.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-17615
https://youtrack.jetbrains.com/issue/KT-30028
https://youtrack.jetbrains.com/issue/KT-32809
https://youtrack.jetbrains.com/issue/KT-28085
https://youtrack.jetbrains.com/issue/KT-37508

KT-17615 "Convert parameter to receiver" changes `this` to `this@ < no name provided >`

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertToBlockBodyIntention.kt
idea/testData/intentions/convertToBlockBody/adjustLineIndent.kt
idea/testData/intentions/convertToBlockBody/adjustLineIndent.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-22368

KT-22368 "Convert to block body" intention incorrectly formats closing brace

---

idea/src/org/jetbrains/kotlin/idea/intentions/RemoveBracesIntention.kt
idea/testData/intentions/removeBraces/elseLambda.kt
idea/testData/intentions/removeBraces/elseLambda2.kt
idea/testData/intentions/removeBraces/elseLambda2.kt.after
idea/testData/intentions/removeBraces/ifLambda.kt
idea/testData/intentions/removeBraces/ifLambda2.kt
idea/testData/intentions/removeBraces/ifLambda2.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35994

KT-35994 "Remove braces from 'if' statement": do not suggest when lambda is directly under 'if'

---

idea/idea-analysis/src/org/jetbrains/kotlin/idea/util/ProjectRootsUtil.kt

Fix NPE in ProjectRootsUtilKt.isKotlinBinary

---

nj2k/src/org/jetbrains/kotlin/nj2k/conversions/InternalDeclarationConversion.kt
nj2k/testData/newJ2k/enum/implicitlyPrivateConstructorsEnum.java
nj2k/testData/newJ2k/enum/implicitlyPrivateConstructorsEnum.kt
nj2k/tests/org/jetbrains/kotlin/nj2k/NewJavaToKotlinConverterSingleFileTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35897

KT-35897: change type for enum constructor for visibility

---

js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrBoxJsTestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/BoxJsTestGenerated.java
js/js.translator/src/org/jetbrains/kotlin/js/translate/initializer/ClassInitializerTranslator.java
js/js.translator/testData/box/jsModule/externalConstructor.js
js/js.translator/testData/box/jsModule/externalConstructor.kt

Primary ordinary -> secondary external

KT-31126 JS. Fix super constructor call. Old backend

---

ReadMe.md

Sync naming with IDEA 2019.3.4
Sync formating for:
* IDEA menu items
* IDEA run configurations
* environment variables

README Actualize IDEA instructions

---

idea/src/org/jetbrains/kotlin/idea/intentions/conventionNameCalls/ReplaceInvokeIntention.kt
idea/testData/intentions/conventionNameCalls/replaceInvoke/java.1.java
idea/testData/intentions/conventionNameCalls/replaceInvoke/java.1.java.after
idea/testData/intentions/conventionNameCalls/replaceInvoke/java.kt
idea/testData/intentions/conventionNameCalls/replaceInvoke/java.kt.after
idea/testData/intentions/conventionNameCalls/replaceInvoke/notOperator.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-37977

KT-37977 "Replace 'invoke' with direct call" intention: false positive when function is not operator

---

compiler/psi/src/org/jetbrains/kotlin/psi/KtPsiUtil.java
idea/testData/intentions/conventionNameCalls/replaceInvoke/dotQualifiedReceiver.kt
idea/testData/intentions/conventionNameCalls/replaceInvoke/dotQualifiedReceiver.kt.after
idea/testData/intentions/conventionNameCalls/replaceInvoke/dotQualifiedReceiver2.kt
idea/testData/intentions/conventionNameCalls/replaceInvoke/dotQualifiedReceiver2.kt.after
idea/testData/intentions/conventionNameCalls/replaceInvoke/dotQualifiedReceiver3.kt
idea/testData/intentions/conventionNameCalls/replaceInvoke/dotQualifiedReceiver3.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-37967

KT-37967 Replace 'invoke' with direct call intention adds unnecessary parenthesis

---

idea/src/org/jetbrains/kotlin/idea/inspections/KotlinUnusedImportInspection.kt
idea/testData/quickfix/optimizeImports/invoke.kt
idea/testData/quickfix/optimizeImports/invoke2.kt
idea/testData/quickfix/optimizeImports/invoke2.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-24281

KT-24281 Importing of invoke() from the same file is reported as unused even if it isn't

---

idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceCollectionCountWithSizeInspection.kt
idea/src/org/jetbrains/kotlin/idea/inspections/collections/ConvertCallChainIntoSequenceInspection.kt
idea/src/org/jetbrains/kotlin/idea/inspections/collections/FunctionUtils.kt
idea/testData/inspectionsLocal/replaceCollectionCountWithSize/countOfIterable.kt
idea/testData/inspectionsLocal/replaceCollectionCountWithSize/countOfIterable2.kt
idea/testData/inspectionsLocal/replaceCollectionCountWithSize/countOfIterable3.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34677

KT-34677 False positive "Collection count can be converted to size" with `Iterable`

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeVariableTypeFix.kt
idea/testData/quickfix/override/typeMismatchOnOverride/changeOverriddenPropertyTypeFromCtorParameter.kt
idea/testData/quickfix/override/typeMismatchOnOverride/changeOverriddenPropertyTypeFromCtorParameter.kt.after
idea/testData/quickfix/override/typeMismatchOnOverride/changeOverridingCtorParameterType.kt
idea/testData/quickfix/override/typeMismatchOnOverride/changeOverridingCtorParameterType.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-29934

KT-29934 No quickfix on primary constructor override val parameter when it has wrong type

---

idea/src/org/jetbrains/kotlin/idea/intentions/AddMissingClassKeywordIntention.kt

@vladimirdolzhenko
Fix for https://github.com/JetBrains/kotlin/commit/b4c62cdb52ad6de1eb195028737912011c780015

Fix for KT-14884

---

idea/idea-core/src/org/jetbrains/kotlin/idea/core/script/configuration/listener/ScriptChangeListener.kt

Move vFile.isValid() check inside read action

---

idea/src/org/jetbrains/kotlin/idea/KotlinDocumentationProvider.kt
idea/testData/editor/quickDoc/JavaClassConstructorUsedInKotlin.kt
idea/testData/editor/quickDoc/JavaClassConstructorUsedInKotlin_Data.java
idea/testData/editor/quickDoc/JavaMethodUsedInKotlinInParen.kt
idea/testData/editor/quickDoc/JavaMethodUsedInKotlinInParen_Data.java
idea/testData/editor/quickDoc/OnMethodUsageInParen.kt
idea/tests/org/jetbrains/kotlin/idea/editor/quickDoc/AbstractQuickDocProviderTest.java
idea/tests/org/jetbrains/kotlin/idea/editor/quickDoc/QuickDocProviderTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-32163

KT-32163: Open Quick Documentation when cursor inside function / constructor brackets

---

libraries/tools/kotlin-gradle-plugin-api/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/HasKotlinDependencies.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/DefaultKotlinDependencyHandler.kt
libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/npm/NpmDependencyExtension.kt

https://youtrack.jetbrains.com/issue/KT-32531
usecase: https://kotlinlang.slack.com/archives/C0BUHC9HD/p1588499421027500

KT-32531 [Gradle, JS]Should add devNpm, optionalNpm and peerNpm to reduce bundle size

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantSuspendModifierInspection.kt
idea/testData/inspectionsLocal/redundantSuspend/actual.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-37746

KT-37746 "Redundant suspend modifier" should not be reported for functions with actual keyword

---

idea/src/org/jetbrains/kotlin/idea/codeInsight/upDownMover/KotlinExpressionMover.kt
idea/testData/codeInsight/moveUpDown/parametersAndArguments/funParams10.kt
idea/testData/codeInsight/moveUpDown/parametersAndArguments/funParams9.kt
idea/tests/org/jetbrains/kotlin/idea/codeInsight/moveUpDown/MoveStatementTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-14757

KT-14757 Move statement up breaks code in function parameter list

---

libraries/stdlib/common/src/generated/_Strings.kt
libraries/stdlib/samples/test/samples/text/strings.kt
libraries/tools/kotlin-stdlib-gen/src/templates/Filtering.kt

[KT-35867](https://youtrack.jetbrains.com/issue/KT-35867) - Adds samples to Text `filter()` and `filterNot` functions.

Add samples for String/CharSequence filter & filterNot

---

idea/src/org/jetbrains/kotlin/idea/codeInliner/CodeToInlineBuilder.kt
idea/testData/quickfix/deprecatedSymbolUsage/importedObjectFunctionAddReceiver.kt
idea/testData/quickfix/deprecatedSymbolUsage/importedObjectFunctionAddReceiver.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33951

KT-33951 ReplaceWith quickfix with unqualified object member call doesn't substitute argument for parameter

---

libraries/stdlib/common/src/generated/_Arrays.kt
libraries/stdlib/common/src/generated/_Collections.kt
libraries/stdlib/common/src/generated/_Sequences.kt
libraries/stdlib/samples/test/samples/collections/collections.kt
libraries/tools/kotlin-stdlib-gen/src/templates/Ordering.kt

KT-20357 Added sortedBy() sample

---

idea/src/org/jetbrains/kotlin/idea/inspections/collections/UselessCallOnCollectionInspection.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/ReplaceSelectorOfQualifiedExpressionFix.kt
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/FilterIsExactInstanceOnArray.kt
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/FilterIsExactInstanceOnArray.kt.after
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/FilterNotNullOnArray.kt
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/FilterNotNullOnArray.kt.after
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/FilterNotNullOnIterable.kt
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/FilterNotNullOnIterable.kt.after
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/FilterNotNullOnSet.kt
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/FilterNotNullOnSet.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-38961

KT-38961 "Useless call on collection type" for filterNotNull on non-null array where list return type is expected

---

libraries/stdlib/js-v1/src/js/polyfills.js

Fix [KT-39244](https://youtrack.jetbrains.com/issue/KT-39244)
On `Object.defineProperty` default value on `enumerable` is `false`

Polyfills on prototype should be non-enumerable

---

idea/src/org/jetbrains/kotlin/idea/inspections/FoldInitializerAndIfToElvisInspection.kt
idea/testData/inspectionsLocal/foldInitializerAndIfToElvis/LongName2.kt
idea/testData/inspectionsLocal/foldInitializerAndIfToElvis/LongName2.kt.after
idea/testData/inspectionsLocal/foldInitializerAndIfToElvis/MultiLineInitializer.kt
idea/testData/inspectionsLocal/foldInitializerAndIfToElvis/MultiLineInitializer.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35805

KT-35805 FoldInitializerAndIfToElvis: should not add new line for multiline initializer

---

idea/src/org/jetbrains/kotlin/idea/inspections/collections/FunctionUtils.kt
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/MapNotNullWithLambda5.kt
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/MapNotNullWithLambda5.kt.after
idea/testData/inspectionsLocal/collections/uselessCallOnCollection/MapNotNullWithLambdaFake2.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-38267

KT-38267 False positive "Call on collection type may be reduced" with Java platform types: suggested to reduce 'mapNotNull' call to 'map'

---

idea/src/org/jetbrains/kotlin/idea/intentions/AnonymousFunctionToLambdaIntention.kt
idea/testData/intentions/anonymousFunctionToLambda/typeParameter.kt
idea/testData/intentions/anonymousFunctionToLambda/typeParameter.kt.after
idea/testData/intentions/anonymousFunctionToLambda/typeParameter2.kt
idea/testData/intentions/anonymousFunctionToLambda/typeParameter2.kt.after
idea/testData/intentions/anonymousFunctionToLambda/typeParameter3.kt
idea/testData/intentions/anonymousFunctionToLambda/typeParameter3.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
j2k/testData/fileOrElement/toKotlinClasses/LibraryFunctions.kt

https://youtrack.jetbrains.com/issue/KT-37748

KT-37748 "Convert anonymous function to lambda expression" intention does not add necessary lambda type parameter

---

idea/src/org/jetbrains/kotlin/idea/intentions/AnonymousFunctionToLambdaIntention.kt
idea/testData/intentions/anonymousFunctionToLambda/typeParameterWithUnusedParameter.kt
idea/testData/intentions/anonymousFunctionToLambda/typeParameterWithUnusedParameter.kt.after
idea/testData/intentions/anonymousFunctionToLambda/typeParameterWithUnusedParameter2.kt
idea/testData/intentions/anonymousFunctionToLambda/typeParameterWithUnusedParameter2.kt.after
idea/testData/intentions/anonymousFunctionToLambda/typeParameterWithVararg.kt
idea/testData/intentions/anonymousFunctionToLambda/typeParameterWithVararg.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-39393

KT-39393 "Convert anonymous function to lambda expression" intention does not add necessary lambda type parameter for outer function

---

idea/ide-common/src/org/jetbrains/kotlin/idea/core/quickfix/QuickFixUtil.java
idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeFunctionLiteralReturnTypeFix.kt
idea/testData/quickfix/typeMismatch/parameterTypeMismatch/changeFunctionParameterTypeWithComment.kt
idea/testData/quickfix/typeMismatch/parameterTypeMismatch/changeFunctionParameterTypeWithComment.kt.after
idea/testData/quickfix/typeMismatch/parameterTypeMismatch/changePrimaryConstructorParameterTypeOnPropertyDelegate.kt
idea/testData/quickfix/typeMismatch/parameterTypeMismatch/changePrimaryConstructorParameterTypeOnPropertyDelegate.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-15846

KT-15846 'Change lambda expression return type' quick fix does nothing

---

idea/src/org/jetbrains/kotlin/idea/refactoring/changeSignature/KotlinChangeSignatureHandler.kt
idea/testData/refactoring/changeSignature/PrimaryConstructorOnConstructorKeywordAfter.kt
idea/testData/refactoring/changeSignature/PrimaryConstructorOnConstructorKeywordBefore.kt
idea/tests/org/jetbrains/kotlin/idea/refactoring/changeSignature/KotlinChangeSignatureTest.kt

https://youtrack.jetbrains.com/issue/KT-19744

KT-19744 "Change Signature" is not available on `constructor` keyword in primary constructor

---

idea/src/org/jetbrains/kotlin/idea/editor/KotlinSmartEnterHandler.kt
idea/src/org/jetbrains/kotlin/idea/editor/fixers/KotlinPropertyAccessorBodyFixer.kt
idea/tests/org/jetbrains/kotlin/idea/codeInsight/smartEnter/SmartEnterTest.kt

https://youtrack.jetbrains.com/issue/KT-31500

KT-31500 Smart enter: support get() clause

---

idea/src/org/jetbrains/kotlin/idea/editor/wordSelection/KotlinStatementGroupSelectioner.kt
idea/testData/wordSelection/ValueParametersInLambda2/0.kt
idea/testData/wordSelection/ValueParametersInLambda2/1.kt
idea/testData/wordSelection/ValueParametersInLambda2/2.kt
idea/testData/wordSelection/ValueParametersInLambda2/3.kt
idea/testData/wordSelection/ValueParametersInLambda2/4.kt
idea/testData/wordSelection/ValueParametersInLambda3/0.kt
idea/testData/wordSelection/ValueParametersInLambda3/1.kt
idea/testData/wordSelection/ValueParametersInLambda3/2.kt
idea/testData/wordSelection/ValueParametersInLambda3/3.kt
idea/testData/wordSelection/ValueParametersInLambda3/4.kt
idea/testData/wordSelection/ValueParametersInLambda3/5.kt
idea/testData/wordSelection/ValueParametersInLambda4/0.kt
idea/testData/wordSelection/ValueParametersInLambda4/1.kt
idea/testData/wordSelection/ValueParametersInLambda4/2.kt
idea/testData/wordSelection/ValueParametersInLambda4/3.kt
idea/testData/wordSelection/ValueParametersInLambda4/4.kt
idea/testData/wordSelection/ValueParametersInLambda4/5.kt
idea/tests/org/jetbrains/kotlin/idea/WordSelectionTest.java

https://youtrack.jetbrains.com/issue/KT-29364

KT-29364 "Extend selection" can't select lambda body with parameters

---

idea/formatter/src/org/jetbrains/kotlin/idea/formatter/KotlinCommonBlock.kt
idea/performanceTests/test/org/jetbrains/kotlin/idea/perf/PerformanceTypingIndentationTestGenerated.java
idea/testData/indentationOnNewline/AfterExtensionPropertyGetter.after.kt
idea/testData/indentationOnNewline/AfterExtensionPropertyGetter.kt
idea/testData/indentationOnNewline/AfterExtensionPropertySetter.after.kt
idea/testData/indentationOnNewline/AfterExtensionPropertySetter.kt
idea/tests/org/jetbrains/kotlin/formatter/TypingIndentationTestBaseGenerated.java

https://youtrack.jetbrains.com/issue/KT-33131

KT-33131 No indent before get/set method while editing extension var declaration

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertReferenceToLambdaIntention.kt
idea/testData/intentions/convertReferenceToLambda/referencedFunctionWithDefaultArugment.kt
idea/testData/intentions/convertReferenceToLambda/referencedFunctionWithDefaultArugment.kt.after
idea/testData/intentions/convertReferenceToLambda/referencedFunctionWithDefaultArugment2.kt
idea/testData/intentions/convertReferenceToLambda/referencedFunctionWithDefaultArugment2.kt.after
idea/testData/intentions/convertReferenceToLambda/referencedFunctionWithDefaultArugment3.kt
idea/testData/intentions/convertReferenceToLambda/referencedFunctionWithDefaultArugment3.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-17222
https://youtrack.jetbrains.com/issue/KT-24138
https://youtrack.jetbrains.com/issue/KT-39532

KT-17222 "Convert reference to lambda" creates red code for method with default argument values

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertLambdaToReferenceIntention.kt
idea/testData/intentions/convertLambdaToReference/defaultArgument.kt
idea/testData/intentions/convertLambdaToReference/defaultArgument2.kt
idea/testData/intentions/convertLambdaToReference/defaultArgument3.kt
idea/testData/intentions/convertLambdaToReference/defaultArgument3.kt.after
idea/testData/intentions/convertLambdaToReference/defaultArgument4.kt
idea/testData/intentions/convertLambdaToReference/defaultArgument4.kt.after
idea/testData/intentions/convertLambdaToReference/defaultArgument5.kt
idea/testData/intentions/convertLambdaToReference/defaultArgument5.kt.after
idea/testData/intentions/convertLambdaToReference/suspendFunctionParameter.kt
idea/testData/intentions/convertLambdaToReference/suspendFunctionParameter3.kt
idea/testData/intentions/convertLambdaToReference/suspendFunctionParameter3.kt.after
idea/testData/intentions/convertLambdaToReference/unit.kt
idea/testData/intentions/convertLambdaToReference/unit2.kt
idea/testData/intentions/convertLambdaToReference/unit2.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-39532

KT-39532 Support intention to convert reference to lambda and vice versa for adapted references

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertLambdaToReferenceIntention.kt
idea/testData/intentions/convertLambdaToReference/generic2.kt
idea/testData/intentions/convertLambdaToReference/generic2.kt.after
idea/testData/intentions/convertLambdaToReference/generic3.kt
idea/testData/intentions/convertLambdaToReference/generic3.kt.after
idea/testData/intentions/convertLambdaToReference/generic4.kt
idea/testData/intentions/convertLambdaToReference/generic4.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-14578
https://youtrack.jetbrains.com/issue/KT-14395

KT-14578 Suggest "Convert lambda to reference" intention for generic extension function

---

idea/resources/injection/kotlinInjections.xml
idea/tests/org/jetbrains/kotlin/psi/KotlinStdlibInjectionTest.kt

https://youtrack.jetbrains.com/issue/KT-39231

KT-39231 Injection: Add receiver of kotlin.text.toPattern to standard Kotlin injections

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertToBlockBodyIntention.kt
idea/testData/intentions/convertToBlockBody/overrideWithPlatformType.kt
idea/testData/intentions/convertToBlockBody/overrideWithPlatformType.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-12222

KT-12222 Intention 'Convert to block body' should take nullability of overriden method into account when expression is of platform type

---

idea/resources-en/messages/KotlinBundle.properties
idea/src/org/jetbrains/kotlin/idea/quickfix/AddEqEqTrueFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixFactoryForTypeMismatchError.kt
idea/testData/quickfix/addEqEqTrue/notBoolean.kt
idea/testData/quickfix/addEqEqTrue/notBoolean2.kt
idea/testData/quickfix/addEqEqTrue/simple.kt
idea/testData/quickfix/addEqEqTrue/simple.kt.after
idea/testData/quickfix/addEqEqTrue/simple2.kt
idea/testData/quickfix/addEqEqTrue/simple2.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-39930

Introduce "Add '== true'" quick fix for TYPE_MISMATCH

---

idea/src/org/jetbrains/kotlin/idea/codeInliner/CallableUsageReplacementStrategy.kt
idea/src/org/jetbrains/kotlin/idea/codeInliner/ClassUsageReplacementStrategy.kt
idea/src/org/jetbrains/kotlin/idea/codeInliner/PropertyUsageReplacementStrategy.kt
idea/src/org/jetbrains/kotlin/idea/codeInliner/UsageReplacementStrategy.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/replaceWith/DeprecatedSymbolUsageFix.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/replaceWith/DeprecatedSymbolUsageFixBase.kt
idea/src/org/jetbrains/kotlin/idea/quickfix/replaceWith/DeprecatedSymbolUsageInWholeProjectFix.kt
idea/testData/quickfix/deprecatedSymbolUsage/operatorCalls/get.kt
idea/testData/quickfix/deprecatedSymbolUsage/operatorCalls/get.kt.after
idea/testData/quickfix/deprecatedSymbolUsage/operatorCalls/set.kt
idea/testData/quickfix/deprecatedSymbolUsage/operatorCalls/set.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-15944

KT-15944 IDEA doesn't suggest to replace deprecated get set operator functions when it used as operator

---

generators/tests/org/jetbrains/kotlin/generators/tests/GenerateTests.kt
idea/src/org/jetbrains/kotlin/idea/codeInsight/upDownMover/AbstractKotlinUpDownMover.java
idea/src/org/jetbrains/kotlin/idea/codeInsight/upDownMover/KotlinDeclarationMover.java
idea/src/org/jetbrains/kotlin/idea/codeInsight/upDownMover/KotlinExpressionMover.kt
idea/testData/codeInsight/moveUpDown/line/fileAnnotation.kt
idea/testData/codeInsight/moveUpDown/line/fileAnnotation.kt.after
idea/tests/org/jetbrains/kotlin/idea/codeInsight/moveUpDown/AbstractCodeMoverTest.kt
idea/tests/org/jetbrains/kotlin/idea/codeInsight/moveUpDown/MoveStatementTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-10790

KT-10790 "Move statement up" for @file-targeted annotation moves package declaration to bottom of file

---

idea/resources-en/inspectionDescriptions/ReplaceWithIgnoreCaseEquals.html
idea/resources-en/messages/KotlinBundle.properties
idea/resources/META-INF/inspections.xml
idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceWithIgnoreCaseEqualsInspection.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/.inspection
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/extension.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/extension.kt.after
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/extension2.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/extension2.kt.after
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/notApplicable.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/notApplicable2.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/notApplicable3.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/notApplicable4.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/nullable.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/nullable.kt.after
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/nullable2.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/nullable2.kt.after
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/nullable3.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/nullable3.kt.after
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/toLowerCase.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/toLowerCase.kt.after
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/toUpperCase.kt
idea/testData/inspectionsLocal/replaceWithIgnoreCaseEquals/toUpperCase.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-40016

KT-40016 Replace 'a.toLowerCase() == b.toLowerCase()' with 'a.equals(b, ignoreCase = true)' inspection

---

idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createCallable/CreateCallableFromCallActionFactory.kt
idea/testData/quickfix/createFromUsage/createFunction/call/abstract/notWritableAbstractSuperclass.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-40215

KT-40215 "Create abstract function" quick fix suggested even though surrounding class is non-abstract

---

idea/src/org/jetbrains/kotlin/idea/intentions/declarations/ConvertMemberToExtensionIntention.kt
idea/testData/intentions/declarations/convertMemberToExtension/delegatedProperty.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35128

KT-35128 Intention `Convert member to extension` hides property delegate text with single line comment

---

idea/src/org/jetbrains/kotlin/idea/intentions/MovePropertyToClassBodyIntention.kt
idea/testData/intentions/movePropertyToClassBody/annotationClass.kt
idea/testData/intentions/movePropertyToClassBody/dataClass.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-40558

KT-40558 False positive "Move to class body" intention on data class constructor property

---

idea/src/org/jetbrains/kotlin/idea/quickfix/WrapWithSafeLetCallFix.kt
idea/testData/quickfix/wrapWithSafeLetCall/invokeFunctionType.kt
idea/testData/quickfix/wrapWithSafeLetCall/invokeFunctionType.kt.after
idea/testData/quickfix/wrapWithSafeLetCall/invokeFunctionType2.kt
idea/testData/quickfix/wrapWithSafeLetCall/invokeFunctionType2.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-39490

KT-39490 'Wrap with ?.let' quickfix put the receiver in `let` lambda

---

idea/src/org/jetbrains/kotlin/idea/intentions/MergeIfsIntention.kt
idea/testData/intentions/mergeIfs/comments.kt.after
idea/testData/intentions/mergeIfs/comments2.kt
idea/testData/intentions/mergeIfs/comments2.kt.after
idea/testData/intentions/mergeIfs/comments3.kt
idea/testData/intentions/mergeIfs/comments3.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-33258
https://youtrack.jetbrains.com/issue/KT-39552

KT-33258 "Merge 'if's" intention drops comment before nested if

---

idea/src/org/jetbrains/kotlin/idea/intentions/ConvertReferenceToLambdaIntention.kt
idea/testData/intentions/convertReferenceToLambda/extensionFunctionalType2.kt
idea/testData/intentions/convertReferenceToLambda/extensionFunctionalType2.kt.after
idea/testData/intentions/convertReferenceToLambda/extensionFunctionalType3.kt
idea/testData/intentions/convertReferenceToLambda/extensionFunctionalType3.kt.after
idea/testData/intentions/convertReferenceToLambda/extensionFunctionalType4.kt
idea/testData/intentions/convertReferenceToLambda/extensionFunctionalType4.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35558

KT-35558 "Convert reference to lambda" intention generates wrong code for a High Order Function which expects an extension lambda

---

idea/src/org/jetbrains/kotlin/idea/intentions/JoinParameterListIntention.kt
idea/testData/intentions/joinArgumentList/hasEndOfLineComment.kt
idea/testData/intentions/joinParameterList/hasEndOfLineComment.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35214

KT-35214 Intention `Put parameters on one line`: don't suggest if parameters has end-of-line comments

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ExclExclCallFixes.kt
idea/testData/quickfix/addExclExclCall/functionReference.kt
idea/testData/quickfix/addExclExclCall/functionReference.kt.after
idea/testData/quickfix/addExclExclCall/functionReference2.kt
idea/testData/quickfix/addExclExclCall/functionReference2.kt.after
idea/testData/quickfix/addExclExclCall/functionReference3.kt
idea/testData/quickfix/addExclExclCall/functionReference3.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-37841

KT-37841 IllegalStateException after "add non-null asserted call" on nullable function reference

---

idea/src/org/jetbrains/kotlin/idea/inspections/branchedTransformations/IfThenToSafeAccessInspection.kt
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/implicitReceiver3.kt
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/implicitReceiver3.kt.after
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/inspectionData/expected.xml
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/senselessComparison.kt
idea/testData/inspectionsLocal/branched/ifThenToSafeAccess/uselessIsCheck.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-36051

KT-36051 IfThenToSafeAccessInspection: do not report if condition is SENSELESS_COMPARISON

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/EliminateWhenSubjectIntention.kt
idea/testData/intentions/branched/when/eliminateSubject/withoutElse.kt
idea/testData/intentions/branched/when/eliminateSubject/withoutElse.kt.after
idea/testData/intentions/branched/when/eliminateSubject/withoutElseUsedAsExpression.kt
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-35526

KT-35526 Intention "Eliminate argument of 'when'" is broken for 'when' expression without 'else' branch

---

idea/src/org/jetbrains/kotlin/idea/quickfix/WrapWithSafeLetCallFix.kt
idea/testData/quickfix/wrapWithSafeLetCall/unsafe.kt
idea/testData/quickfix/wrapWithSafeLetCall/unsafe.kt.after
idea/testData/quickfix/wrapWithSafeLetCall/unsafe2.kt
idea/testData/quickfix/wrapWithSafeLetCall/unsafe2.kt.after
idea/testData/quickfix/wrapWithSafeLetCall/unsafeForNullableParameter.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-18125

KT-18125 "Wrap with let {...}" intention not available in all cases

---

idea/src/org/jetbrains/kotlin/idea/inspections/NamingConventionInspections.kt
idea/testData/inspections/naming/function/test.kt

https://youtrack.jetbrains.com/issue/KT-20438

KT-20438 Naming convention inspections: factory functions that are named like classes are flagged

---

js/npm/templates/kotlin-test/README.md

Improve spelling in Kotlin Test module's README.md

---

idea/src/org/jetbrains/kotlin/idea/inspections/RedundantNullableReturnTypeInspection.kt
idea/testData/inspectionsLocal/redundantNullableReturnType/function/returnNullableForLambda.kt
idea/testData/inspectionsLocal/redundantNullableReturnType/function/returnNullableForLambda.kt.after
idea/testData/inspectionsLocal/redundantNullableReturnType/function/returnNullableForLocalFunction.kt
idea/testData/inspectionsLocal/redundantNullableReturnType/function/returnNullableForLocalFunction.kt.after
idea/testData/inspectionsLocal/redundantNullableReturnType/function/returnNullableFromLambdaInBlockBody.kt
idea/testData/inspectionsLocal/redundantNullableReturnType/function/returnNullableFromLambdaInSingleExpressionBody.kt
idea/testData/inspectionsLocal/redundantNullableReturnType/property/returnNullableFromLambdaInGetter.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-41800
https://youtrack.jetbrains.com/issue/KT-41817

`Redundant nullable return type` inspection: fix false positives/negatives

---

idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeMemberFunctionSignatureFix.kt
idea/testData/quickfix/override/nothingToOverride/addFunctionReciever.kt
idea/testData/quickfix/override/nothingToOverride/addFunctionReciever.kt.after
idea/testData/quickfix/override/nothingToOverride/changeFunctionReciever.kt
idea/testData/quickfix/override/nothingToOverride/changeFunctionReciever.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-21799

KT-21799 Quickfix "Change function signature" for receiver type doesn't change it

---

idea/resources/META-INF/inspections.xml

https://youtrack.jetbrains.com/issue/KT-33096

KT-33096 Turn 'MapGetWithNotNullAssertionOperator' into an intention

---

idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createClass/createClassUtils.kt
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/enumInBinaryExpression.kt
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/enumInBinaryExpression.kt.after
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-22666

KT-22666 "Create enum constant" quick fix could be provided

---

idea/resources-en/messages/KotlinBundle.properties
idea/resources/META-INF/inspections.xml
idea/resources/inspectionDescriptions/UnusedDataClassCopyResult.html
idea/src/org/jetbrains/kotlin/idea/inspections/UnusedDataClassCopyResultInspection.kt
idea/testData/inspectionsLocal/unusedDataClassCopyResult/.inspection
idea/testData/inspectionsLocal/unusedDataClassCopyResult/basic.kt
idea/testData/inspectionsLocal/unusedDataClassCopyResult/basic2.kt
idea/testData/inspectionsLocal/unusedDataClassCopyResult/used.kt
idea/testData/inspectionsLocal/unusedDataClassCopyResult/used2.kt
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-34121

KT-34121 Report unused result of data class `copy` method

---

idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createClass/CreateClassFromReferenceExpressionActionFactory.kt
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/enumEntryWithSuperclass.kt
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/objectForEnum.kt
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/objectForEnum.kt.after
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/objectForEnumInArgument.kt
idea/testData/quickfix/createFromUsage/createClass/referenceExpression/objectForEnumInEquals.kt
idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-22665

KT-22665 "Create object" quick fix produce wrong code for enum

---

compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/PropertyReferenceLowering.kt
compiler/testData/codegen/box/callableReference/property/inReceiverOfAnother.kt
compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java

JVM_IR: add a transformChildren call to PropertyReferenceLowering

---

compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/generators/DataClassMembersGenerator.kt
compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/DataClassMembersGenerator.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DataClassMembersGenerator.kt
compiler/testData/debug/localVariables/copyFunction.kt
compiler/testData/debug/stepping/dataClass.kt
compiler/testData/ir/sourceRanges/declarations/synthesizedDataClassMembers.txt
compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/IrSteppingTestGenerated.java
compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/SteppingTestGenerated.java
idea/jvm-debugger/jvm-debugger-test/testData/evaluation/singleBreakpoint/dataClassCopy.out

[IR] Do not generate line numbers for synthesized data class members.

---

idea/idea-analysis/resources/messages/KotlinIdeaAnalysisBundle.properties
idea/idea-analysis/src/org/jetbrains/kotlin/idea/highlighter/IdeErrorMessages.java

fixed grammar in DELEGATE_SPECIAL_FUNCTION_NONE_APPLICABLE error message

small change: DELEGATE_SPECIAL_FUNCTION_NONE_APPLICABLE: is -> are

---

libraries/stdlib/samples/test/samples/collections/builders.kt
libraries/stdlib/src/kotlin/collections/Collections.kt

Update example for default buildList to not use capacity
KT-41136

doc: update collection example

---

js/js.translator/src/org/jetbrains/kotlin/js/translate/declaration/DelegationTranslator.kt
js/js.translator/testData/box/propertyAccess/configurable.kt

Details - [KT-42364](https://youtrack.jetbrains.com/issue/KT-42364)

KT-42364 JS. Configurable delegated properties

---

idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/ElvisToIfThenIntention.kt
idea/testData/intentions/branched/elvisToIfThen/assignmentAndError.kt
idea/testData/intentions/branched/elvisToIfThen/assignmentAndError.kt.after
idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-42255

KT-42255 "Replace elvis expression with 'if' expression" intention shouldn't introduce unnecessary variable if 'error' expression is used

---

libraries/stdlib/jdk7/src/kotlin/io/path/ExperimentalPathApi.kt

Update ExperimentalPathApi annotation's SinceKotlin value to 1.4

---

libraries/stdlib/samples/test/samples/misc/preconditions.kt
libraries/stdlib/src/kotlin/util/Preconditions.kt

In the sample code, I think it's easier to understand if we emphasize the effect that requireNotNull can convert an argument to a non-null value.

KT-20357: Add a sample for requireNotNull

---

libraries/stdlib/jdk8/src/kotlin/streams/Streams.kt
libraries/stdlib/samples/test/samples/streams/streams.kt

Added samples for the kotlin.streams package
Issue: https://youtrack.jetbrains.com/issue/KT-20357

Added samples for the kotlin.streams package

---

libraries/stdlib/wasm/src/generated/_ArraysWasm.kt
libraries/stdlib/wasm/src/generated/_ComparisonsWasm.kt
libraries/stdlib/wasm/src/kotlin/Kotlin.kt
libraries/tools/kotlin-stdlib-gen/src/generators/GenerateStandardLib.kt
libraries/tools/kotlin-stdlib-gen/src/templates/Arrays.kt
libraries/tools/kotlin-stdlib-gen/src/templates/Comparables.kt
libraries/tools/kotlin-stdlib-gen/src/templates/dsl/CommonTypes.kt
libraries/tools/kotlin-stdlib-gen/src/templates/dsl/MemberBuilder.kt

When you merge it to your branch, please squash it with your commits related to stdlib, because these commits partially revert them.

Reuse more Native implementations for Wasm

---

plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/AbstractSerialGenerator.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/TypeUtil.kt

https://github.com/Kotlin/kotlinx.serialization/issues/984

Add support of nullable serializers to UseSerializers annotation

---

libraries/tools/kotlin-gradle-plugin-integration-tests/build.gradle.kts
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/java/org/jetbrains/kotlin/gradle/incapt/IncrementalAggregatingProcessor.java
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/java/org/jetbrains/kotlin/gradle/incapt/IncrementalBinaryIsolatingProcessor.java
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/java/org/jetbrains/kotlin/gradle/incapt/IncrementalIsolatingProcessor.java
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/KaptIncrementalWithAggregatingApt.kt
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/KaptIncrementalWithIsolatingApt.kt
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kaptIncrementalAggregatingProcessorProject/build.gradle
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kaptIncrementalAggregatingProcessorProject/src/main/java/bar/noAnnotations.kt
libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kaptIncrementalAggregatingProcessorProject/src/main/java/bar/withAnnotation.kt
plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/Kapt.kt
plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/KaptContext.kt
plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/KaptOptions.kt
plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/annotationProcessing.kt
plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/incremental/IncrementalAptCache.kt
plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/incremental/cache.kt
plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/incremental/classStructureCache.kt
plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/incremental/incrementalProcessors.kt
plugins/kapt3/kapt3-base/test/org/jetbrains/kotlin/kapt3/base/incremental/AnnotationProcessorDependencyCollectorTest.kt

It's first attempt to fix problem with micronaut: https://youtrack.jetbrains.com/issue/KT-40493
1. First commit repeat gradle logic for aggregating processors dependency tracking
2. Second add additional dependency tracking for processors `.class` file outputs to fix fail in new test (with binary outputs, before only dependencies for `.java` file was tracked)
3. new test

Fix incremental compilation 

---

plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/resolve/SerializableProperties.kt

Fixes Kotlin/kotlinx.serialization#956

Fix serializing properties with custom accessors

---

compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/ConversionUtils.kt
compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrDeclarationStorage.kt
compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/generators/AdapterGenerator.kt
compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/generators/DataClassMembersGenerator.kt
compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/IrUtils.kt
compiler/ir/backend.common/src/org/jetbrains/kotlin/ir/builders/declarations/declarationBuilders.kt
compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ArgumentsGenerationUtils.kt
compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ReflectionReferencesGenerator.kt
compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ScriptGenerator.kt
compiler/ir/ir.tree.impl/src/org/jetbrains/kotlin/ir/declarations/impl/IrValueParameterImpl.kt
compiler/ir/ir.tree.persistent/src/org/jetbrains/kotlin/ir/declarations/persistent/PersistentIrValueParameter.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrFactory.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/lazy/IrLazyDeclarationBase.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/descriptors/IrBuiltIns.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/descriptors/IrFunctionFactory.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/overrides/FakeOverrideCopier.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DeclarationStubGenerator.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DeepCopyIrTreeWithSymbols.kt
compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/SymbolTable.kt
plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/codegen/AndroidIrExtension.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/ir/GeneratorHelpers.kt

There were a couple of places where they were confused and
isAssignable was passed as a positional parameter in the position
of isHidden.

[IR] Make isHidden and isAssignable explicit on IrValueParameter.

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FileClassLowering.kt
compiler/testData/codegen/bytecodeListing/fileClassWithPrivateDeclarationsOnly_after.kt
compiler/testData/codegen/bytecodeListing/fileClassWithPrivateDeclarationsOnly_after.txt
compiler/testData/codegen/bytecodeListing/fileClassWithPrivateDeclarationsOnly_before.kt
compiler/testData/codegen/bytecodeListing/fileClassWithPrivateDeclarationsOnly_before.txt
compiler/tests-gen/org/jetbrains/kotlin/codegen/BytecodeListingTestGenerated.java
compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/IrBytecodeListingTestGenerated.java
compiler/util/src/org/jetbrains/kotlin/config/LanguageVersionSettings.kt

Make file classes with all private members package-private during lowering.
Related issue: https://youtrack.jetbrains.com/issue/KT-10884

[JVM_IR] Make file classes with all private members package-private

---

plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/TypeUtil.kt

Fixes Kotlin/kotlinx.serialization#1265

Returned support for nullable types by not null serializers

---

ant/src/org/jetbrains/kotlin/ant/Kotlin2JvmTask.kt
compiler/testData/integration/ant/jvm/doNotIncludeRuntimeByDefault/build.log.expected
compiler/testData/integration/ant/jvm/doNotIncludeRuntimeByDefault/build.xml
compiler/testData/integration/ant/jvm/doNotIncludeRuntimeByDefault/test.kt
compiler/testData/integration/ant/jvm/kt11995/build.xml
compiler/tests-gen/org/jetbrains/kotlin/integration/AntTaskTestGenerated.java

[KT-16227](https://youtrack.jetbrains.com/issue/KT-16227)

Ant task: do not include runtime by default if destination is a jar

---

plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/AbstractSerialGenerator.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/TypeUtil.kt

Fixes Kotlin/kotlinx.serialization#1305

Returned support for generic serializers in @UseSerializers

---

compiler/tests-common/tests/org/jetbrains/kotlin/integration/AbstractAntTaskTest.java

192 Mb is not enought anymore apparently

Increase -Xmx for Ant tests

---

plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/AbstractSerialGenerator.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/SerializableCodegen.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/ir/GeneratorHelpers.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/ir/SerializableIrGenerator.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/ir/SerializerIrGenerator.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/jvm/SerializableCodegenImpl.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/resolve/SerializableProperties.kt

- added fallback support of external serializers in IR
- implemented calculations of properties default values in IR
- swapped check of shouldEncodeElementDefault and comparing the property with default value in IR. Now default value calculated only of shouldEncodeElementDefault returns false

Added external serializers in serialization plugin for IR backend

---

plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/ir/GeneratorHelpers.kt

Fixes Kotlin/kotlinx.serialization#1334

Support serialization of java enum classes in IR

---

libraries/tools/new-project-wizard/src/org/jetbrains/kotlin/tools/projectWizard/Versions.kt

Use appropriate kotlin wrappers version (1.4.21 -> 1.4.30)

---

libraries/tools/new-project-wizard/src/org/jetbrains/kotlin/tools/projectWizard/Versions.kt

[Details](https://youtrack.jetbrains.com/issue/KTOR-1084)
cc @ilgonmic

Use optimized Ktor client in wizard (-0.5MB)

---

libraries/stdlib/src/kotlin/reflect/typeOf.kt

please tag with `hacktoberfest-approved`

small change: update with fix of KT-12448

---

compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/FirSourceChild.kt
compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirDeclarationCheckerUtils.kt
compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirMemberPropertiesChecker.kt
compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirTopLevelPropertiesChecker.kt
compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/diagnostics/SourceElementPositioningStrategies.kt

This is a simple follow-up PR to address comments from previous PRs.
* https://github.com/JetBrains/kotlin/pull/4162#discussion_r587332152
* https://github.com/JetBrains/kotlin/pull/4142#discussion_r587280893

FIR checker: minor cleanups

---

core/builtins/src/kotlin/Progressions.kt
core/builtins/src/kotlin/Range.kt
core/builtins/src/kotlin/Ranges.kt
generators/builtins/progressions.kt
generators/builtins/ranges.kt
generators/builtins/unsignedTypes.kt
libraries/stdlib/unsigned/src/kotlin/UIntRange.kt
libraries/stdlib/unsigned/src/kotlin/ULongRange.kt

[KT-33783](https://youtrack.jetbrains.com/issue/KT-33783)
@p7nov, please take a look.

KT-33783 KDoc: Detail when a range is empty

---

compiler/testData/codegen/box/reflection/methodsFromAny/propertyToString.kt
core/reflection.jvm/src/kotlin/reflect/jvm/internal/KPropertyImpl.kt

Related to [KT-10838](https://youtrack.jetbrains.com/issue/KT-10838)

Reflection: provide sensible toString for getter/setter in reflection

---

libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/internal/kapt/Kapt3KotlinGradleSubplugin.kt
plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/KaptOptions.kt

Group flag names and default values in one place to make the code easier
to read and prevent mistakes and inconsistencies.
Bug: Clean-up after commit e252171 for KT-43593
Test: Existing tests

Kapt: Ensure flag names and default values are consistent

---

compiler/frontend/src/org/jetbrains/kotlin/resolve/BodyResolver.java
compiler/testData/resolve/regressions/kt45676.resolve
compiler/tests-gen/org/jetbrains/kotlin/resolve/ResolveTestGenerated.java

Please see the bug for more details: https://youtrack.jetbrains.com/issue/KT-45676

KT-45676: fix backing field annotation resolve

---

kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/StubRenderer.kt
kotlin-native/backend.native/tests/build.gradle
kotlin-native/backend.native/tests/objcexport/expectedLazy.h
kotlin-native/backend.native/tests/objcexport/kdocExport.kt

Fix indentation and extra blank lines in exported kdoc

[Native] Add test for -Xexport-kdoc

---

idea/src/org/jetbrains/kotlin/idea/inspections/UnnecessaryVariableInspection.kt
idea/testData/inspectionsLocal/unnecessaryVariable/ifElse.kt
idea/testData/inspectionsLocal/unnecessaryVariable/ifElse.kt.after
idea/testData/inspectionsLocal/unnecessaryVariable/ifElse2.kt
idea/testData/inspectionsLocal/unnecessaryVariable/ifElse2.kt.after
idea/testData/inspectionsLocal/unnecessaryVariable/ifElse3.kt
idea/testData/inspectionsLocal/unnecessaryVariable/ifElse3.kt.after
idea/testData/inspectionsLocal/unnecessaryVariable/ifElse4.kt
idea/testData/inspectionsLocal/unnecessaryVariable/ifElse4.kt.after
idea/testData/inspectionsLocal/unnecessaryVariable/ifElse5.kt
idea/testData/inspectionsLocal/unnecessaryVariable/ifElse5.kt.after
idea/testData/inspectionsLocal/unnecessaryVariable/lambda.kt
idea/testData/inspectionsLocal/unnecessaryVariable/lambda.kt.after
idea/testData/inspectionsLocal/unnecessaryVariable/lambda2.kt
idea/testData/inspectionsLocal/unnecessaryVariable/lambda2.kt.after
idea/testData/inspectionsLocal/unnecessaryVariable/try.kt
idea/testData/inspectionsLocal/unnecessaryVariable/try.kt.after
idea/testData/inspectionsLocal/unnecessaryVariable/when.kt
idea/testData/inspectionsLocal/unnecessaryVariable/when.kt.after
idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java

https://youtrack.jetbrains.com/issue/KT-26752

KT-26752 Separate "try-catch-finally" situation from the generic "Unnecessary local variable" inspection

---

plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/TypeUtil.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/ir/SerializerIrGenerator.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/js/SerializerJsTranslator.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/jvm/SerializerCodegenImpl.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/resolve/KSerializationUtil.kt
plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/resolve/SerializableProperties.kt

Fixes Kotlin/kotlinx.serialization#1386

Add `.serializer()` to enum companion and object with custom serializer

---

plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/TypeUtil.kt

Fixes Kotlin/kotlinx.serialization#1353

Support serializable classes clash with JVM primitive types by name

---

compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IteratorNext.kt
compiler/testData/codegen/box/callableReference/function/kt47741.kt
compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java

the expected type.
^KT-47741 Fixed.

Fix IteratorNext intrinsic to cast its dispatch receiver to

---

compiler/testData/diagnostics/foreignAnnotationsTests/java8Tests/misc/enhancedRecursiveStarProjection.fir.kt
compiler/testData/diagnostics/foreignAnnotationsTests/java8Tests/misc/enhancedRecursiveStarProjection.kt
compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/ForeignAnnotationsCompiledJavaTestGenerated.java
compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/ForeignAnnotationsCompiledJavaWithPsiClassReadingTestGenerated.java
compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/ForeignAnnotationsSourceJavaTestGenerated.java
core/descriptors/src/org/jetbrains/kotlin/types/TypeSubstitutor.java

FE: avoid stack overflow on star projection of enhanced type parameter

---

compiler/backend/src/org/jetbrains/kotlin/codegen/inline/InlineCodegen.kt
compiler/testData/debug/localVariables/tryFinally10.kt
compiler/testData/debug/localVariables/tryFinally9.kt

Copy locals in addition to instructions when inlining finally blocks

---

plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/codegen/AbstractAndroidExtensionsExpressionCodegenExtension.kt
plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/codegen/AndroidIrExtension.kt
plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/codegen/AndroidOnDestroyClassBuilderInterceptorExtension.kt

JVM_IR: implement view caching in kotlin-android-extensions

---

compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
compiler/testData/debug/localVariables/tryFinally11.kt
compiler/testData/debug/localVariables/tryFinally12.kt
compiler/testData/debug/localVariables/tryFinally17.kt
compiler/testData/debug/stepping/tryFinally.kt
compiler/tests-gen/org/jetbrains/kotlin/codegen/debugInformation/IrLocalVariableTestGenerated.java
compiler/tests-gen/org/jetbrains/kotlin/codegen/debugInformation/LocalVariableTestGenerated.java

[JVM IR] Generate line number for exception store for finally.

---

kotlin-native/NEW_MM.md

Update New memory model guide

---

plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ParcelizeAnnotationChecker.kt

See https://issuetracker.google.com/177404709

Parcelize: Allow IgnoredOnParcel annotations on object properties

---

compiler/cli/cli-runner/src/org/jetbrains/kotlin/runner/Main.kt
compiler/cli/cli-runner/src/org/jetbrains/kotlin/runner/runners.kt
compiler/testData/launcher/defaultPackage.kt
compiler/tests/org/jetbrains/kotlin/cli/LauncherScriptTest.kt

Related to [KT-11164](https://youtrack.jetbrains.com/issue/KT-11164)

CLI: Allow running class files with '.class' extension in 'kotlin' script

---

libraries/kotlinx-metadata/jvm/ReadMe.md

Modify ReadMe of `kotlinx-metadata-jvm`.

---

compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/ReflectiveAccess.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmReflectSymbols.kt
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSymbols.kt

[IR] Refactor `JvmSymbols` for on-demand `java.lang.reflect` symbols

---

plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/codegen/AndroidIrExtension.kt
plugins/android-extensions/android-extensions-compiler/testData/codegen/android/singleFile/0.kt

https://youtrack.jetbrains.com/issue/KT-49799
to avoid NPEs if it is used during instance initialization.

IR/Android: place the cache field first

---

compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBytecodeTextTestGenerated.java
compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/MemoizedInlineClassReplacements.kt
compiler/testData/codegen/box/annotations/annotationDefaultValueOfUnsigned.kt
compiler/testData/codegen/bytecodeText/annotationDefaultValueOfUnsigned.kt
compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBytecodeTextTestGenerated.java

issue: [KT-49998](https://youtrack.jetbrains.com/issue/KT-49998)

JVM_IR: recover accidentally lost backingField (KT-49998)

---

plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/codegen/AndroidIrExtension.kt

https://youtrack.jetbrains.com/issue/KT-50784

Android extensions: do not produce unbound symbol for mutableMapOf

---

docs/analysis/low-level-api-fir/low-level-api-fir.md

Docs: fix typos and references

---

compiler/testData/codegen/box/reflection/callBy/inlineClassDefaultArguments.kt
core/reflection.jvm/src/kotlin/reflect/jvm/internal/calls/InlineClassAwareCaller.kt

The issues fixed are as described in the ticket.
https://youtrack.jetbrains.com/issue/KT-51804

Fix KT-51804

---

compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt

This change originates with KTIJ-21907: the IR fragment compiler includes various, transitive dependencies of the fragment code including the file with the breakpoint.
If...
1. the fragment sufficiently depends on its context that the file with the breakpoint is included; and...
2. the file with the breakpoint contains _other_, unrelated declarations that call inline functions in a different file; and...
3. that file is not included by the fragment compiler...
... then compilation of the files included due to 2. cause failures in the JVM codegen when it wants to inline the bytecode for those definitions.
The fragment compiler discards the generated code regardless, so we may as well not generate the bytecode. Alternatively, we could _include_ all the files, remedying 3., but at the limit …

[IR] Have JVM codegen respect the GenerateClassFilter supplied to GenerationState

---

kotlin-native/Interop/Indexer/src/main/kotlin/org/jetbrains/kotlin/native/interop/indexer/Utils.kt
kotlin-native/backend.native/tests/build.gradle
kotlin-native/backend.native/tests/interop/objc/kt53151/main.kt
kotlin-native/backend.native/tests/interop/objc/kt53151/objclib.def
kotlin-native/backend.native/tests/interop/objc/kt53151/testFramework/Foo.framework/Headers/Foo.h
kotlin-native/backend.native/tests/interop/objc/kt53151/testFramework/Foo.framework/Modules/module.modulemap

Fixes [KT-53151](https://youtrack.jetbrains.com/issue/KT-53151/Custom-declarations-in-def-dont-work-with-modules-only-headers).

KT-53151 support custom declarations with modules def file

---

libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/targets/native/NativeBinaries.kt

See also https://youtrack.jetbrains.com/issue/KTIJ-14967

Native: add KDoc for entryPoint

---

compiler/config/src/org/jetbrains/kotlin/config/CommonConfigurationKeys.kt

Fix typo in name for EXPECT_ACTUAL_LINKER key

---

libraries/stdlib/jvm/src/kotlin/io/ReadWrite.kt

Also replace semicolon with comma to fix grammar.

Close parenthesis

---

compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/FirKotlinToJvmBytecodeCompiler.kt
compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/KotlinToJVMBytecodeCompiler.kt
compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/cliCompilerUtils.kt
compiler/ir/backend.jvm/entrypoint/src/org/jetbrains/kotlin/backend/jvm/JvmIrCodegenFactory.kt
compiler/testData/cli/jvm/conflictingJvmDeclarations.test
compiler/testData/cli/jvm/conflictingJvmDeclarationsK2.args
compiler/testData/cli/jvm/conflictingJvmDeclarationsK2.out
compiler/testData/cli/jvm/conflictingJvmDeclarationsK2.test
compiler/testData/integration/smoke/destinationDirNoPermission/test.notWindows.compile.expected
compiler/tests-gen/org/jetbrains/kotlin/cli/CliTestGenerated.java

Fixes [#KT-53825](https://youtrack.jetbrains.com/issue/KT-53825/class-files-are-generated-when-compilation-fails-with-platform-declaration-clash)

JVM_IR: Prevent writing output after an error is reported

---

libraries/stdlib/common/src/generated/_Maps.kt
libraries/stdlib/samples/test/samples/collections/sequences.kt
libraries/tools/kotlin-stdlib-gen/src/templates/Sequence.kt

want to add samples on sequence for the standard library

Add sample on sequence

---

compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirLightTreeBlackBoxCodegenTestGenerated.java
compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirPsiBlackBoxCodegenTestGenerated.java
compiler/testData/codegen/box/reflection/call/inlineClasses/simpleConstructorWithInlineClassParameter.kt
compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
core/reflection.jvm/src/kotlin/reflect/jvm/internal/calls/InlineClassAwareCaller.kt

SSIA
https://youtrack.jetbrains.com/issue/KT-56650

Fix KT-56650

---

plugins/parcelize/parcelize-compiler/parcelize.backend/src/org/jetbrains/kotlin/parcelize/ir/IrParcelSerializerFactory.kt
plugins/parcelize/parcelize-compiler/testData/box/nullableSparseArrays.kt
plugins/parcelize/parcelize-compiler/tests-gen/org/jetbrains/kotlin/parcelize/test/runners/ParcelizeBoxTestGenerated.java
plugins/parcelize/parcelize-compiler/tests-gen/org/jetbrains/kotlin/parcelize/test/runners/ParcelizeFirLightTreeBoxTestGenerated.java
plugins/parcelize/parcelize-compiler/tests-gen/org/jetbrains/kotlin/parcelize/test/runners/ParcelizeIrBoxTestGenerated.java

Fixes https://issuetracker.google.com/269956252

Parcelize: Handle nullable sparse arrays

---

compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/BridgeLowering.kt

Simplify and optimize BridgeLowering

---

compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/transformers/plugin/AbstractFirSpecificAnnotationResolveTransformer.kt

`withFileScopes`  has created import scope

remove duplicate import scope create

---

compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/AnnotationCodegen.kt

Instead of printing the value parameter instance, pretty print the value parameter

[IR] Improve printing the value parameter when there is an error

---

repo/scripts/cache-redirector.settings.gradle.kts

Commit c198d4d90de0f90a6da0171b53b015b36339ecdd renamed the cache-redirector file. This PR adjusts sources to changes.

Update cache-redirector file
