JetBrains/kotlin

- compiler/backend/src/org/jetbrains/kotlin/codegen/MemberCodegen.java
- compiler/testData/codegen/bytecodeText/redundantInitializer.kt
- compiler/testData/codegen/bytecodeText/redundantInitializerNumber.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
Since only 'val' properties store initializers as compile time constants in descriptors, we need to take the initializer expression from the PSI and try to evaluate it as a constant.
#KT-6661 fixed
> Don't generate redundant initializers for 'var' properties.

- idea/src/org/jetbrains/kotlin/idea/kdoc/KDocFinder.kt
- idea/testData/kdoc/finder/Overridden.kt
- idea/testData/kdoc/finder/OverriddenWithSubstitutedType.kt
- idea/tests/org/jetbrains/kotlin/idea/kdoc/KDocFinderTest.kt
(The test doesn't actually reproduce the problem because it can't be done in a single-file setup, but it verifies that the basic functionality continues to work.)
> Fix retrieving documentation for overridden methods.

- idea/src/META-INF/plugin.xml
It makes no sense to include attempt number in 'since/until-build' attributes because only one of these builds is publicly available, also the attempt number in these attributes currently confuses Plugin Verifier.
> fixed 'since-build' attribute

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinPlugin.kt
When you build the project for the first time after cleaning, you lose paths to internal_impl jars of support libraries such as
build/intermediates/exploded-aar/com.android.support/support-v4/21.0.2/libs/internal_impl-21.0.2.jar
They are absent in javaCompile.getClasspath() when javaCompile task starts.
This patch fixes it.
#KT-7277 Fixed
> Fix #KT-7277 Build fails after project cleaning

- idea/idea-core/src/org/jetbrains/kotlin/idea/core/codeInsight/OverrideImplementMethodsHandler.java
- idea/testData/codeInsight/overrideImplement/escapeIdentifiers.kt
- idea/testData/codeInsight/overrideImplement/escapeIdentifiers.kt.after
- idea/tests/org/jetbrains/kotlin/idea/codeInsight/OverrideImplementTest.java
> escape identifiers in generated super method call in Override/Implement

- build.xml
- libraries/examples/browser-example-with-library/pom.xml
- libraries/examples/browser-example/pom.xml
- libraries/kotlin.test/js/pom.xml
- libraries/kotlin.test/junit/pom.xml
- libraries/kotlin.test/pom.xml
- libraries/kotlin.test/shared/pom.xml
- libraries/stdlib/pom.xml
- libraries/tools/kotlin-compiler-embeddable/pom.xml
- libraries/tools/kotlin-js-tests-junit/pom.xml
1. rename artifact names
2. exclude `OnlyInputTypes` from the jar
> Testlib fix

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/android/AndroidGradleWrapper.groovy
This includes the output directories from tasks which generate Java code which were registered with `registerJavaGeneratingTask()`.
I'm not sure how to implement a fallback for this for newer Android plugins as was added recently for the other source folders lookup.
cc @NataliaUkhorskaya
> Include source folders from registered source-generating tasks.

- idea/src/org/jetbrains/kotlin/idea/run/JetRunConfiguration.java
…to avoid sharing RunConfigurationModule instances between different run configurations (KT-12204)
> run configuration: use default logic of creating new run configurations

- idea/formatter/src/org/jetbrains/kotlin/idea/formatter/kotlinSpacingRules.kt
- idea/testData/formatter/ClassTypeParam.after.kt
- idea/testData/formatter/ClassTypeParam.kt
- idea/tests/org/jetbrains/kotlin/formatter/FormatterTestGenerated.java
> Formatter: handle spaces between class name and type parameters

- ReadMe.md
I would link to start contributing kotlin and noticed "this query" link is not related with Kotlin issues. I believe Kotlin repo's contributing section should show open kotlin issues.
Sorry if I skip steps before sending pull request.
> Change contributing section of "this query" link to finding open Kotlin issue

- idea/src/org/jetbrains/kotlin/idea/quickfix/NumberConversionFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixFactoryForTypeMismatchError.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/WrongPrimitiveLiteralFix.kt
- idea/testData/quickfix/typeMismatch/numberConversion/convertExpression.kt
- idea/testData/quickfix/typeMismatch/numberConversion/convertExpression.kt.after
- idea/testData/quickfix/typeMismatch/wrongPrimitive/doubleToIntDecimalPlaces.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/doubleToLongNotInRange.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/doubleToShortNotInRange.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/floatToDoubleWithDecimal.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/floatToDoubleWithDecimal.kt.after
- idea/testData/quickfix/typeMismatch/wrongPrimitive/floatToInt.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/floatToInt.kt.after
- idea/testData/quickfix/typeMismatch/wrongPrimitive/floatToInt2.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/floatToInt2.kt.after
- idea/testData/quickfix/typeMismatch/wrongPrimitive/floatToLong.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/floatToLong.kt.after
- idea/testData/quickfix/typeMismatch/wrongPrimitive/hexToFloat.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/hexToFloat.kt.after
- idea/testData/quickfix/typeMismatch/wrongPrimitive/intToFloat.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/intToFloat.kt.after
- idea/testData/quickfix/typeMismatch/wrongPrimitive/longToDouble.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/longToDouble.kt.after
- idea/testData/quickfix/typeMismatch/wrongPrimitive/longToInt.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/longToInt.kt.after
- idea/testData/quickfix/typeMismatch/wrongPrimitive/longToIntBinary.kt
- idea/testData/quickfix/typeMismatch/wrongPrimitive/longToIntBinary.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
Fixes: KT-12251
Not sure if I should disable the other quickfix which adds a call to `.toX()`
> Implement quickfix for wrong primitive literal

- idea/src/META-INF/plugin.xml
- idea/src/org/jetbrains/kotlin/idea/editor/wordSelection/KotlinInvokedExpressionSelectioner.kt
- idea/testData/wordSelection/InvokedExpression/0.kt
- idea/testData/wordSelection/InvokedExpression/1.kt
- idea/testData/wordSelection/InvokedExpression/2.kt
- idea/testData/wordSelection/InvokedExpression/3.kt
- idea/testData/wordSelection/InvokedExpression/4.kt
- idea/testData/wordSelection/InvokedExpression/5.kt
- idea/tests/org/jetbrains/kotlin/idea/WordSelectionTest.java
#KT-12887 fixed
This probably conflicts with #898
> KT-12887 Extend selection should select call's invoked expression

- idea/src/org/jetbrains/kotlin/idea/quickfix/MakeConstructorParameterPropertyFix.kt
- idea/testData/quickfix/makeConstructorParameterProperty/inner.kt.after
- idea/testData/quickfix/makeConstructorParameterProperty/val.kt.after
- idea/testData/quickfix/makeConstructorParameterProperty/var.kt.after
> Quickfix "Make primary constructor parameter a val" makes the val private now

- compiler/frontend/src/org/jetbrains/kotlin/psi/KtTypeReference.kt
A year old typo had this redundantly checking for LPAR twice, rather than checking once for LPAR and once for RPAR.
> Fix KtTypeReference.hasParentheses() to check for both LPAR and RPAR

- j2k/src/org/jetbrains/kotlin/j2k/Converter.kt
- j2k/testData/fileOrElement/annotations/serialVersionUID.java
- j2k/testData/fileOrElement/annotations/serialVersionUID.kt
- j2k/testData/fileOrElement/issues/kt-837.kt
- j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterForWebDemoTestGenerated.java
- j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterSingleFileTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-13750
Notes: Should it add `@JvmStatic` really even if field matches `* static final long serialVersionUID` or preform check for `java.io.Serializable` is implemented
Now it preforms check.
Also topic on discuss: `@JvmStatic` or `@JvmField`
> #KT-13750 fix

- js/js.translator/src/org/jetbrains/kotlin/js/sourceMap/SourceMap3Builder.java
The usage of `//@` in sourceMappingURL pragmas was deprecated in favor of `//#`. 
The deprecation happened in 2013, and was motivated by incompatibilities in IE.
The Chromium and Mozilla issues tracking the change:
https://bugs.chromium.org/p/chromium/issues/detail?id=239660
https://bugzilla.mozilla.org/show_bug.cgi?id=870361
And the Mozilla documentation on the warning that is issued as a result of using the deprecated syntax:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_source_map_pragma
> Update usage of deprecated sourceMappingURL format

- idea/src/org/jetbrains/kotlin/idea/inspections/KotlinUnusedImportInspection.kt
New IDEA per-project setting was completely ignored by Kotlin.
> Deprecated setting was used for import optimization on the fly.

- idea/src/org/jetbrains/kotlin/idea/intentions/ConvertPrimaryConstructorToSecondaryIntention.kt
- idea/testData/intentions/convertPrimaryConstructorToSecondary/annotationClass.kt
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
> Do not suggest 'Convert to secondary constructor' for annotation classes

- idea/src/org/jetbrains/kotlin/idea/intentions/MovePropertyToClassBodyIntention.kt
- idea/testData/quickfix/typeOfAnnotationMember/star.kt
- idea/testData/quickfix/typeOfAnnotationMember/string.kt
As I understand, annotation classes cannot have a body. Consequently, the "Move to class body" intention should not be available for annotation parameters.
#KT-17708 Fixed
> KT-17708 - Remove "Move to class body" intention for annotation parameters

- js/js.libraries/src/core/math.kt
https://youtrack.jetbrains.com/issue/KT-17853
The current exposition of the JavaScript [Math object] switched the parameters names: x and y are inverted which is confusing. 
The correct version is `atan2(y,x)` and not the current `atan2(x,y)`
> KT-17853: Kotlin.js switched parameters of Math.atan2

- ReadMe.md
Created with https://github.com/dkhamsing/frankenstein
Was | Now 
--- | --- 
http://try.kotlinlang.org/ | https://try.kotlinlang.org/
> Update README URLs based on HTTP redirects

- compiler/frontend/src/org/jetbrains/kotlin/psi/KtPsiFactory.kt
- idea/src/org/jetbrains/kotlin/idea/intentions/ConvertFunctionToPropertyIntention.kt
- idea/testData/intentions/convertFunctionToProperty/addExplicitAnonymousType.kt.after
- idea/testData/intentions/convertFunctionToProperty/addExplicitLocalType.kt.after
- idea/testData/intentions/convertFunctionToProperty/addExplicitType.kt.after
- idea/testData/intentions/convertFunctionToProperty/annotationLineBreak.kt
- idea/testData/intentions/convertFunctionToProperty/annotationLineBreak.kt.after
- idea/testData/intentions/convertFunctionToProperty/comments.kt
- idea/testData/intentions/convertFunctionToProperty/comments.kt.after
- idea/testData/intentions/convertFunctionToProperty/noExplicitType.kt
- idea/testData/intentions/convertFunctionToProperty/noExplicitType.kt.after
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
> Convert function to property shouldn't insert explicit type if it was inferred previously

- idea/src/org/jetbrains/kotlin/idea/intentions/MovePropertyToConstructorIntention.kt
- idea/testData/quickfix/canBePrimaryConstructorProperty/vararg.kt
- idea/testData/quickfix/canBePrimaryConstructorProperty/vararg.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
> Move property to constructor preserves vararg keyword

- ReadMe.md
http://kotlinslackin.herokuapp.com/ is down, replaced with http://slack.kotlinlang.org/
> Fixed Slack link

- ultimate/resources/META-INF/kotlin-spring.xml
- ultimate/resources/inspectionDescriptions/KotlinFinalClassOrFunSpring.html
Because Uast-based "Final declaration can't be overridden at runtime" inspection covers it's functionality
> Disabling obsolete "Final Kotlin class or function with Spring annotation" inspection 

- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
- idea/testData/quickfix/modifiers/redundantOpenInInterface.kt
- idea/testData/quickfix/modifiers/redundantOpenInInterface.kt.after
https://youtrack.jetbrains.com/issue/KT-18738
> KT-18738 Misleading quick fix message for an 'open' modifier on an interface member

- idea/src/org/jetbrains/kotlin/idea/intentions/DestructureIntention.kt
- idea/testData/intentions/destructuringVariables/classProperty.kt
- idea/testData/intentions/destructuringVariables/toplevel.kt
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
> "Use destructuring declaration" should not be available for top-level and class properties

- ReadMe.md
Reduce the barrier to entry for working on Kotlin by providing a download link for the MacOS JDK6 in the ReadMe.
One of the big things that prevented me from being able to contribute and test my previous fix was not being able to find a copy of the JDK 6 to run on MacOS.
Providing a link directly in the Readme will help new developers dive in and contribute easier.
It certainly would have helped me.
> Add download link for JDK6 on MacOS to Readme.md

- ReadMe.md
- js/npm.templates/kotlin-compiler/README.md
- js/npm.templates/kotlin/README.md
Replaced public slack channel link,
http://kotlinslackin.herokuapp.com/ to http://slack.kotlinlang.org/
> Fix incorrect slack link

- core/builtins/native/kotlin/Boolean.kt
I and my coworker @nicholaspark09 notice some differences in the generated bytecode when using the `&&` operator and the `and` infix function. 
For
```kotlin
fun andOperator(a: Boolean, b: Boolean) = a && b
```
the generated bytecode is : 
```
L0
LINENUMBER 3 L0
ILOAD 0
IFEQ L1
ILOAD 1
IFEQ L1
L2
ICONST_1
GOTO L3
L1
ICONST_0
L3
IRETURN
L4
```
Whereas for 
```kotlin
fun andInfixFun(a: Boolean, b: Boolean) = a and b
```
the bytecode is : 
```
L0
LINENUMBER 5 L0
ILOAD 0
ILOAD 1
IAND
IRETURN
```
In other words,  the Kotlin `&&` operates in similar fashion to Java `&&` operator performing short-circuit evaluation, whereas the `and` infix function -- like Java `&` operator with `Boolean`  args -- does not.  I think that is an important difference in behavior and therefore it should be denoted …
> Improve Boolean infix functions' documentation

- j2k/src/org/jetbrains/kotlin/j2k/ExpressionConverter.kt
- j2k/testData/fileOrElement/issues/kt-19634.java
- j2k/testData/fileOrElement/issues/kt-19634.kt
- j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterForWebDemoTestGenerated.java
- j2k/tests/org/jetbrains/kotlin/j2k/JavaToKotlinConverterSingleFileTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-19634
> KT-19634 <boxed_value> == <primitive_value> converted to reference equality in Kotlin

- grammar/src/lexical.grm
This change prohibits such illegal numeric literals as `13_37_` or `0xCAFE_BABE_` (note the trailing underscores).
> Fix minor grammar inconsistency: trailing underscores in numeric literals

- compiler/light-classes/src/org/jetbrains/kotlin/asJava/elements/KtLightParameter.java
- compiler/light-classes/src/org/jetbrains/kotlin/asJava/elements/KtLightParameterList.kt
- idea/tests/org/jetbrains/kotlin/idea/lightClasses/LightElementsEqualsTest.kt
An obvious fix for proper equality for LightElements retrieved from same origin. And `hashCode` overriding check (ha-ha).
But also there is an opinion that it is generally a bad idea to create new LightElements each time. Maybe it worth to store weak reference in original PsiElement?
> Fix for `KtLightParameter` and `KtLightParameterList` equality

- libraries/tools/kotlin-gradle-plugin-api/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinGradleSubplugin.kt
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/internal/AndroidSubplugin.kt
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/internal/Kapt3KotlinGradleSubplugin.kt
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinPlugin.kt
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/tasks/Tasks.kt
Because ServiceLoader can't check generic argument of
KotlinGradleSubplugin in runtime, we have to manually check the type in
`isApplicable`.
> Support for gradle subplugins in Kotlin2JS compilation

- compiler/light-classes/src/org/jetbrains/kotlin/asJava/elements/lightAnnotations.kt
- idea/tests/org/jetbrains/kotlin/asJava/KtLightAnnotationTest.kt
`LightElementValue` made PsiCompiledElement to make it properly anchorable when creating smartpointers, when still use `kotlinOrigin.containingFile` for it to be able to `registerProblem` on such elements. (refs KT-18054)
> `KtLightAnnotationForSourceEntry` fix for smart-pointers creating

- ReadMe.md
This section is valid before kotlin is built by gradle. Since there is
no working directory setting in run configuration, we need to delete
this document
> Delete "Running specific generated tests" from README

- idea/idea-gradle/src/org/jetbrains/kotlin/idea/core/script/GradleScriptTemplateProvider.kt
- idea/src/META-INF/gradle.xml
This commit introduces `GradleSettingsKotlinDSLTemplateProvider` and registers it as Kotlin IntelliJ plugin extension.
> Script template provider for settings.gradle.kts files

- ultimate/src/org/jetbrains/kotlin/idea/spring/lineMarking/KotlinSpringClassAnnotator.kt
- ultimate/testData/spring/core/gutter/autowiredConstructor/autowiredConstructor.test
- ultimate/tests/org/jetbrains/kotlin/idea/spring/tests/gutter/AbstractSpringClassAnnotatorTest.kt
Platform now allows Gutter to be placed only on leafs elements, this patch fixes it for Spring-Kotlin.
> Spring-Kotlin: Gutter repaired (KT-20550, KT-20566)

- build.gradle.kts
Couldn't build the project without this option because of:
```
> Task :compiler:util:compileJava
/Users/ilyazorin/Development/kotlin/compiler/util/src/org/jetbrains/kotlin/config/MavenComparableVersion.java:58: error: unmappable character for encoding ASCII
* @author <a href="mailto:hboutemy@apache.org">Herv?? Boutemy</a>
```
I don't know why it suddenly happened, but looks like it [could happen](https://discuss.gradle.org/t/unmappable-character-for-encoding-ascii-when-building-a-utf-8-project/10692/11) and in general, it is a good practice to set up encoding explicitly.
> Explicitly set utf-8 encoding

- ReadMe.md
```console
$ ./gradlew gradlePluginsTest
…
FAILURE: Build failed with an exception.
* What went wrong:
Task 'gradlePluginsTest' not found in root project 'kotlin'. Some candidates are: 'gradlePluginTest'.
```
Correct task name: https://github.com/JetBrains/kotlin/blob/55416341871259c6aef9912fce51fba74f1202ac/build.gradle.kts#L324
> Fix Gradle plugin task name in readme.

- libraries/stdlib/src/kotlin/io/files/FileTreeWalk.kt
Looks like all three functions should use a consistent scheme. Also, it'll be more readable this way, when fun is overloading each param in different cases.
> Use consistent explicit FileTreeWalk named parameters

- idea/src/org/jetbrains/kotlin/idea/highlighter/KotlinRunLineMarkerContributor.kt
Kotlin plugin adds very attractive and distractive icon into the gutter for main methods. I propose to use well-known platform icon for that which is suitable and has familiar metaphor instead of just Kotlin logo.
> Change run icon in gutter to default one from IJ Platform (KT-15254)

- .gitignore
Remove duplicate `.idea/modules.xml` from `.gitignore`.
Another declaration is in L33.
https://github.com/JetBrains/kotlin/pull/1416/files#diff-a084b794bc0759e7a6b77810e01874f2L33
> .gitignore: remove duplicates

- idea/idea-android/src/org/jetbrains/kotlin/android/configure/AndroidGradleModelFacade.kt
- idea/idea-gradle/src/org/jetbrains/kotlin/idea/configuration/KotlinGradleProjectResolverExtension.kt
- idea/idea-gradle/src/org/jetbrains/kotlin/idea/inspections/gradle/KotlinGradleModelFacade.kt
Calls to `ExternalSystemApiUtil.findFirstRecursively` can take a lot of time on large projects.
Also, `Key.findKeyByName` is slow and deprecated.
> Optimize dependency handling during import of Gradle project

- ReadMe.md
update README.md with direct download link to IntelliJ IDEA latest version
> README: IntelliJ IDEA 2017.3 is not early access anymore

- compiler/tests-common/tests/org/jetbrains/kotlin/integration/KotlinIntegrationTestBase.java
Do not store process standard error messages into execution
log if the process exit code does not indicate an error. Such
messages are warning or important information, not errors, they
should not trigger failures.
FIX KT-22241
> Log standard error only on exit status error

- plugins/android-extensions/android-extensions-idea/src/org/jetbrains/kotlin/android/synthetic/idea/AndroidSimpleNameReferenceExtension.kt
The method is deprecated and will be removed.
> Inline AndroidFacet.getAllResourceDirectories() usage

- idea/idea-gradle/src/org/jetbrains/kotlin/idea/core/script/GradleScriptTemplateProvider.kt
The next release of the Kotlin DSL to be included in Gradle 4.6 includes support for init scripts.
Init scripts act on the `Gradle` object and thus expose a different API than the other types of scripts which act on `Project` and `Settings` objects.
See gradle/kotlin-dsl#662
> Make Kotlin Idea plugin aware of the Gradle initscript template

- idea/idea-gradle/src/org/jetbrains/kotlin/idea/configuration/KotlinGradleProjectResolverExtension.kt
- idea/idea-gradle/tests/org/jetbrains/kotlin/gradle/MultiplatformProjectImportingTest.kt
Gradle's subproject name/path is only a part of a module ID, when composite build is imported. Included build's name is missing.
It is easy to obtain it, as long as `expectedBy` dependency does not cross gradle build boundary.
> Fix import of `expectedBy` scope dependencies inside composite builds

- libraries/stdlib/src/kotlin/util/BigDecimals.kt
...by calling BigDecimal.valueOf(this), which doesn't create a new BigDecimal instance if the argument falls in the range [0..10].
(there's a `private static final BigDecimal[] zeroThroughTen` cache in BigDecimal.java with 11 BigDecimal instances)
Here's the bytecode diff for the Int receiver:
```patch
--- inline fun Int.toBigDecimal()
+++ inline fun Int.toBigDecimal()
@@ -4,10 +4,12 @@
@Lkotlin/internal/InlineOnly;() // invisible
L0
LINENUMBER 92 L0
-    NEW java/math/BigDecimal
+    ILOAD 0
+    I2L
+    INVOKESTATIC java/math/BigDecimal.valueOf (J)Ljava/math/BigDecimal;
DUP
-    ILOAD 0
-    INVOKESPECIAL java/math/BigDecimal.<init> (I)V
+    LDC "BigDecimal.valueOf(this.toLong())"
+    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull …
```
> Long.toBigDecimal(): avoid new BigDecimal instance

- idea/src/org/jetbrains/kotlin/idea/formatter/CollectChangesWithoutApplyModel.kt
Otherwise IDEA will run preformat and postformat processors, which don't
expect to run outside of EDT (IDEA-185991)
> Pass canChangeWhitespaceOnly flag in reformat inspection

- libraries/stdlib/src/kotlin/text/Strings.kt
If I pass in a CharSequence with different spans (ImageSpans, colors, etc), the original trimEnd using substring incorrectly wiped out the spans.
changing to subSequence correctly preserves the span data
> Fix problem with trimEnd wiping out valid spans

- plugins/kapt3/kapt3-compiler/src/org/jetbrains/kotlin/kapt3/Kapt3Plugin.kt
- Since warnings are discarded when there are others errors, replace the
current warning by an error to always display the message and inform the
user that its annotation processor is badly configured.
Fix of https://youtrack.jetbrains.com/issue/KT-23721
> KT-23721 Emit an error when 'tools.jar' is not into plugin classpath

- license/README.md
Fixes indentation in license readme so bullet points render correctly
> fix bullet point indentation in license readme

- ReadMe.md
Changes the link name for the Sublime Text Package from "TextMate" to "Sublime Text"
> Updates ReadMe.md to name the Sublime Text Package

- libraries/stdlib/js/src/kotlin/annotations.kt
This PR just contains a fix of a few typos in the documentation of the JsQualifier annotation.
The checklist for this PR:
YES  - You do not have merge commits in PR
YES  - You made a few changes
NO - You provided the link to related issue from YouTrack
YES - You can describe changes made in PR
YES - You made changes related to only one issue
YES - You are ready to defend your changes on code review
YES - You didn't touch what you don't understand
NO - You ran the build locally, and verified new functionality
NO  - You ran related tests locally, and it passed
> fix typos in documentation of JsQualifier annotation

- idea/idea-analysis/src/org/jetbrains/kotlin/idea/inspections/KotlinInspectionSuppressor.kt
- idea/src/META-INF/plugin.xml
- idea/src/META-INF/plugin.xml.172
- idea/src/META-INF/plugin.xml.173
- idea/src/META-INF/plugin.xml.182
- idea/src/META-INF/plugin.xml.as31
- idea/src/META-INF/plugin.xml.as32
- idea/testData/quickfix/suppress/external/suppressActive.kt
- idea/testData/quickfix/suppress/external/suppressAvailable.kt
- idea/testData/quickfix/suppress/external/suppressAvailable.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
So https://youtrack.jetbrains.com/issue/KT-11154 Fixed
So https://youtrack.jetbrains.com/issue/KT-25169 Fixed
Well, spell checking inspection is now suppressable, I checked it. But I don't know this place well enough and it would be good if somebody else looked attentively at this place. Feel free to merge / rebase it yourself, if it's Ok.
> Introduce KotlinInspectionSuppressor

- libraries/stdlib/jvm/runtime/kotlin/jvm/annotations/JvmPlatformAnnotations.kt
Docs on this annotation were missing since its addition to the stdlib & compiler support.
This PR adds missing documentation while highlighting that the annotation is not intended for mass use, but rather for *rare cases*. 
I've tried to keep the style of the text consistent with other documentation within the file.
Use case: https://github.com/gojuno/koptional/pull/30
> Add documentation for @JvmSynthetic

- libraries/tools/kotlin-script-util/src/main/kotlin/org/jetbrains/kotlin/script/util/resolvers/maven.kt
This PR addresses YouTrack issue: https://youtrack.jetbrains.com/issue/KT-26142
---
Kotlin declares http://repo1.maven.apache.org/maven2 maven-central remote repository url. We could mimic Maven and switch to https://repo.maven.apache.org/maven2.
See issue https://issues.apache.org/jira/browse/MNG-5151 : maven switched to this new url starting from Maven 3.0.4. You can fetch maven 3.5.4 sources, go to "maven-model-builder\src\main\resources\org\apache\maven\model\pom-4.0.0.xml" and see that https://repo.maven.apache.org/maven2 is the new maven-central repo url.
Also, keep in mind that many IDE (at least NetBeans and IntelliJ) can dowload Maven repo index for offline use/search. For Maven projects, IDEs offer you do download index for the new url (https://repo.maven.apache.org/maven2) …
> KT-26142 Update Maven central repository url to latest version

- libraries/tools/kotlin-gradle-plugin/src/agp25/kotlin/org/jetbrains/kotlin/gradle/plugin/android/Android25ProjectHandler.kt
A new method has been added in the Android Gradle
plugin 3.3.0. This commit switches from ussing the
MergeResources task, and uses getAllRawAndroidResources
API instead.
Test: manually verified
> Use new API for getting the raw Android resources

- idea/src/org/jetbrains/kotlin/idea/inspections/RemoveRedundantBackticksInspection.kt
- idea/testData/inspectionsLocal/removeRedundantBackticks/yield.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-25968
> KT-25968 False positive "Remove redundant backticks" with keyword `yield`

- idea/src/org/jetbrains/kotlin/idea/quickfix/RemoveUnusedFunctionParameterFix.kt
- idea/testData/quickfix/changeSignature/removeUnusedParameterWithTypeParameter7.kt
- idea/testData/quickfix/changeSignature/removeUnusedParameterWithTypeParameter7.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-23511#comment=27-2882256
Fix for this case:
```kt
interface TypeHolder<T, U>
fun <T, U> baz(<caret>x: TypeHolder<T, U>) {}
fun test(holder: TypeHolder<String, Int>) {
baz(holder)
}
```
> KT-23511 "Remove parameter" quick fix: Remove unused type parameter used as type projection

- compiler/frontend.java/src/org/jetbrains/kotlin/load/java/sam/SingleAbstractMethodUtils.java
Android Studio users who migrated to AndroidX are running into the
databinding deadlock again: https://issuetracker.google.com/111788726
> Expand the fix from commit 6c274cecff3 to cover AndroidX

- idea/src/org/jetbrains/kotlin/idea/inspections/ReplacePutWithAssignmentInspection.kt
- idea/testData/inspectionsLocal/replacePutWithAssignment/putOnSuper.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-27146
> KT-27146 False positive "map.put() can be converted to assignment" on `super` keyword with `LinkedHashMap` inheritance

- idea/src/org/jetbrains/kotlin/idea/quickfix/AddModifierFix.kt
- idea/testData/quickfix/modifiers/addOpenToClassDeclaration/dataSuperType.kt
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-27354
> KT-27354 False positive "Make 'Foo' open" for `data` class inheritance

- grammar/src/expressions.grm
The backslash renders at https://kotlinlang.org/docs/reference/grammar.html#precedence.
> Fix typo in expression precedence table

- idea/idea-core/src/org/jetbrains/kotlin/idea/core/psiModificationUtils.kt
- idea/testData/inspectionsLocal/moveLambdaOutsideParentheses/delegation.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-27584
> KT-27584 False positive "Move lambda argument out of parentheses" when implementing interface by delegation

- idea/idea-gradle/src/org/jetbrains/kotlin/idea/configuration/KotlinGradleSourceSetDataService.kt
- idea/src/org/jetbrains/kotlin/idea/facet/facetUtils.kt
If `kotlinOptions.jdkHome` is set, this will still override the setting from the Gradle Idea plugin.
> Do not configure module SDK after the Gradle import if it was set explicitly with the Gradle Idea plugin (fixes KT-27530)

- idea/src/org/jetbrains/kotlin/idea/quickfix/DeprecatedJavaAnnotationFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
- idea/testData/quickfix/deprecatedJavaAnnotation/withArgument.kt
- idea/testData/quickfix/deprecatedJavaAnnotation/withArgument.kt.after
- idea/testData/quickfix/deprecatedJavaAnnotation/withoutArguments.kt
- idea/testData/quickfix/deprecatedJavaAnnotation/withoutArguments.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
This adds a Quick Fix that allows users to automatically switch deprecated Java annotations with their Kotlin counterparts. The fix does not attempt to migrate arguments for the annotation as that would introduce significant complexity and be frail for changes to the detection in the future. I can, however, add this logic if requested though I may need some pointers towards wrangling the needed PSI statements. 
I included tests for both annotations without arguments like `@Documented`  and with arguments like `@Retention`.  I also tested each annotation supported by the `JavaAnnotationCallChecker` manually using the _runIde_ build target. 
This fixes https://youtrack.jetbrains.com/issue/KT-27445
> KT-27445: Add Quick Fix for DEPRECATED_JAVA_ANNOTATION compiler warning

- libraries/stdlib/coroutines/src/kotlin/Result.kt
Coroutines will be added to the stdlib of Kotlin 1.3.
`Result` and `runCatching` are two examples which come with it.
Currently they are marked as available since Kotlin 1.0 in the API documentation.
This PR attempts to change this for the Result class and the other functions defined in the `Result.kt` file.
This is my first contribution to kotlin and I have not used the `@SinceKotlin` annotation before.
I'm unsure whether it is sufficient to place it on top of the class or if I need to also place it on top of `PublishedApi` internal functions as well.
> Mark Result and runCatching as available since 1.3

- idea/src/org/jetbrains/kotlin/idea/inspections/UnusedReceiverParameterInspection.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/RemoveUnusedFunctionParameterFix.kt
- idea/testData/inspectionsLocal/unusedReceiverParameter/functionWithTypeParameter.kt
- idea/testData/inspectionsLocal/unusedReceiverParameter/functionWithTypeParameter.kt.after
- idea/testData/inspectionsLocal/unusedReceiverParameter/functionWithTypeParameter2.kt
- idea/testData/inspectionsLocal/unusedReceiverParameter/functionWithTypeParameter2.kt.after
- idea/testData/inspectionsLocal/unusedReceiverParameter/functionWithTypeParameter3.kt
- idea/testData/inspectionsLocal/unusedReceiverParameter/functionWithTypeParameter3.kt.after
- idea/testData/inspectionsLocal/unusedReceiverParameter/functionWithTypeParameterInClass.kt
- idea/testData/inspectionsLocal/unusedReceiverParameter/functionWithTypeParameterInClass.kt.after
- idea/testData/inspectionsLocal/unusedReceiverParameter/functionWithTypeParameterInClass2.kt
- idea/testData/inspectionsLocal/unusedReceiverParameter/functionWithTypeParameterInClass2.kt.after
- idea/testData/inspectionsLocal/unusedReceiverParameter/propertyWithTypeParameter.kt
- idea/testData/inspectionsLocal/unusedReceiverParameter/propertyWithTypeParameter.kt.after
- idea/testData/inspectionsLocal/unusedReceiverParameter/propertyWithTypeParameterInClass.kt
- idea/testData/inspectionsLocal/unusedReceiverParameter/propertyWithTypeParameterInClass.kt.after
- idea/testData/inspectionsLocal/unusedReceiverParameter/propertyWithTypeParameterInClass2.kt
- idea/testData/inspectionsLocal/unusedReceiverParameter/propertyWithTypeParameterInClass2.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-23512
> KT-23512 "Remove redundant receiver" quick fix makes generic function call incompilable when type could be inferred from removed receiver only

- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/model/KotlinProjectIT.kt
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/model/builder/KotlinModelBuilder.kt
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinPlugin.kt
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinPluginWrapper.kt
- libraries/tools/kotlin-gradle-plugin/src/test/kotlin/org/jetbrains/kotlin/gradle/model/builder/KotlinModelBuilderTest.kt
This change ensures that the KotlinModelBuilder is registered for the kotlin-android plugin. This is required since the Android IDEA plugin (and Android Studio) lacks the information needed to configure the Kotlin facet. Information we are unable to get from the Android specific models include, compiler arguments and co-routine support.
This change also ensures that the KotlinProject that is built for Android projects has its project type set to PLATFORM_JVM and that the above information is set correctly on the model. Note: for some fields that we obtain from the Android Gradle Plugin we leave empty or return placeholder values.
> Register KotlinModelBuilder for kotlin-android plugin

- idea/src/org/jetbrains/kotlin/idea/KotlinPairMatcher.kt
https://youtrack.jetbrains.com/issue/KT-9840
> KT-9840 Right parenthesis doesn't appear after class name before the colon

- compiler/psi/src/org/jetbrains/kotlin/psi/VisitorWrappers.kt
- idea/resources/inspectionDescriptions/RemoveEmptyParenthesesFromAnnotationEntry.html
- idea/src/META-INF/plugin-common.xml
- idea/src/org/jetbrains/kotlin/idea/inspections/RemoveEmptyParenthesesFromAnnotationEntryInspection.kt
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/.inspection
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/allParameterHaveDefaults.kt
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/allParameterHaveDefaults.kt.after
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/annotatedExpr.kt
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/annotatedExpr.kt.after
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/parenthesesWithWhitespace.kt
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/parenthesesWithWhitespace.kt.after
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/requiresArguments.kt
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/simple.kt
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/simple.kt.after
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/usingJavaAnnotation.1.java
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/usingJavaAnnotation.kt
- idea/testData/inspectionsLocal/removeEmptyParenthesesFromAnnotationEntry/usingJavaAnnotation.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
YT link: https://youtrack.jetbrains.com/issue/KT-28118
> KT-28118: Remove empty parentheses for annotation entries

- idea/src/org/jetbrains/kotlin/idea/quickfix/RemoveSingleLambdaParameterFix.kt
- idea/testData/quickfix/removeSingleLambdaParameter/propertyWithExplicitType.kt
- idea/testData/quickfix/removeSingleLambdaParameter/propertyWithExplicitType.kt.after
- idea/testData/quickfix/removeSingleLambdaParameter/propertyWithImplicitType.kt
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-23134
> KT-23134 "Remove single lambda parameter" quick fix applied to a lambda parameter with explicit type breaks ::invoke reference on lambda

- ReadMe.md
Update to better describe first time import of project. In particular, the way it reads it makes it seem like the option to defer builds to gradle can be found on the import screen when in fact it's in the IDE settings - this can confuse people trying to follow the steps exactly. 
Changed URL for up for grabs to filter to only show Open issues. Previously the filter used in the ReadMe included other statuses as well like In Progress - now that it only shows Open issues it'll be easier to click the link and find all the "Up For Grabs" issues that haven't been worked on already. 
I also adjusted some basic verbiage for clarity.
> Update ReadMe for readability for first time contributors  

- idea/src/org/jetbrains/kotlin/idea/inspections/NestedLambdaShadowedImplicitParameterInspection.kt
- idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicit.kt
- idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicit.kt.after
- idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicit3.kt
- idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicit3.kt.after
- idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/implicitGrandParent.kt.after
- idea/testData/inspectionsLocal/nestedLambdaShadowedImplicitParameter/notUsedItInParentLambda.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-26710
> KT-26710 Should not report "implicit 'it' is shadowed when outer it is not used"

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/HierarchyAttributeContainer.kt
Given the prior faulty logic, no tree of `HierarchyAttributeContainer`s would ever report itself as empty (not even a 'tree' consisting of a single, attribute-less/empty HierarchyAttributeContainer), since every tree will have a root, which will lack a parent, and it considered the lack of existence of a parent to mean that that root container is not empty.
// good work on this project, btw :+1:
> Consider non-existent parent `AttributeContainer`s empty

- compiler/resolution/src/org/jetbrains/kotlin/resolve/calls/tower/ImplicitScopeTower.kt
- compiler/resolution/src/org/jetbrains/kotlin/resolve/calls/tower/InvokeProcessors.kt
- compiler/resolution/src/org/jetbrains/kotlin/resolve/calls/tower/TowerLevels.kt
- compiler/resolution/src/org/jetbrains/kotlin/resolve/calls/tower/TowerUtils.kt
Interface CandidateWithBoundDispatchReceiver had a unique
implementation, which was private.
Turned interface CandidateWithBoundDispatchReceiver into a
class. Removed CandidateWithBoundDispatchReceiverImpl. Removed
string "Impl" suffix at constructor call sites.
> Remove CandidateWithBoundDispatchReceiverImpl

- compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/tower/NewResolutionOldInference.kt
LanguageVersionSettings is not used in convertToOverloadResults. Let's remove it.
> Remove useless parameter

- libraries/stdlib/samples/test/samples/text/strings.kt
- libraries/stdlib/src/kotlin/text/Strings.kt
[KT-20357](https://youtrack.jetbrains.com/issue/KT-20357) - Samples for `commonPrefixWith()` and `commonSuffixWith()`
The samples demonstrate both case-sensitive and case-insensitive matches, plus the behavior when there's no match.  I didn't include a sample demonstrating surrogate pairs, because regardless of whether the input contains surrogate pairs, the function is still called the same way - but if you feel that it's critical to include samples for that, just let me know.
> KT-20357: Add samples for commonPrefixWith and commonSuffixWith

- libraries/stdlib/src/kotlin/collections/Maps.kt
I hope I got all occurrences where this behavior is the case. I was wondering how it would behave especially because Java's **Stream.collect(Collectors.toMap())** throws when duplicate keys are encountered
> Add documentation on how merging works for toMap() for Iterables, Arrays and Sequences

- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/SurroundWithLambdaFix.kt
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMatch.kt
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMatch.kt.after
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMatchInt.kt
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMatchInt.kt.after
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMatchNullable.kt
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMatchNullable.kt.after
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMatchSubclass.kt
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMatchSubclass.kt.after
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMismatch.kt
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMismatchNull.kt
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
Hi, first open source contribution! Hope I did everything right.
https://youtrack.jetbrains.com/issue/KT-27670
Does NOT check for nullability
```kotlin
fun foo(str: () -> String) {}
...
val str: String? = null
foo(str) // shows quickfix
```
> #KT-27670 Add quick fix: wrap expression in a lambda if compatible functional type is required

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLoweringPhases.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/NegatedExpressionLowering.kt
- compiler/testData/codegen/bytecodeText/lazyCodegen/negateVarChain.kt
Introduce lowering phase that turns !!exp -> exp for the boolean 'not' builtin. This makes sure that code such as
```
if (!!!!!booleanValue) {
doStuff()
}
```
generates only one branch.
> JVM IR: simplify chains of negations in if conditions.

- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixFactoryForTypeMismatchError.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/WrapWithArrayLiteralFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/WrapWithCollectionLiteralCallFix.kt
- idea/testData/quickfix/typeMismatch/wrapWithArrayLiteral.kt
- idea/testData/quickfix/typeMismatch/wrapWithArrayLiteral.kt.after
- idea/testData/quickfix/typeMismatch/wrapWithCollectionLiteral/inAnnotation.kt
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-28969
> KT-28969 TYPE_MISMATCH in array vs non-array case: two quick fixes exist for annotation and none of them adds array literal

- compiler/psi/src/org/jetbrains/kotlin/psi/KtPsiUtil.java
- idea/testData/intentions/removeUnnecessaryParentheses/lambda.kt
- idea/testData/intentions/removeUnnecessaryParentheses/lambda2.kt
- idea/testData/intentions/removeUnnecessaryParentheses/lambda3.kt
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens1.kt
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens1.kt.after
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens2.kt
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens2.kt.after
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens3.kt
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens3.kt.after
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens4.kt
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens4.kt.after
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens5.kt
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens5.kt.after
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens6.kt
- idea/testData/quickfix/expressions/removeUselessCastForLambdaInParens6.kt.after
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-28641
> KT-28641 "Remove useless cast" produces a dangling lambda ("Too many arguments" error)

- idea/src/org/jetbrains/kotlin/idea/inspections/conventionNameCalls/ReplaceCallWithBinaryOperatorInspection.kt
- idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/dynamicEquals.kt
- idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/dynamicEquals.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-28773
> KT-28773 Kotlin/JS: Wrong inspection to replace .equals() with == on dynamic values

- idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/IfThenToElvisIntention.kt
- idea/testData/intentions/branched/ifThenToElvis/ifToElvisSwallowComments.kt
- idea/testData/intentions/branched/ifThenToElvis/ifToElvisSwallowComments.kt.after
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-18715
Adds a CommentSaver to the IfThenToElvis intention that will save and
restore comments when converting an if expression to elvis expression.
As a side note, when I'm editing `IfThenToElvisIntention.kt`, I am unable to Ctrl-Click into other classes like, like if I ctrl-click `CommentSaver` IDEA doesn't do anything. I also have no auto-imports and it doesn't detect errors (like spelling or type checking) until I compile. Is there a way to fix this? This is on a fresh IDEA installation.
> KT-18715: don't swallow comments for if->elvis

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmBuiltinOptimizationLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/IrUtils.kt
- compiler/testData/codegen/box/classes/kt496.kt
- compiler/testData/codegen/box/controlStructures/tryCatchInExpressions/splitTryCorner1.kt
- compiler/testData/codegen/box/deadCodeElimination/kt14357.kt
- compiler/testData/codegen/box/finally/finallyAndFinally.kt
- compiler/testData/codegen/boxInline/nonLocalReturns/tryFinally/exceptionTable/nestedWithReturnsSimple.kt
- compiler/testData/codegen/bytecodeText/deadCodeElimination/kt14357.kt
- compiler/testData/codegen/bytecodeText/exclExcl/primitive.kt
- compiler/testData/codegen/bytecodeText/when/whenNull.kt
- compiler/testData/lineNumber/custom/primitiveNullChecks.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/IrBytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LineNumberTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrLineNumberTestGenerated.java
Simplify ifs when branches have condition true/false.
Simplify blocks containing only a variable declaration
and a variable get of the same variable. Simplify to
just the condition.
Do not introduce temporary variables for constants for
null checks. Constants have no side-effects and can be
reloaded freely instead of going through a local.
This simplifies code such as "42.toLong()!!" so that the
resulting code has no branches and uses no locals. The
simplifications happen as follows:
```
block
temp = 42.toLong()
when
(temp == null) throw NPE
(true) load temp
---> null test simplification
block
temp = 42.toLong()
when
(false) throw NPE
(true) load temp
---> when simplification
block
temp = 42.toLong()
load temp
---> block simplification
42.toLong()
```
> JVM_IR: Generate better code for null checks.

- idea/src/org/jetbrains/kotlin/idea/inspections/BooleanLiteralArgumentInspection.kt
- idea/src/org/jetbrains/kotlin/idea/intentions/AddNameToArgumentIntention.kt
- idea/testData/inspectionsLocal/booleanLiteralArgument/vararg.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-29469
> KT-29469 False positive in "Boolean literal argument without parameter name" inspection for varargs parameters

- idea/src/org/jetbrains/kotlin/idea/inspections/SortModifiersInspection.kt
- idea/testData/inspectionsLocal/sortModifiers/annotatedBefore2.kt
- idea/testData/inspectionsLocal/sortModifiers/annotation2.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-29238
> KT-29238 Non-canonical modifiers order inspection incorrectly includes annotations into range

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/bytecodeText/boxingOptimization/maxMinBy.kt
- compiler/testData/lineNumber/if.kt
This used to generate an ACONST_NULL instruction leading to incorrect
stack height for code such as:
```
if (condition) else 32
```
> JVM_IR: Fix codegeneration for missing branches.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/bytecodeText/redundantValInitializer.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/IrBytecodeTextTestGenerated.java
Initializers are "set field" expressions and are considered redundant
when they are:
1. In the primary constructor; and
2. Set the field to `0`, `false`, or `null`; and
3. Have a `null` origin. I.e., not in an initializer block or
constructor body, and therefore the field could not have been set by a
prior expression.
> JVM_IR: Do not add redundant field initializers.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLoweringPhases.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmTypeOperatorLoweringPhase.kt
- compiler/testData/codegen/box/when/noElseCoerceToUnit.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
Code such as
```
val b = getBoolean()
if (b) 4
else if (b) 5
```
didn't generate a value on the stack always and therefore would
have control-flow paths leading to a pop instruction with nothing
on the stack.
> JVM_IR: Fix stack underflow for unit coercion of when expressions.

- idea/src/org/jetbrains/kotlin/idea/inspections/MemberVisibilityCanBePrivateInspection.kt
- idea/testData/inspections/memberVisibilityCanBePrivate/inline.kt
https://youtrack.jetbrains.com/issue/KT-29085
> KT-29085 False positive "Class member can have 'private' visibility" for a `const val` used in a public inline function

- idea/src/org/jetbrains/kotlin/idea/inspections/SuspiciousCollectionReassignmentInspection.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/ChangeToMutableCollectionFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createCallable/CreateSetFunctionActionFactory.kt
- idea/testData/quickfix/changeToMutableCollection/list.kt
- idea/testData/quickfix/changeToMutableCollection/list.kt.after
- idea/testData/quickfix/changeToMutableCollection/list2.kt
- idea/testData/quickfix/changeToMutableCollection/list2.kt.after
- idea/testData/quickfix/changeToMutableCollection/map.kt
- idea/testData/quickfix/changeToMutableCollection/map.kt.after
- idea/testData/quickfix/changeToMutableCollection/map2.kt
- idea/testData/quickfix/changeToMutableCollection/map2.kt.after
- idea/testData/quickfix/changeToMutableCollection/set.kt
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-29193
> KT-29193 Quick fix "Create extension function" `List<Int>.set` should not be suggested for read-only collections

- compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/smartcasts/DataFlowUtils.kt
- idea/src/org/jetbrains/kotlin/idea/inspections/conventionNameCalls/ReplaceCallWithBinaryOperatorInspection.kt
- idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/equalsDoubleSmartCast2.kt
- idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/equalsDoubleSmartCast2.kt.after
- idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/equalsDoubleSmartCast3.kt
- idea/testData/inspectionsLocal/conventionNameCalls/replaceCallWithBinaryOperator/equalsDoubleSmartCast3.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-28596
> KT-28596 "Can be replaced with binary operator" shouldn't be suggested when receiver or argument is floating point type

- idea/idea-core/src/org/jetbrains/kotlin/idea/core/psiModificationUtils.kt
- idea/testData/inspectionsLocal/moveLambdaOutsideParentheses/typeParameter.kt
- idea/testData/inspectionsLocal/moveLambdaOutsideParentheses/typeParameter.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-26979
> KT-26979 "Lambda argument inside parentheses" inspection is not reported, if function type is actual type argument, but not formal parameter type

- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrDeclaration.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/impl/IrDeclarationBase.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/lazy/IrLazyDeclarationBase.kt
When plugins perform various IR transforms, it sometimes becomes necessary to modify the origin of a declaration.  When the origin is a `val`, this requires creating a new declaration and copying the old values into the new declaration.  Unfortunately, this also requires applying a transform over the entire module to rewrite references from the old declaration to the new declaration, which ends up becoming a rather complex codepath for what would otherwise be a straightforward lowering transformation.
By making the `origin` field be a `var` instead of a `val`, these lowering transformations can be dramatically simplified.
cc @udalov @erokhins
> Make IrDeclaration.origin mutable

- idea/src/org/jetbrains/kotlin/idea/inspections/RedundantGetterInspection.kt
- idea/testData/inspectionsLocal/redundantGetter/external.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-29416
> KT-29416 False positive "Redundant property getter" for `external` getter

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/CompareTo.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/Equals.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IntrinsicMethod.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IrIntrinsicFunction.kt
- compiler/testData/codegen/bytecodeText/conditions/negatedZeroCompare.kt
- compiler/testData/codegen/bytecodeText/conditions/zeroCompare.kt
- compiler/testData/codegen/bytecodeText/lazyCodegen/negateObjectComp.kt
- compiler/testData/codegen/bytecodeText/lazyCodegen/negateObjectCompChaing.kt
- compiler/testData/codegen/bytecodeText/nullCheckOptimization/alreadyCheckedForIs.kt
For comparison intrinsics and for instanceof checks, make
it possible to get the the stack value produced and branch
on that directly instead of materializing a boolean to
branch on from it.
That reduces code such as
```
IF_CMPEQ L1
CONST_0
GOTO L2
L1: CONST_1
L2: IFEQ L3
```
to just one IF_CMP instruction.
> Generate better code for branches based on comparisons.

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/FlattenStringConcatenationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/strings/nestedConcat.kt
- compiler/testData/codegen/bytecodeText/stringOperations/concat.kt
- compiler/testData/codegen/bytecodeText/stringOperations/multipleNestedConcat.kt
- compiler/testData/codegen/bytecodeText/stringOperations/nestedConcat.kt
- compiler/testData/codegen/bytecodeText/stringOperations/plusAssign.kt
- compiler/testData/codegen/bytecodeText/stringOperations/primitivesAsStringTemplates.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
Consolidating these into IrStringConcatenations allows the backend to produce efficient code for string concatenations (e.g., using StringBuilder for JVM).
> Flatten nested string concatenation expressions into a single IrStringConcatenation, in a separate lowering phase.

- idea/src/org/jetbrains/kotlin/idea/intentions/ReplaceSingleLineLetIntention.kt
- idea/testData/intentions/replaceSingleLineLetIntention/functionInVariableCall.kt
- idea/testData/intentions/replaceSingleLineLetIntention/functionInVariableInvokeCall.kt
- idea/testData/intentions/replaceSingleLineLetIntention/functionInVariableInvokeCall.kt.after
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-30082
> KT-30082 False positive "redundant `.let` call" for lambda functions stored in nullable references

- idea/src/org/jetbrains/kotlin/idea/inspections/RedundantUnitExpressionInspection.kt
- idea/testData/inspectionsLocal/redundantUnitExpression/returnAsNullableUnit.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-30038
> KT-30038 'Remove redundant Unit" false positive when return type is nullable Unit

- idea/src/org/jetbrains/kotlin/idea/intentions/ReplaceSingleLineLetIntention.kt
- idea/testData/intentions/replaceSingleLineLetIntention/invokeCall.kt
- idea/testData/intentions/replaceSingleLineLetIntention/invokeCall.kt.after
- idea/testData/intentions/replaceSingleLineLetIntention/invokeCall2.kt
- idea/testData/intentions/replaceSingleLineLetIntention/invokeCall2.kt.after
- idea/testData/intentions/replaceSingleLineLetIntention/invokeCall3.kt
- idea/testData/intentions/replaceSingleLineLetIntention/invokeCall3.kt.after
- idea/testData/intentions/replaceSingleLineLetIntention/invokeCall4.kt
- idea/testData/intentions/replaceSingleLineLetIntention/invokeCall5.kt
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-29556
> KT-29556 "Remove redundant 'let' call" doesn't rename parameter with convention `invoke` call

- compiler/backend/src/org/jetbrains/kotlin/codegen/when/SwitchCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/SwitchGenerator.kt
- compiler/testData/codegen/bytecodeText/when/inlineConstValsInsideWhen.kt
- compiler/testData/codegen/bytecodeText/when/lookupSwitch.kt
- compiler/testData/codegen/bytecodeText/when/qualifiedConstValsInsideWhen.kt
- compiler/testData/codegen/bytecodeText/when/simpleConstValsInsideWhen.kt
- compiler/testData/codegen/bytecodeText/when/tableSwitch.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
A lookupswitch or tableswitch can be used if all conditions are equality
checks to constants. To be more specific, it can be done if:
1. All conditions are CALL 'EQEQ(Any?, Any?)': Boolean
2. All types of variables involved in comparison are in the same group
of Char/Byte/Short/Int, String or enum.
3. All arg0 refer to the same value.
4. All arg1 are IrConst<*>.
> when: emit lookupswitch/tableswitch if possible

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/bothInExpectAndActual.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/bothInExpectAndActual2.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/constructor.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/dispatchReceiverValue.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/extensionReceiverValue.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/function.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/inheritedFromCommonClass.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/inheritedFromExpectedClass.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/inheritedFromExpectedInterface.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/inheritedFromExpectedMethod.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/inheritedInExpectedDeclarations.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/inheritedViaAnotherInterfaceIndirectly.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/jvmOverloads.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/kt23239.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/kt23739.kt
- compiler/testData/codegen/box/multiplatform/defaultArguments/parametersInArgumentValues.kt
- compiler/testData/codegen/box/multiplatform/optionalExpectation.kt
The expect/actual mechanism is already implemented in the JS backend and seems to work fine in the JVM backend as well.
> Run ExpectDeclarationsRemoving in the JVM_IR backend.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/dataClasses/unitComponent.kt
This ensures that the Unit instance is loaded when string
concatenation contains a sub part that is a call of a Unit
return-type method.
> JVM_IR: Perform asm type conversion for string concat arguments.

- idea/src/org/jetbrains/kotlin/idea/quickfix/AddReturnToLastExpressionInFunctionFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/AddReturnToUnusedLastExpressionInFunctionFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
- idea/testData/quickfix/addReturnToLastExpressionInFunction/notSubtype.kt
- idea/testData/quickfix/addReturnToLastExpressionInFunction/nothing.kt
- idea/testData/quickfix/addReturnToLastExpressionInFunction/simpleBoolean.kt
- idea/testData/quickfix/addReturnToLastExpressionInFunction/simpleBoolean.kt.after
- idea/testData/quickfix/addReturnToLastExpressionInFunction/subtype.kt
- idea/testData/quickfix/addReturnToLastExpressionInFunction/subtype.kt.after
- idea/testData/quickfix/addReturnToUnusedLastExpressionInFunction/notSubtype.kt
- idea/testData/quickfix/addReturnToUnusedLastExpressionInFunction/nothing.kt
- idea/testData/quickfix/addReturnToUnusedLastExpressionInFunction/simpleBoolean.kt
- idea/testData/quickfix/addReturnToUnusedLastExpressionInFunction/simpleBoolean.kt.after
- idea/testData/quickfix/addReturnToUnusedLastExpressionInFunction/subtype.kt
- idea/testData/quickfix/addReturnToUnusedLastExpressionInFunction/subtype.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
Related YouTrack issue: https://youtrack.jetbrains.com/issue/KT-25272
This PR adds two quickfixes and tests for two types of diagnostic message: `NO_RETURN_IN_FUNCTION_WITH_BLOCK_BODY` and `UNUSED_EXPRESSION`, both of which are shown in this example program:
```kotlin
fun test(): Boolean {
true // UNUSED_EXPRESSION reported here
} // NO_RETURN_IN_FUNCTION_WITH_BLOCK_BODY reported here
```
Both quick fixes will add `return` before `true` in this case.
> KT-25272: Unused expression as last expression of normal function should have quickfix to add "return"

- idea/src/org/jetbrains/kotlin/idea/inspections/collections/SimplifyCallChainFix.kt
- idea/testData/inspectionsLocal/collections/simplifiableCallChain/saveComment.kt
- idea/testData/inspectionsLocal/collections/simplifiableCallChain/saveComment.kt.after
- idea/testData/inspectionsLocal/collections/simplifiableCallChain/saveComment2.kt
- idea/testData/inspectionsLocal/collections/simplifiableCallChain/saveComment2.kt.after
- idea/testData/inspectionsLocal/collections/simplifiableCallChain/saveComment3.kt
- idea/testData/inspectionsLocal/collections/simplifiableCallChain/saveComment3.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-27821
> KT-27821 Fix `SimplifiableCallChain` inspection quick fix removes comments for intermediate operations

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/InnerClassesLowering.kt
- compiler/testData/codegen/box/classes/inheritedInnerClass.kt
- compiler/testData/codegen/box/classes/inner/kt6708.kt
- compiler/testData/codegen/box/classes/propertyInInitializer.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/constructorParameterAndLocalCapturedInLambdaInLocalClass.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/constructorParameterCapturedInLambdaInLocalClass2.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/kt13454.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/kt14148.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/localCapturedInLambdaInInnerClassInLocalClass.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/outerCapturedInFunctionLiteral.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/outerCapturedInLambda.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/outerCapturedInLambda2.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/outerCapturedInLambdaInSecondaryConstructor.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/outerCapturedInLambdaInSubExpression.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/outerCapturedInNestedLambda.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/outerCapturedInNestedObject.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/outerCapturedInObject.kt
- compiler/testData/codegen/box/closures/captureInSuperConstructorCall/outerCapturedInObject2.kt
- compiler/testData/codegen/box/innerNested/innerJavaClass.kt
- compiler/testData/codegen/box/innerNested/passingOuterRef.kt
- compiler/testData/codegen/box/innerNested/superConstructorCall/deepInnerHierarchy.kt
- compiler/testData/codegen/box/innerNested/superConstructorCall/innerExtendsInnerViaSecondaryConstuctor.kt
- compiler/testData/codegen/box/innerNested/superConstructorCall/innerExtendsInnerWithProperOuterCapture.kt
- compiler/testData/codegen/box/localClasses/innerOfLocalCaptureExtensionReceiver.kt
- compiler/testData/codegen/box/secondaryConstructors/innerClasses.kt
- compiler/testData/codegen/box/secondaryConstructors/innerClassesInheritance.kt
- compiler/testData/codegen/box/typealias/innerClassTypeAliasConstructorInSupertypes.kt
Inner class constructors should use the argument instead of reading outer `this` from a field because if such an access happens before a delegating constructor call, e.g. when evaluating an argument, a JVM
bytecode validation error will be thrown. (The only operation on `this` allowed before a delegating constructor call is SETFIELD, and only if the field in question is declared in the same class.)
> Refactor InnerClassesLowering & fix `this` remapping

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/SwitchGenerator.kt
- compiler/testData/codegen/box/when/edgeCases.kt
- compiler/testData/codegen/box/when/stringOptimization/duplicatingItemsSameHashCode2.kt
- compiler/testData/codegen/box/when/stringOptimization/duplicatingItemsSameHashCode3.kt
- compiler/testData/codegen/box/when/switchOptimizationDuplicates.kt
- compiler/testData/codegen/bytecodeText/when/edgeCases.kt
- compiler/testData/codegen/bytecodeText/when/switchOptimizationDuplicates.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/denseHashCode.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/duplicatingItems.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/duplicatingItemsSameHashCode2.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/duplicatingItemsSameHashCode3.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/expression.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/nullability.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/sameHashCode.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/statement.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
Effectively, the following when structure:
```
when (s) {
s1, s2 -> e1,
s3 -> e2,
s4 -> e3,
...
else -> e
}
```
is implemented as:
```
when (s.hashCode()) {
h1 -> {
if (s == s1)
e1
else if (s == s2)
e1
else if (s == s3)
e2
else
e
}
h2 -> if (s == s3) e2 else e,
...
else -> e
}
```
where `s1.hashCode() == s2.hashCode() == s3.hashCode() == h1,
s4.hashCode() == h2`.
A `tableswitch` or `lookupswitch` is used for the hash code lookup.
> when: emit switch for String if possible

- compiler/frontend/src/org/jetbrains/kotlin/resolve/constants/evaluate/ConstantExpressionEvaluator.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FoldConstantLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/descriptors/IrBuiltIns.kt
- compiler/testData/codegen/box/constants/comparisonFalse.kt
- compiler/testData/codegen/box/constants/comparisonTrue.kt
- compiler/testData/codegen/box/constants/divisionByZero.kt
- compiler/testData/codegen/box/primitiveTypes/kt2269.kt
- compiler/testData/codegen/box/primitiveTypes/kt2269NotOptimizable.kt
- compiler/testData/codegen/bytecodeText/constants/byte.kt
- compiler/testData/codegen/bytecodeText/constants/comparisonFalse.kt
- compiler/testData/codegen/bytecodeText/constants/comparisonTrue.kt
- compiler/testData/codegen/bytecodeText/constants/floatingPoints.kt
- compiler/testData/codegen/bytecodeText/constants/partialString.kt
- compiler/testData/codegen/bytecodeText/constants/short.kt
- compiler/testData/codegen/bytecodeText/constants/string.kt
- compiler/testData/codegen/bytecodeText/deadCodeElimination/boxingNotOptimizable.kt
- compiler/testData/codegen/bytecodeText/deadCodeElimination/simpleConstructorNotRedundantNotOptimizable.kt
- compiler/testData/codegen/bytecodeText/stringOperations/concat.kt
- compiler/testData/codegen/bytecodeText/stringOperations/primitiveToString.kt
- compiler/testData/codegen/bytecodeText/stringOperations/primitiveToStringNotOptimizable.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
The newly added pass folds the same set of constant functions of the
current backend.
Change-Id: I739bcb3e0fc549a87123422d7ca46e44d61f24dd
> Implement constant folding in the IR backend for JVM

- idea/src/org/jetbrains/kotlin/idea/intentions/loopToCallChain/matchAndConvert.kt
- idea/testData/intentions/useWithIndex/destructuringDeclaration.kt
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-30341
> KT-30341 False positive 'Use withIndex() instead of manual index increment' inspection with destructive declaration in 'for' loop

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/serialization/IrModuleDeserializer.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/serialization/KotlinIrLinker.kt
- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/compiler.kt
- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/lower/serialization/ir/JsIrLinker.kt
* Eliminated global state in IR deserializer. 
* Disentangled module header creation and declaration deserialization
* Allow forward declarations bring additional IR dependencies for modules present in metadata.
> Allow forward declarations bring additional IR dependencies for modules present in metadata.

- compiler/build.gradle.kts
- compiler/tests-common/tests/org/jetbrains/kotlin/checkers/AbstractForeignAnnotationsNoAnnotationInClasspathTest.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/checkers/KotlinMultiFileTestWithJava.java
- compiler/tests-common/tests/org/jetbrains/kotlin/test/KotlinTestUtils.java
- compiler/tests-common/tests/org/jetbrains/kotlin/test/testFramework/KtUsefulTestCase.java
- compiler/tests/org/jetbrains/kotlin/daemon/CompilerDaemonTest.kt
- js/js.tests/build.gradle.kts
- js/js.tests/test/org/jetbrains/kotlin/js/test/interop/ScriptEngineV8.kt
Parallel tests are currently broken for two reasons.
- Tests sometimes use the same root for temporary directories (e.g., /tmp/unitTest_simple), which is deleted once one of the tests finishes.
- There are several places in the code which delete temporary directories. The root temporary directory for a test is always deleted in the `shutDown` method. Other temporary directories are deleted by the `com.intellij.openapi.util.io.FileUtil` class when the test runner shuts down. Some of these temporary directories are also redundantly handled by the `com.intellij.openapi.util.ShutDownTracker` class. The latter two cause problems when running tests in parallel since they may attempt to delete files which are still in use.
This PR fixes these problems by consolidating all temporary files for a …
> Allow tests to be run in parallel.

- idea/src/org/jetbrains/kotlin/idea/inspections/SuspiciousVarPropertyInspection.kt
- idea/testData/inspectionsLocal/suspiciousVarProperty/hasBackingFieldRef3.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-30565
> KT-30565 False positive "Suspicious 'var' property" inspection with annotated default property getter

- compiler/backend/src/org/jetbrains/kotlin/codegen/AsmUtil.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/Equals.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IntrinsicMethods.java
- compiler/testData/codegen/box/dataClasses/doubleParam.kt
- compiler/testData/codegen/box/dataClasses/floatParam.kt
- compiler/testData/codegen/box/ieee754/dataClass.kt
Previously,
* Equals performs IEEE 754 equality check for floating points and
byte-to-byte checks for other types, including references.
* Ieee754Equals performs IEEE 754 for primitive types
* TotalOrderEquals performs total order equals to all types, including
floating points.
Now it is simplified,
* Equals performs total order checks for all types.
* Ieee754Equals performs IEEE 754 for primitive types.
* (TotalOrderEquals is removed.)
> IrBuiltins: refactoring for equality checks

- idea/resources/META-INF/plugin-common.xml
- idea/src/org/jetbrains/kotlin/idea/editor/KotlinStripTrailingSpacesFilterFactory.kt
- idea/testData/editor/stripTrailingSpaces/keepTrailingSpacesInRawString.kt
- idea/testData/editor/stripTrailingSpaces/keepTrailingSpacesInRawString.kt.after
- idea/tests/org/jetbrains/kotlin/idea/editor/StripTrailingSpacesTest.kt
https://youtrack.jetbrains.com/issue/KT-13048
> KT-13048 "Strip trailing spaces on Save" should not strip trailing spaces inside multiline strings in Kotlin

- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/lower/inline/FunctionInlining.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/IrBlock.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/impl/IrBlockImpl.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DeepCopyIrTreeWithSymbols.kt
This change let backend calculate and bind right function to the code block on generation debug information
e.g. for Kotlin/Native backend this let codegnerator to produce DILocation(..., inlinedAt:..) with correct value
for inlinedAt parameter, thus signifiacntly improve behaviour of debugger.
https://github.com/JetBrains/kotlin-native/pull/2849
> [IR] introduced additional field 'inlineFunctionSymbol' to IrReturnableBlock

- idea/resources/META-INF/plugin-common.xml
- idea/resources/intentionDescriptions/ConvertCollectionConstructorToFunction/after.kt.template
- idea/resources/intentionDescriptions/ConvertCollectionConstructorToFunction/before.kt.template
- idea/resources/intentionDescriptions/ConvertCollectionConstructorToFunction/description.html
- idea/src/org/jetbrains/kotlin/idea/intentions/ConvertCollectionConstructorToFunction.kt
- idea/testData/intentions/convertCollectionConstructorToFunction/.intention
- idea/testData/intentions/convertCollectionConstructorToFunction/keepArrayListCallWithArgument.kt
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceArrayListCall.kt
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceArrayListCall.kt.after
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceArrayListCallWithType.kt
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceArrayListCallWithType.kt.after
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceHashMapCall.kt
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceHashMapCall.kt.after
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceHashSetCall.kt
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceHashSetCall.kt.after
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceLinkedHashSetCall.kt
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceLinkedHashSetCall.kt.after
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
YouTrack: https://youtrack.jetbrains.com/issue/KT-13962
Example of this intention:
```
fun foo() {
var list: ArrayList<Int> = ArrayList()
}
```
to
```
fun foo() {
var list: ArrayList<Int> = arrayListOf()
}
```
> KT 13962: Intention to replace Java collection constructor calls with  function calls from stdlib (ArrayList() → arrayListOf())

- idea/src/org/jetbrains/kotlin/idea/intentions/ConvertCollectionConstructorToFunction.kt
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceArrayListCallQualified.kt
- idea/testData/intentions/convertCollectionConstructorToFunction/replaceArrayListCallQualified.kt.after
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
@mglukhikh, I saw this too late. My apologies.
Related to #2185.
YouTrack: https://youtrack.jetbrains.com/issue/KT-13962
* Identified copy/paste error in implementation code.
* Identified error occurring when using a FQN java collection call.
> Fix KT-13962 with kotlin.collections constructors

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendContext.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AnnotationLowering.kt
This improves JVM_IR compilation times a bit.
> Create a single instance of IrIntrinsicMethods per context

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/descriptors/SharedVariablesManager.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IrIntrinsicFunction.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/descriptors/IrBuiltIns.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/types/irTypes.kt
The KotlinType.toIrType function sometimes produces unbound symbols and was used in IrIntrinsicFunction and SharedVariablesManager.
This change removes the broken function and changes SharedVariableManager to use IrType consistently and IrIntrinsicFunction to use KotlinType consistently.
Note that I haven't checked whether this function is used by kotline-native (build problems), so you may want to hold off on merging the changes to `compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/types/irTypes.kt`.
> Remove broken KotlinType.toIrType function

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/phaser/PhaseBuilders.kt
This makes stack traces and flame graphs significantly more readable, which is important when trying to improve performance.
> Flatten phase compositions

- libraries/scripting/jvm-host/src/kotlin/script/experimental/jvmhost/jvmScriptEvaluation.kt
- libraries/scripting/jvm-host/test/kotlin/script/experimental/jvmhost/test/ConstructorArgumentOrderTest.kt
- libraries/scripting/jvm-host/test/kotlin/script/experimental/jvmhost/test/TestScriptDefinitions.kt
Change BasicJvmScriptEvaluator to pass constructor parameters in the
correct order, include tests for scripts w/ provided properties, and
implicit receiver, and both.
https://youtrack.jetbrains.com/issue/KT-30816
> KT-30816 BasicJvmScriptEvaluator incorrect arg order

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SingletonReferencesLowering.kt
- compiler/testData/codegen/box/enum/deepInnerClassInEnumEntryClass.kt
- compiler/testData/codegen/box/enum/deepInnerClassInEnumEntryClass2.kt
- compiler/testData/codegen/box/enum/enumEntryReferenceFromInnerClassConstructor1.kt
- compiler/testData/codegen/box/enum/enumEntryReferenceFromInnerClassConstructor2.kt
- compiler/testData/codegen/box/enum/enumEntryReferenceFromInnerClassConstructor3.kt
- compiler/testData/codegen/box/enum/innerClassInEnumEntryClass.kt
- compiler/testData/codegen/box/enum/innerClassMethodInEnumEntryClass.kt
- compiler/testData/codegen/box/enum/kt20651.kt
- compiler/testData/codegen/box/enum/kt20651_inlineLambda.kt
- compiler/testData/codegen/box/enum/kt7257.kt
- compiler/testData/codegen/box/enum/kt7257_anonObjectInit.kt
- compiler/testData/codegen/box/enum/kt7257_anonObjectMethod.kt
- compiler/testData/codegen/box/enum/kt7257_boundReference1.kt
- compiler/testData/codegen/box/enum/kt7257_boundReference2.kt
- compiler/testData/codegen/box/enum/kt7257_explicitReceiver.kt
- compiler/testData/codegen/box/enum/kt7257_fullyQualifiedReceiver.kt
- compiler/testData/codegen/box/enum/kt7257_namedLocalFun.kt
- compiler/testData/codegen/box/enum/kt7257_notInline.kt
The reference can be lowered to `this` if it is captured in the lexical
scope of the corresponding enum entry, and not used by the enum entry's
super constructor. Otherwise, it is lowered to
`GETFIELD SomeEnum.SomeEntry`.
> JVM_IR: Lower IrGetEnumValue to `this` whenever possible.

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/tasks/FatFrameworkTask.kt
https://youtrack.jetbrains.com/issue/KT-31008
I tested it on my project and it does fix the issue.
The fix is consistent with [another use](https://github.com/JetBrains/kotlin/blob/977d3ef840604959c90d950f94d2fc6069eb556c/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/tasks/FatFrameworkTask.kt#L268) of `project.copy` in the same file.
Would it be possible to include it into a 1.3.30 bugfix release?
> KT-31008 Fix fat dSYM Info.plist copying

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/PropertiesLowering.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/SharedVariablesLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/descriptors/SharedVariablesManager.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/CallableReferenceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/EnumClassLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FileClassLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FunctionNVarargInvokeLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InterfaceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/MoveCompanionObjectFieldsLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/PropertyReferenceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/RenameFieldsLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/PatchDeclarationParents.kt
This PR fixes various places where the lateinit parent field of an IrDeclaration was either unset or not updated properly.
- Reparent declarations in FileClassLowering, InterfaceLowering,
StaticDefaultFunctionsLowering, EnumClassLowering, and
RenameFieldsLowering
- Set correspondingPropertySymbol in MoveCompanionObjectFieldsLowering
- Reparent field initializers in MoveCompanionObjectFieldsLowering and
EnumClassLowering
- Ensure that parents are unique in PropertiesLowering
- Set declaration parent in SharedVariableManager
- Set field declaration parents in CallableReferenceLowering
- Set declaration parents in FunctionNVarargInvokeLowering
- Set declaration parents for external declaration fields
> Fix IR declaration parents.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/AndAnd.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IrIntrinsicMethods.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmBuiltinOptimizationLowering.kt
- compiler/testData/codegen/box/intrinsics/nonShortCircuitAnd.kt
- compiler/testData/codegen/bytecodeText/conditions/conjunction.kt
- compiler/testData/codegen/bytecodeText/conditions/conjunctionInDoWhile.kt
- compiler/testData/codegen/bytecodeText/conditions/conjunctionInWhile.kt
- compiler/testData/lineNumber/custom/ifThenElseFalse.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LineNumberTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrLineNumberTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
Implement an intrinsic method for boolean.and operation, and replace
ANDAND condition with a call to such intrinsic method.
Also added a new test case to make sure existing non-shortcircuit "and" function is not being shadowed by other functions.
> Optimize JVM byte code generation for conditional conjunction

- libraries/stdlib/src/kotlin/coroutines/CoroutineContext.kt
KT-26398 had updated behavior from reference comparison to regular
equality, but the documentation for CoroutineContext was left out.
The whole "by reference" needs to be removed, because it now
follows default behavior of all Kotlin collections and need no
further clarification.
> Fix CoroutineContext documentation

- compiler/testData/cli/jvm/internalArgOverrideLanguageFeature.out
- compiler/testData/cli/jvm/internalArgOverrideOffLanguageFeature.out
The expectations contained ';' instead of ':' which makes two
CLI tests fail.
> Fix typo in expectation files for command line tests.

- compiler/backend/src/org/jetbrains/kotlin/codegen/AsmUtil.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/HashCode.kt
- compiler/testData/codegen/box/dataClasses/hashCode/boolean.kt
- compiler/testData/codegen/bytecodeText/jvm8/hashCode/dataClass.kt
- compiler/testData/codegen/bytecodeText/jvm8/hashCode/hashCode.kt
In the jvm backend the behavior of Object.hashCode applied to primitive types depends on the context. 
Inside of the auto generated hashCode method of data or inline classes we inline the implementation of hashCode for primitive types. Otherwise we either call Object.hashCode or the static hashCode methods for primitive types (Integer.hashCode, etc.) on targets where they exist.
> Implement special cases for the hashCode intrinsic in JVM_IR

- compiler/testData/lineNumber/custom/functionCallWithDefault.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/ir/AbstractIrLineNumberTest.kt
Fix compareCustom function in IrLineNumberTest class, to exclude comment lines that are not related to line number verification.
Unmute a test case should have been unmuted but shadowed by this bug.
> Fix compareCustom function in IrLineNumberTest class, to exclude comment

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/smap/chainCalls.kt
- compiler/testData/codegen/box/smap/infixCalls.kt
- compiler/testData/codegen/box/smap/simpleCallWithParams.kt
Currently, line number for a function call is only generated for the line when start entering function call, before visiting arguments, therefore missing line number after all function arguments are visited.
> Change order of line number geneartion for function call, and also force  line number generation after visiting inline functions

- idea/resources/META-INF/plugin-common.xml
- idea/resources/inspectionDescriptions/ConvertNaNEquality.html
- idea/src/org/jetbrains/kotlin/idea/inspections/ConvertNaNEqualityInspection.kt
- idea/testData/inspectionsLocal/convertNaNEquality/.inspection
- idea/testData/inspectionsLocal/convertNaNEquality/float.kt
- idea/testData/inspectionsLocal/convertNaNEquality/float.kt.after
- idea/testData/inspectionsLocal/convertNaNEquality/importedProperty.kt
- idea/testData/inspectionsLocal/convertNaNEquality/importedProperty.kt.after
- idea/testData/inspectionsLocal/convertNaNEquality/inequality.kt
- idea/testData/inspectionsLocal/convertNaNEquality/inequality.kt.after
- idea/testData/inspectionsLocal/convertNaNEquality/javaDouble.kt
- idea/testData/inspectionsLocal/convertNaNEquality/javaDouble.kt.after
- idea/testData/inspectionsLocal/convertNaNEquality/javaFloatNaN.kt
- idea/testData/inspectionsLocal/convertNaNEquality/javaFloatNaN.kt.after
- idea/testData/inspectionsLocal/convertNaNEquality/negative.kt
- idea/testData/inspectionsLocal/convertNaNEquality/simple.kt
- idea/testData/inspectionsLocal/convertNaNEquality/simple.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
YouTrack: https://youtrack.jetbrains.com/issue/KT-26629
Replaces fragments like `5.0 == Double.NaN` with `5.0.equals(Double.NaN)`.
> KT-26629 Inspection to replace `==` operator on Double.NaN with `equals` call

- idea/src/org/jetbrains/kotlin/idea/inspections/RedundantRequireNotNullCallInspection.kt
- idea/testData/inspectionsLocal/redundantRequireNotNullCall/usedAsExpression.kt
- idea/testData/inspectionsLocal/redundantRequireNotNullCall/usedAsExpression.kt.after
- idea/testData/inspectionsLocal/redundantRequireNotNullCall/usedAsExpression2.kt
- idea/testData/inspectionsLocal/redundantRequireNotNullCall/usedAsExpression2.kt.after
- idea/testData/inspectionsLocal/redundantRequireNotNullCall/usedAsExpression3.kt
- idea/testData/inspectionsLocal/redundantRequireNotNullCall/usedAsExpression3.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-31404
> KT-31404 Redundant 'requireNotNull' or 'checkNotNull' inspection: don't remove first argument

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/IrUtils.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/InnerClassesLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/CallableReferenceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FunctionNVarargInvokeLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/PropertyReferenceLowering.kt
There are two ways of accessing `this` in the IR:
- In a member function we use the `dispatchReceiverParameter`
- In a constructor we use the `thisReceiver` of the constructed class
Right now there are several passes which produce IR which accesses the `thisReceiver` in member functions, necessitating a workaround in ExpressionCodegen. This patch fixes the passes in question and removes the workaround.
There's also an unrelated fix to the parameter indices in SyntheticAccessorLowering. Currently this pass produces static functions with parameter indices < 0. I didn't want to open a separate PR for that.
> IR parameter fix

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/EnumWhenLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/DeclarationOrigins.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/MappedEnumWhenLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/descriptors/IrBuiltIns.kt
- compiler/testData/codegen/bytecodeText/inline/whenMappingOnCallSite.kt
- compiler/testData/codegen/bytecodeText/when/exhaustiveWhenUnit.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/bigEnum.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/duplicatingItems.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/expression.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/functionLiteralInTopLevel.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/importedEnumEntry.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/manyWhensWithinClass.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/nullability.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/withoutElse.kt
- compiler/testData/writeFlags/class/accessFlags/mappingWhen.kt
The base EnumWhenLowering is mostly copied from Kotlin/Native; the only functional difference is that a nullable subject is converted into ordinal -1 when null rather than never being optimized at all, and the null checks are transformed accordingly. K/N tests pass when using this version of the lowering, so its copy can be removed after the next revision sync. On top of that, a JVM-specific subclass of EnumWhenLowering remaps the ordinals using WhenMappings.
> JVM_IR: implement the when(enum) optimization

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/phaser/PhaseConfig.kt
In Terminal.app and xterm the output columns get misaligned when using tabs.
Tabbed output only renders correctly when `tabstop=1`.
> Use spaces instead of tabs to indent -Xlist-phases.

- compiler/backend/src/org/jetbrains/kotlin/codegen/DefaultParameterValueSubstitutor.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmOverloadsAnnotationLowering.kt
- compiler/testData/checkLocalVariablesTable/jvmOverloads.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/AbstractCheckLocalVariablesTableTest.kt
Since we generate local variable entries for the rest of the arguments
we should do it for the receiver as well.
> JVM: Generate LVT entry for this in @JvmOverload methods.

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/DefaultArgumentStubGenerator.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/InnerClassesLowering.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LateinitLowering.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LocalDeclarationsLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
Suggested by @udalov in this comment: https://github.com/JetBrains/kotlin/pull/2310#discussion_r283411966
This allows us to add prerequisites on backend specific phases.
> Move jvm specific phases to JvmLower

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/Clone.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ArgumentsGenerationUtils.kt
- compiler/testData/ir/irText/classes/qualifiedSuperCalls.txt
- compiler/testData/ir/irText/classes/superCalls.fir.txt
- compiler/testData/ir/irText/classes/superCalls.kt
- compiler/testData/ir/irText/classes/superCalls.txt
In the IR there is no real distinction between `super` and `this`. Instead, this distinction is made at the call site where some calls are marked as super calls. This is in contrast to the representation of super in psi, which has a separate representation.
Currently, when we translate from psi to IR, some of this distinction shines through in that this code
```
class A { fun f() = super.hashCode() }
```
gets turned into IR accessing the dispatch receiver of `f` *with type Any instead of type A*.
For technical reasons (invokespecial) this is unfortunate for the JVM backend, in particular in combination with inline classes. I propose that we change this to treat `super` and `this` interchangeably in the IR instead.
> Fix type of super

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/descriptors/WrappedDescriptors.kt
- compiler/testData/ir/irText/classes/delegatingConstructorCallToTypeAliasConstructor.fir.txt
- compiler/testData/ir/irText/declarations/fakeOverrides.fir.txt
- compiler/testData/ir/irText/declarations/parameters/constructor.fir.txt
- compiler/testData/ir/irText/declarations/parameters/typeParameterBoundedBySubclass.fir.txt
- compiler/testData/ir/irText/stubs/genericClassInDifferentModule_m2.fir.txt
`IrConstructorCall` has type parameters from the constructed class as well as the constructor type parameters. This is currently not implemented in `WrappedClassConstructorDescriptor`, which breaks constructor calls with type arguments generated in an IR lowering pass.
Among other places, you can see the problem in the IR generated by fir2ir, which is why the tests have to be updated.
> Fix type parameters in WrappedClassConstructorDescriptor

- compiler/daemon/daemon-common-new/build.gradle.kts
- compiler/daemon/daemon-common/build.gradle.kts
Added by this commit for some reason: https://github.com/JetBrains/kotlin/commit/ced973b7074f4207859d9709375f2bf28b3e2c55
> Remove imports of javafx from Gradle build files

- compiler/backend/src/org/jetbrains/kotlin/codegen/state/KotlinTypeMapper.kt
The function `isStaticMethod` makes its decision based on the kind and annotation, but doesn't check whether the function has a null dispatch receiver. Apparently this case never happens in the current backend, but I had to add this test for #2326.
> Fix test for static default methods in KotlinTypeMapper

- compiler/backend/src/org/jetbrains/kotlin/codegen/state/KotlinTypeMapper.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/defaultArguments/constructor/innerClass32Args.kt
- compiler/testData/codegen/box/enum/manyDefaultParameters.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
The synthesized arguments caused the size of default value mask off by
one when it is close to the boundary of Int.SIZE, which in turn
resulted in wrong signature at call sites.
> Fix signature generation for calls to enum and inner class constructors

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/testData/codegen/box/diagnostics/functions/tailRecursion/defaultArgs2.kt
- compiler/testData/codegen/box/diagnostics/functions/tailRecursion/defaultArgs2.txt
- compiler/testData/codegen/box/diagnostics/functions/tailRecursion/defaultArgsWithSideEffects.kt
- compiler/testData/codegen/box/diagnostics/functions/tailRecursion/defaultArgsWithSideEffects.txt
- compiler/testData/codegen/box/diagnostics/functions/tailRecursion/defaultArgsWithSideEffects2.kt
- compiler/testData/codegen/box/diagnostics/functions/tailRecursion/defaultArgsWithSideEffects2.txt
- compiler/tests/org/jetbrains/kotlin/checkers/DiagnosticsTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/checkers/javac/DiagnosticsUsingJavacTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
So that default values can be copied to the recursive call sites.
> Move tailrecPhase before defaultArgumentStubPhase

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/LambdaInfo.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/SourceCompilerForInline.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrSourceCompilerForInline.kt
- compiler/testData/codegen/boxInline/simple/inlineCallInInlineLambda.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
It uses isStaticMethod to determine whether to set ACC_STATIC, which is not correct (see PR #2341). This results in using incorrectly typed opcodes (as all arguments are shifted by 1) when modifying the inlined lambda's bytecode. For example, in the test added by this commit, these opcodes are inserted to spill the stack into locals before calling another inline function. Without the patch, `ILOAD 0` for the lambda's `it` is considered to refer to a nonexistent `this`, which is spilled with an `ASTORE` instead of `ISTORE`.
Because getMethodAsmFlags is used by the non-IR backend (see PR #2341 again for why changing stuff might not be a good idea), the proposed solution is to ditch it completely and override generateLambdaBody in IrExpressionLambdaImpl to use FunctionCodegen's IR-based flag …
> JVM_IR: sidestep defective getMethodAsmFlags when inlining lambdas

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
When moving away from descriptors, this top-level declaration check
was lost. That leads to many useless annotation elements in
inner classes attributes for annotations that are not inner classes.
> JVM_IR: Restore lost top-level declaration check in annotation gen.

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/yarn/YarnSetupTask.kt
https://youtrack.jetbrains.com/issue/KT-31645
According to docs (https://docs.gradle.org/current/javadoc/org/gradle/api/file/FileCopyDetails.html#getPath--)  FileCopyDetails uses '/' as separator regardless of platform, on Windows standard separator is '\'
Addditionally, it returns the path relative to the root of destination
So separator is unnecessary to remove
> KT-31645 Fix yarn downloading on Windows

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/fir/Fir2IrTextTestGenerated.java
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/BranchingExpressionGenerator.kt
- compiler/testData/codegen/box/constants/constantsInWhen.kt
- compiler/testData/ir/irText/expressions/whenUnusedExpression.fir.txt
- compiler/testData/ir/irText/expressions/whenUnusedExpression.kt
- compiler/testData/ir/irText/expressions/whenUnusedExpression.txt
- compiler/tests/org/jetbrains/kotlin/ir/IrTextTestCaseGenerated.java
Ideally, the type of `IrWhen` should be provided by type inference for
a consistent behavior. `USED_AS_EXPRESSION` from CFG isn't always
consistent with type inference, unfortunately.
The behavior is now aligned with `if`. The type of `when` is kept when
it *can* be an expression, instead of whether it is used or not.
> psi2ir: keep the type of `when` when possible

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
- compiler/testData/loadJava/compiledKotlin/classObject/Delegation.kt
This currently leads to a compilation error due to metadata
generation.
> JVM_IR: Allow delegated companion objects.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmDefaultConstructorLowering.kt
- compiler/testData/codegen/box/jvmOverloads/primaryConstructorWithAllDefaults.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
when the primary constructor with @JvmOverloads has default values for all arguments.
Bugfix for #2372.
> JVM_IR: do not generate two nullary constructors

- idea/src/org/jetbrains/kotlin/idea/quickfix/ConvertLateinitPropertyToNotNullDelegateFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
- idea/testData/quickfix/convertLateinitPropertyToNotNullDelegate/basic.kt
- idea/testData/quickfix/convertLateinitPropertyToNotNullDelegate/basic.kt.after
- idea/testData/quickfix/convertLateinitPropertyToNotNullDelegate/basic2.kt
- idea/testData/quickfix/convertLateinitPropertyToNotNullDelegate/basic2.kt.after
- idea/testData/quickfix/convertLateinitPropertyToNotNullDelegate/hasInitializer.kt
- idea/testData/quickfix/convertLateinitPropertyToNotNullDelegate/noType.kt
- idea/testData/quickfix/convertLateinitPropertyToNotNullDelegate/notPrimitive.kt
- idea/testData/quickfix/convertLateinitPropertyToNotNullDelegate/nullablePrimitive.kt
- idea/testData/quickfix/convertLateinitPropertyToNotNullDelegate/val.kt
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-12515
> KT-12515 Quickfix "by Delegates.notNull()" as replacement for "lateinit" for primitive type

- compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/AsmTypes.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/ir/util/IrTypeUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/PromisedValue.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AnnotationLowering.kt
- compiler/testData/codegen/boxAgainstJava/annotations/kClassMapping/arrayClassParameter.kt
- compiler/testData/codegen/boxAgainstJava/annotations/kClassMapping/arrayClassParameterOnJavaClass.kt
- compiler/testData/codegen/boxAgainstJava/annotations/kClassMapping/classParameter.kt
- compiler/testData/codegen/boxAgainstJava/annotations/kClassMapping/classParameterOnJavaClass.kt
- compiler/testData/codegen/boxAgainstJava/annotations/kClassMapping/varargClassParameter.kt
- compiler/testData/codegen/boxAgainstJava/annotations/kClassMapping/varargClassParameterOnJavaClass.kt
This PR implements the special cases around KClass and Array<KClass> fields in annotation classes in ExpressionCodegen instead of as a lowering. Since the special cases in question are already implemented as part of the type mapper this results in less code overall while also handling external declarations correctly.
> JVM_IR: Handle annotation KClass fields in external declarations

- compiler/backend/src/org/jetbrains/kotlin/codegen/optimization/LabelNormalizationMethodTransformer.kt
Reduce calls to Object.hashCode originating from LabelNormalizationMethodTransformer
Building on the work in #2403, shaves 1% of compilation time on kotlinx.serialization
by using SmartIdentityTable instead of hashMap in LabelNormailizationMethodTransformer.
Metrics on the prior hashMap use in this code:
| What      | Count |
| --------- | ----- |
| instances | 21530 |
| min       | 0     |
| max       | 174   |
| mean      | 4     |
| stddev    | 8.24  |
| median    | 4     |
| 90p       | 8     |
| 95p       | 15    |
> Reduce calls to Object.hashCode from LabelNormalizationMethodTransformer

- compiler/backend/src/org/jetbrains/kotlin/codegen/intrinsics/IntrinsicMethods.java
- compiler/backend/src/org/jetbrains/kotlin/codegen/intrinsics/Java8Unsigned.kt
- compiler/testData/codegen/box/unsignedTypes/unsignedIntToString.kt
- compiler/testData/codegen/box/unsignedTypes/unsignedLongToString.kt
- compiler/testData/codegen/bytecodeText/unsignedTypes/unsignedIntToString_jvm18.kt
- compiler/testData/codegen/bytecodeText/unsignedTypes/unsignedLongToString_jvm18.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
Unfortunately this cannot currently be done for the extension overload which accepts a radix due to behavior difference with regard to invalid radix values.
> Add intrinsic for ULong/UInt.toString on Java 8+

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/dsl/KotlinMultiplatformExtension.kt
Fore the case where a target has been created or configured twice with different presets,
avoid showing "null" inside the error message if existing target has not preset,
and append a point.
> Improve error message

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/Ir.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/IrUtils.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/DefaultArgumentStubGenerator.kt
- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/JsIrBackendContext.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendContext.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmDefaultParameterInjector.kt
- compiler/testData/codegen/bytecodeText/defaultArguments/noEmptyArray.kt
- compiler/testData/codegen/bytecodeText/inlineClasses/defaultParametersDontBox.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
There are some cases where `DefaultParameterInjector` adds unnecessary boxing for inline class arguments, since `IrClass.underlyingType` doesn't recursively unfold inline classes. Since the rules for unfolding inline classes differ by backend I've fixed this by adding a new function in the `Ir` class and removing the `IrClass.underlyingType` function.
I've added a test for this, as well as for another issue where default vararg arguments allocate an unnecessary array. I've got a different fix in the works for the latter, but we might as well add the test now.
> Fix handling of inline classes in DefaultParameterInjector

- compiler/frontend/src/org/jetbrains/kotlin/resolve/diagnostics/KotlinSuppressCache.kt
We've found that the BindingContext is necessary for any meaningful suppressor.
This change adds the ability for suppressors to use the BindingContext when available.
The change was intentionally formulated to minimize churn/changes to the codebase, but if you would prefer that we have only a single `isSuppressed` method on the interface (specifically, the isSuppressed that includes the BindingContext), I'm happy to update the PR.  Or if you have any other feedback, just let me know.
cc @erokhins
> Make context available to suppressors

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/MoveCompanionObjectFieldsLowering.kt
- compiler/testData/codegen/box/objects/interfaceCompanion.kt
- compiler/testData/codegen/bytecodeText/companion/kt14258_5.kt
- compiler/testData/codegen/bytecodeText/constProperty/nonConstValHasNoDefaultValue_after.kt
- compiler/testData/writeFlags/property/classObject/trait/delegatedProtectedVar.kt
- compiler/testData/writeFlags/property/classObject/trait/delegatedPublicVal.kt
- compiler/testData/writeFlags/property/classObject/trait/internalConstVal.kt
- compiler/testData/writeFlags/property/classObject/trait/privateVal.kt
- compiler/testData/writeFlags/property/classObject/trait/privateVar.kt
- compiler/testData/writeFlags/property/classObject/trait/publicConstVal.kt
`MoveCompanionObjectFieldsLowering` replaces fields in a companion object with static fields in the enclosing class. Currently the lowering ignores fields in interface companions (unless they are marked with `@JvmField`). This PR adds support for fields in interface companions, which we do not want to move, but still have to mark as static.
> JVM IR: Convert interface companion fields to static fields.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmStaticAnnotationLowering.kt
- compiler/testData/codegen/boxInline/defaultValues/lambdaInlining/jvmStaticDefault.kt
Note: this currently results in invalid IR (but valid bytecode) if the @JvmStatic function is imported, because its IR representation is unlowered and therefore has a dispatch receiver, but the call will not.
> JVM_IR: lower calls to @JvmStatic functions from other files.

- idea/src/org/jetbrains/kotlin/idea/quickfix/InitializePropertyQuickFixFactory.kt
- idea/testData/quickfix/addInitializer/topLevelPropertyVarClass.kt
- idea/testData/quickfix/addInitializer/topLevelPropertyVarClass.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-28471
Remove call to `CodeInsightUtils.defaultInitializer(descriptor.type)` in favor of `TODO()`.
> KT-28471: "Add initializer" quickfix initializes non-null variable with null

- idea/src/org/jetbrains/kotlin/idea/inspections/KotlinRedundantOverrideInspection.kt
- idea/testData/inspectionsLocal/redundantOverride/getterWithDerivedProperty.kt
- idea/testData/inspectionsLocal/redundantOverride/getterWithDerivedProperty2.kt
- idea/testData/inspectionsLocal/redundantOverride/getterWithDerivedProperty3.kt
- idea/testData/inspectionsLocal/redundantOverride/getterWithDerivedProperty3.kt.after
- idea/testData/inspectionsLocal/redundantOverride/getterWithDerivedProperty4.kt
- idea/testData/inspectionsLocal/redundantOverride/getterWithDerivedProperty4.kt.after
- idea/testData/inspectionsLocal/redundantOverride/setterWithDerivedProperty.kt
- idea/testData/inspectionsLocal/redundantOverride/setterWithDerivedProperty2.kt
- idea/testData/inspectionsLocal/redundantOverride/setterWithDerivedProperty3.kt
- idea/testData/inspectionsLocal/redundantOverride/setterWithDerivedProperty3.kt.after
- idea/testData/inspectionsLocal/redundantOverride/setterWithDerivedProperty4.kt
- idea/testData/inspectionsLocal/redundantOverride/setterWithDerivedProperty4.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-32479
> KT-32479 False positive "Redundant overriding method" with derived property and base function starting with "get" (Accidental override)

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSymbols.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/TypeOperatorLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/builders/ExpressionHelpers.kt
- compiler/testData/codegen/box/javaInterop/notNullAssertions/errorMessage.kt
- compiler/testData/codegen/box/javaInterop/notNullAssertions/staticCallErrorMessage.kt
- compiler/testData/codegen/boxAgainstJava/platformTypes/genericUnit.kt
- compiler/testData/codegen/bytecodeText/inline/reifiedSafeAsWithMutable.kt
- compiler/testData/codegen/bytecodeText/reifiedSafeAsCheck.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
This PR moves some of the logic from ExpressionCodegen/codegenUtils to the IR level, where it can potentially be shared with [JS_IR](https://github.com/JetBrains/kotlin/blob/72f7287ad2897fd97da3f24d256076b3ced3ca75/compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/lower/TypeOperatorLowering.kt) and [native](https://github.com/JetBrains/kotlin-native/blob/4da64036c188e3e29dff00ed4dac071fb4412d34/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/lower/TypeOperatorLowering.kt) in the future.
I've also added two tests for the error messages around not-null assertions. They are currently disabled on JVM_IR, since the IMPLICIT_NOTNULL casts are missing. With these casts, "testErrorMessage" succeeds while "testStaticCallErrorMessage" fails, since the …
> Implement a lowering for type operators in the JVM_IR backend

- idea/src/org/jetbrains/kotlin/idea/intentions/ToOrdinaryStringLiteralIntention.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent1.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent1.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent2.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent2.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent3.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent3.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent4.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent4.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent5.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent5.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent6.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent6.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent7.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent7.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent8.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent8.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent9.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimIndent9.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimMargin1.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimMargin1.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimMargin2.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimMargin2.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimMargin3.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimMargin3.kt.after
- idea/testData/intentions/toOrdinaryStringLiteral/trimMargin4.kt
- idea/testData/intentions/toOrdinaryStringLiteral/trimMargin4.kt.after
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-32616
> KT-32616 "To ordinary string literal" doesn't remove indents, newlines and `trimIndent`

- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/FunctionGenerator.kt
- compiler/testData/codegen/box/annotations/annotationsOnLateinitAccessors.kt
- compiler/testData/codegen/box/annotations/annotationsOnNonExistentAccessors.kt
- compiler/testData/diagnostics/testsWithStdLib/annotations/annotationsTargetingLateinitAccessors.kt
- compiler/testData/diagnostics/testsWithStdLib/annotations/annotationsTargetingLateinitAccessors.txt
- compiler/testData/diagnostics/testsWithStdLib/annotations/annotationsTargetingNonExistentAccessor.kt
- compiler/testData/diagnostics/testsWithStdLib/annotations/annotationsTargetingNonExistentAccessor.txt
- compiler/testData/ir/irText/declarations/classLevelProperties.txt
- compiler/testData/ir/irText/declarations/packageLevelProperties.txt
- compiler/testData/ir/irText/expressions/propertyReferences.txt
- compiler/testData/ir/sourceRanges/declarations/classProperties.txt
- compiler/testData/ir/sourceRanges/declarations/topLevelProperties.txt
- compiler/tests/org/jetbrains/kotlin/checkers/DiagnosticsTestWithStdLibGenerated.java
- compiler/tests/org/jetbrains/kotlin/checkers/javac/DiagnosticsTestWithStdLibUsingJavacGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
They are currently marked as defined even when they get a default implementation. That makes it hard to figure out if the accessor should be removed when introducing a backing field in the JVM_IR backend.
The only actual change here is to psi2ir/generators/FunctionGenerator.kt. The rest are test changes to make sure that we run all the non-lateinit property annotation tests on the JVM_IR backend. The JVM_IR backend has different behavior from the current backend (on purpose) for lateinit properties and therefore the test has to be split to make sure we do not regress on the parts that work the same.
> Psi2Ir: Mark accessors with no bodies as default accessors.

- buildSrc/src/main/kotlin/jdksFinder.kt
When testing for the JAVA_HOME environment variable, expand potential
symlinks first. This is almost guaranteed to be the case in all modern
Linux distributions putting the JDK / JRE behind update-alternatives to
be able to select the *current* version [0], e.g. on Fedora:
$ ls -l $JAVA_HOME
lrwxrwxrwx. ... /usr/lib/jvm/java -> /etc/alternatives/java_sdk
[0] https://linux.die.net/man/8/update-alternatives
> Support symlinked JAVA_HOME

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/ClosureAnnotator.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LocalDeclarationsLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/irCodegenUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/CallableReferenceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InterfaceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/PropertyReferenceLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrClass.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/impl/IrClassImpl.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/lazy/IrLazyClass.kt
- compiler/testData/writeFlags/callableReference/visibility/functionReference.kt
- compiler/testData/writeFlags/callableReference/visibility/propertyReference.kt
- compiler/testData/writeFlags/function/constructors/objectLiteral.kt
- compiler/testData/writeFlags/inline/inlineOnly.kt
- compiler/testData/writeFlags/lambda/simpleLambda.kt
This is a new implementation of #2523, which moves the logic for setting the visibility of callable references into several lowerings instead of keeping it in the backend.
> JVM IR: Implement visibility rules for CallableReferences

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmBuiltinOptimizationLowering.kt
- compiler/testData/codegen/box/primitiveTypes/equalityWithObject/intEqualsNull.kt
- compiler/testData/codegen/bytecodeText/conditions/nullCompareConst.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
```
1.equals(null)
```
Caused generation of invalid bytecode.
> JVM_IR: Fix null-constant comparison with primitive types.

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/yarn/YarnSetupTask.kt
"installationDir" is the non-version specific top-level Yarn
installation directory simply called "yarn". Checking for its existence
is not sufficient to be able to skip the task, as another version than
the requested one could be installed below the "yarn" directory.
Instead of taking the version into account in this check, simply remove
it as the version-specific installation directory at "env.home" is
already marked as an "OutputDirectory", so Gradle itself already takes
care of skipping task execution if the output files were created before.
> YarnSetupTask: Remove a too coarse "onlyIf" in the init block

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/HeaderProcessor.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/ProgressionHandlers.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmBuiltinOptimizationLowering.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/LoopExpressionGenerator.kt
- compiler/testData/codegen/bytecodeText/forLoop/forInStringSpecialized.kt
- compiler/testData/ir/irText/expressions/for.txt
Avoid using a separate origin for temporary variables introduced
for for loops. That doesn't add anything and gives one more case
for optimizations to deal with.
Extend the JVM specific optimizations to remove temporary
variables to deal with more cases encountered in for loops
lowering.
> [JVM_IR, IR] Remove more needless temporary variables.

- compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/KotlinJavaPsiFacade.java
This may help with some UI freezes caused by KT-33394, although
it does not fix the underlying performance problem.
> Check cancelation in KotlinJavaPsiFacade.findPackage()

- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/DataClassMembersGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/transformations/InsertImplicitCasts.kt
- compiler/testData/ir/irText/classes/dataClassWithArrayMembers.txt
- compiler/testData/ir/irText/classes/dataClasses.txt
- compiler/testData/ir/irText/classes/dataClassesGeneric.txt
- compiler/testData/ir/irText/classes/inlineClass.txt
- compiler/testData/ir/irText/classes/lambdaInDataClassDefaultParameter.txt
- compiler/testData/ir/irText/declarations/parameters/dataClassMembers.txt
- compiler/testData/ir/irText/lambdas/destructuringInLambda.txt
- compiler/testData/ir/sourceRanges/declarations/synthesizedDataClassMembers.txt
This PR changes `DataClassMembersGenerator` to
- Access underlying fields directly, instead of using accessors. This is safe since data classes are always final.
- Don't generate a temporary variable in hashCode to use as the accumulator.
Both optimizations are effectively present in the current JVM backend and with these changes the generated code is much closer to what the current backend generates.
Most of the changes are just updating `IrText` tests.
> psi2ir: Optimize generated data class members

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendContext.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmInlineClassLowering.kt
- compiler/testData/codegen/boxInline/inlineClasses/inlineFunctionInsideInlineClassesBox.kt
Currently, we are caching inline class replacements at the file level, which breaks when you have an inline function taking inline class arguments defined in a different file in the same module. This PR just moves the cache to the backend context, effectively caching at the level of modules instead.
> JVM IR: Cache inline class replacements at the module level

- idea/resources/META-INF/plugin-common.xml
https://youtrack.jetbrains.com/issue/KT-33235
> KT-33235 Remove "Replace guard clause with kotlin's function call" inspection and tranform it to J2K post-processing

- idea/src/org/jetbrains/kotlin/idea/inspections/MoveVariableDeclarationIntoWhenInspection.kt
- idea/testData/inspectionsLocal/moveVariableDeclarationIntoWhen/hasBreak.kt
- idea/testData/inspectionsLocal/moveVariableDeclarationIntoWhen/hasContinue.kt
- idea/testData/inspectionsLocal/moveVariableDeclarationIntoWhen/hasReturn.kt
- idea/testData/inspectionsLocal/moveVariableDeclarationIntoWhen/hasReturn2.kt
- idea/testData/inspectionsLocal/moveVariableDeclarationIntoWhen/hasThrow.kt
- idea/testData/inspectionsLocal/moveVariableDeclarationIntoWhen/hasThrow2.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-31999
> KT-31999 "Variable declaration could be moved into `when`" inspection suggests to inline expression containing return (throw) statement

- idea/src/org/jetbrains/kotlin/idea/formatter/KotlinPreFormatProcessor.kt
- idea/testData/quickfix/createFromUsage/createFunction/call/funOnEnumClass.kt
- idea/testData/quickfix/createFromUsage/createFunction/call/funOnEnumClass.kt.after
- idea/testData/quickfix/createFromUsage/createFunction/call/funOnEnumClass2.kt
- idea/testData/quickfix/createFromUsage/createFunction/call/funOnEnumClass2.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-14899
> KT-14899 Quickfix "Create member function" inserts too many semicolons when applied to Enum

- idea/src/org/jetbrains/kotlin/idea/quickfix/ReplaceCallFix.kt
- idea/testData/quickfix/replaceWithDotCall/comment.kt
- idea/testData/quickfix/replaceWithDotCall/comment.kt.after
- idea/testData/quickfix/replaceWithDotCall/lineBreak.kt
- idea/testData/quickfix/replaceWithDotCall/lineBreak.kt.after
- idea/testData/quickfix/replaceWithSafeCall/comment.kt
- idea/testData/quickfix/replaceWithSafeCall/comment.kt.after
- idea/testData/quickfix/replaceWithSafeCall/lineBreak.kt
- idea/testData/quickfix/replaceWithSafeCall/lineBreak.kt.after
- idea/testData/quickfix/replaceWithSafeCallForScopeFunction/comment.kt
- idea/testData/quickfix/replaceWithSafeCallForScopeFunction/comment.kt.after
- idea/testData/quickfix/replaceWithSafeCallForScopeFunction/lineBreak.kt
- idea/testData/quickfix/replaceWithSafeCallForScopeFunction/lineBreak.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-25697
> KT-25697 `Replace with dot call` quickfix breaks formatting

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/HeaderInfo.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/HeaderProcessor.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/ProgressionHandlers.kt
- compiler/testData/codegen/box/ranges/forInCharSequenceLengthDecreasedInLoopBody.kt
- compiler/testData/codegen/box/ranges/forInCharSequenceLengthIncreasedInLoopBody.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
CharSequences may be mutable (e.g., StringBuilder) and therefore its contents and length can change within the loop.
This issue was introduced in #2541. This fix matches the optimization in current JVM backend (https://github.com/JetBrains/kotlin/blob/master/compiler/backend/src/org/jetbrains/kotlin/codegen/range/forLoop/ForInCharSequenceLoopGenerator.kt#L56).
> Do not cache "last" value in lowered for-loop over CharSequences

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/ProgressionHandlers.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/ir/util/IrBackendUtils.kt
...getters instead of directly retrieving the property first. When the IR backend is used to compile the standard library, the progression classes (in sources) are lowered, and therefore do not have properties anymore (only fields and functions).
> Use `getPropertyGetter()` in ForLoopsLowering to retrieve property getters

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
- compiler/testData/codegen/box/inlineClasses/functionNameMangling/mangledFunctionsCanBeOverridden.kt
We don't lower descriptors in the JVM IR backend, but we still use them for ClassBuilders. This causes a spurious diagnostic related to inline classes which breaks one test.
This PR changes ClassCodegen to pass a WrappedDescriptor to the ClassBuilder instead.
> JVM IR: Use WrappedClassDescriptor in class builder.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/ConstLowering.kt
- compiler/testData/codegen/box/constants/kt9532_lv10.kt
- compiler/testData/codegen/bytecodeText/constProperty/noInline.kt
- compiler/testData/codegen/bytecodeText/constProperty/noInlineInCmp.kt
- compiler/testData/codegen/bytecodeText/lazyCodegen/negateConstantCompare.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/nonInlinedConst.kt
I'm honestly not sure if this feature is relevant for the IR backends - as far as I can tell, this is merely for compatibility with Kotlin before version 1.1
> JVM IR: Respect InlineConstVals

- compiler/testData/codegen/bytecodeText/deadCodeElimination/boxing.kt
- compiler/testData/codegen/bytecodeText/deadCodeElimination/simpleConstructorNotRedundant.kt
- compiler/testData/codegen/bytecodeText/stringOperations/primitiveToString.kt
As part of #2111, @ting-yuan muted some bytecode text tests for the JVM_IR backend which were optimized away. At the time, the problem was that we were also removing line numbers, and the tests remained so that we would know to come back to this issue again.
Well, turns out that this was fixed at some point (probably before the PR got merged), but the superfluous tests never got removed.
> Minor: Fix some test cases

- compiler/backend/src/org/jetbrains/kotlin/codegen/ClosureGenerationStrategy.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/FunctionCodegen.java
- compiler/backend/src/org/jetbrains/kotlin/codegen/codegenUtil.kt
- compiler/testData/checkLocalVariablesTable/destructuringInFor.kt
- compiler/testData/checkLocalVariablesTable/destructuringInLambdas.kt
- compiler/testData/checkLocalVariablesTable/destructuringInlineLambda.kt
- compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/inline.kt
- compiler/testData/checkLocalVariablesTable/underscoreNames.kt
- compiler/testData/codegen/asmLike/receiverMangling/deepInline.txt
- compiler/testData/codegen/asmLike/receiverMangling/deepInlineWithLabels.txt
- compiler/testData/codegen/asmLike/receiverMangling/deepNoinlineWithLabels_after.txt
- compiler/testData/codegen/asmLike/receiverMangling/deepNoinlineWithLabels_before.txt
- compiler/testData/codegen/asmLike/receiverMangling/deepNoinline_after.txt
- compiler/testData/codegen/asmLike/receiverMangling/deepNoinline_before.txt
- compiler/testData/codegen/asmLike/receiverMangling/inlineReceivers.txt
- compiler/testData/codegen/asmLike/receiverMangling/mangledNames.txt
- compiler/testData/codegen/asmLike/receiverMangling/nonInlineReceivers_after.txt
- compiler/testData/codegen/asmLike/receiverMangling/nonInlineReceivers_before.txt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/AbstractAsmLikeInstructionListingTest.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/AbstractCheckLocalVariablesTableTest.kt
- compiler/tests/org/jetbrains/kotlin/codegen/CheckLocalVariablesTableTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCheckLocalVariablesTableTestGenerated.java
CheckLocalVariablesTableTests will now check the validity of
the locals table against types of locals computed based on the
bytecode.
These checks and the new destructuringInFor test act as a
regression test for the changes in
https://github.com/JetBrains/kotlin/pull/2613
These checks also caught a similar issue for destructuring
lambda parameters, where the local is introduced before the
value has been written to the local slot. This change also
fixes that.
Finally, this change fixes the asmLike tests to correctly
look up the name of parameters in the locals table.
> Introduce local variable type checker.

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/fir/Fir2IrTextTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/DefaultArgumentStubGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/FunctionGenerator.kt
- compiler/testData/codegen/box/defaultArguments/useNextParamInLambda.kt
- compiler/testData/ir/irText/declarations/parameters/useNextParamInLambda.fir.txt
- compiler/testData/ir/irText/declarations/parameters/useNextParamInLambda.kt
- compiler/testData/ir/irText/declarations/parameters/useNextParamInLambda.txt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/ir/IrTextTestCaseGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
Rely on the frontend weeding out cases that are not supported.
In psi2ir, introduce all the parameters before processing default
values.
Change the DefaultArgumentStubGenerator to generate code that
matches the behavior of the current backend.
> [IR] Deal with forward references in default argument lambdas.

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/InlineCodegen.kt
- compiler/testData/codegen/boxInline/assert/jvmClassInitializer.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
This fixes the problem where compiling a class initializer that contains a call to an `assert`ing function in a separate module causes the assertion to always be enabled (i.e. the attached test used to fail in CompileKotlinAgainstInlineKotlin mode).
> JVM: generate $assertionsDisabled before inlining the node

- js/js.translator/build.gradle.kts
This was causing re-indexing in IntelliJ after every time the JS tests are run.
(Credit goes to @sfs for finding the cause and fix! :clap:)
> Exclude additional generated testData/out-min dir in js/js.translator.

- compiler/ir/serialization.common/src/org/jetbrains/kotlin/backend/common/serialization/IrFileSerializer.kt
- compiler/ir/serialization.common/src/org/jetbrains/kotlin/backend/common/serialization/KotlinIrLinker.kt
- compiler/ir/serialization.js/src/org/jetbrains/kotlin/ir/backend/js/klib.kt
- compiler/testData/codegen/box/properties/initOrderMultiModule.kt
- compiler/testData/codegen/box/properties/sideEffectInTopLevelInitializerMultiModule.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/generators/tests/GenerateCompilerTests.kt
- compiler/tests/org/jetbrains/kotlin/ir/IrJsTextTestCaseGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
This is @romanart fix for property initialization order with a little fixup for forward declarations caught by the native build failure.
> fix init order + forward declarations fixup

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/testData/codegen/box/syntheticAccessors/inlineInOtherClass.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
Turns out private inline functions *can* be called from other classes.
> JVM_IR: fix synthetic accessor generation (again)

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/InnerClassesLowering.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/ir/builders/declarations/declarationBuilders.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSymbols.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrInlineCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/MethodSignatureMapper.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/irCodegenUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IrIntrinsicMethods.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/SignatureString.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/CallableReferenceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/PropertyReferenceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/RemoveDeclarationsThatWouldBeInlinedLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/InlineClassAbi.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/MemoizedInlineClassReplacements.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrConstructor.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/impl/IrFunctionBase.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/lazy/IrLazyFunctionBase.kt
- compiler/testData/codegen/box/reflection/call/inlineClasses/constructorWithInlineClassParameters.kt
- compiler/testData/codegen/box/reflection/mapping/constructor.kt
- compiler/testData/codegen/box/reflection/mapping/constructorWithInlineClassParameters.kt
- compiler/testData/codegen/bytecodeText/inlineClasses/constructorBridge.kt
- compiler/testData/writeFlags/function/constructors/withMangledArguments.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/flags/WriteFlagsTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrWriteFlagsTestGenerated.java
- core/reflection.jvm/src/kotlin/reflect/jvm/internal/KDeclarationContainerImpl.kt
- plugins/kotlin-serialization/kotlin-serialization-compiler/testData/codegen/Basic.ir.txt
On the JVM backend, we hide constructors taking inline class parameters and call them through public bridge methods. This PR implements the same feature in the JVM IR backend.
> JVM IR: Hide constructors with inline class parameters

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SingleAbstractMethodLowering.kt
- compiler/testData/codegen/box/sam/inlinedSamWrapper.kt
- compiler/testData/codegen/box/sam/nullableSam.kt
- compiler/testData/codegen/box/sam/predicateSamWrapper.kt
- compiler/testData/codegen/bytecodeText/sam/samWrapperForNullableInitialization.kt
- compiler/testData/compileKotlinAgainstKotlin/copySamOnInline2.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
This PR fixes the visibility of generated SAM wrappers (public inside the scope of an inline function and package private otherwise) and makes the caching scheme match the current backend.
There is still some work left to do in order to make `singleAbstractMethodPhase` produce correct IR types, but at least the generated code is correct.
> JVM IR: Generate public SAM wrappers in inline function scope

- compiler/backend/src/org/jetbrains/kotlin/codegen/optimization/RedundantGotoMethodTransformer.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/DefaultArgumentStubGenerator.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSymbols.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IrIntrinsicMethods.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/ReassignParameter.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmDefaultArgumentStubGenerator.kt
- compiler/testData/codegen/bytecodeText/argumentOrder/sameOrderWithDefault.kt
- compiler/testData/codegen/bytecodeText/defaultArguments/maskCheckSequence.kt
- compiler/testData/codegen/bytecodeText/defaultMethodBody.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
Given the strict pattern-matching in the inliner, this is the only way to make it not crash when attempting to inline these stubs. Note that the IR backend does not currently use the inliner's default method stub handling; the crash only occurs when a module compiled with the non-IR JVM backend is attempting to call an inline function with default arguments defined in a module that was compiled with the IR backend.
> JVM_IR: never create temporaries in $default stubs

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/DeclarationOrigins.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/CoroutineCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/coroutines/localFunctions/named/rec.kt
The arguments are null whenever the suspend function is resumed
and takes its state from the continuation parameter.
> JVM_IR: Do not generate null checks for suspend function views.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/testData/codegen/boxAgainstJava/visibility/protectedAndPackage/protectedAccessor.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxAgainstJavaCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxAgainstJavaCodegenTestGenerated.java
Class B : A cannot access a protected field of A through a reference to an instance of C : A.
> JVM_IR: add accessors for protected members in divergent hierarchies

- compiler/backend/src/org/jetbrains/kotlin/codegen/coroutines/CoroutineTransformerMethodVisitor.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/optimization/common/Util.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/coroutines/debug/multipleSuspendCallsOnSameLine.kt
- compiler/testData/codegen/box/coroutines/debug/throwsOnSameLine.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
Take branching and method calls into account when finding the line
number of the continuation. If there is no line number before
branching instructions or method calls, the following code is
still on the line of the suspend call itself.
This fixes a couple of issues with incorrect line numbers for
multiple throws on the same line or multipe suspend calls on
the same line.
In addition, it avoids the need to spam the method node with
repeated line number instructions in the IR backend.
> JVM: Improve line number handling for suspend calls.

- idea/formatter/src/org/jetbrains/kotlin/idea/formatter/KotlinCommonBlock.kt
- idea/testData/formatter/ElvisInStringTemplate.after.kt
- idea/testData/formatter/ElvisInStringTemplate.kt
- idea/tests/org/jetbrains/kotlin/formatter/FormatterTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-34049
> KT-34049 Formatter breaks string inside template expression with elvis operator

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/HeaderProcessor.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/ProgressionHandlers.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/Utils.kt
This broke the K/N build which validates IR types (reported by @vvlevchenko).
> Fix type of IllegalArgumentException call for illegal step in StepHandler

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AnonymousObjectSuperConstructorLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SingleAbstractMethodLowering.kt
- compiler/testData/codegen/boxInline/anonymousObject/sam/anonymousObjectToSam.kt
- compiler/testData/codegen/boxInline/anonymousObject/superConstructorWithObjectParameter.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
The SAM case was spotted while trying to compile RxKotlin; the object super constructor case is currently broken in the non-IR backend (see KT-21781).
> JVM_IR inliner fixes: anonymous objects as anonymous object constructor parameters

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendContext.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendFacade.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmIrCodegenFactory.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSymbols.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/CollectionStubMethodLowering.kt
- compiler/testData/loadJava/compiledKotlin/coroutines/Basic.kt
- compiler/testData/writeSignature/callableReference/suspendFunctionReference.kt
We recently saw a performance regression after merging #2657 on a small benchmark where deserializing `java.lang.String` ended up being a bottleneck. There are currently several symbols in JvmSymbols which we hardcode and some which are deserialized from disk instead (and in Fir mode we always have to hardcode all dependencies).
This PR makes JvmSymbols consistent by hardcoding all dependencies for the IR backend, which results in slightly better performance and allows us to remove the special cases for the Fir backend.
> JVM IR: Avoid getTopLevelClass for performance and Fir

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/MethodInliner.kt
- compiler/testData/codegen/boxInline/capture/captureInlinable.kt
- compiler/testData/codegen/boxInline/capture/captureInlinableAndOther.kt
- compiler/testData/codegen/boxInline/lambdaTransformation/regeneratedLambdaName.kt
Part of #2643, sort of. This used to be fixed with a patch to `ParametersBuilder`, but it turns out the root cause of the bug is much simpler: primitive-typed captures were not replaced with `$$$$something` placeholders.
> JVM_IR: fix load check in inliner (should accept primitives too)

- compiler/fir/resolve/tests/org/jetbrains/kotlin/fir/FirDiagnosticsSmokeTestGenerated.java
- compiler/frontend/src/org/jetbrains/kotlin/types/expressions/ExpressionTypingVisitorForStatements.java
- compiler/testData/diagnostics/tests/inference/genericAssignmentOperator.kt
- compiler/testData/diagnostics/tests/inference/genericAssignmentOperator.txt
- compiler/tests/org/jetbrains/kotlin/checkers/DiagnosticsTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/checkers/javac/DiagnosticsUsingJavacTestGenerated.java
Right now, we typecheck the right hand side of assignment operators  `x += 1` twice if the left hand side is an assignable lvalue. This can lead to exponential slowdowns in some cases, i.e.,
```kotlin
fun main() {
var x = 0
x += try {
x += try {
x += ...
x
} finally {}
x
} finally {}
}
```
In simple cases we can avoid this by typechecking the right hand side before resolution. Note that typechecking `+=` is still slow, though, since there are so many resolution candidates for `plusAssign` in the standard library.
> Frontend: Avoid retypechecking the right hand side of assignment operators

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/MethodInliner.kt
- compiler/testData/codegen/box/unsignedTypes/unsignedRangeIterator.kt
- compiler/testData/codegen/boxInline/simple/captureAndArgumentIncompatibleTypes.kt
- compiler/testData/codegen/bytecodeText/boxingOptimization/unsignedRangeIteratorSpecialization.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
For example, a lambda `{ param -> captured }` of type `E.(T) -> U` will be transformed by LocalDeclarationsLowering into a private static method
fun f$lambda-0($this: E, $captured: U, param: T) = $captured
The reason for such an ordering is that a lambda looks the same as a local function, and local function can have default arguments, and those arguments can reference captured variables; thus, captured variables must come before actual declared arguments.
However, this is not the order that the inliner wants. Moreover, since it was written to handle lambdas represented as `invoke` methods of anonymous objects, it does not expect the actual callable method to have any parameters corresponding to captured variables at all. This results in it attempting to generate a temporary node with …
> JVM_IR: move lambda captures to end of signature when inlining

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/HeaderInfo.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/HeaderProcessor.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/ProgressionHandlers.kt
- compiler/testData/codegen/box/ranges/forInCharSequenceWithCustomIterator.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
We only want to handle the known extension function for `CharSequence` in the standard library (top level `kotlin.text.iterator`). The behavior of this iterator is well-defined and can be lowered. `CharSequences` can have their own iterators, either as a member or extension function, and the behavior of those custom iterators is unknown.
> Ensure ForLoopsLowering only handles the CharSequence.iterator() stdlib extension function

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/MainMethodGenerationLowering.kt
- compiler/testData/codegen/bytecodeText/parameterlessMain/dontGenerateOnJvmNameMain.kt
- compiler/testData/codegen/bytecodeText/parameterlessMain/dontGenerateOnJvmOverloads.kt
- compiler/testData/codegen/bytecodeText/parameterlessMain/dontGenerateOnMain.kt
- compiler/testData/codegen/bytecodeText/parameterlessMain/dontGenerateOnMainExtension.kt
- compiler/testData/codegen/bytecodeText/parameterlessMain/dontGenerateOnNullableArray.kt
- compiler/testData/codegen/bytecodeText/parameterlessMain/dontGenerateOnVarargsString.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
Resolves the interaction of @JvmOverloads annotations and
parameterless main methods.
In the following code, both mechanisms generate methods that
ultimately produce the signature `public static void main(String[] args)`
of which there can be only one (true in general of any signature).
```
fun main() { }
@JvmOverloads
fun main(Array<String> args, x: Int = 42) { }
```
This PR simply shuffles the lowerings around, letting parameterless
main methods detect the presence of the default overload produced by
the annotation.
Additionally, this PR improves the testing of parameterless main
methods by actual bytecode patterns, and not simple check for
successful compilation (as @sfs and I discovered, there are issues in
flagging an error on duplicate signatures on the IR backend).
> [JVM IR] Fix @JvmOverloads + Parameterless Main

- compiler/ir/backend.common/src/org/jetbrains/kotlin/ir/builders/declarations/declarationBuilders.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/MethodSignatureMapper.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/MemoizedInlineClassReplacements.kt
- compiler/testData/compileKotlinAgainstKotlin/inlineClassInlineProperty.kt
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstKotlinTestGenerated.java
Since the inliner uses descriptors to identify external declarations we need to preserve PropertyGetter/SetterDescriptors in the IR backend.
This hit the inline class lowering, which replaces getters/setters with new static functions inside of inline classes. I've not found any other places where this is broken so far, but there is a comment in the IR `MethodSignatureMapper` that we sometimes lose `correspondingPropertySymbols` in the IR backend. Should this happen for external inline properties we'll run into a `NullPointerException` in the inliner (which has nothing to do with this PR, though).
> JVM IR: Fix inlining of inline class properties in external modules

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrUtils.kt
- compiler/testData/codegen/box/jvmName/functionWithDefault.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
Technically a backwards compatibility problem, as the new backend *consistently* renamed `f$default` on `f` with `@JvmName("g")` to `g` instead of `g$default`, so it all worked out. However, this breaks when encountering libraries compiled with the non-IR backend.
> JVM_IR: keep the $default suffix for stubs for @JvmName functions

- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/ExpectDeclarationRemover.kt
- compiler/testData/codegen/boxAgainstJava/multiplatform/annotationsViaActualTypeAliasFromBinary.kt
- compiler/testData/compileKotlinAgainstKotlin/expectClassActualTypeAlias.kt
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstKotlinTestGenerated.java
May happen when a function in an `expect` class is aliased through an `actual typealias`; the matching declaration is filtered out in `ExpectedActualResolver.findActualForExpected` as it has no source.
> IR: don't attempt to move defaults to `actual` in another module

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/IrUtils.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/AbstractSuspendFunctionsLowering.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/DefaultArgumentStubGenerator.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/ProgressionHandlers.kt
- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/lower/ClassReferenceLowering.kt
- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/lower/ConstLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendFacade.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSymbols.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrTypeMapper.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/descriptors/SharedVariablesManager.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AssertionLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/CallableReferenceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/EnumClassLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/MappedEnumWhenLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/types/irTypes.kt
This is yet another step towards enabling type checking in the jvm ir backend (this came up in the discussion for #2760).
> IR type fixes

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/testData/codegen/box/vararg/notInLastPosition.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
Fun fact: this is not actually validated when loading the class; and even when compiling a java file against a class file that does this, only javac 9 has a check (1.8 and before simply crashes with NullPointerException somewhere deep inside the compiler).
> JVM_IR: do not set ACC_VARARGS if vararg is not the last parameter

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LowerUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/DeclarationOrigins.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/descriptors/JvmDeclarationFactory.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmStaticAnnotationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/MoveCompanionObjectFieldsLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/ObjectClassLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SingletonReferencesLowering.kt
- compiler/testData/codegen/box/objects/interfaceCompanion.kt
- compiler/testData/codegen/box/objects/interfaceCompanionObjectReference.kt
- compiler/testData/codegen/box/objects/selfReferenceToInterfaceCompanionObjectInInlineLambdaInConstructorBody.kt
* When referencing the companion itself, they should use the $$INSTANCE field, not the (null until \<clinit\> returns) Companion field of the interface.
* Interface companion init blocks should be made static.
> JVM_IR: fix NPE in interface companion initializers

- libraries/tools/kotlin-gradle-plugin/build.gradle.kts
Details - https://github.com/michel-kraemer/gradle-download-task/issues/143
Otherwise - no loading progress log
> Gradle 6.0.1 support. Fix Yarn loading progress logging

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/BridgeLowering.kt
- compiler/testData/codegen/box/specialBuiltins/removeSetInt.kt
If there is a concrete method that will have its argument types
remapped to boxed types, make sure to reflect that in the IR so
that code will be generated for a boxed value instead of a
primitive value.
> JVM_IR: More special bridge rewriting.

- compiler/testData/debug/localVariables/destructuringInLambdas.kt
- compiler/testData/debug/localVariables/localFun.kt
- compiler/testData/debug/localVariables/underscoreNames.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/debugInformation/AbstractDebugTest.kt
Keep time out to avoid network related issue interrupt test, but add a retry in case a given timeout is still not sufficient.
Also handle the case where bad code cause test exit test method while keeping test process in suspended state.
> debug information test: handle virtualMachine timeout

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/ProgressionHandlers.kt
- compiler/testData/codegen/box/controlStructures/forInCharSequenceWithIndex/forInCharSequenceTypeParameterWithIndex.kt
- compiler/testData/codegen/box/controlStructures/forInIterableWithIndex/forInIterableTypeParameterWithIndex.kt
- compiler/testData/codegen/box/controlStructures/forInSequenceWithIndex/forInSequenceTypeParameterWithIndex.kt
- compiler/testData/codegen/bytecodeText/forLoop/forInIterableWithIndex/forInIterableTypeParameterWithIndex.kt
- compiler/testData/codegen/bytecodeText/forLoop/forInSequenceWithIndex/forInEmptySequenceWithIndex.kt
- compiler/testData/codegen/bytecodeText/forLoop/forInSequenceWithIndex/forInSequenceTypeParameterWithIndex.kt
- compiler/testData/codegen/bytecodeText/forLoop/forInSequenceWithIndex/forInSequenceWithIndex.kt
- compiler/testData/codegen/bytecodeText/forLoop/forInSequenceWithIndex/forInSequenceWithIndexNoElementVar.kt
- compiler/testData/codegen/bytecodeText/forLoop/forInSequenceWithIndex/forInSequenceWithIndexNoIndexVar.kt
- compiler/testData/codegen/bytecodeText/forLoop/forInSequenceWithIndex/forInSequenceWithIndexThrowsCME.kt
- compiler/testData/codegen/bytecodeText/forLoop/forInSequenceWithIndex/forInSequenceWithIndexWithExplicitlyTypedIndexVariable.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
TODO: Handle Sequences by extending DefaultIterableHandler.
> ForLoopsLowering: Handle Iterable.withIndex() where the type is a bounded type parameter.

- idea/src/org/jetbrains/kotlin/idea/inspections/SortModifiersInspection.kt
- idea/testData/inspectionsLocal/sortModifiers/annotation.kt
- idea/testData/inspectionsLocal/sortModifiers/annotation.kt.after
- idea/testData/inspectionsLocal/sortModifiers/annotationGroup.kt
- idea/testData/inspectionsLocal/sortModifiers/annotationGroup.kt.after
- idea/testData/inspectionsLocal/sortModifiers/simple.kt
- idea/testData/inspectionsLocal/sortModifiers/simple.kt.after
- nj2k/nj2k-services/src/org/jetbrains/kotlin/nj2k/postProcessing/J2kPostProcessor.kt
- nj2k/testData/newJ2k/postProcessing/SortModifiers.java
- nj2k/testData/newJ2k/postProcessing/SortModifiers.kt
- nj2k/tests/org/jetbrains/kotlin/nj2k/NewJavaToKotlinConverterSingleFileTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-32551
> KT-32551 New J2K: Non-canonical modifiers order inspection is not applied during convertion of inner super class

- libraries/stdlib/src/kotlin/random/XorWowRandom.kt
This commit changes XorWowRandom.kt documentation to include a HTTPS link instead of a HTTP link, for security purposes.
This commit also changes the same documentation to reflect the real cycles from the `xorwow` algorithm:
Simple and very fast (125 million/sec), the elements in its cycle of 2^192 − 2^32 easily pass all the tests in Diehard.
Marsaglia, G. 2003. Xorshift RNGs. J. Statis. Soft. 8, 14, p. 5
At last, this commit explicits which part of the code is the implementation of the mentioned algorithm.
Closes KT-35175
> KT-35175 Clarify documentation for XorWowRandom

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrTypeMapper.kt
- compiler/testData/writeSignature/annotations/kArrayClassOfKClass.kt
- compiler/testData/writeSignature/annotations/kClassOfKClass.kt
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrWriteSignatureTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/jvm/compiler/WriteSignatureTestGenerated.java
- core/descriptors.jvm/src/org/jetbrains/kotlin/load/kotlin/TypeMappingMode.kt
- core/descriptors.jvm/src/org/jetbrains/kotlin/load/kotlin/typeSignatureMapping.kt
* JVM incorrectly mapped T<KClass<...>> to T<Class<...>> because the annotation-ness of the type mapping mode was inherited one level down into a generic signature independent of T
* JVM_IR was even worse as it did not use VALUE_FOR_ANNOTATION at all, mapping T<T<KClass<...>> to T<T<Class<...>> as well.
The correct behavior is to map KClass to Class only at top level or as an argument of Array.
> JVM/JVM_IR: fix mapping of KClass in annotation classes

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InterfaceDelegationLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/IrUtils.kt
- compiler/testData/codegen/box/super/interfaceHashCode.kt
- compiler/testData/codegen/bytecodeText/hashCode/interfaceHashCode.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
This works on HotSpot, but might confuse other VMs.
> JVM_IR: do not do invokeinterface on Object methods

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/TailrecLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmTailrecLowering.kt
- compiler/testData/codegen/box/diagnostics/functions/tailRecursion/defaultArgsWithSideEffectsOld.kt
Before 1.4 tailrec function default arguments were evaluated
right-to-left instead of left-to-right. This is controlled
by a compile-time flag. This change adds support for the
right-to-left evaluation order when that flag is not set.
> JVM_IR: Backwards compatible handling of default tailrec params.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/testData/writeFlags/function/constructors/localClass.kt
- compiler/tests/org/jetbrains/kotlin/codegen/flags/WriteFlagsTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrWriteFlagsTestGenerated.java
They are accessible through reflection
> JVM_IR: make constructors of named local classes public

- idea/src/org/jetbrains/kotlin/idea/inspections/SuspiciousCollectionReassignmentInspection.kt
https://youtrack.jetbrains.com/issue/KT-31967
> KT-31967 Typo in inspection name: "'+=' create new list under the hood"

- idea/src/org/jetbrains/kotlin/idea/quickfix/ExclExclCallFixes.kt
- idea/testData/quickfix/addExclExclCall/implicit2.kt
- idea/testData/quickfix/addExclExclCall/implicit2.kt.after
- idea/testData/quickfix/addExclExclCall/implicit3.kt
- idea/testData/quickfix/addExclExclCall/implicit3.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-34894
> KT-34894 Action "Add not-null asserted (!!) call" doesn't fix error for properties with omitted `this`

- idea/src/org/jetbrains/kotlin/idea/inspections/JavaMapForEachInspection.kt
- idea/testData/inspectionsLocal/javaMapForEach/destructuringDeclaration.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-34511
> KT-34511 kotlin.KotlinNullPointerException after using intention Replace Java Map.forEach with Kotlin's forEach for Map with Pairs as keys

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrInlineReferenceLocator.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FakeInliningLocalVariablesLowering.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/ir/AbstractIrCheckLocalVariablesTableTest.kt
The debugger [looks for marker variables](https://github.com/JetBrains/kotlin/blob/0b7c11c96e844488dff632763cd6d64377274b99/idea/jvm-debugger/jvm-debugger-core/src/org/jetbrains/kotlin/idea/debugger/debuggerUtil.kt#L60) of the form `$i$a$-functionName-lambdaClassName` to determine whether we are inside of an inline argument, where `lambdaClassName` is the name which would have been generated for the class implementing the argument lambda.
This PR implements the same naming convention in the IR backend (which is simple, since the work is already done in `InventNamesForLocalClasses`).
Note that the PR doesn't fix any new tests, it just makes some existing tests more strict.
> JVM IR: Fix names of fake local variables for inline arguments

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LocalDeclarationsLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/CallableReferenceLowering.kt
- compiler/testData/debug/stepping/callableReference.kt
- compiler/testData/debug/stepping/inlineCallableReference.kt
- compiler/testData/debug/stepping/inlineNamedCallableReference.kt
- compiler/testData/debug/stepping/namedCallableReference.kt
- compiler/testData/lineNumber/custom/functionCallWithLambdaParam.kt
- compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/IrSteppingTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/SteppingTestGenerated.java
In particular, there should be no line numbers in the constructor of a callable reference, since otherwise the debugger (smart) steps into the constructor, which is pretty jarring.
> JVM IR: Fix line numbers in callable reference classes

- idea/idea-core/src/org/jetbrains/kotlin/idea/core/psiModificationUtils.kt
- idea/testData/inspectionsLocal/removeCurlyBracesFromTemplate/necessaryBrackets8.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-35475
> KT-35475 Applying intention "Redundant curly braces in string template" for label references change semantic

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/MemoizedInlineClassReplacements.kt
- compiler/testData/codegen/box/inlineClasses/defaultWithInlineClassArgument.kt
- compiler/testData/codegen/box/reflection/lambdaClasses/reflectOnDefaultWithInlineClassArgument.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
>  JVM_IR: do not copy defaults in functions with inline class parameters

- idea/src/org/jetbrains/kotlin/idea/quickfix/AddModifierFix.kt
- idea/testData/quickfix/modifiers/openCompanionObject.kt
- idea/testData/quickfix/modifiers/openCompanionObject.kt.after
- idea/testData/quickfix/modifiers/openCompanionObject2.kt
- idea/testData/quickfix/modifiers/openCompanionObject2.kt.after
- idea/testData/quickfix/modifiers/openObject.kt
- idea/testData/quickfix/modifiers/openObject.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-35604
> KT-35604 Too long quickfix message for "modifier 'open' is not applicable to 'companion object'"

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/DefaultArgumentStubGenerator.kt
- compiler/testData/compileKotlinAgainstKotlin/delegatedDefault.kt
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstKotlinTestGenerated.java
interface I {
fun f(x: Int = 1)
}
class C(val y: I) : I by y {
// implicit `override fun f(x: Int) = y.f(x)` has a default value for `x`
}
-- the only case where a function with overridden symbols has defaults.
> IR: work around a bug in interface delegation descriptors

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmDefaultParameterInjector.kt
- compiler/testData/codegen/box/inlineClasses/unboxParameterOfSuspendLambdaBeforeInvoke.kt
Whenever we want the default 0/null value for a type we need to
check if it is a non-nullable inline class type and produce
the right value for the underlying type.
> JVM_IR: deal with inline class arguments in AddContinuationLowering

- nj2k/src/org/jetbrains/kotlin/nj2k/conversions/JavaAnnotationsConversion.kt
- nj2k/testData/newJ2k/annotations/java9Deprecated.java
- nj2k/testData/newJ2k/annotations/java9Deprecated.kt
- nj2k/tests/org/jetbrains/kotlin/nj2k/NewJavaToKotlinConverterSingleFileTestGenerated.java
For any @Deprecated with parameters, unconditionally changing it to @Deprecated("") in kotlin.
> KT-20120 fixing bug for Java 9 Deprecated

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/IrUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/CoroutineCodegen.kt
- compiler/testData/codegen/box/coroutines/reflect/callSuspendBy.kt
This is important for calls using reflection as the reflect
library assumes this ordering of arguments.
It would be nice if this could be handled in the lowerings.
Currently AddContinuationLowering is after
DefaultArgumentStubGenerator. If we could add the continuation
first and then do default stub generation maybe we could avoid
the reshuffling introduced in coroutine codegen in this change.
> JVM_IR: Put continuation parameter before default mask and handler.

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/IrInlineUtils.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/IrUtils.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/ArrayConstructorLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AssertionLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/CallableReferenceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InterfaceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/StaticDefaultFunctionLowering.kt
- compiler/testData/codegen/boxInline/nonLocalReturns/fromInterfaceDefaultGetter.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrNonLocalReturnsTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/NonLocalReturnsTestGenerated.java
Also,
1. remove some redundant copies;
2. fix remapping of non-local returns in lambdas if the body is moved after LocalDeclarationsLowering (the lambda is no longer inside the body, but must still be visited)
> IR: unify 3 copies of function body remapping

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
Otherwise, should the local coincide with another one, the incorrect range causes D8 to generate invalid bytecode in debug mode.
> JVM_IR: mark the exception local as live only after the store

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/MemoizedInlineClassReplacements.kt
> JVM_IR: patch parents of defaults in MemoizedInlineClassReplacements

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LocalDeclarationsLowering.kt
- compiler/testData/codegen/box/coroutines/tailCallOptimizations/innerObjectRetransformation_ir.txt
- compiler/testData/codegen/bytecodeText/mangling/parentheses.kt
If parent is an anonymous object that could lead to the use
of names such as `$this$no name provided` which is invalid
in dex files.
> JVM_IR: Avoid using parent name in name of captures.

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/IrUtils.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/DefaultArgumentStubGenerator.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/MemoizedInlineClassReplacements.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrDeclarationOrigin.kt
- compiler/testData/codegen/box/parametersMetadata/inlineClassMethodParameterModifiers.kt
- compiler/testData/codegen/box/parametersMetadata/inlineClassMethodParameterNames.kt
- compiler/testData/codegen/box/reflection/callBy/inlineClassFunctionsAndConstructors.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
When called by reflection the bit mask will be generated
discounting dispatch/extension receivers. Make sure that the
interpretation of the bit mask is consistent for direct and
reflective calls.
> JVM_IR: Fix default argument bit mask for methods made static.

- compiler/testData/codegen/bytecodeText/mangling/parentheses.kt
Do not check for occurrences of "this" on the current backend.
I accidentally unified the checking for the two backends
without checking that it worked (used the wrong test suite to
test).
> Fix test expectations.

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/MethodInliner.kt
- compiler/testData/codegen/boxInline/reified/nonCapturingObjectInLambda.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
The only case where this code is reachable at all is objects in lambdas that use reified type parameters of the outer inline function. Since the type parameters are declared outside the inlining root, regenerating the object is actually pointless, and remapping its captures even more so (not to mention that the code under the condition uses the captures of the lambda, not of the method it's currently transforming).
> JVM_IR: do not remap locals in contexts nested inside lambdas

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/bridges/kt1959.kt
- compiler/testData/codegen/box/bridges/overrideAbstractProperty.kt
- compiler/testData/codegen/box/elvis/kt6694ExactAnnotationForElvis.kt
- compiler/testData/codegen/box/functions/functionExpression/functionExpressionWithThisReference.kt
- compiler/testData/codegen/box/javaInterop/notNullAssertions/nullableTypeParameter.kt
- compiler/testData/codegen/box/regressions/noAssertionsWhenNullableTypeParameterReplacedWithIntersectionType.kt
- compiler/testData/codegen/box/statics/inheritedPropertyInObject.kt
- compiler/testData/compileKotlinAgainstKotlin/useDeserializedFunInterface.kt
Instead, determine whether the return type of a call is Nothing, by looking at the type of the call expression.
CC @kandersen
> JVM IR: Remove type substitutions from ExpressionCodegen

- idea/src/org/jetbrains/kotlin/idea/inspections/CanBeParameterInspection.kt
- idea/testData/inspections/canBeParameter/test.kt
https://youtrack.jetbrains.com/issue/KT-34686
> KT-34686 False positive "Constructor parameter is never used as a property" if property is used as a reference

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmOptimizationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/PropertiesToFieldsLowering.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/transformations/InsertImplicitCasts.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/IrUtils.kt
- compiler/testData/codegen/bytecodeText/accessorForOverridenVal.kt
- compiler/testData/codegen/bytecodeText/constants/noInlineNonConst.kt
- compiler/testData/codegen/bytecodeText/kt3845.kt
Final default properties accessors that access a backing field
on the same class can be replaced by direct field use.
Perform the optimization late in the pipeline to allow lowerings
to expose more opportunities for optimizations.
> JVM_IR: Use direct field access instead of calling certain accessors.

- idea/idea-gradle/src/org/jetbrains/kotlin/idea/configuration/KotlinGradleWebMultiplatformModuleBuilder.kt
The path of the webpacked JavaScript file that should be included in the server JAR is constructed by taking the webpack tasks output directory, and appending the filename of the JavaScript module. Previously, the constructor arguments were flipped, leading to an invalid path.
Furthermore, I migrated away from the deprecated `outputPath` property, to the recommended `destinationDirectory` property.
I verified that the code was not working previously, but is working as expected with the suggested changes.
> Fix file components order

- build.gradle.kts
- compiler/testData/codegen/box/classes/quotedClassName.kt
- compiler/testData/codegen/box/localClasses/nameWithWhitespace.kt
- compiler/tests-common/build.gradle.kts
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/CodegenTestCase.java
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/D8Checker.java
- compiler/tests/org/jetbrains/kotlin/codegen/TestStdlibWithDxTest.kt
This change adds D8 in addition to Dx which is being deprecated.
At some point after the official Dx deprecation, we should remove
the Dx checker.
Moving to D8 has the additional benefit that D8 can dex code
using java 8 features without using a separate desugaring tool.
> JVM: Add D8 check that class files can be dexed with D8.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrInlineReferenceLocator.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/CallableReferenceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FakeInliningLocalVariablesLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InlineCallableReferenceToLambda.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/testData/codegen/boxAgainstJava/visibility/protectedAndPackage/protectedPropertyInPackageFromCrossinline.kt
- compiler/testData/codegen/boxInline/syntheticAccessors/withinInlineLambda/protectedMembersFromSuper.kt
- compiler/testData/codegen/bytecodeText/noAccessorForProtectedInSamePackageCrossinline.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxAgainstJavaCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxAgainstJavaCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
References to protected members from crossinline lambdas in the same package do not need accessors.
> JVM_IR: further refine synthetic accessor generation

- core/reflection.jvm/src/kotlin/reflect/jvm/internal/EmptyContainerForLocal.kt
For example, this exception can be triggered by the following snippet:
```kotlin
data class Test(
val field: String
)
typealias TestAlias = Test
fun main(args: Array<String>) {
println(::TestAlias)
}
```
with no local functions, lambdas, anonymous functions or local variables in sight.
> Update message on KotlinReflectionInternalError to reflect that typeliases are also unsupported

- idea/src/org/jetbrains/kotlin/idea/highlighter/KotlinSuspendCallLineMarkerProvider.kt
- idea/testData/inspectionsLocal/redundantSuspend/parenthesized.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-24869
> KT-24869 False positive inspection "Redundant 'suspend' modifier"

- idea/testData/refactoring/rename/renameKotlinFunctionInGenericClass/after/RenameKotlinFunctionInGenericClass.kt
- idea/testData/refactoring/rename/renameKotlinFunctionInGenericClass/before/RenameKotlinFunctionInGenericClass.kt
- idea/testData/refactoring/rename/renameKotlinFunctionInGenericClass/renameKotlinFunctionInGenericClass.test
- idea/testData/refactoring/rename/renameKotlinFunctionInGenericClass/renameKotlinFunctionInGenericClassFromSubclass.test
- idea/tests/org/jetbrains/kotlin/idea/refactoring/rename/RenameTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-26047
> KT-26047 Refactor -> Rename: Overridden method renaming in generic class doesn't rename base method

- idea/src/org/jetbrains/kotlin/idea/inspections/SelfReferenceConstructorParameterInspection.kt
- idea/testData/inspectionsLocal/selfReferenceConstructorParameter/vararg.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-36160
> KT-36160 False positive "Constructor has non-null self reference parameter" with vararg parameter of class

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/InlineCodegen.kt
- compiler/testData/codegen/bytecodeText/storeStackBeforeInline/simple.kt
`dx` has entered the final stage of sunset:
https://android-developers.googleblog.com/2020/02/the-path-to-dx-deprecation.html
> KT-20844 Re-enable stack spilling during inline.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/testData/codegen/box/reflection/genericSignature/suspendFunctionLiteralGenericSignature.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
The generic signatures of the `Function<n>` interface implemented by suspend lambdas should always use a return type of `Object`.
This brings the behavior in line with the JVM backend, although I think we might be generating wrong generic signatures for function types to begin with. Based on the variance declarations in Kotlin, we should be generating signatures of the form `Function1<? super java.lang.Integer, ? extends java.lang.Integer>` for a function `(Int) -> Int`, yet we actually generate invariant type arguments `Function1<java.lang.Integer, java.lang.Integer>`.
> JVM IR: Fix suspend lambda generic signatures

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/BridgeLowering.kt
- compiler/testData/codegen/box/coroutines/bridges/interfaceSpecialization.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
`invoke` in suspend lambdas overrides FunctionN.invoke, so the refactored BridgeLowering already generates correct bridges there. All the hack does is break overrides of interface suspend methods.
> JVM_IR: remove a suspend-related hack from BridgeLowering

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AssertionLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InterfaceLowering.kt
- compiler/testData/codegen/bytecodeText/assert/jvmNestedClass.kt
It should be package private, as stated in `compiler/testData/codegen/bytecodeText/assert/jvmNestedClass.kt`.
> JVM IR: Fix visibility for $assertionsDisabled fields

- idea/src/org/jetbrains/kotlin/idea/inspections/ReplaceToStringWithStringTemplateInspection.kt
- idea/testData/inspectionsLocal/replaceToStringWithStringTemplate/callExpression.kt
- idea/testData/inspectionsLocal/replaceToStringWithStringTemplate/callExpression.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-36735
> KT-36735 Inspection 'Replace 'toString' with string template' miss curly braces and generates wrong code for constructor calls

- idea/src/org/jetbrains/kotlin/idea/inspections/UnusedSymbolInspection.kt
- idea/testData/inspectionsLocal/unusedSymbol/secondaryConstructorCalledByTypeAlias.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-20907
> KT-20907 Secondary constructor is marked as unused by IDE when called by typealias 

- idea/src/org/jetbrains/kotlin/idea/refactoring/changeSignature/usages/KotlinFunctionCallUsage.kt
- idea/testData/quickfix/changeSignature/removeFunctionLastLambdaParameter.kt
- idea/testData/quickfix/changeSignature/removeFunctionLastLambdaParameter.kt.after
- idea/testData/refactoring/changeSignature/AddParameterAfterLambdaParameterAfter.kt
- idea/testData/refactoring/changeSignature/AddParameterAfterLambdaParameterBefore.kt
- idea/testData/refactoring/changeSignature/RemoveLambdaParameter2After.kt
- idea/testData/refactoring/changeSignature/RemoveLambdaParameter2Before.kt
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
- idea/tests/org/jetbrains/kotlin/idea/refactoring/changeSignature/KotlinChangeSignatureTest.kt
https://youtrack.jetbrains.com/issue/KT-23510
> KT-23510 "Remove parameter" quick fix keeps lambda argument when it's out of parentheses

- idea/idea-core/src/org/jetbrains/kotlin/idea/core/overrideImplement/OverrideImplementMembersHandler.kt
- idea/testData/quickfix/implement/dataClass.kt
- idea/testData/quickfix/implement/dataClass.kt.after
- idea/testData/quickfix/implement/dataClass2.kt
- idea/testData/quickfix/implement/dataClass2.kt.after
- idea/testData/quickfix/implement/dataClass3.kt
- idea/testData/quickfix/implement/dataClass3.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-36686
> KT-36686 Implement members quickfix puts the implementation *before* the data class if it already has a body

- compiler/ir/backend.common/src/org/jetbrains/kotlin/ir/util/IrTypeUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FunctionNVarargBridgeLowering.kt
Now that suspend function views are created in
AddContinuationLowering, we can let the
FunctionNVarargBridgeLowering deal with rewriting of large
arity FunctionN/SuspendFunctionN.
> [JVM_IR] Handle big arity suspend functions in existing lowering.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/CoroutineCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/testData/codegen/box/coroutines/suspendImplBridge.kt
- compiler/testData/codegen/box/coroutines/suspendReturningPlatformType.kt
- compiler/testData/codegen/box/coroutines/tailCallOptimizations/unit/functionReference.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
Otherwise:
* should the dispatch receiver of a call be another call to a `suspend fun` wrapped in something that is optimized away later, the owner of the method will be incorrect;
* references to functions returning non-Unit but casted to `() -> Unit` (allowed by new inference) might in fact not return Unit after tail call optimization.
> JVM_IR: keep `suspend fun` return type in IrCalls

- idea/idea-gradle/src/org/jetbrains/kotlin/idea/scripting/gradle/AsyncFileChangeListenerHelper.kt
- idea/idea-gradle/src/org/jetbrains/kotlin/idea/scripting/gradle/AsyncFileChangeListenerHelper.kt.201
isRelevant() method is a hotspot, as it is called for each file in bulk VFS event.
As there can be hundreds of files in each event, we should keep operations minimal.
> Reduce UI freezes by preparing affected Gradle project files lists in advance

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/BridgeLowering.kt
`mapAsmMethod` is somewhat slow, so this helps if there are a lot of overrides of same methods and/or deep class hierarchies in a single file (though it would probably help more if lowerings were not reconstructed for every file).
> JVM_IR: cache signatures in BridgeLowering

- idea/src/org/jetbrains/kotlin/idea/inspections/RedundantLetInspection.kt
- idea/testData/inspectionsLocal/simpleRedundantLet/extensionCall.kt
- idea/testData/inspectionsLocal/simpleRedundantLet/extensionCall.kt.after
- idea/testData/inspectionsLocal/simpleRedundantLet/extensionWithNullableReceiverCall.kt
- idea/testData/inspectionsLocal/simpleRedundantLet/extensionWithNullableReceiverCall2.kt
- idea/testData/inspectionsLocal/simpleRedundantLet/extensionWithNullableReceiverCall3.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-31601
> KT-31601 "Remove redundant let call" changes semantics by introducing multiple safe calls

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/MethodSignatureMapper.kt
- compiler/testData/codegen/boxInline/suspend/inlineSuspendInMultifileClass.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
Private $$forInline versions of public suspend functions should not be mangled. (Note that there are no $$forInline versions of private suspend functions, as those are effectively inline-only.)
> JVM_IR: refine the condition for mangling names of multifile members

- compiler/backend/src/org/jetbrains/kotlin/codegen/DelegationFieldsInfo.java
- compiler/backend/src/org/jetbrains/kotlin/codegen/ImplementationBodyCodegen.java
- compiler/testData/codegen/bytecodeListing/specialBridges/signatures/genericClass.txt
- compiler/testData/codegen/bytecodeListing/specialBridges/signatures/nonGenericClass.txt
- compiler/testData/codegen/bytecodeListing/specialBridges/signatures/partiallySpecializedClass.txt
The JVM IR backend already generates generic signatures on `$$delegate_n` fields and this PR changes the JVM backend to do the same.
There was a TODO comment from 2014 for this, so this is probably not very pressing. :)
> JVM: Generate generic signatures for delegate fields

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/testData/codegen/box/syntheticAccessors/superCallFromMultipleSubclasses.kt
- compiler/testData/codegen/boxInline/syntheticAccessors/superCallFromMultipleSubclasses.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
This was an interesting edge case where only one accessor was being generated for a target function within the same file, but it is possible to need multiple accessors for the same target function. See test data for examples.
> [JVM IR] Ensure there is one accessor for each `super` access from a subclass when there are multiple subclasses in a file

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendContext.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrInlineCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrSourceCompilerForInline.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/testData/codegen/boxInline/suspend/defaultParameter/defaultValueInClass.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrInlineSuspendTestsGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/InlineSuspendTestsGenerated.java
Which means the lowering should create them for inline lambdas as well (but leave the continuation parameter in references unbound).
Otherwise, should a lowering after AddContinuationLowering replace a view with a modified version, we will not consider the modified version to be a view and calling `getOrCreateSuspendFunctionViewIfNeeded` on it in the inliner will destroy it by adding a second continuation.
> JVM_IR: do not create suspend views outside of AddContinuationLowering at all

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/TailCallOptimizationLowering.kt
- compiler/testData/codegen/box/coroutines/unitTypeReturn/interfaceDelegation.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
Even if a function is known to be tail call because it's a compiler generated bridge, the tail return might still need to be added in case of Unit return type.
> JVM_IR: apply TailCallOptimizationLowering to all suspend functions

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InterfaceLowering.kt
- compiler/testData/codegen/box/defaultArguments/function/kt15971.kt
- compiler/testData/codegen/box/defaultArguments/function/kt15971_2.kt
- compiler/testData/codegen/box/defaultArguments/function/kt15971_3.kt
- compiler/testData/codegen/box/defaultArguments/function/kt36188.kt
- compiler/testData/codegen/box/defaultArguments/function/kt36188_2.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
The tests fail on JS (non-IR). Currently running tests on Native; not sure if this util function is used there.
> [JVM IR] Maintain KT-36188 bug compatibility between non-IR and IR backends

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/CoroutineCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InlineCallableReferenceToLambda.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/TailCallOptimizationLowering.kt
- compiler/testData/codegen/boxInline/suspend/callableReference/nonTailCall.kt
- compiler/testData/codegen/boxInline/suspend/callableReference/unitReturn.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java
Otherwise, the assumption that coroutine codegen makes about every inlined function already having the markers breaks and it is no longer true that calls to inline lambdas do not require them.
> JVM_IR: place suspend markers in faux lambdas around inline references

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmInlineClassLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/InlineClassAbi.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/MemoizedInlineClassReplacements.kt
- compiler/testData/codegen/bytecodeText/inlineClasses/mangledInlineClassInterfaceImplementation.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
Fixes [KT-37024](https://youtrack.jetbrains.com/issue/KT-37024).
> JVM IR: Mangle interface implementation methods in inline classes

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/testData/codegen/boxInline/syntheticAccessors/withinInlineLambda/protectedInCrossinline.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
Not sure how many more attempts I'll need to finally get this right.
> JVM_IR: fix accesses from crossinline lambdas in other packages

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/SMAP.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrSourceCompilerForInline.kt
- compiler/testData/codegen/boxInline/smap/smap.kt
- compiler/testData/codegen/bytecodeText/kt10259.kt
- compiler/testData/codegen/bytecodeText/kt10259_3.kt
- compiler/testData/lineNumber/custom/inTheEndOfLambdaArgumentOfInlineCall.kt
Otherwise, file mappings in the source map would be accumulated, resulting in consistent shifting of line numbers (as shown at `smap.kt` test).
> JVM_IR: use fresh source map when generating lambda body for inline.

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/utils.kt
Additional fix - only files with `js` extension processed (directories excluded)
`listFiles()` already contains 'is directory' check. Duplicated check removed
> KT-37240 Deterministic order for webpack config patches

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/MethodInliner.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/TransformationInfo.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LocalDeclarationsLowering.kt
- compiler/testData/codegen/boxInline/reified/nonCapturingObjectInLambda.kt
- compiler/testData/codegen/boxInline/reified/nonCapturingObjectInLambda.txt
- compiler/testData/codegen/boxInline/reified/nonCapturingObjectInLambda_ir.txt
- compiler/testData/codegen/bytecodeListing/coroutines/tcoContinuation_ir.txt
**Commit 1:**
All reified type parameters referenced by objects in non-default lambdas are from outside the inline call, thus they cannot be substituted yet. This means if the only reason for object regeneration is reification, then regeneration isn't actually necessary.
E.g. in this code:
inline fun <reified T> f(x: () -> Unit) = x()
inline fun <reified V> g() = f<V> { { println(V::class.simpleName) }() }
we first inline the lambda into f(), then inline f()-with-lambda into g(). Because the object inside the lambda captures nothing from outside g(), the original class can be used both times.
**Commit 2**:
Same thing, but instead of reified type parameters it's suspend lambdas: if the actual lambda to inline is not known yet (or will never be known because the inline root is not an inline …
> Do fewer unnecessary anonymous object regenerations

- libraries/stdlib/jvm/src/kotlin/io/Console.kt
- libraries/stdlib/jvm/test/io/Console.kt
There are several performance optimizations:
* ByteBuffer/CharBuffer/StringBuilder objects pre-allocated and are reused on each call to readLine.
* The state for readLine is lazily allocated via JVM classloading (using a singleton object).
* There is an auto-detection heuristic for "directEOL" encodings which represent LF ('\n') directly as the corresponding byte (UTF-8 and many single-byte encodings are like that). When "directEOL" encoding is used, then bytes are batched into ByteBuffer for a single call to CharsetDecoder.decode which results in higher throughput. Otherwise (UTF-16, etc), slower byte-by-byte approach is used.
* Bytes and chars are directly moved in/out of byte/char arrays and ByteBuffer/CharBuffer wrappers are used only to interface with JVM CharsetDecoder class (which …
> Speed up stdlib readLine function

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrConversionScope.kt
- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/testData/codegen/box/properties/classFieldInsideNestedLambda.kt
- compiler/testData/codegen/box/properties/classFieldInsideNestedNestedLambda.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
This is a follow-up of https://github.com/JetBrains/kotlin/pull/3220. Special thanks to @punzki
> FIR: consider all functions in scope when computing dispatch receiver parameter.

- idea/src/org/jetbrains/kotlin/idea/inspections/RedundantLambdaArrowInspection.kt
- idea/testData/inspectionsLocal/redundantLambdaArrow/typeParameter4.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-37502
> KT-37502 False positive "redundant lambda arrow" with inline generic function with reified type in object and anonymous parameter name

- idea/src/org/jetbrains/kotlin/idea/quickfix/SurroundWithLambdaFix.kt
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMatchSuspend.kt
- idea/testData/quickfix/typeMismatch/paramTypeLambdaMatchSuspend.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-34371
> KT-34371 "Surround with lambda" quickfix is not available for suspend lambda parameters.

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/SingleAbstractMethodLowering.kt
- compiler/testData/codegen/box/sam/nonInlinedSamWrapper.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
The wrappers for conversions to nullable and non-nullable SAM types are the same, so differentiating those has no effect other than class name collisions.
> JVM_IR: use non-nullable types as SAM super types

- plugins/scripting/scripting-compiler/src/org/jetbrains/kotlin/scripting/compiler/plugin/repl/ReplInterpreter.kt
Issue found while investigating https://youtrack.jetbrains.com/issue/KT-35925.
This fixes a *class not found* exception that happens when launching the autoconfiguration of Spring Boot from the REPL. It happens with JDK 11 but not with 1.8
This is the exception that is fixed:
```
Caused by: java.lang.NoClassDefFoundError: org/ietf/jgss/GSSContext
at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3197)
at java.base/java.lang.Class.getMethods(Class.java:1904)
at org.apache.tomcat.util.modeler.modules.MbeansDescriptorsIntrospectionSource.createManagedBean(MbeansDescriptorsIntr …
```
> Add the system classloader as a parent of ReplClassLoader

- compiler/fir/tree/src/org/jetbrains/kotlin/fir/declarations/FirDeclarationUtil.kt
Mistakes from 44c34ab8c37d2a3f81f9f96399759cc2e5a08b7b found by @punzki
> FIR: fix visibility extension for fake override.

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/inlineCodegenUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/CoroutineCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrSourceCompilerForInline.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/testData/codegen/box/coroutines/tailCallOptimizations/crossinline_ir.txt
- compiler/testData/codegen/boxInline/suspend/nonLocalReturn.kt
- compiler/testData/codegen/bytecodeText/coroutines/nonLocalReturn.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java
This should improve performance a bit, especially with nested hierarchies of anonymous objects/lambdas in suspend methods. Also, this fixes non-local returns from inline suspend functions, as currently they are remapped to `$$forInline` versions so the bytecode of the original is incorrect (this is only observable from Java or by tools like Proguard which complain about the nonexistent class `$$$$$NON_LOCAL_RETURN$$$$$`); the only alternative here is to worsen the performance even more by copying lambdas as well.
> JVM_IR: reuse IR for $$forInline versions of suspend funs

- compiler/backend/src/org/jetbrains/kotlin/codegen/FunctionCodegen.java
- compiler/backend/src/org/jetbrains/kotlin/codegen/coroutines/SuspendFunctionGenerationStrategy.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
- compiler/testData/codegen/bytecodeText/coroutines/effectivelyInlineOnly.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
Otherwise, the generated bytecode is unnecessarily suboptimal in some (arguably weird) cases.
In the JVM backend, this was an accidental regression in #3260, as I had not noticed that effectively inline-only functions were handled by a separate branch in FunctionCodegen. In JVM_IR, I'm pretty sure the redundant markers have always been there as `isSuspensionPoint` in ExpressionCodegen never checked for effectively-inline-only-ness.
> JVM: erase conditional suspension markers from inline-only functions

- build.gradle.kts
This PR fixes the zipPlugin task by:
1) **Removing the deprecated calls.** Previously, the zipPlugin task would consistently give the following error due do the deprecated calls on L805-806:
```
Could not create task ':zipPlugin'.
> path may not be null or empty string. path='null'
```
2) **Allowing the default destination path for an empty pluginZipPath argument.**  At L804, if destPath were null due to an empty `zipPluginPath` argument, a default path is used. The doFirst block at L807-809 prevents the default path from being used by error'ing prematurely on a null destPath. Therefore, the doFirst block is removed.
> Fix zipPlugin task

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DeclarationStubGenerator.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/ExternalDependenciesGenerator.kt
- compiler/testData/codegen/box/javaInterop/samUnboundTypeParameter.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
Without NewInference we sometimes generate unbound type parameters, which end up breaking at random points during lowering. This PR fixes the problem for the JVM IR backend. I'm not sure if the same thing can happen in the JS_IR or NATIVE backends, though.
> Psi2Ir: Bind unbound type parameters

- idea/src/org/jetbrains/kotlin/idea/inspections/ConstantConditionIfInspection.kt
- idea/testData/inspectionsLocal/constantConditionIf/endWithElseIf2.kt
- idea/testData/inspectionsLocal/constantConditionIf/endWithElseIf2.kt.after
- idea/testData/inspectionsLocal/constantConditionIf/expressionElseIfBlock2.kt
- idea/testData/inspectionsLocal/constantConditionIf/expressionElseIfBlock2.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-34713
> KT-34713 "Condition is always 'false'": quickfix "Delete expression" doesn't remove `else` keyword (may break control flow)

- idea/src/org/jetbrains/kotlin/idea/intentions/branchedTransformations/intentions/WhenToIfIntention.kt
- idea/testData/intentions/branched/ifWhen/whenToIf/whenWithoutElseUsedAsExpression.kt
- idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-35329
> KT-35329 Replace 'when' with 'if' intention: do not suggest if 'when' is used as expression and it has no 'else' branch

- plugins/scripting/scripting-ide-services-test/test/org/jetbrains/kotlin/scripting/ide_services/ReplCompletionAndErrorsAnalysisTest.kt
- plugins/scripting/scripting-ide-services/src/org/jetbrains/kotlin/scripting/ide_services/compiler/impl/KJvmReplCompleter.kt
This PR fixes wrongly suggested variants after numeric, char and string literals in scripting REPL compiler with IDE services
> Fix scripting REPL completion after literals

- plugins/scripting/scripting-ide-services-test/test/org/jetbrains/kotlin/scripting/ide_services/ReplCompletionAndErrorsAnalysisTest.kt
- plugins/scripting/scripting-ide-services/src/org/jetbrains/kotlin/scripting/ide_services/compiler/impl/KJvmReplCompleter.kt
Final expressions here are literals, "closed" function calls, expressions in brackets. Completion variants should not appear after them if they are not followed by by dot (.) or double colon (::).
Note that identifiers are not considered as final expressions.
> Fix REPL completion after "final" expressions

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/MethodSignatureMapper.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/BridgeLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/GenerateMultifileFacades.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmStaticAnnotationLowering.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ClassGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/DelegatedPropertyGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/PropertyGenerator.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DeepCopyIrTreeWithSymbols.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/PatchDeclarationParents.kt
- compiler/testData/codegen/bytecodeText/builtinFunctions/size.kt
This allows removing a hack in the MethodSignatureMapper.
When introducing non-getter methods that dispatch to a getter
we have to be careful to use the right name.
DeepCopyIrTreeWithSymbols should create the link between new
properties and their new getter/setter.
> Properly link properties and their getter/setters.

- idea/formatter/src/org/jetbrains/kotlin/idea/formatter/kotlinSpacingRules.kt
- idea/testData/formatter/BlankLinesAfterClassHeader.after.kt
- idea/testData/formatter/BlankLinesAfterClassHeader2.after.kt
- idea/testData/formatter/BlankLinesAfterClassHeader2.kt
- idea/tests/org/jetbrains/kotlin/formatter/FormatterTestGenerated.java
Fixes; https://youtrack.jetbrains.com/issue/KT-24750
When `Minimum Blank Line` -> `After class header` formatter setting changed, code formatter needs to respect new setting.
| Before | Minimum 1 | Minimum after header 5 and Max line 2 |
| - | - | - |
| <img width="739" alt="Screenshot 2020-03-25 at 15 10 07" src="https://user-images.githubusercontent.com/2559837/77566403-ab0c7b00-6ed6-11ea-94bb-859f8d1e0c2f.png"> | <img width="738" alt="Screenshot 2020-03-25 at 15 10 12" src="https://user-images.githubusercontent.com/2559837/77566417-afd12f00-6ed6-11ea-9207-22b7d397b029.png"> | <img width="736" alt="Screenshot 2020-03-25 at 15 10 31" src="https://user-images.githubusercontent.com/2559837/77566427-b495e300-6ed6-11ea-83e4-a4db50109c98.png"> |
> KT-24750 Blank line after class header formatter should use user setting

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/InliningContext.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/MethodInliner.kt
- compiler/testData/codegen/boxInline/suspend/twiceRegeneratedAnonymousObject.kt
- compiler/testData/codegen/boxInline/suspend/twiceRegeneratedSuspendLambda.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java
In general, `InliningContext.findAnonymousTransformationInfo` was not reliable because it mapped each type to *some* info for that type, preferring ones with `shouldRegenerate == true` if those exist. Thus, it returned incorrect results if one type was regenerated multiple times, e.g. in a nested inlining context or because of a `finally` (which duplicates anonymous objects). The solution is to avoid a global map and attach the current transformation info directly to the current inlining context.
> JVM: fix remapping of `new T` inside regenerated copies of `T`

- compiler/util-io/src/org/jetbrains/kotlin/konan/file/File.kt
- compiler/util-io/src/org/jetbrains/kotlin/konan/file/ZipUtil.kt
Build systems like bazel rely on the output of a compilation being
deterministic. File checksums determine when an artifact is safe to
cache across builds. One can produce a klib deterministically by using a
fixed timestamp during klib compression.
Before this change:
```
$ kotlinc-native  -produce library -output /tmp/first/color.klib Color.kt
$ kotlinc-native  -produce library -output /tmp/second/color.klib Color.kt
$ shasum  /tmp/first/color.klib /tmp/second/color.klib
bc3f73678ff025cfbec9009f9a851a8ca74e1037  /tmp/first/color.klib
65aa37886fbd53285f2e449a4dab6a2ad02732e6  /tmp/second/color.klib
```
After this change:
```
$ kotlinc-native  -produce library -output /tmp/first/color.klib Color.kt
$ kotlinc-native  -produce library -output /tmp/second/color.klib Color.kt
$ shasum …
```
> Produce deterministic klib files.

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/secondaryConstructors/fieldInitializerOptimization.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
Don't generate code to initialize fields to their default values in secondary constructors as well as in the primary constructor. This optimization is done by the JVM backend and has some observable effects.
Note that this currently fails on both JS backends.
CC @pyos
> JVM IR: Optimize field initializers in secondary constructors

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/bytecodeText/enum/enumCheckcasts.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
This is a small optimization to remove CHECKCAST instructions from Enum class initializers.
The background is that we had a bug with an internal tool which tries to parse the bytecode in an enum class initializer and looks for patterns such as 
```
LDC "C"
ICONST_2
ACONST_NULL
INVOKESPECIAL Foo$C.<init> (Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
<...>
PUTSTATIC Foo.C : LFoo;
```
We currently generate an unnecessary CHECKCAST instruction before the PUTSTATIC, which ended up breaking the tool.
I originally tried to fix this by just generating fewer CHECKCAST instructions in general (that was what #3171 was about), but doing this correctly is fairly complicated and expensive.
> JVM IR: Avoid unnecessary CHECKCASTs in enum classes

- compiler/backend/src/org/jetbrains/kotlin/codegen/FunctionCodegen.java
- compiler/backend/src/org/jetbrains/kotlin/codegen/ScriptCodegen.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/MethodInliner.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/inlineCodegenUtils.kt
- compiler/testData/codegen/bytecodeText/lineNumbers/stdlibInlineOnly.kt
- compiler/testData/codegen/bytecodeText/lineNumbers/stdlibInlineOnlyOneLine.kt
- compiler/testData/repl/evaluationErrors.repl
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
This makes the behavior of JVM and JVM_IR the same without having to deal with PSI nodes.
> JVM: move synthetic line number generation to the inliner

- libraries/kotlin.test/js/src/main/kotlin/kotlin/test/FrameworkAdapter.kt
The example code shows up all on one line in the generated docs.
https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/-framework-adapter/ shows
> suite('a suite', false, function() { suite('a subsuite', false, ...
This indents the code block by 4 spaces so that dokka recognizes it as such.  I believe [dokka supports indented code blocks](https://github.com/Kotlin/dokka/releases/tag/0.9.14) but have not regenerated the docs myself.
> Reformat example code in comment

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmInlineClassLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/builders/ExpressionHelpers.kt
- compiler/testData/codegen/box/inlineClasses/mangledSuperCalls.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
Specifically, super calls with inline class parameters were broken.
The PR also adds a test for this case. It's honestly surprising that we didn't have such a test already.
> JVM IR: Take superQualifierSymbols into account when lowering inline classes

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/KotlinNothingValueExceptionLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/coroutines/tailCallToNothing.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
Else they wouldn't be tail call, would they?
> JVM_IR: do not handle Nothing in suspend tail call bridges

- idea/idea-analysis/src/org/jetbrains/kotlin/idea/highlighter/KotlinHighlightingColors.java
https://youtrack.jetbrains.com/issue/KT-15143
> KT-15143 Kotlin: Colors&Fonts -> "Enum entry" should use Language Default -> Classes - Static field

- idea/src/org/jetbrains/kotlin/idea/refactoring/changeSignature/KotlinChangeSignatureProcessor.kt
- idea/testData/refactoring/changeSignature/MoveLambdaParameterToLastAfter.kt
- idea/testData/refactoring/changeSignature/MoveLambdaParameterToLastBefore.kt
- idea/tests/org/jetbrains/kotlin/idea/refactoring/changeSignature/KotlinChangeSignatureTest.kt
https://youtrack.jetbrains.com/issue/KT-30128
> KT-30128 Change Signature should move lambda outside of parentheses if the arguments are reordered so that the lambda goes last

- libraries/stdlib/common/src/generated/_UArrays.kt
- libraries/tools/kotlin-stdlib-gen/src/templates/Arrays.kt
- libraries/tools/kotlin-stdlib-gen/src/templates/Sequence.kt
- libraries/tools/kotlin-stdlib-gen/src/templates/dsl/MemberBuilder.kt
It's more common for a function to have the single sample, and it's more convenient to override it in `specialFor` blocks, rather than to append another one.
> Make 'sample' function overwrite samples list instead of adding

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmStaticAnnotationLowering.kt
- compiler/testData/codegen/bytecodeText/jvmStaticInternalMangling.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
Right now the same function gets mangled twice.
> JVM IR: Fix mangling of @JvmStatic internal function in companion objects

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrDeclarationStorage.kt
- compiler/fir/raw-fir/light-tree2fir/src/org/jetbrains/kotlin/fir/lightTree/fir/ClassWrapper.kt
- compiler/fir/raw-fir/psi2fir/src/org/jetbrains/kotlin/fir/builder/RawFirBuilder.kt
- compiler/fir/raw-fir/psi2fir/testData/rawBuilder/declarations/annotation.txt
- compiler/fir/raw-fir/psi2fir/testData/rawBuilder/declarations/constructorInObject.txt
- compiler/fir/raw-fir/psi2fir/testData/rawBuilder/declarations/enums.txt
- compiler/fir/raw-fir/psi2fir/testData/rawBuilder/declarations/enums2.txt
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/transformers/FirStatusResolveTransformer.kt
Based on `DescriptorUtils#getDefaultConstructorVisibility in core.descriptors`, the visibility for the default constructor is slightly updated to include enum entry as well.
> FIR: fix default constructor visibility for enum entry.

- libraries/stdlib/js-ir/src/kotlin/coroutines_13/IntrinsicsJs.kt
- libraries/stdlib/js-v1/src/kotlin/coroutines/intrinsics/IntrinsicsJs.kt
- libraries/stdlib/jvm/src/kotlin/coroutines/intrinsics/IntrinsicsJvm.kt
- libraries/stdlib/src/kotlin/coroutines/CoroutinesIntrinsicsH.kt
- libraries/stdlib/src/kotlin/util/DeepRecursive.kt
- libraries/stdlib/test/utils/DeepRecursiveTest.kt
- libraries/tools/binary-compatibility-validator/reference-public-api/kotlin-stdlib-runtime-merged.txt
Introduces coroutine-based framework to execute deeply recursive functions that utilitie the heap and thus avoid StackOverflowError.
Fixes KT-31741
> stdlib: DeepRecursiveFunction

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrInlineCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/defaultMethodUtilIr.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrUtils.kt
- compiler/testData/codegen/boxInline/syntheticAccessors/withinInlineLambda/privateInDefaultStubArgument.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java
If an inline parameter has a default value, its type is nullable. There's already code to handle this in `IrInlineCodegen`, but it really should be in `isInlineParameter` instead, otherwise e.g. SyntheticAccessorLowering fails.
> JVM_IR: fix a bug when `isInlineParameter` is applied to default stubs

- plugins/scripting/scripting-ide-services-test/test/org/jetbrains/kotlin/scripting/ide_services/ReplCompletionAndErrorsAnalysisTest.kt
- plugins/scripting/scripting-ide-services/src/org/jetbrains/kotlin/scripting/ide_services/compiler/CompletionOptions.kt
- plugins/scripting/scripting-ide-services/src/org/jetbrains/kotlin/scripting/ide_services/compiler/KJvmReplCompilerWithIdeServices.kt
- plugins/scripting/scripting-ide-services/src/org/jetbrains/kotlin/scripting/ide_services/compiler/impl/KJvmReplCompleter.kt
nameFilter - way of filtering descriptors by their names;
filterOutShadowedDescriptors - if true, filters out descriptors
shadowed by descriptors in latter-compiled snippets. May slow down
completion performance.
> Add scripting REPL completion options

- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/transformers/body/resolve/FirArrayOfCallTransformer.kt
- compiler/testData/codegen/box/annotations/parameters.kt
- compiler/testData/codegen/box/defaultArguments/constructor/annotationWithEmptyArray.kt
- compiler/testData/ir/irText/declarations/annotations/arrayInAnnotationArguments.fir.txt
At https://github.com/JetBrains/kotlin/pull/3404, only `arrayOf` call is supported. This is a follow-up to extend it to other variants, such as `emptyArray`, `intArrayOf`, `floatArrayOf`, etc.
> FIR: extend arrayOf call transformation to other variants

- compiler/testData/codegen/box/operatorConventions/kt14227.kt
The test used to fail because it has an augmented assignment for
elements in a HashMap of Strings, and "plus" fails to resolve due to
ambiguity: besides String.plus, BigDecimal.plus in the standard
library is also considered. BigDecimal is not resolved and thus
isError returns true. During type checking, the context has
isErrorTypeEqualsAnything set to true, and BigDecimal is now regarded
as a super type of String and BigDecimal.plus is a valid
candidate. Adding the directive "FULL_JDK" enables resolving of
BigDecimal so that BigDecimal.plus is excluded.
> [FIR] unmute testKt14227 with FULL_JDK

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/debug/stepping/tryCatchExpression.kt
- compiler/testData/debug/stepping/tryCatchFinally.kt
- compiler/testData/debug/stepping/tryFinally.kt
In particular, the current line numbers could lead to stepping
into the catch handler even when the code in the try did not
throw an exception.
This was caused by the code materializing the final value having
the catch line number. This patch delays the materialization
until the line number of the usage has been emitted.
> [JVM_IR] Fix line number information for try-catch.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/AnnotationCodegen.kt
- compiler/testData/codegen/bytecodeListing/lateInitNotNull.kt
- compiler/testData/codegen/bytecodeListing/lateInitNotNull.txt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeListingTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeListingTestGenerated.java
This is needed for compatibility with the JVM backend.
> JVM IR: Mark lateinit fields as NotNull

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/debug/stepping/initBlocks.kt
- compiler/testData/debug/stepping/initBlocksCompanion.kt
- compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/IrSteppingTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/SteppingTestGenerated.java
- plugins/kotlin-serialization/kotlin-serialization-compiler/testData/codegen/Basic.ir.txt
This seems to be what JVM does and it allows you to set a
breakpoint on the init line.
> [JVM_IR] Generate line numbers and nops for init blocks.

- idea/src/org/jetbrains/kotlin/idea/intentions/Utils.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/AddFunctionParametersFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixFactoryForTypeMismatchError.kt
- idea/testData/quickfix/changeSignature/addFunctionParameterWithAnonymousFunction.kt
- idea/testData/quickfix/changeSignature/addFunctionParameterWithAnonymousFunction.kt.after
- idea/testData/quickfix/changeSignature/addFunctionParameterWithFunctionReference.kt
- idea/testData/quickfix/changeSignature/addFunctionParameterWithFunctionReference.kt.after
- idea/testData/quickfix/changeSignature/addFunctionParameterWithLambda.kt
- idea/testData/quickfix/changeSignature/addFunctionParameterWithLambda.kt.after
- idea/testData/quickfix/changeSignature/addFunctionParameterWithSuspendFunctionReference.kt
- idea/testData/quickfix/changeSignature/addFunctionParameterWithSuspendFunctionReference.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-33211
> KT-33211 Quickfix "add parameter" for method references should infer functional type instead of KFunction

- idea/src/org/jetbrains/kotlin/idea/inspections/RemoveRedundantQualifierNameInspection.kt
- idea/testData/inspectionsLocal/removeRedundantQualifierName/notApplicableSameNameVariable.kt
- idea/testData/inspectionsLocal/removeRedundantQualifierName/notApplicableSameNameVariable2.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-39200
> KT-39200 False positive "Redundant qualifier name" with same-named member object and companion property

- compiler/fir/fir-serialization/src/org/jetbrains/kotlin/fir/serialization/FirElementSerializer.kt
- compiler/testData/codegen/box/reflection/modifiers/functions.kt
Even though the name of `FirDefaultPropertyAccessor` implies that it's default, it just means it doesn't have body. It can have some other information, e.g., annotations, user-contributed visibility (like `val x private get`), and modifiers (like `val y external get`). Those are technically not default, and their serialized flags should indicate that. Otherwise, reflective inspection via property reference won't catch such attributes.
> FIR serializer: regard property accessors with modifiers as non-default

- idea/src/org/jetbrains/kotlin/idea/highlighter/markers/KotlinLineMarkerProvider.kt
- idea/testData/codeInsight/lineMarker/MethodSeparators.kt
https://youtrack.jetbrains.com/issue/KT-24352
> KT-24352 Method separators: displayed between properties, not displayed between companion object and function

- ReadMe.md
It is not JDK 6 but JDK 9 that is needed for build, so added installation guide of jdk9 instead of 6.
> Update deprecated doc about mac build environment requirements

- compiler/fir/analysis-tests/testData/loadCompiledKotlin/annotations/parameters/ExtensionPropertySetter.txt
- compiler/fir/analysis-tests/testData/loadCompiledKotlin/annotations/parameters/PropertySetterInClass.txt
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/deserialization/FirMemberDeserializer.kt
At https://github.com/JetBrains/kotlin/pull/3464/files#diff-aca6498e9ef1b1d053cffda7fb32d750, when there is a non-default property accessor, a corresponding accessor has been built by FIR deserializer. That, however, should have read an annotation associated with the value parameter of setter, if any. (Instead, it always used kind of hard-coded, predefined value parameter.) This is a quick fix for that, by applying https://github.com/JetBrains/kotlin/commit/7834284bece00ffa8fe2b9d2211b963ff2448cb8 to the value parameter of setter.
> FIR deserializer: proper annotation loading for value parameter of property setter

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/debug/stepping/classObject.kt
- compiler/testData/debug/stepping/constructorCall.kt
- compiler/testData/debug/stepping/enum.kt
- compiler/testData/debug/stepping/initBlocksCompanion.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/debugInformation/AbstractDebugTest.kt
- compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/IrSteppingTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/SteppingTestGenerated.java
In addition, made the stepping information for constructor calls
consistent across JVM_IR and JVM. For JVM_IR that stepping behavior
is consistent for enum constructor calls in <clinit> for JVM it
is not.
> [JVM] Extend stepping tests with <clinit> stepping.

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/generators/FakeOverrideGenerator.kt
- compiler/testData/codegen/box/syntheticAccessors/kt10047.kt
> Otherwise, IR validation failed: "Overrides private declaration ..."
This is supposed to be part of https://github.com/JetBrains/kotlin/pull/3252, which missed substitution case.
> FIR2IR: discard fake overrides for property accessors according to base visibility

- compiler/backend/src/org/jetbrains/kotlin/codegen/coroutines/RedundantLocalsEliminationMethodTransformer.kt
- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/testData/codegen/box/coroutines/unitTypeReturn/inlineUnitFunction.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
A second version of #3501, this time without `SourceInterpreter` (or rather using an ad-hoc version of the same which only works on certain Unit values).
> Coroutines: Fix RedundantLocalsEliminationMethodTransformer

- compiler/fir/analysis-tests/testData/loadCompiledKotlin/annotations/parameters/EnumConstructor.txt
- compiler/fir/java/src/org/jetbrains/kotlin/fir/java/deserialization/JvmBinaryAnnotationDeserializer.kt
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/deserialization/AbstractAnnotationDeserializer.kt
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/deserialization/ClassDeserialization.kt
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/deserialization/FirMemberDeserializer.kt
When computing shifted index for value parameter in constructor, we need to know the kind of the enclosing class, e.g., whether it's enum or inner class. To be general, whenever value parameters are visited, the containing class's proto will be passed.
> FIR deserializer: fix parameter shift for constructor of inner classes and enums

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrVisitor.kt
- compiler/testData/codegen/box/dataClasses/copy/copyInObjectNestedDataClass.kt
- compiler/testData/codegen/box/enum/deepInnerClassInEnumEntryClass.kt
- compiler/testData/codegen/box/enum/deepInnerClassInEnumEntryClass2.kt
- compiler/testData/codegen/box/enum/innerClassInEnumEntryClass.kt
- compiler/testData/codegen/box/enum/innerClassMethodInEnumEntryClass.kt
- compiler/testData/codegen/box/enum/kt7257_anonObjectInit.kt
- compiler/testData/codegen/box/enum/kt7257_anonObjectMethod.kt
- compiler/testData/codegen/box/enum/kt7257_boundReference1.kt
- compiler/testData/codegen/box/enum/kt9711_2.kt
- compiler/testData/codegen/box/ir/serializationRegressions/innerClassInEnumEntryClass.kt
- compiler/testData/ir/irText/expressions/enumEntryReferenceFromEnumEntryClass.fir.txt
- compiler/testData/ir/irText/singletons/enumEntry.fir.txt
`InnerClassesLowering` in backend IR expects _implicit_ `this` receiver to be retrieved via `IrGetValue`. During `fir2ir` conversion, _implicit_ `this` and explicit one are mangled, and for anonymous object as an implicit receiver, we passed `IrGetObjectValue` instead, resulting in missed lowering that causes dangling static call.
To distinguish implicit v.s. explicit `this` (without revealing corresponding internal declarations: `FirImplicitThisReference` and `FirExplicitThisReference`), this PR passes the context callee so that we can match the class bound to `this` reference against the context where such `this` receiver is going to be used. Then, for anonymous object case, we can avoid using `IrGetObjectValue` if it is used as an implicit receiver (so that `InnerClassesLowering` can …
> FIR2IR: handle 'this' as reference to outer object

- idea/resources/META-INF/plugin-common.xml
IDEA 2020.3 uses `id` from extension definition to avoid creating instance of converter without need.
I do not change `KotlinNonJvmSourceRootConverterProvider` because using of deprecated constructor `ConverterProvider(id)` is still required as you don't have a special branch for 2020.3 IDE.
> Explicitly specify id of `KotlinNonJvmSourceRootConverterProvider`

- compiler/fir/analysis-tests/testData/loadCompiledKotlin/annotations/classMembers/ClassObjectPropertyField.txt
- compiler/fir/analysis-tests/testData/loadCompiledKotlin/annotations/classMembers/HiddenConstructorWithInlineClassParameters.txt
- compiler/fir/analysis-tests/testData/loadCompiledKotlin/annotations/parameters/InnerClassConstructor.txt
- compiler/fir/analysis-tests/testData/loadCompiledKotlin/annotations/propertiesWithoutBackingFields/ClassObject.txt
- compiler/fir/analysis-tests/testData/loadCompiledKotlin/annotations/propertiesWithoutBackingFields/TraitClassObject.txt
- compiler/fir/java/src/org/jetbrains/kotlin/fir/java/deserialization/JvmBinaryAnnotationDeserializer.kt
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/deserialization/AbstractAnnotationDeserializer.kt
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/deserialization/ClassDeserialization.kt
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/deserialization/FirMemberDeserializer.kt
This is a follow-up work on https://github.com/JetBrains/kotlin/pull/3512, which fixed parameter shifts for constructors of inner classes and enums, but only enum tests were affected.
It turns out that, when visiting inner classes, deserializer in the parent context, i.e., outer class, has been always used. When creating "child" context, we need a fresh deserializer that loads that child class of interest. To do so, in the 1st commit, container source and annotation deserializer are passed down to child context creation accordingly.
That revealed one subtle case: annotations on fields inside a companion object whose actual field declared in the outer class. In that case, we need loaded annotation info from the outer, enclosing class, in addition to the companion class. The 2nd commit adds …
> FIR deserializer: load annotations on inner classes

- compiler/fir/analysis-tests/testData/resolve/diagnostics/projectionsOnNonClassTypeArguments.kt
- compiler/fir/analysis-tests/testData/resolve/diagnostics/projectionsOnNonClassTypeArguments.txt
- compiler/fir/analysis-tests/tests/org/jetbrains/kotlin/fir/FirDiagnosticsTestGenerated.java
- compiler/fir/analysis-tests/tests/org/jetbrains/kotlin/fir/FirDiagnosticsWithLightTreeTestGenerated.java
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/expression/DefaultExpressionCheckers.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/expression/FirProjectionsOnNonClassTypeArgumentChecker.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/diagnostics/FirErrors.kt
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/transformers/FirCallCompletionResultsWriterTransformer.kt
- compiler/testData/diagnostics/tests/ProjectionOnFunctionArgumentErrror.fir.kt
- compiler/testData/diagnostics/tests/StarsInFunctionCalls.fir.kt
- compiler/testData/diagnostics/tests/modifiers/incompatibleVarianceModifiers.fir.kt
- compiler/testData/diagnostics/tests/qualifiedExpression/nullCalleeExpression.fir.kt
- compiler/testData/diagnostics/tests/typealias/projectionsInTypeAliasConstructor.fir.kt
- compiler/testData/diagnostics/tests/typealias/typeAliasConstructorForProjection.fir.kt
`computeTypeArguments()` used to lose `StarProjection` instances replacing them with `TypeProjectionWithVariance`. Added a checker for PROJECTION_ON_NON_CLASS_TYPE_ARGUMENT as well.
> [FIR] Fixed computeTypeArguments() & added diagnostic for type args

- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/calls/Arguments.kt
- compiler/testData/codegen/box/classes/kt1980.kt
The motivation is `Classes.kt1980` where `Int` extension, `times`, that inputs a lambda, is there to test resolutions against `Int.times(Int)`. For that top-level `times`, `fir` simply failed with a cast exception while retrieving the expected type for the argument. That is easy to avoid, since the underlying assumption was, when parameter is integer literal type, the corresponding argument type has been resolved, which is never guaranteed. (In the test, a lambda body is given as an argument, and thus we should discard that candidate, instead of cast exception.)
> FIR: avoid cast exception in Candidate.prepareExpectedType

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/MemoizedInlineClassReplacements.kt
- compiler/testData/codegen/bytecodeText/inlineClasses/delegatedPropertyMangling.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
We have to avoid mangling local delegated properties in `MemoizedInlineClassReplacements`, since they do not have corresponding properties. It turns out that the check for this was overly broad and also excluded delegated properties in classes.
> JVM IR: Mangle delegated properties with inline class type (fix KT-40125)

- idea/src/org/jetbrains/kotlin/idea/quickfix/AddSuspendModifierFix.kt
- idea/testData/quickfix/modifiers/suspend/inLambda.kt
- idea/testData/quickfix/modifiers/suspend/inLambda.kt.after
- idea/testData/quickfix/modifiers/suspend/inLambda2.kt
- idea/testData/quickfix/modifiers/suspend/inLambda3.kt
- idea/testData/quickfix/modifiers/suspend/inLambda3.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-38139
> KT-38139 False negative "Add suspend modifier" quickfix when suspend function is called in inline lambda

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/irCodegenUtils.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/PsiSourceManager.kt
This is necessary for our synthetics which can't easily be registered with the SourceManager fileEntriesByIrFile, but which can be provided a fileEntry on the IR node.
> Fallback to fileEntry provided by irFile

- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/calls/ResolutionStages.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/bothWithCoercionToUnit.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/boundReferences.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/defaultAfterVararg.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/emptyVarargAndDefault.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/inlineBound.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/inlineVarargAndDefault.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/manyDefaultsAndVararg.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/simpleEmptyVararg.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/unboundReferences.kt
- compiler/testData/codegen/box/callableReference/equality/varargWithDefaults.kt
- compiler/testData/codegen/box/callableReference/kt37604.kt
- compiler/testData/codegen/box/funInterface/equality/functionReferencesBound.kt
- compiler/testData/codegen/box/funInterface/equality/functionReferencesUnbound.kt
- compiler/testData/codegen/box/funInterface/equality/localFunctionReferences.kt
- compiler/testData/codegen/box/sam/equality/functionReferencesBound.kt
- compiler/testData/codegen/box/sam/equality/functionReferencesUnbound.kt
- compiler/testData/codegen/box/sam/equality/localFunctionReferences.kt
- compiler/testData/diagnostics/tests/callableReference/referenceAdaptationHasDependencyOnApi14.fir.kt
- compiler/testData/ir/irText/expressions/callableReferences/adaptedExtensionFunctions.fir.txt
- compiler/testData/ir/irText/expressions/callableReferences/adaptedWithCoercionToUnit.fir.txt
- compiler/testData/ir/irText/expressions/callableReferences/boundInlineAdaptedReference.fir.txt
- compiler/testData/ir/irText/expressions/callableReferences/funWithDefaultParametersAsKCallableStar.fir.txt
- compiler/testData/ir/irText/expressions/callableReferences/withAdaptedArguments.fir.txt
- compiler/testData/ir/irText/expressions/funInterface/samConversionOnCallableReference.fir.txt
The motivation is `callableReference.kt37604`:
```
fun useUnit(fn: () -> Unit) {
fn.invoke()
}
...
var cWithVarargInit = false
class CWithVararg(vararg x: Int) {
init {
cWithVarargInit = true
}
}
fun box(): String {
...
useUnit(::CWithVararg)
if (!cWithVarargInit) throw AssertionError("cWithVarargInit")
return "OK"
```
Other class references with no parameter or default value parameter were resolved well, but that one with `vararg` wasn't. It turns out that, when computing the resulting type for callable reference of the candidate, if it is a class reference, its primary constructor is the call target, and while collecting value parameter of interest, `vararg` is simply missed. Since its use is callable reference, i.e., no arguments, we can ignore `vararg` when computing the `KFunction` …
> FIR: account for vararg when creating KFunction type for callable reference

- compiler/frontend/src/org/jetbrains/kotlin/resolve/AbstractFilteringTrace.kt
report() already delegates to the parentTrace, so
wantsDiagnostics() should delegate to it as well.
cc @dsavvinov who wrote `AbstractFilteringTrace`.
(Does this change look right to you?)
This change came about while investigating Android Lint performance,
which uses `TopDownAnalyzerFacadeForJVM`.
> Set wantsDiagnostics() in AbstractFilteringTrace

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/testData/codegen/bytecodeText/enum/constructorAccessors.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
Enum entry constructors are package private and only called from the enclosing enum class, so we don't need to generate accessors.
> JVM IR: Do not create accessors for enum entry constructors

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrDeclarationStorage.kt
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/calls/ResolutionStages.kt
- compiler/testData/codegen/box/intrinsics/monitorEnterMonitorExit.kt
`monitor{Enter|Exit}` are defined in `kotlin.jvm.internal.unsafe.MonitorKt` with `private` visibility, but they're "intrinsics." During visibility check in resolution, we need a special handling to allow them to be accessed from anywhere.
IR functions for those, however, had an incorrect `parent`: external package fragment, in lieu of facade class. `SymbolTable` walks through registered symbols and returns those with `DescriptorWithContainerSource` (which usually refers to such facade class), and then stub generator will update `parent` of those symbols with the facade class. Therefore, `fir` should have used `DescriptorWithContainerSource` if container source is available.
Such correct `parent` class setting matters because backend's synthetic accessor lowering depends on it. Proper …
> FIR: special visibility handling for monitor{Enter|Exit}

- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/calls/tower/FirTowerResolverSession.kt
- compiler/testData/codegen/box/typealias/typeAliasObjectCallable.kt
- compiler/testData/diagnostics/tests/typealias/typeAliasObjectWithInvoke.fir.kt
The motivation is bb test `typealias/typeAliasObjectCallable.kt`:
```
object O {
...
operator fun invoke() = ...
}
typealias A = O
fun box(): String = A()
```
Currently, `A()` is resolved as object `O`'s private constructor, resulting in `HIDDEN` applicability of the candidate. Rather, `O.invoke()` should be chosen as the call target. This is because, during `invoke` candidate resolution, only callable symbol and class symbol were assumed and handled. Since type alias has the expand type on it, it could be treated similar to regular class. This PR adds necessary handling of type alias symbol to `invoke` resolution.
> FIR: handle object invoke via type alias

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/SpecialBridgeMethods.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/DeclarationOrigins.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/BridgeLowering.kt
- compiler/testData/codegen/box/jvm8/treeMapBridge.kt
- compiler/testData/codegen/bytecodeListing/immutableCollection.kt
- compiler/testData/codegen/bytecodeListing/specialBridges/removeAtTwoSpecialBridges.kt
- compiler/testData/codegen/bytecodeListing/specialBridges/signatures/genericClass.kt
- compiler/testData/codegen/bytecodeListing/specialBridges/signatures/nonGenericClass.kt
- compiler/testData/codegen/bytecodeListing/specialBridges/signatures/nonGenericClass_ir.txt
- compiler/testData/codegen/bytecodeListing/specialBridges/signatures/partiallySpecializedClass.kt
- compiler/testData/codegen/bytecodeListing/specialBridges/signatures/partiallySpecializedClass_ir.txt
- compiler/testData/codegen/bytecodeText/builtinFunctions/removeAt.kt
- compiler/testData/codegen/bytecodeText/mapGetOrDefault.kt
Second attempt at #3163.
We produce special bridge methods for overrides of Java methods which have different names or signatures in the Kotlin standard library. Since these methods are visible to Java (they are non-synthetic bridge methods) we need to produce proper generic signatures to ensure that they are callable from Java.
The JVM backend currently does *not* do this in 6 out of the 7 cases where we have special bridge methods which are generic in Java. This can lead to Java code seeing less precise types for Kotlin collections. It does not break compilation, because of a quirk of javac, which skips the usual override checks for bridge methods (which, as far as I know, are always synthetic in Java).
Rather than replicating the behavior of the JVM backend, this PR tries to produce …
> JVM IR: Fix generic signatures for special bridge methods

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/Ir.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/handlers/DefaultProgressionHandler.kt
- compiler/testData/codegen/bytecodeText/forLoop/primitiveRange.kt
- compiler/testData/codegen/bytecodeText/forLoop/stepped/stepNonConstOnNonLiteralProgression.kt
- compiler/testData/codegen/bytecodeText/forLoop/stepped/stepOnNonLiteralRange.kt
- compiler/testData/codegen/bytecodeText/forLoop/unsigned/stepNonConstOnNonLiteralProgression.kt
- compiler/testData/codegen/bytecodeText/forLoop/unsigned/stepOnNonLiteralRange.kt
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
...and handle accordingly (e.g., do not read `step` property).
> ForLoopsLowering: Assume `step` == 1 for *Range (e.g., IntRange)

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrDeclarationStorage.kt
- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrLocalStorage.kt
- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrScopeCache.kt
- compiler/testData/codegen/box/closures/kt10044.kt
because, e.g., local function could be defined in an anonymous initializer, which is not a callable. In that case, `cacheStack` in the local storage is empty, and thus no callable cache to put parameter, variable, and local function.
------
An alternative is, whenever we want to put those into a callable cache, we can make sure there is indeed a callable in the conversion scope. This sounds over engineered, time-consuming task without visible effects. :\
> FIR2IR: make local storage track scopes, including anonymous init

- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/transformers/body/resolve/FirDeclarationsResolveTransformer.kt
- compiler/testData/codegen/box/enum/innerClassMethodInEnumEntryClass2.kt
so that `this` reference with the enum entry name as label can be resolved.
The motivation is `enum.innerClassMethodInEnumEntryClass2`:
```
enum class A {
X {
val x = ...
inner class Inner {
fun foo() = this@X.x
}
...
};
...
}
```
where `this@X` was not resolved because, in the implicit receiver stack, there was nothing associated with the label `X`. Declaration resolver definitely visited the enum entry, but it is an anonymous object, and for all anonymous objects, labels were ignored. However, an anonymous object as enum entry has the name for label: enum entry name itself! That can be retrieved from the primary constructor.
> FIR: distinguish anonymous object as enum entry when scoping

- libraries/stdlib/samples/test/samples/misc/controlFlow.kt
This commit adds the zero-based index of current iteration from the passed HOF "action" of the repeat function to its associated code sample.
related to KT-20357
> Make repeat example more expressive

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrTypeConverter.kt
- compiler/testData/codegen/box/typealias/simple.kt
- compiler/testData/ir/irText/classes/delegatingConstructorCallToTypeAliasConstructor.fir.txt
- compiler/testData/ir/irText/regressions/integerCoercionToT.fir.txt
because, if the type is a nested type alias (e.g., one of type argument is another type alias), converting the type argument at the current level may lead to mismatched number of type parameters.
> FIR2IR: use type arguments from fully expanded type

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/SwitchGenerator.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InheritedDefaultMethodsOnClassesLowering.kt
- compiler/testData/codegen/bytecodeText/controlStructures/kt17110.kt
- compiler/testData/debug/stepping/stringSwitches.kt
- compiler/testData/debug/stepping/stringSwitchesSmall.kt
- compiler/testData/debug/stepping/trait.kt
- compiler/testData/debug/stepping/when.kt
- compiler/testData/debug/stepping/whenComplicatedSubject.kt
- compiler/testData/debug/stepping/whenMultiLine.kt
- compiler/testData/debug/stepping/whenMultiLineSubject.kt
- compiler/testData/debug/stepping/whenSubject.kt
- compiler/testData/debug/stepping/whenSubject2.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/debugInformation/AbstractSteppingTest.kt
- compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/IrSteppingTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/SteppingTestGenerated.java
- plugins/kotlin-serialization/kotlin-serialization-compiler/testData/codegen/Basic.ir.txt
Additionally, use the line number of the class for default interface
dispatch methods.
> [JVM_IR]: Improve stepping for `when`.

- idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/callableBuilder/CallableBuilder.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/callableBuilder/CallableInfo.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createClass/CreateClassFromConstructorCallActionFactory.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/createFromUsage/createClass/CreateClassFromUsageFix.kt
- idea/testData/quickfix/createFromUsage/createClass/callExpression/parameterClassIsInternal.kt
- idea/testData/quickfix/createFromUsage/createClass/callExpression/parameterClassIsInternal.kt.after
- idea/testData/quickfix/createFromUsage/createClass/callExpression/parameterClassIsPrivate.kt
- idea/testData/quickfix/createFromUsage/createClass/callExpression/parameterClassIsPrivate.kt.after
- idea/testData/quickfix/createFromUsage/createClass/callExpression/parameterClassIsPublic.kt
- idea/testData/quickfix/createFromUsage/createClass/callExpression/parameterClassIsPublic.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-29844
> KT-29844 "Create class from usage" should mark constructor of created class as internal if its parameters have internal visibility

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/MethodSignatureMapper.kt
- compiler/testData/compileKotlinAgainstKotlin/specialBridgesInDependencies.kt
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstKotlinTestGenerated.java
In the descriptor hierarchy we replace special bridge methods with their Kotlin equivalents, which leads to some differences between external and local Kotlin declarations. This carries over to the IR declarations, where we use `initialSignatureFunction` to map a declaration back to its original (non-substituted) declaration. For fake overrides, this has the unintended effect of mapping to the original non-substituted version in a superclass, which causes the method signature mapper to return wrong results for fake overrides (which are only used in bridge generation).
Ideally, we should avoid `initialSignatureFunction` altogether and this is what I tried first. This currently fails because there are too many places in the IR backend which still use descriptors. When the IR structures …
> JVM IR: Fix special bridge generation with external Kotlin dependencies

- nj2k/src/org/jetbrains/kotlin/nj2k/printing/JKCodeBuilder.kt
- nj2k/testData/newJ2k/issues/kt-20421.java
- nj2k/testData/newJ2k/issues/kt-20421.kt
- nj2k/tests/org/jetbrains/kotlin/nj2k/NewJavaToKotlinConverterSingleFileTestGenerated.java
The fix will add braces so the code look like: 
```
internal object A : Base() {
const val F1 = 0
}
```
https://youtrack.jetbrains.com/issue/KT-20421
> KT-20421 fixing code generation for the case when "object" extends "class"

- idea/src/org/jetbrains/kotlin/idea/inspections/UnnecessaryVariableInspection.kt
- idea/testData/inspectionsLocal/unnecessaryVariable/override.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-39263
> KT-39263 False positive "Variable should be inlined" for override value in  initialized object

- idea/src/org/jetbrains/kotlin/idea/inspections/ScopeFunctionConversionInspection.kt
- idea/testData/inspectionsLocal/scopeFunctions/runToLet/noReceiver.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-35525
> KT-35525 False positive intention for 'run': "Convert to 'let'" when invoked without receiver

- compiler/psi/src/org/jetbrains/kotlin/psi/KtPackageDirective.java
- idea/testData/multiFileLocalInspections/reconcilePackageWithDirectory/changeToNonDefaultPackageFromRootWithPackageKeyword/after/com/example/test.kt
- idea/testData/multiFileLocalInspections/reconcilePackageWithDirectory/changeToNonDefaultPackageFromRootWithPackageKeyword/before/com/example/test.kt
- idea/testData/multiFileLocalInspections/reconcilePackageWithDirectory/changeToNonDefaultPackageFromRootWithPackageKeyword/changeToNonDefaultPackageFromRootWithPackageKeyword.test
- idea/tests/org/jetbrains/kotlin/idea/inspections/MultiFileLocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-39604
> KT-39604 "Package directive doesn't match file location" quick fix does not insert a space between keyword `package` and the package name

- idea/src/org/jetbrains/kotlin/idea/quickfix/SurroundWithNullCheckFix.kt
- idea/testData/quickfix/surroundWithNullCheck/in.kt
- idea/testData/quickfix/surroundWithNullCheck/in.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixMultiFileTestGenerated.java
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-31749
> KT-31749 "Surround with null check" produces incorrect check for 'in' expression

- compiler/cli/cli-runner/src/org/jetbrains/kotlin/runner/Main.kt
This PR contains the following changes:
Updated the path passed as an argument to ```adPath()```
```classpath.addPath(KOTLIN_HOME + "/lib/kotlin-stdlib.jar")```
to:
```classpath.addPath("$KOTLIN_HOME/lib/kotlin-stdlib.jar")```
It now uses String Templates instead of String concatenation.
> KT-41211: Use string template instead of concatenation

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
- compiler/testData/codegen/box/classes/kt40332.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
The corresponding classes end up nested in the class initializer of the surrounding class and we need to take this into account when creating instances of ClassCodegen.
This fixes KT-40332 on the JVM IR backend.
> JVM IR: Fix compilation of inline functions in anonymous objects inside of field initializers

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrClassifierStorage.kt
- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrDeclarationStorage.kt
- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrLocalStorage.kt
- compiler/testData/codegen/box/objects/companionObjectAccess/multipleCompanionsWithAccessors/anonymousObjectInPropertyInitializer.kt
Members that belong to local classes can't set up `parent`, since symbol provider doesn't allow `ClassId` lookup for local classes. At least, we can look up cached local classes in the classifier storage.
> FIR2IR: introduce & use ClassId-based lookup for local class as IrParent

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/generators/CallAndReferenceGenerator.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/suspendConversion/adaptedWithVarargs.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/suspendConversion/inlineAdaptedWithVarargs.kt
- compiler/testData/ir/irText/expressions/callableReferences/adaptedWithCoercionToUnit.fir.txt
- compiler/testData/ir/irText/expressions/callableReferences/suspendConversion.fir.txt
- compiler/testData/ir/irText/expressions/callableReferences/unboundMemberReferenceWithAdaptedArguments.fir.txt
- compiler/testData/ir/irText/expressions/callableReferences/withAdaptationForSam.fir.txt
- compiler/testData/ir/irText/expressions/callableReferences/withArgumentAdaptationAndReceiver.fir.txt
- compiler/testData/ir/irText/expressions/funInterface/samConversionInVarargs.fir.txt
This is the follow-up of https://github.com/JetBrains/kotlin/pull/3614, where I said:
> Note that, in this PR, only the adaptation on reference type is done. For some other cases, we will need a different conversion for such adapted callable reference, which will reuse #3599.
That PR adapted callable reference type with `vararg` such that the reference can be used in a different form at the use site. This PR now converts such adapted callable reference. All necessary pieces of callable reference conversion were done at #3599. This PR just extends how value argument from the adapter function can be mapped to `vararg` parameter in the adaptee.
> FIR2IR: convert adapted callable reference with vararg

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/InnerClassesLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/testData/codegen/box/innerNested/nestedInnerClass.kt
- compiler/testData/codegen/bytecodeListing/annotations/literals.kt
- compiler/testData/codegen/bytecodeListing/annotations/localClassWithCapturedParams.kt
- compiler/testData/codegen/bytecodeListing/coroutines/spilling/booleanParameter_ir.txt
- compiler/testData/codegen/bytecodeText/fieldsForCapturedValues/extensionLambdaExtensionReceiver.kt
- compiler/testData/codegen/bytecodeText/fieldsForCapturedValues/extensionReceiver.kt
- compiler/testData/codegen/bytecodeText/fieldsForCapturedValues/innerAndOuterThis.kt
- compiler/testData/codegen/bytecodeText/fieldsForCapturedValues/labeledExtensionLambdaExtensionReceiver.kt
- compiler/testData/codegen/bytecodeText/fieldsForCapturedValues/multipleExtensionReceivers.kt
- compiler/testData/codegen/bytecodeText/fieldsForCapturedValues/outerThis.kt
- compiler/testData/codegen/bytecodeText/fieldsForCapturedValues/outerThisInInnerConstructor.kt
- compiler/testData/codegen/bytecodeText/fieldsForCapturedValues/outerThisInInnerInitBlock.kt
- compiler/testData/codegen/bytecodeText/fieldsForCapturedValues/this.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- Fix the lookup for the `this` reference in `InnerClassesLowering`. The fix was found by @pyos. This previously caused problems with the compilation of nested inner classes, see the added test.
- Create fields for captured values as package private, same as in the JVM backend. Otherwise, nested inner classes would require accessors. There were also some cases where the fields needed to be package private instead of private anyway, see the unmuted tests.
> JVM IR: Fixes for nested inner classes

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmLocalClassPopupLowering.kt
- compiler/testData/codegen/box/secondaryConstructors/inlineIntoTwoConstructors.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
> JVM_IR: move classes out of lambdas inlined into initializers

- idea/resources-en/inspectionDescriptions/SimplifyNestedEachInScopeFunction.html
- idea/resources-en/messages/KotlinBundle.properties
- idea/resources/META-INF/inspections.xml
- idea/src/org/jetbrains/kotlin/idea/inspections/SimplifyNestedEachInScopeFunctionInspection.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/.inspection
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/also.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/also.kt.after
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/also2.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/also3.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/also3.kt.after
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/also4.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/also5.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/alsoLabel.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/alsoLabel2.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/alsoLabel3.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/alsoLabel3.kt.after
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/apply.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/apply.kt.after
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/apply2.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/apply3.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/apply3.kt.after
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/applyLabel.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/applyLabel2.kt
- idea/testData/inspectionsLocal/simplifyNestedEachInScope/applyLabel2.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-40283
> KT-40283: Inspection which replaces `also`/`apply` with nested `forEach` to `onEach`

- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/JsLoweringPhases.kt
- compiler/testData/codegen/box/ranges/contains/inComparableRange.kt
- compiler/testData/codegen/box/ranges/contains/inExtensionRange.kt
- compiler/testData/codegen/box/ranges/contains/inIntRange.kt
- compiler/testData/codegen/box/ranges/contains/inOptimizableDoubleRange.kt
- compiler/testData/codegen/box/ranges/contains/inOptimizableFloatRange.kt
- compiler/testData/codegen/box/ranges/contains/inOptimizableIntRange.kt
- compiler/testData/codegen/box/ranges/contains/inOptimizableLongRange.kt
- compiler/testData/codegen/box/ranges/contains/inRangeWithCustomContains.kt
- compiler/testData/codegen/box/ranges/contains/inRangeWithImplicitReceiver.kt
- compiler/testData/codegen/box/ranges/contains/inRangeWithNonmatchingArguments.kt
Also unmuted some tests in `box/ranges/contains` by changing `assert()` calls (not available in JS) to `assertTrue()`. It seems to be the only reason they were muted in the first place.
> [JS_IR] Enable RangeContainsLowering optimizations

- idea/src/org/jetbrains/kotlin/idea/inspections/collections/RedundantAsSequenceInspection.kt
- idea/testData/inspectionsLocal/collections/redundantAsSequence/map.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-41338
> KT-41338 False positive "Redundant 'asSequence' call" when Map.Entry properties are used.

- idea/src/org/jetbrains/kotlin/idea/parameterInfo/KotlinFunctionParameterInfoHandler.kt
- idea/testData/parameterInfo/functionCall/NamedParameter3.kt
- idea/testData/parameterInfo/functionCall/NamedParameter4.kt
- idea/tests/org/jetbrains/kotlin/idea/parameterInfo/MockParameterInfoUIContext.java
- idea/tests/org/jetbrains/kotlin/idea/parameterInfo/ParameterInfoTestGenerated.java
When using named arguments the IDE might be unable to map the current argument to a parameter. In that case this change marks already used parameters as disabled. That way developers can easily see which parameters have not been used yet.
Fixes [KTIJ-128](https://youtrack.jetbrains.com/issue/KTIJ-128)
> [IDEA] Mark used parameters as disabled in parameter info popup

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrInlineCodegen.kt
This allows compiler plugins such as Compose to do custom
default argument handling in methods that do not have origin
`FUNCTION_FOR_DEFAULT_PARAMETER`.
The code still bails out early is there is not defaults
mask, so there should be no compile-time penalty.
> [JVM_IR] Always look for default lambdas in the inliner.

- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/calls/FirArgumentsToParametersMapper.kt
- compiler/testData/codegen/box/defaultArguments/convention/incWithDefaults.kt
- compiler/testData/codegen/box/defaultArguments/convention/kt16520.kt
- compiler/testData/codegen/box/defaultArguments/convention/plusAssignWithDefaults.kt
- compiler/testData/diagnostics/tests/checkArguments/arrayAccessSet.fir.kt
- compiler/testData/diagnostics/tests/regressions/kt10633.fir.kt
- compiler/testData/ir/irText/expressions/kt28456b.fir.txt
Users can be overloading [Indexed access operator](https://kotlinlang.org/docs/reference/operator-overloading.html#indexed), and in that case, for `setter`, the last parameter is supposed to be the updated value. By wrapping that one as a named argument, we can handle any other parameters in the middle, which could have default values.
> FIR: map arguments for overloading indexed access operator

- libraries/kotlin.test/Module.md
Sending this PR so the change is reflected there: https://kotlinlang.org/api/latest/kotlin.test/
> Add missing "The" article in kotlin.test doc

- idea/jvm-debugger/jvm-debugger-test/testData/stepping/stepOut/fwBackingField.ir.out
The difference is that JVM_IR generates line numbers for the
constructor field initialization.
In this case:
```
29: class B {
30:   // comment
31:   val bPropVal: Int,
32:   // comment
33:   var bProbVar: Int
34: ) {
```
the line numbers for the field initializations are 31 and 33 where
in the current backend the whole constructor has line number 29.
> [JVM_IR] Rebase fwBackingField stepping test.

- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/transformers/FirCallCompletionResultsWriterTransformer.kt
- compiler/testData/codegen/box/coroutines/featureIntersection/funInterface.kt
The motivation is bb test `coroutines/featureIntersection/funInterface`:
```kt
fun interface Action {
suspend fun run()
}
suspend fun runAction(a: Action) {
a.run()
}
fun box() {
...
runAction { // this lambda, as Action#run, should be "suspend"
...
}
}
```
where the type of the lambda passed to `runAction` is still a non-suspend functional type. From the expected argument type, `Action`, which is a functional interface, we can retrieve SAM (`Action#run`) and rebuild the expected type of the lambda correctly.
> FIR: update the type of anonymous function as SAM

- idea/jvm-debugger/jvm-debugger-test/testData/stepping/stepOut/fwBackingField.ir.out
The test relies on fixes not yet landed, so it currently fails.
> [JVM_IR] Ignore fwBackingField stepping test.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/TypeOperatorLowering.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ClassGenerator.kt
- compiler/testData/diagnostics/testsWithJvmBackend/duplicateJvmSignature/accidentalOverrides/delegatedFunctionOverriddenByProperty_ir.kt
- compiler/testData/diagnostics/testsWithJvmBackend/duplicateJvmSignature/erasure/delegateToTwoTraits_ir.kt
- compiler/testData/diagnostics/testsWithJvmBackend/duplicateJvmSignature/erasure/delegationAndOwnMethod_ir.kt
- compiler/testData/diagnostics/testsWithJvmBackend/duplicateJvmSignature/erasure/delegationToTraitImplAndOwnMethod_ir.kt
- compiler/testData/diagnostics/testsWithJvmBackend/duplicateJvmSignature/erasure/superTraitAndDelegationToTraitImpl_ir.kt
- idea/jvm-debugger/jvm-debugger-test/testData/stepping/custom/smartStepIntoWithDelegates.out
This fixes smart step into for delegated member functions.
Additionally, we align on the string "memberFunctionName(...)"
for expression non-null checks for both JVM_IR and JVM
backends.
> [JVM_IR] Remove line numbers from delegated member functions.

- idea/src/org/jetbrains/kotlin/idea/codeInliner/CodeInliner.kt
- idea/testData/quickfix/deprecatedSymbolUsage/functionLiteralArguments/keepOutsideWithNamedArgument.kt
- idea/testData/quickfix/deprecatedSymbolUsage/functionLiteralArguments/keepOutsideWithNamedArgument.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-31523
> KT-31523 ReplaceWith introduces additional argument name for lambda when named argument is used on call-site

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/ConstLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmOptimizationLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/IrConst.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/impl/IrConstImpl.kt
- compiler/testData/debug/stepping/whenConstant.kt
- compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/IrSteppingTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/debugInformation/SteppingTestGenerated.java
- idea/jvm-debugger/jvm-debugger-test/testData/stepping/stepOver/stepOverWhenWithInline.ir.out
- idea/jvm-debugger/jvm-debugger-test/testData/stepping/stepOver/stepOverWhenWithInline.kt
Loads of temporary variables that contain constants are replaced
with a copy of the constant. This avoids locals loads and stores.
However, the copy of the constant needs to have the offset of
the load and not of the original constant.
Fixes KT-41963.
> [JVM_IR] Fix offsets in constant propagation optimization.

- idea/idea-core/src/org/jetbrains/kotlin/idea/core/generateUtil.kt
- idea/testData/codeInsight/overrideImplement/overrideExternalFunction.kt
- idea/testData/codeInsight/overrideImplement/overrideExternalFunction.kt.after
- idea/tests/org/jetbrains/kotlin/idea/codeInsight/OverrideImplementTest.kt
https://youtrack.jetbrains.com/issue/KT-33466
> KT-33466 IDE generates incorrect `external override` with body for overriding `open external` method

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AnonymousObjectSuperConstructorLowering.kt
- compiler/testData/codegen/box/argumentOrder/argumentOrderInObjectSuperCallWithPlatformType.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
If the arguments are reordered, they can not only be reads of temporary variables, but also implicit type casts of said reads.
Fixes #KT-42002
> JVM_IR: fix lifting of arguments to object super constructors

- idea/src/org/jetbrains/kotlin/idea/inspections/KotlinRedundantOverrideInspection.kt
- idea/testData/inspectionsLocal/redundantOverride/callDifferentSuperMethod2.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-34959
> KT-34959 False positive "Redundant overriding method" with different implemented/overridden signatures

- idea/idea-core/src/org/jetbrains/kotlin/idea/core/psiModificationUtils.kt
- idea/testData/inspectionsLocal/moveLambdaOutsideParentheses/hasComments.kt
- idea/testData/inspectionsLocal/moveLambdaOutsideParentheses/hasComments.kt.after
- idea/testData/inspectionsLocal/moveLambdaOutsideParentheses/hasComments2.kt
- idea/testData/inspectionsLocal/moveLambdaOutsideParentheses/hasComments2.kt.after
- idea/testData/inspectionsLocal/moveLambdaOutsideParentheses/lambdaWithCommas3.kt.after
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-35357
> KT-35357 "Move lambda argument out of parentheses" does not preserve block comments

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/boxAgainstJava/visibility/protectedAndPackage/protectedSuperField.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxAgainstJavaCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxAgainstJavaCodegenTestGenerated.java
It's only for computing the field owner.
#KT-42131 Fixed
> JVM_IR: do not use fields' superQualifierSymbol to cast the receiver

- plugins/parcelize/parcelize-compiler/testData/codegen/customParcelablesSameModule.ir.txt
- plugins/parcelize/parcelize-compiler/testData/codegen/customSimple.ir.txt
- plugins/parcelize/parcelize-compiler/testData/codegen/customSimpleDeprecated.ir.txt
- plugins/parcelize/parcelize-compiler/testData/codegen/customSimpleWithNewArray.ir.txt
The generated bridges now have line numbers as for the JVM
backend. There are some extra (irrelevant) labels in the JVM_IR
bytecode listing compared to JVM so expectations can still not
be shared even though they are closer.
> [JVM_IR] Fix expectations for parcelize tests.

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FunctionReferenceLowering.kt
- compiler/testData/codegen/box/coroutines/suspendFunctionMethodReference.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
This fixes a build error when compiling [arcs](https://github.com/PolymerLabs/arcs/blob/73da1581cfb4871b89925f67929a86ccd44f2a26/java/arcs/core/storage/DirectStoreMuxer.kt#L77) with the JVM IR backend.
Interestingly enough, the added `testSuspendFunctionMethodReference` currently fails for the JVM backend, but works fine when compiled from the command line.
> JVM IR: Fix types in generated function reference constructor

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrInlineCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/irCodegenUtils.kt
* reduce code duplication for constructing JvmDeclarationOrigin;
* move all `visitor.visitInnerClass` calls to before `visitor.done`;
* make the order of members more strict & remove 3 mutable fields, as order-dependent mutation can lead to differences with incremental compilation due to inline calls (thus keeping mutable state in ClassCodegen is in general unsafe).
> JVM_IR: slightly refactor ClassCodegen

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrInlineCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrInlineReferenceLocator.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FunctionReferenceLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InlineCallableReferenceToLambda.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/RemoveDeclarationsThatWouldBeInlinedLowering.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/suspendConversion/bound.kt
- compiler/testData/codegen/box/callableReference/adaptedReferences/suspendConversion/boundExtension.kt
- compiler/testData/codegen/box/callableReference/equality/suspendConversion.kt
- compiler/testData/codegen/boxInline/callableReference/adapted.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/JvmIrAgainstOldBoxInlineTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/JvmOldAgainstIrBoxInlineTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenInlineES6TestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java
Also, treat adapted function references as lambdas for inlining.
#KT-42021 Fixed
#KT-38536 Fixed
#KT-38535 Fixed
> JVM_IR: fix bound suspend-converted references

- compiler/psi/src/org/jetbrains/kotlin/psi/KtClass.kt
- compiler/psi/src/org/jetbrains/kotlin/psi/KtClassOrObject.kt
Currently it is only possible to get the colon(`:`) from classes.
This changes makes it possible to retrieve the colon from KtObjectDeclarations as well.
> Move getColon from KtClass to KtClassOrObject

- idea/idea-gradle/src/org/jetbrains/kotlin/idea/configuration/KotlinGradleProjectResolverExtension.kt
Use hash table to quickly lookup idea module by gradle project path.
Colleagues from Android Studio team have a CPU snapshot, where line `KotlinGradleProjectResolverExtension.kt:161` takes almost 3 minutes (166 000 ms) of CPU time during import. This patch should mitigate the problem
> Avoid iterating over all idea modules.

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrConversionScope.kt
- compiler/testData/codegen/box/secondaryConstructors/withNonLocalReturn.kt
The motivation is `secondaryConstructors/withNonLocalReturn`, which literally has a non-local return in secondary constructor, which reveals that, when retrieving IR target for the return target, constructor and normal functions should be treated differently (since they're stored in different caches). This should have been done at https://github.com/JetBrains/kotlin/pull/3720.
> FIR2IR: distinguish constructor when picking return target

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/Fir2IrConversionScope.kt
- compiler/testData/codegen/box/secondaryConstructors/innerClasses.kt
- compiler/testData/codegen/box/secondaryConstructors/innerClassesInheritance.kt
The motivation is `secondaryConstructors/innerClasses`:
```kt
class Outer {
inner class A1() {
var prop: ...
constructor(x: String): this() {
prop = x + ...
}
}
}
```
The (secondary) constructor of `Outer.A1` needs `Outer` instance as a dispatch receiver. But, when (implicit) `this` receiver inside that constructor is converted, e.g., `<set-prop>`, the same `Outer`'s `<this>` is used, which supposed to be `Outer.A1`'s `<this>`.
In general, the dispatch receiver for the top function in the conversion scope is the one we're looking for as `this` receiver, but the inner class's constructor should be handled differently.
> FIR2IR: correct dispatch receiver inside inner class constructor

- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ClassGenerator.kt
This allows kotlin-native to generate code in debug mode.
LLVM requires debug attributes for this code and SYNTHETIC_OFFSET
makes kotlin-native generate dummy debug attributes.
> [PSI2IR] Use SYNTHETIC_OFFSET for delegated brigdes.

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/FirCompileKotlinAgainstKotlinTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/MemoizedInlineClassReplacements.kt
- compiler/testData/compileKotlinAgainstKotlin/defaultWithInlineClassAndReceivers.kt
- compiler/tests/org/jetbrains/kotlin/codegen/CompileKotlinAgainstKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstKotlinTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/JvmIrAgainstOldBoxTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/JvmOldAgainstIrBoxTestGenerated.java
If an extension receiver is copied into a normal parameter, this may later cause default argument masks to be shifted.
> JVM_IR: fix copying of receivers when unboxing inline class parameters

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/testData/codegen/box/syntheticAccessors/accessorForAbstractProtected.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/test/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
> JVM_IR: generate accessors for inherited abstract members too

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
More specifically, it should be done *just before* JvmPropertiesLowering, as walking the IR tree between them will result in visiting the moved backing fields twice (once via the companion's parent, once via the IrProperty).
Ideally, this group of 3 lowerings should be merged into 1 as they are completely inseparable, but this is slightly harder to do properly.
#KT-42527 Fixed
> JVM_IR: move MoveOrCopyCompanionObjectFields down a bit

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/InitializersLowering.kt
- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/JsLoweringPhases.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmLocalClassPopupLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SuspendLambdaLowering.kt
- compiler/ir/backend.wasm/src/org/jetbrains/kotlin/backend/wasm/WasmLoweringPhases.kt
- compiler/testData/codegen/box/reflection/lambdaClasses/reflectOnSuspendLambdaInField.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
This loses reflection metadata (and also sometimes fails). Which was missing anyway - this is also fixed now.
#KT-42554 Fixed
> JVM_IR: do not deep-copy suspend lambdas in initializers

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/PropertyReferenceLowering.kt
- compiler/testData/codegen/box/reflection/properties/localDelegated/inLambda.kt
- compiler/testData/codegen/box/reflection/properties/localDelegated/inLambdaInInline.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
Otherwise kotlin-reflect won't find it (and it won't even be serialized anyway). Note that this is separate from the `$$delegatedProperties` field.
Also, refactor PropertyReferenceLowering so that it's not quadratic in the nesting level of classes (90% of that is changing indentation levels).
#KT-42562 Fixed
> JVM_IR: add local delegated property metadata to non-synthetic classes

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/IrUtils.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/DefaultArgumentStubGenerator.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/RangeContainsLowering.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/HeaderProcessor.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/ProgressionType.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/Utils.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/handlers/DefaultProgressionHandler.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/loops/handlers/StepHandler.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/GenerateMultifileFacades.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmDefaultConstructorLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmInnerClassesSupport.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmOverloadsAnnotationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmStaticAnnotationLowering.kt
to make it harder to hide incorrect uses.
> IR: remove unnecessary calls to deepCopyWithSymbols

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/CoroutineCodegen.kt
- idea/jvm-debugger/jvm-debugger-test/testData/stepping/stepInto/stepIntoSuspendFunctionSimple.out
> [JVM_IR] Fix off-by-one line number error in CoroutineCodegen.

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBytecodeTextTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/CompareTo.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/Equals.kt
- compiler/testData/codegen/bytecodeText/deadCodeElimination/unusedPrimitiveAndObjectEquals.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeTextTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeTextTestGenerated.java
Discarding the value used to leave an unused-but-never-destroyed temporary variable. It's best to not separate calls to `enterTemp` and `leaveTemp`.
Not sure what kind of test to add though, since this is minor -- if the result of the comparison is discarded, then the entire statement is more or less pointless.
#KT-42251 Fixed
> JVM_IR: make `primitive == object` slightly less lazy.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InventNamesForLocalClasses.kt
- compiler/testData/checkLocalVariablesTable/objectInLocalPropertyDelegate.kt
- compiler/tests/org/jetbrains/kotlin/codegen/CheckLocalVariablesTableTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrCheckLocalVariablesTableTestGenerated.java
> JVM_IR: generate shorter names for classes in delegate initializers

- compiler/ir/backend.common/src/org/jetbrains/kotlin/ir/builders/declarations/declarationBuilders.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SuspendLambdaLowering.kt
- idea/jvm-debugger/jvm-debugger-test/testData/stepping/stepOver/coroutines/sequenceNested.out
- idea/jvm-debugger/jvm-debugger-test/testData/stepping/stepOver/coroutines/sequenceNested2.ir.out
- idea/jvm-debugger/jvm-debugger-test/testData/stepping/stepOver/coroutines/sequenceSimple.out
- idea/jvm-debugger/jvm-debugger-test/testData/stepping/stepOver/soSuspendableCallInEndOfFun.out
Otherwise, implicit returns in void returning suspend functions
will not have the line number of the end brace.
Fixes KT-41962 and KT-40464.
> [JVM_IR] Copy offsets from the original function to invokeSuspend.

- compiler/fir/analysis-tests/testData/resolveWithStdlib/contracts/fromSource/bad/callsInPlace/inLocalFunction.dot
- compiler/fir/resolve/src/org/jetbrains/kotlin/fir/resolve/dfa/cfg/ControlFlowGraphBuilder.kt
- compiler/testData/diagnostics/tests/controlFlowAnalysis/assignedInIfElse.kt
so that local function enter node can be visited by FIR CFA
The motivation is https://youtrack.jetbrains.com/issue/KT-42814:
```kt
fun foo(arg: Boolean) {
val callToUse: Int
if (arg) {
callToUse = 1
} else {
callToUse = 2
}
fun local(): Int {
return <!UNINITIALIZED_VARIABLE!>callToUse<!>
}
}
```
which is quite similar to https://youtrack.jetbrains.com/issue/KT-42348
The only difference is, the function inside a local class has an incoming edge from the end of the previous expression, along with `CfgForward` kind, whereas the local function has an incoming edge with `DfgForward` kind, which prevents CFA from picking up that edge and legitimate incoming flow.
Similar to the local class exit node, which acts like a `CfgForward` entrance towards function enter, the local function declaration …
> FIR CFG: revise edge kind between local func node and fun enter node

- idea/src/org/jetbrains/kotlin/idea/inspections/RedundantInnerClassModifierInspection.kt
- idea/testData/inspectionsLocal/redundantInnerClassModifier/extendJavaNestedClass.1.java
- idea/testData/inspectionsLocal/redundantInnerClassModifier/extendJavaNestedClass.kt
- idea/testData/inspectionsLocal/redundantInnerClassModifier/extendJavaNestedInterface.1.java
- idea/testData/inspectionsLocal/redundantInnerClassModifier/extendJavaNestedInterface.1.java.after
- idea/testData/inspectionsLocal/redundantInnerClassModifier/extendJavaNestedInterface.kt
- idea/testData/inspectionsLocal/redundantInnerClassModifier/extendJavaNestedInterface.kt.after
- idea/testData/inspectionsLocal/redundantInnerClassModifier/extendJavaNestedStaticClass.1.java
- idea/testData/inspectionsLocal/redundantInnerClassModifier/extendJavaNestedStaticClass.1.java.after
- idea/testData/inspectionsLocal/redundantInnerClassModifier/extendJavaNestedStaticClass.kt
- idea/testData/inspectionsLocal/redundantInnerClassModifier/extendJavaNestedStaticClass.kt.after
- idea/testData/inspectionsLocal/redundantInnerClassModifier/hasConstructorCallOfOuterClassMember.kt
- idea/testData/inspectionsLocal/redundantInnerClassModifier/hasConstructorCallOfOuterClassMember2.kt
- idea/testData/inspectionsLocal/redundantInnerClassModifier/hasConstructorCallOfOuterClassMember3.kt
- idea/testData/inspectionsLocal/redundantInnerClassModifier/hasConstructorCallOfOuterClassMember3.kt.after
- idea/testData/inspectionsLocal/redundantInnerClassModifier/hasOuterClassMemberReferenceInSuperTypeConstructorCall.kt
- idea/testData/inspectionsLocal/redundantInnerClassModifier/hasOuterClassMemberReferenceInSuperTypeConstructorCall2.kt
- idea/tests/org/jetbrains/kotlin/idea/inspections/LocalInspectionTestGenerated.java
https://youtrack.jetbrains.com/issue/KT-40879
https://youtrack.jetbrains.com/issue/KT-41223
https://youtrack.jetbrains.com/issue/KT-41311
https://youtrack.jetbrains.com/issue/KT-41680
> KT-40879 False positive "Redundant 'inner' modifier" when calling another inner class with empty constructor

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/SMAP.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/irCodegenUtils.kt
- idea/jvm-debugger/jvm-debugger-test/testData/stepping/filters/stepIntoMultiFileFacade.out
This is necessary for the intellij debugger filters to hide
these bridges.
Fixes KT-41961.
> [JVM_IR] Use line number 1 for multifile bridge methods.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FunctionReferenceLowering.kt
- compiler/testData/codegen/bytecodeListing/kt42879.kt
- compiler/testData/codegen/bytecodeListing/kt42879.txt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeListingTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeListingTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/generators/tests/GenerateCompilerTests.kt
Currently the names are mangled twice. The only reason things didn't break was that bridge generation added bridges to fix these naming issues.
This fixes the ABI issue in KT-42879 for the JVM IR backend, although KT-42879 remains broken on the JVM backend.
> JVM IR: Fix names for SAM callable references with inline class return types

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/javaInterop/notNullAssertions/privateOperatorParameterAssertions.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
The null check on the extension receiver of private operator functions is a special case and doesn't extend to value parameters.
> JVM IR: Don't generate null checks on value parameters of private operator functions

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/MethodSignatureMapper.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/irCodegenUtils.kt
- compiler/testData/codegen/bytecodeListing/varargsBridge.kt
- compiler/testData/codegen/bytecodeListing/varargsBridge.txt
- compiler/tests/org/jetbrains/kotlin/codegen/BytecodeListingTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBytecodeListingTestGenerated.java
The old backend makes bridges for protected and package-private
methods public. Also, for bridges for vararg methods, the vararg
marker is not on the bridge.
These differences seem minor but are visible via reflection, so
we might as well follow the old backend.
> [JVM_IR] Follow old backend in bridge visibility and varargs marking.

- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/native/CocoaPodsIT.kt
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/cocoapods/KotlinCocoapodsPlugin.kt
As sdk developers we would like to have possibility to specify a concrete list of architectures to build as fat framework. When clients of ours would like to use the framework they need to be able to run it on both iPhone and Simulator.
Therefore in this PR I am proposing a change that allows to dynamically specify a list of architectures with comma separated manner. Rest of the functionality stays untouched, meaning user still can provide just one target if they wish.
> kotlin.native.cocoapods.targets can be a custom list of architectures

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/kotlinTargets.kt
AbstractKotlinTarget#buildAdhocComponentsFromKotlinVariants passes a
non-serializable local object to a lambda, which will fail during
serialization when configuration caching is enabled.
To fix that, this commit passes only the relevant parts of the object
to the lambda.
Bug: KT-43054
Test: Manually verified on
https://android.googlesource.com/platform/tools/metalava/+/refs/heads/master/
where the issue was detected (I haven't been able to create a mininal
reproducible project)
> Fix configuration cache issue in AbstractKotlinTarget

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxAgainstJavaCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FunctionReferenceLowering.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/types/IrTypeSystemContext.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/IrUtils.kt
- compiler/testData/codegen/boxAgainstJava/varargs/varargsOverride.kt
- compiler/testData/codegen/boxAgainstJava/varargs/varargsOverride2.kt
- compiler/testData/codegen/boxAgainstJava/varargs/varargsOverride3.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxAgainstJavaCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxAgainstJavaCodegenTestGenerated.java
When calling vararg methods with a generic vararg type without
passing explicit parameters, we have to allocate an empty array
of the right type. We failed to do so previously, as we did
not take the type arguments for the dispatch receiver into
account.
> [JVM_IR] Determine correct type of empty varargs array.

- compiler/fir/fir2ir/tests/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendContext.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmStaticAnnotationLowering.kt
- compiler/testData/codegen/box/jvmStatic/functionReference.kt
- compiler/tests/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
Do not destructively update @JvmStatic functions in objects,
instead create a copy on first access, and replace the original with
the copy in the jvm static lowering. This ensures that the original
function is seen in other lowerings independently of file lowering
order.
> [JVM_IR] Deal with lowering ordering for JvmStatic function references

- plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/common/TypeUtil.kt
Fixes Kotlin/kotlinx.serialization#984
> Add support of nullable serializers to UseSerializers annotation

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/defaultMethodUtil.kt
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/codegen/ir/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrTypeMapper.kt
- compiler/testData/codegen/box/coroutines/kt42554.kt
- compiler/testData/codegen/box/defaultArguments/function/defaultLambdaInline.kt
- compiler/testData/codegen/boxInline/defaultValues/lambdaInlining/genericLambda.kt
- compiler/testData/codegen/boxInline/defaultValues/lambdaInlining/simpleGeneric.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/D8Checker.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/IrBlackBoxCodegenTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
If we do, the local variable table will not make sense. As as
example:
```
inline fun foo(getString: () -> String = { "OK" }) {
println(getString())
}
inline fun bar() {
}
fun main() {
bar()
foo()
}
```
leads to the following bytecode:
```
public static final void main();
descriptor: ()V
flags: ACC_PUBLIC, ACC_STATIC, ACC_FINAL
Code:
stack=2, locals=4, args_size=0
0: iconst_0
1: istore_0
2: nop
3: nop
4: iconst_0
5: istore_1
6: nop
7: ldc           #53                 // String OK
9: astore_2
10: iconst_0
11: istore_3
12: getstatic     #30                 // Field java/lang/System.out:Ljava/io/PrintStream;
15: aload_2
16: invokevirtual #36                 // Method java/io/PrintStream.println:(Ljava/lang/Object;)V
19: nop
20: return
LineNumberTable:
line 9: 0
line 13: 2
line 10: 3
line …
```
> [JVM] Do not put the name of default lambda parameter in LVT.

- compiler/cli/bin/kotlinc.bat
- plugins/kapt3/kapt3-cli/test/org/jetbrains/kotlin/kapt/cli/test/AbstractArgumentParsingTest.kt
- plugins/kapt3/kapt3-cli/test/org/jetbrains/kotlin/kapt/cli/test/AbstractKaptToolIntegrationTest.kt
- plugins/kapt3/kapt3-cli/testData/integration/argfile/kaptArgs.txt
- Fix line separator issue
- Always quote args with delimiters (=, :)
- fix one of args files by removing obsolete stdlib reference
- Fix kotlinc.bat to ensure lazy evaluation of additional classpath
> Fix KAPT cli tests on windows

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/codegen/ir/FirBlackBoxInlineCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrInlineReferenceLocator.kt
- compiler/testData/codegen/boxInline/anonymousObject/kt42815.kt
- compiler/testData/codegen/boxInline/anonymousObject/kt42815_delegated.kt
- compiler/tests-gen/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/JvmIrAgainstOldBoxInlineTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/JvmOldAgainstIrBoxInlineTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenInlineES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java
Allow to inline anonymous objects from `init` block to several constructors
Mostly it's a workaround to avoid assertion on generating `init` block in several constructors
#KT-42815 Fixed
> Allow to inline anonymous objects from `init` block to several constructors

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SuspendLambdaLowering.kt
- compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/dataClass.kt
- compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/extensionComponents.kt
- compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/generic.kt
- compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/otherParameters.kt
- compiler/testData/checkLocalVariablesTable/parametersInSuspendLambda/parameters.kt
- compiler/testData/codegen/bytecodeText/coroutines/debug/localVariableCorrectLabel.kt
- compiler/testData/debug/localVariables/suspend/underscoreNames.kt
- idea/jvm-debugger/jvm-debugger-test/test/org/jetbrains/kotlin/idea/debugger/test/IrKotlinEvaluateExpressionTestGenerated.java
- idea/jvm-debugger/jvm-debugger-test/test/org/jetbrains/kotlin/idea/debugger/test/KotlinEvaluateExpressionTestGenerated.java
- idea/jvm-debugger/jvm-debugger-test/testData/evaluation/singleBreakpoint/coroutines/capturedReceiverName.kt
- idea/jvm-debugger/jvm-debugger-test/testData/evaluation/singleBreakpoint/coroutines/capturedReceiverName.out
The existing backend restores LVs and parameters from the suspend lambda
fields used for spilling between suspension points, hence they are
visible in the debugger as local variables, plain and simple.
This PR introduces the same pattern to the IR backend, to bring the
debugging experience in line with the existing backend.
Both backends are still at the mercy of the liveness analysis
performed in the coroutine transformer where a liveness analysis
minimizes live ranges of entries in the LVT. E.g. an unused parameter
will be dropped entirely.
Adjusted existing test expectations accounting for the differences in
LV behavior.
> [IR] Align debugging of suspend lambdas with old BE

- compiler/fir/fir2ir/src/org/jetbrains/kotlin/fir/backend/generators/AdapterGenerator.kt
- compiler/testData/codegen/box/coroutines/suspendFunctionMethodReference.kt
The motivation is bb test `coroutines/suspendFunctionMethodReference`:
```kt
fun f(a: suspend () -> Unit) {
val f = a::invoke
...
}
```
That `invoke` from external stub has a type parameter `R` as a return type, and is determined as a candidate for generating coercion-to-Unit adapter, which shouldn't be the case.
> FIR2IR: check non-parameter Unit type for adapted callable references

- ant/src/org/jetbrains/kotlin/ant/Kotlin2JvmTask.kt
- ant/src/org/jetbrains/kotlin/ant/KotlinCompilerBaseTask.kt
- compiler/testData/integration/ant/jvm/fork/build.log.expected
- compiler/testData/integration/ant/jvm/fork/build.xml
- compiler/testData/integration/ant/jvm/fork/hello.kt
- compiler/testData/integration/ant/jvm/fork/premain/Premain.java
- compiler/testData/integration/ant/jvm/forkOnError/build.log.expected
- compiler/testData/integration/ant/jvm/forkOnError/build.xml
- compiler/testData/integration/ant/jvm/forkOnError/premain/Premain.java
- compiler/testData/integration/ant/jvm/forkOnError/test.kt
- compiler/tests-gen/org/jetbrains/kotlin/integration/AntTaskTestGenerated.java
Without support for fork-mode, a OOM error can be produced like below.  Since tasks ```java``` and ```javac``` both support fork-mode in Ant, it is better to have a fork-mode supported by the task ```kotlinc``` I think.
```
D:\Github-scaventz\lwjgl3\build.xml:204: java.lang.OutOfMemoryError: Java heap space
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:109)
at org.apache.tools.ant.Task.perform(Task.java:350)
at org.apache.tools.ant.Target.execute(Target.java:449)
at org.apache.tools.ant.Target.performTasks(Target.java:470)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at …
```
> Ant: Add support for fork-mode

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/npm/KotlinNpmResolutionManager.kt
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/npm/tasks/KotlinPackageJsonTask.kt
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/npm/tasks/RootPackageJsonTask.kt
in Android Studio, before run a gradle task, AS will configure the project, this will download all dependencies which call `KotlinCompilationNpmResolver.resolve()` function, and in `RootPackageJsonTask` and `KotlinPackageJsonTask`, `KotlinCompilationNpmResolver.resolve()` function will be called twice, and it errors.
this first call stack is:
```
at org.jetbrains.kotlin.gradle.targets.js.npm.resolver.KotlinCompilationNpmResolver.resolve(KotlinCompilationNpmResolver.kt:100)
at org.jetbrains.kotlin.gradle.targets.js.npm.resolver.KotlinCompilationNpmResolver.resolve$default(KotlinCompilationNpmResolver.kt:99)
at org.jetbrains.kotlin.gradle.targets.js.npm.resolver.KotlinCompilationNpmResolver.getResolutionOrResolveIfForced(KotlinCompilationNpmResolver.kt:116)
at …
```
> KT-43818：NPM Dependencies already resolved and installed in Android Studio

- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/Kapt3AndroidIT.kt
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/android-databinding-androidX/app/build.gradle
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/android-databinding-androidX/app/src/main/AndroidManifest.xml
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/android-databinding-androidX/app/src/main/java/com/example/databinding/MyBindingMethods.kt
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/android-databinding-androidX/build.gradle
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/android-databinding-androidX/gradle.properties
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/android-databinding-androidX/settings.gradle
- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/internal/kapt/Kapt3KotlinGradleSubplugin.kt
This is so AGP does not try to apply AndroidX substitution
to dependencies found in the annotation processor classpath.
AGP does this by checking if the configuration name starts
with "kapt".
Test: Kapt3Android42IT
> KT-44020: Rename KAPT configuration used as task property

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/codegen/FirCompileKotlinAgainstKotlinTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/irCodegenUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/MemoizedInlineClassReplacements.kt
- compiler/testData/compileKotlinAgainstKotlin/inlineClassInlineFunctionCall.kt
- compiler/tests-gen/org/jetbrains/kotlin/codegen/CompileKotlinAgainstKotlinTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstKotlinTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/JvmIrAgainstOldBoxTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/JvmOldAgainstIrBoxTestGenerated.java
When resolving inline class methods in binary dependencies we look for methods matching both the new and the old mangling scheme.
On the IR backend the method signature has to be computed for the inline class replacement, since the logic for signature mangling is not contained in the method signature mapping, unlike in the old backend.
> JVM IR: Fix signature mapping for inline classes using new the mangling scheme

- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirMemberFunctionChecker.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirMemberPropertyChecker.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/diagnostics/FirDefaultErrorMessages.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/diagnostics/FirErrors.kt
1st commit adds error messages for property/accessor diagnostics, which should have done at #3952 
2nd commit adds error messages for destructuring declaration diagnostic, which should have done at #4032 
3rd commit adds error messages for function diagnostics, which should have done at #4035 
Also, error inputs are slightly adjusted to conform to old FE's.
> FIR checker: add missed error messages so far

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/testData/codegen/bytecodeListing/accessorForTopLevelMembers.kt
- compiler/testData/codegen/bytecodeListing/accessorForTopLevelMembers.txt
- compiler/testData/codegen/bytecodeListing/accessorForTopLevelMembers_ir.txt
- compiler/tests-gen/org/jetbrains/kotlin/codegen/BytecodeListingTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/IrBytecodeListingTestGenerated.java
- plugins/parcelize/parcelize-compiler/testData/codegen/customSimple.ir.txt
- plugins/parcelize/parcelize-compiler/testData/codegen/customSimpleWithNewArray.ir.txt
The super suffix was used for any static field/method that needed
an accessor. We should only use it when that field or method is
inherited.
> [JVM_IR] Reduce the amount of `super` suffixes on accesibility bridges.

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/MethodInliner.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/TransformationInfo.kt
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/codegen/ir/FirBlackBoxInlineCodegenTestGenerated.java
- compiler/testData/codegen/boxInline/anonymousObject/constructOriginalInRegenerated.kt
- compiler/tests-gen/org/jetbrains/kotlin/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/JvmIrAgainstOldBoxInlineTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/JvmOldAgainstIrBoxInlineTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenInlineES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java
This is a hack to work around the fact that type mappings should not be inherited by inlining contexts for lambdas called from anonymous objects. As the lambda can call the inline function again, this could produce a reference to the original object, which is remapped to a new type in the parent context. Unfortunately, there are many redundant `MethodRemapper`s between the lambda and the class file, so simply editing `TypeRemapper` does not work. Hence, this hack. For now.
(Issue found by compiling IntelliJ IDEA BTW.)
> JVM: regenerate objects if they have been regenerated in parent contexts

- compiler/testData/debug/localVariables/suspend/completion/nonStaticStateMachine.kt
- compiler/testData/debug/localVariables/suspend/completion/staticStateMachine.kt
- compiler/testData/debug/localVariables/suspend/completion/staticStateMachineReceiver.kt
- compiler/testData/debug/localVariables/suspend/inlineLocalsStateMachineTransform.kt
- compiler/testData/debug/localVariables/suspend/localsStateMachineTransform.kt
- compiler/testData/debug/localVariables/suspend/underscoreNames.kt
- compiler/testData/debug/stepping/suspendFunWithSuspendLambdaParameter.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/debugInformation/AbstractDebugTest.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/debugInformation/AbstractLocalVariableTest.kt
- compiler/tests-common/tests/org/jetbrains/kotlin/codegen/debugInformation/AbstractSteppingTest.kt
This solves no immediate deficiency, but is a to-do that arose as part
of an ongoing effort to port the old, slightly too restrictive
checkLocalVariableTable tests to the more "functional" debugger
infrastructure.
This just shaves a little bit of overhead off the test expectations
and couples them less tightly to the specifics of the test
infrastructure.
> [Test] Ignore test helpers in debugging tests

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/codegen/FirCompileKotlinAgainstKotlinTestGenerated.java
- compiler/incremental-compilation-impl/test/org/jetbrains/kotlin/incremental/IncrementalMultiModuleJsCompilerRunnerTestGenerated.java
- compiler/incremental-compilation-impl/test/org/jetbrains/kotlin/incremental/IncrementalMultiModuleJsKlibCompilerRunnerTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/MethodSignatureMapper.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/irCodegenUtils.kt
- compiler/testData/compileKotlinAgainstKotlin/internalWithInlineClass.kt
- compiler/tests-gen/org/jetbrains/kotlin/codegen/CompileKotlinAgainstKotlinTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/IrCompileKotlinAgainstKotlinTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/JvmIrAgainstOldBoxTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/JvmOldAgainstIrBoxTestGenerated.java
This can happen when using `-Xfriend-paths`.
> JVM IR: Fix inline class mangling for calls to internal functions in a different module

- compiler/testData/diagnostics/ReadMe.md
The `testData/diagnostics/ReadMe.md` suggests to use `!` to exclude everything but one diagnostic.
That's actually not supported, and doing so will cause all the diagnostic tests to fail:
https://github.com/JetBrains/kotlin/blob/e7c4121e6785d1ac4cd7633066b4662ea3a23248/compiler/tests-common-new/tests/org/jetbrains/kotlin/test/services/DiagnosticsService.kt#L30-L34
The error messages mentions to use only `+` and `-`:
https://github.com/JetBrains/kotlin/blob/e7c4121e6785d1ac4cd7633066b4662ea3a23248/compiler/tests-common-new/tests/org/jetbrains/kotlin/test/directives/DiagnosticsDirectives.kt#L18-L26
> Remove unsupported '!' from DIAGNOSTICS directive

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/testData/codegen/bytecodeListing/accessorsForProtectedStaticJavaFieldInOtherPackage.kt
- compiler/testData/codegen/bytecodeListing/accessorsForProtectedStaticJavaFieldInOtherPackage.txt
- compiler/testData/codegen/bytecodeListing/accessorsForProtectedStaticJavaFieldInOtherPackage_ir.txt
- compiler/tests-gen/org/jetbrains/kotlin/codegen/BytecodeListingTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/ir/IrBytecodeListingTestGenerated.java
Super-qualifiers have to be taken into account. Otherwise, too
few accessibility bridges will be generated which can lead to
binary compatibility issues.
> [JVM_IR] Fix accessibility bridges for static protected fields.

- compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/CompileEnvironmentUtil.java
- compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/KotlinToJVMBytecodeCompiler.kt
- compiler/cli/src/org/jetbrains/kotlin/cli/jvm/jvmArguments.kt
- compiler/config.jvm/src/org/jetbrains/kotlin/config/JVMConfigurationKeys.java
- compiler/testData/integration/smoke/noReflect/noReflect.compile.expected
- compiler/testData/integration/smoke/noReflect/noReflect.kt
- compiler/testData/integration/smoke/noReflect/noReflect.run.expected
- compiler/testData/integration/smoke/reflect/reflect.compile.expected
- compiler/testData/integration/smoke/reflect/reflect.kt
- compiler/testData/integration/smoke/reflect/reflect.run.expected
- compiler/tests/org/jetbrains/kotlin/integration/CompilerSmokeTest.java
We should Include ```kotlin-reflect``` to resulting jar when option ```-include-runtime``` is specified  and option ```-no-reflect``` is not. For more details, please see [KT-17344](https://youtrack.jetbrains.com/issue/KT-17344)  && [KT-43220 ](https://youtrack.jetbrains.com/issue/KT-43220).
> kotlinc: Include kotlin-reflect to resulting jar when option -include-runtime is specified and option -no-reflect is not

- ReadMe.md
`brew tap caskroom/versions` is no longer valid, so we should use `brew tap homebrew/cask-versions` instead.
`brew cask install` is disabled, should use `brew install --cask` instead.
> Update steps to install JDK 6 on Mac OS

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBytecodeTextTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/SwitchGenerator.kt
- compiler/testData/codegen/bytecodeText/when/switchOptimizationDuplicates.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/bigEnum.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/duplicatingItems.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/expression.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/manyWhensWithinClass.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/nullability.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/whenOr.kt
- compiler/testData/codegen/bytecodeText/whenEnumOptimization/withoutElse.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/duplicatingItems.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/expression.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/inlineStringConstInsideWhen.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/nullability.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/sameHashCode.kt
- compiler/testData/codegen/bytecodeText/whenStringOptimization/statement.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BytecodeTextTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBytecodeTextTestGenerated.java
FIR translates:
```
when (x) {
1, 2, 3 -> action
else -> other_action
}
```
to an IR structure with nested ors:
```
if ((x == 1 || x == 2) || (x == 3)) action
else other_action
```
This change allows that to turn into switch instructions in the
JVM backend.
> [JVM_IR] Extend when to switch translation to deal with nested ors.

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/AnonymousObjectTransformer.kt
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxInlineCodegenTestGenerated.java
- compiler/testData/codegen/boxInline/anonymousObject/twoCapturedReceivers/kt8668_nested.kt
- compiler/testData/codegen/boxInline/anonymousObject/twoCapturedReceivers/kt8668_nested_2.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/JvmIrAgainstOldBoxInlineTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/JvmOldAgainstIrBoxInlineTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenInlineES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java
In the old backend, this was unnecessary because nested objects would reference their lambdas' captures through the original this$0. On JVM_IR, using loose capture fields means a name/descriptor clash can occur on any level of nesting, not just the top.
> JVM: rename this$0 when regenerating nested objects too

- idea/idea-frontend-independent/src/org/jetbrains/kotlin/idea/quickfix/AddFunctionBodyFix.kt
This is a mechanical change. Only logic change is removing the
apparenly unneeded `allowCachedResolveInDispatchThread` check in
`AddFunctionBodyFix.isAvailableImpl()`.
> FIR IDE: Move AddFunctionBodyFix to fe-independent

- idea/idea-frontend-independent/src/org/jetbrains/kotlin/idea/quickfix/AddModifierFix.kt
- idea/src/org/jetbrains/kotlin/idea/inspections/AddModifierFixFactory.kt
- idea/src/org/jetbrains/kotlin/idea/inspections/LeakingThisInspection.kt
- idea/src/org/jetbrains/kotlin/idea/inspections/MemberVisibilityCanBePrivateInspection.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/AddConstModifierFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/AddDataModifierFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/AddInlineModifierFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/AddInlineToFunctionWithReifiedFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/AddModifierFixMpp.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/AddReifiedToTypeParameterOfFunctionFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/AddSuspendModifierFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/MakeTypeParameterReifiedAndFunctionInlineFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/crossLanguage/KotlinElementActionsFactory.kt
- nj2k/nj2k-services/src/org/jetbrains/kotlin/nj2k/postProcessing/J2kPostProcessor.kt
This change strips the MPP part off AddModifierFix and create a new fix
AddModifierFixMpp that behaves exactly as the original fix in FE1.0.
In addition, the original fix checks if the element belongs to project source
and report it's availability accordingly. Part of this check requires FE1.0
logic to determine if the source is in a Kotlin script. It looks like porting
this check to FIR is infeasible at the moment. Hence the availability check in
the FIR version of AddModifierFix is simplified. AFAIK, this should be fine
since in the other cases, this check won't be reported in the first place for
library code.
> FIR IDE: Split and AddModifierFix to fe-independent

- plugins/kotlin-serialization/kotlin-serialization-compiler/testData/codegen/Basic.ir.txt
`shouldEncodeElementDefault` now checked before evaluating default value
> Updated bytecode of serialization for IR

- idea/idea-fir/src/org/jetbrains/kotlin/idea/fir/api/fixes/KtQuickFixesList.kt
- idea/idea-fir/src/org/jetbrains/kotlin/idea/quickfix/MainKtQuickFixRegistrar.kt
- idea/idea-frontend-independent/src/org/jetbrains/kotlin/idea/quickfix/RemoveModifierFix.kt
- idea/src/org/jetbrains/kotlin/idea/quickfix/QuickFixRegistrar.kt
- nj2k/nj2k-services/src/org/jetbrains/kotlin/nj2k/postProcessing/J2kPostProcessor.kt
This change makes it possible to register multiple fixes for a
diagnostic. Also, the previous registerPsiQuickFix that relies compiler
to infer the KtFirDiagnostic type parameter is dangerous since it
can silently register fixes on interface `KtDiagnosticWithPsi` if caller
doesn't specify it explicitly.
> FIR IDE: Simplify registerPsiQuickFixes

- compiler/fir/checkers/checkers-component-generator/src/org/jetbrains/kotlin/fir/checkers/generator/diagnostics/FirDiagnosticsList.kt
- compiler/fir/checkers/gen/org/jetbrains/kotlin/fir/analysis/diagnostics/FirErrors.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirDeclarationCheckerUtils.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirMemberPropertyChecker.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirTopLevelPropertyChecker.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/diagnostics/FirDefaultErrorMessages.kt
- compiler/fir/raw-fir/light-tree2fir/src/org/jetbrains/kotlin/fir/lightTree/converter/DeclarationsConverter.kt
- compiler/fir/raw-fir/light-tree2fir/tests/org/jetbrains/kotlin/fir/lightTree/TotalKotlinTest.kt
- compiler/fir/raw-fir/psi2fir/src/org/jetbrains/kotlin/fir/builder/RawFirBuilder.kt
- compiler/fir/raw-fir/psi2fir/tests/org/jetbrains/kotlin/fir/builder/RawFirBuilderTotalKotlinTestCase.kt
- compiler/testData/diagnostics/tests/Properties.fir.kt
- idea/idea-completion/testData/basic/common/CompletionInSetter.kt
- idea/idea-fir/src/org/jetbrains/kotlin/idea/quickfix/MainKtQuickFixRegistrar.kt
- idea/idea-frontend-fir/src/org/jetbrains/kotlin/idea/frontend/api/fir/diagnostics/KtFirDataClassConverters.kt
- idea/idea-frontend-fir/src/org/jetbrains/kotlin/idea/frontend/api/fir/diagnostics/KtFirDiagnostics.kt
- idea/idea-frontend-fir/src/org/jetbrains/kotlin/idea/frontend/api/fir/diagnostics/KtFirDiagnosticsImpl.kt
- idea/testData/quickfix/variables/changeMutability/valWithSetter.kt
- idea/testData/quickfix/variables/changeMutability/valWithSetter.kt.after
The changes to FIR building were necessary as no `FirPropertyAccessor` was created for a setter inside a `val` property.
> FIR checker/IDE: Add checker and quickfix for VAL_WITH_SETTER

- idea/idea-frontend-fir/idea-fir-low-level-api/src/org/jetbrains/kotlin/idea/fir/low/level/api/lazy/resolve/FirLazyDeclarationResolver.kt
Apparently there is a race condition when collecting the `fromPhase`.
The change moves the read inside a lock to avoid the race condition.
This causes the same resolver to run multiple times on FIR.
> FIR IDE: fix redundant resolve [#KT-45121]

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/testData/codegen/box/binaryOp/kt44402.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- core/descriptors/src/org/jetbrains/kotlin/types/TypeUtils.kt
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
> [JVM IR] Make upper bounds check recursive for ieee Equals.

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LocalDeclarationsLowering.kt
- compiler/testData/codegen/box/annotations/javaAnnotationOnSecondaryConstructorOfLocalClass.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
LocalDeclarationsLowering did not move annotations when creating
a new constructor declaration, thereby losing the annotations.
Fixes KT-45298
> [IR] Move annotations from original to new constructor declarations.

- compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/CompileEnvironmentUtil.java
This bug was introduced by #4080
https://github.com/JetBrains/kotlin/pull/4080#issuecomment-791598992
> Kotlinc: Fix the NullPointerException when pathname does not name a parent.

- compiler/cli/bin/kotlinc
- compiler/cli/bin/kotlinc.bat
- compiler/tests/org/jetbrains/kotlin/cli/LauncherScriptTest.kt
Related to [KT-40977](https://youtrack.jetbrains.com/issue/KT-40977)
> CLI: Report a readable diagnostic on empty -J argument in CLI.

- compiler/backend/src/org/jetbrains/kotlin/codegen/optimization/common/Util.kt
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/KaptIncrementalIT.kt
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kaptIncrementalCompilationProject/src/main/java/delegate/Delegate.kt
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kaptIncrementalCompilationProject/src/main/java/delegate/Usage.kt
KAPT uses light classes, where methods don't have bodies. In incremental compilation there is some cases when we get empty instructions list from such methods. It leads to NPE
> KT-45032 Don't fail on empty InsnList

- libraries/stdlib/jvm/runtime/kotlin/jvm/internal/DefaultConstructorMarker.java
- libraries/tools/binary-compatibility-validator/reference-public-api/kotlin-stdlib-runtime-merged.txt
DefaultConstructorMarker is used as a marker to ensure that a
constructor is unique for companion objects. Prior to this change,
DefaultConstructorMarker was package private.
Being package private worked when calling the
DefaultConstructorMarker-marked constsructor using `invokespecial`,
likely because the JVM may not perform strict access checks in this
situation.
However, when access checks are performed, trying to call a
DefaultConstructorMarker-marked constructor will fail. This could happen
if the constructor was called using reflection or the MethodHandle API.
These APIs may be used by tools that perform bytecode instrumentation
on Kotlin JVM bytecode, such as Robolectric. It also caused problems
when using ByteBuddy validation.
Fixes https://youtrack.jetbrains.com/issue/KT-20869
> Make kotlin.jvm.internal.DefaultConstructorMarker public

- idea/idea-frontend-fir/idea-fir-low-level-api/src/org/jetbrains/kotlin/idea/fir/low/level/api/file/structure/FileStructureElement.kt
Currently the IDE skips checking the delegated constructor call because
the primary constructor is generated if it's declared with the class.
> FIR IDE: check generated primary constructor

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/InlineCodegen.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/PsiInlineCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrInlineCallGenerator.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrInlineCodegen.kt
- compiler/testData/diagnostics/testsWithJvmBackend/propertyInlineCycle.kt
- compiler/testData/diagnostics/testsWithJvmBackend/propertyInlineCycle.txt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/DiagnosticsTestWithJvmIrBackendGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/DiagnosticsTestWithOldJvmBackendGenerated.java
1. use the correct descriptor in the old backend;
2. clear the temporary variables for arguments in the IR backend.
#KT-45292 Fixed
> JVM: fix inline cycle detection

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/controlStructures/breakContinueInExpressions/breakInLoopConditions.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
This breaks from the loop itself which is inconsistent with
what happens for breaks in while conditions.
Also, the frontend will report that code after the loop is
unreachable, which it isn't. :-\
However, those issues are covered in
https://youtrack.jetbrains.com/issue/KT-17728, so for now
we follow the old backend to not "break" anyone. :)
Fixes KT-44412
> [JVM IR] Support break in do-while condition.

- compiler/testData/integration/smoke/destinationDirNoPermission/test.notWindows.compile.expected
- compiler/testData/integration/smoke/destinationJarNoPermission/test.notWindows.compile.expected
- compiler/tests/org/jetbrains/kotlin/integration/CompilerSmokeTest.java
This PR contains the following:
- Add a test to for the situation where pathname of destination does not name a parent, it is related to #4183 ;
- Make sure we test the original issue at least on Linux, this is related to https://github.com/JetBrains/kotlin/pull/4080#discussion_r587750927 ;
- Minor: suppress the warning "ignored method call result" .
> kotlinc: Add a test to for the situation where pathname of destination does not name a parent

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSymbols.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/EnumClassLowering.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/EnumClassMembersGenerator.kt
- compiler/testData/codegen/bytecodeText/enum/enumCheckcasts.kt
- compiler/testData/ir/sourceRanges/declarations/classes.txt
These are all minor, but there are tools out there which seem to be very sensitive to the code in enum classes:
- Use `Object.clone` in the `Enum.values` function rather than arraycopy.
- Don't produce a null check in `Enum.valueOf`. The JVM backend doesn't and it's superfluous since `java.lang.Enum.valueOf` includes a null check.
- Don't produce line numbers in `Enum.values` and `Enum.valueOf`.
> JVM IR: Minor changes to Enum codegen to align with the JVM backend

- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/Kapt3IT.kt
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/build.gradle
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/gradle.properties
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/src/main/java/dagger_example/ApplicationComponent.java
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/src/main/java/dagger_example/ExampleModule.java
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/src/main/java/dagger_example/Main.java
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/src/main/java/dagger_example/OtherInjected.java
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/src/main/java/dagger_example/OtherInjectedImpl.java
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/src/main/java/module-info.java
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/src/main/kotlin/dagger_example/InjectedClass.kt
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/src/main/kotlin/dagger_example/SomeOtherClass.kt
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/src/main/kotlin/lab/test.kt
- libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/resources/testProject/kapt2/jpms-module/src/main/kotlin/test/ModuleUser.kt
- plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/KaptContext.kt
- plugins/kapt3/kapt3-base/src/org/jetbrains/kotlin/kapt3/base/annotationProcessing.kt
Disable jpms for kapt, because modules will be validated in kotlin compiler and in javac anyway.
> [KAPT] KT-32202 JPMS support

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrCallableMethod.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/MethodSignatureMapper.kt
- compiler/testData/codegen/box/inlineClasses/kt44867.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
Note that this PR doesn't fix the problem on the old backend.
> JVM IR: Resolve fake overrides when calculating return types (KT-44867)

- core/descriptors/src/org/jetbrains/kotlin/descriptors/impl/ModuleDescriptorImpl.kt
Besides favoring gender neutral language where you can, I think it reads like a strange anthropomorphization to refer to code with pronouns of any gender. It seemed so strange to me, that I did a double take, thinking maybe it was an acronym at first.
> Change pronoun in execption from "his" to "its"

- idea/idea-fir/src/org/jetbrains/kotlin/idea/fir/api/applicator/HLApplicator.kt
- idea/idea-fir/src/org/jetbrains/kotlin/idea/fir/api/fixes/HLDiagnosticFixFactory.kt
- idea/idea-fir/src/org/jetbrains/kotlin/idea/fir/api/fixes/KtQuickFixesList.kt
- idea/idea-fir/src/org/jetbrains/kotlin/idea/fir/applicators/CallableReturnTypeUpdaterApplicator.kt
- idea/idea-fir/src/org/jetbrains/kotlin/idea/quickfix/fixes/ChangeReturnTypeOnOverrideQuickFix.kt
- idea/idea-fir/src/org/jetbrains/kotlin/idea/quickfix/fixes/ReplaceCallFixFactories.kt
This PR has the following commits
FIR IDE: remove type parameter `TARGET_PSI` and `INPUT`
====
The factory does not need to care about what target PSI and input a quick
fix should need. We only need to ensure these two types match when an
`HLQuickfix` is created. With this constraint loosened, now one factory can
register multiple quickfixes applied on different targets and different
input. This makes it much more flexible when implementing quickfixes.
FIR IDE: remove type parameter `DIAGNOSTIC_PSI`
====
This information is already determined by `DIAGNOSTIC` so there is no need
to repeat it.
FIR IDE: tweak nullability of applyTo
====
It looks like `project` can never be null
It seems unnecessary to force all quickfixes to fit the `HLQuickfix`
API, especially for those existing trivial …
> FIR IDE: simplify HLDiagnosticFixFactory

- compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/checkers/ExternalFunChecker.kt
- compiler/testData/diagnostics/testsWithStdLib/native/nonFunction.kt
- idea/idea-fir/tests/org/jetbrains/kotlin/idea/quickfix/HighLevelQuickFixTestGenerated.java
- idea/testData/quickfix/modifiers/removeExternalModifier.kt
- idea/testData/quickfix/modifiers/removeExternalModifier.kt.after
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
Report `WRONG_MODIFIER_TARGET` on the modifier instead of the declaration in `ExternalFunChecker`. This allows `RemoveModifierFix` to provide a quickfix to remove it.
> Provide quickfix for wrong `external` modifier on declarations

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmCachedDeclarations.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmStaticAnnotationLowering.kt
- compiler/testData/codegen/box/jvmStatic/companionObjectProtected.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
Protected functions on unrelated classes cannot be called from outside the current package, so in general, we can only call the static proxy, not the original companion method.
This has an ABI compatibility implication in that removing `@JvmStatic` from a protected companion method will require recompiling Kotlin use sites (of course, this is already source- and binary-incompatible from Java perspective).
#KT-12063 Fixed
> JVM_IR: remap calls to protected `@JvmStatic` in companions

- compiler/fir/checkers/checkers-component-generator/src/org/jetbrains/kotlin/fir/checkers/generator/CheckersConfiguration.kt
- compiler/fir/checkers/checkers-component-generator/src/org/jetbrains/kotlin/fir/checkers/generator/Generator.kt
- compiler/fir/checkers/checkers-component-generator/src/org/jetbrains/kotlin/fir/checkers/generator/Main.kt
- compiler/fir/checkers/checkers-component-generator/src/org/jetbrains/kotlin/fir/checkers/generator/diagnostics/FirDiagnosticsList.kt
- compiler/fir/checkers/gen/org/jetbrains/kotlin/fir/analysis/checkers/declaration/ComposedDeclarationCheckers.kt
- compiler/fir/checkers/gen/org/jetbrains/kotlin/fir/analysis/checkers/declaration/DeclarationCheckers.kt
- compiler/fir/checkers/gen/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirDeclarationCheckerAliases.kt
- compiler/fir/checkers/gen/org/jetbrains/kotlin/fir/analysis/checkers/expression/ComposedExpressionCheckers.kt
- compiler/fir/checkers/gen/org/jetbrains/kotlin/fir/analysis/checkers/expression/ExpressionCheckers.kt
- compiler/fir/checkers/gen/org/jetbrains/kotlin/fir/analysis/diagnostics/FirErrors.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirFunctionNameChecker.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/expression/FirUpperBoundViolatedChecker.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/collectors/components/DeclarationCheckersDiagnosticComponent.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/collectors/components/ExpressionCheckersDiagnosticComponent.kt
- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/diagnostics/FirDefaultErrorMessages.kt
- compiler/fir/entrypoint/src/org/jetbrains/kotlin/fir/checkers/CommonDeclarationCheckers.kt
- idea/idea-frontend-fir/src/org/jetbrains/kotlin/idea/frontend/api/fir/diagnostics/KtFirDataClassConverters.kt
- idea/idea-frontend-fir/src/org/jetbrains/kotlin/idea/frontend/api/fir/diagnostics/KtFirDiagnostics.kt
- idea/idea-frontend-fir/src/org/jetbrains/kotlin/idea/frontend/api/fir/diagnostics/KtFirDiagnosticsImpl.kt
- idea/testData/checker/Bounds.fir.kt
- idea/testData/checker/Bounds2.fir.kt
- idea/testData/checker/BoundsWithSubstitutors.fir.kt
- idea/testData/checker/Builders.fir.kt
- idea/testData/checker/MultipleBounds.fir.kt
Previously, composed checker passes the `allXXX` flavor of checkers to
each category of checkrs. This makes the composed checkers
non-transparent: behavior changes after composing. In addition, nested
composing would create redundant checkers.
As a result, some checkers registered in the IDE mode
(org.jetbrains.kotlin.idea.fir.low.level.api.diagnostics.AbstractFirIdeDiagnosticsCollector)
are not invoked with the FIR plugin.
This change does two things:
1. pass on checkers to composed checkers without combining
2. use combined checkers in DeclarationCheckersDiagnosticComponent and
ExpressionCheckersDiagnosticComponent
Also fixed UPPER_BOUND_VIOLATED diagnostic message to make the IDE diagnostic test pass.
> FIR checker: fix checker registration

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/EnumIntrinsics.kt
- compiler/testData/codegen/box/enum/enumValueOf.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
Generic functions and implicit casts may return a supertype instead.
> JVM_IR: cast argument of enumValueOf to String in bytecode

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/testData/codegen/box/coroutines/bridges/interfaceGenericDefault.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
This looks like something that broke after changing the lowering order. The only change in this PR is removing
```kotlin
if (origin != JvmLoweredDeclarationOrigin.SUPER_INTERFACE_METHOD_BRIDGE) {
```
from `AddContinuationLowering`, and it fixes KT-45166, KT-45320, KT-45490, and KT-45954 as far as I can tell.
> JVM IR: Handle suspend interface default methods with generic types (KT-45166)

- compiler/fir/analysis-tests/legacy-fir-tests/tests-gen/org/jetbrains/kotlin/fir/FirLoadCompiledKotlinGenerated.java
- compiler/fir/analysis-tests/testData/loadCompiledKotlin/annotations/AnnotationInArray.txt
- compiler/fir/java/src/org/jetbrains/kotlin/fir/java/deserialization/AnnotationsLoader.kt
- compiler/frontend.java/src/org/jetbrains/kotlin/load/kotlin/FileBasedKotlinClass.java
- compiler/testData/loadJava/compiledKotlin/annotations/AnnotationInArray.kt
- compiler/testData/loadJava/compiledKotlin/annotations/AnnotationInArray.txt
- compiler/tests-gen/org/jetbrains/kotlin/jvm/compiler/LoadJavaTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/jvm/compiler/LoadKotlinWithTypeTableTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/jvm/compiler/ir/IrLoadJavaTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/jvm/compiler/javac/LoadJavaUsingJavacTestGenerated.java
- core/descriptors.jvm/src/org/jetbrains/kotlin/load/kotlin/BinaryClassAnnotationAndConstantLoaderImpl.kt
- core/descriptors.jvm/src/org/jetbrains/kotlin/load/kotlin/header/ReadKotlinClassHeaderAnnotationVisitor.java
- core/descriptors.runtime/src/org/jetbrains/kotlin/descriptors/runtime/components/ReflectKotlinClass.kt
- core/descriptors.runtime/tests/org/jetbrains/kotlin/jvm/runtime/JvmRuntimeDescriptorLoaderTestGenerated.java
- core/deserialization.common.jvm/src/org/jetbrains/kotlin/load/kotlin/KotlinJvmBinaryClass.kt
- idea/tests/org/jetbrains/kotlin/idea/decompiler/stubBuilder/LoadJavaClsStubTestGenerated.java
- idea/tests/org/jetbrains/kotlin/idea/stubs/ResolveByStubTestGenerated.java
`KotlinJvmBinaryClass.AnnotationArrayArgumentVisitor` didn't cover the
case when the element type is an `Annotation`. Therefore, when the
compiler read an array of annotations from JVM binary classes built from
Kotlin sources, it got an empty array regardless of what was written in
the bytecode.
For example, `Foo.value` below is read as an empty array when `SomeClass`
resides in another Kotlin module.
```
@Foo(
value = [Bar(1), Bar(2)]
)
class SomeClass
```
> Support array of annotation in KotlinJvmBinaryClass

- generators/tests/org/jetbrains/kotlin/generators/tests/GenerateTests.kt
- idea/idea-fir/src/org/jetbrains/kotlin/idea/quickfix/MainKtQuickFixRegistrar.kt
- idea/idea-fir/tests/org/jetbrains/kotlin/idea/quickfix/HighLevelQuickFixTestGenerated.java
- idea/idea-frontend-independent/src/org/jetbrains/kotlin/idea/quickfix/ReplaceCallFix.kt
- idea/testData/quickfix/expressions/unnecessarySafeCall1.kt
- idea/testData/quickfix/expressions/unnecessarySafeCall1.kt.after
- idea/testData/quickfix/expressions/unnecessarySafeCall2.kt
- idea/tests/org/jetbrains/kotlin/idea/quickfix/QuickFixTestGenerated.java
`unnecessarySafeCall2.kt` was removed in https://github.com/JetBrains/kotlin/commit/0c758902efb64137fe658617967e5e887fc24fa8#diff-1e769b5e958acf313fdbcc14e29b3f2443ac596595e132f2d4ce5ccd98269049 and is no longer applicable (didn't know Kotlin allowed this kind of pattern matching before!) so I replaced it with some other test.
> FIR checker: Enable ReplaceWithDotCallFix for UNNECESSARY_SAFE_CALL

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBytecodeTextTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FunctionReferenceLowering.kt
- compiler/testData/codegen/box/inlineClasses/funInterface/mangledSamWrappers.kt
- compiler/testData/codegen/bytecodeText/inlineClasses/mangledSamWrappers.kt
- compiler/testData/codegen/bytecodeText/inlineClasses/mangledSamWrappersIndy.kt
- compiler/testData/codegen/bytecodeText/inlineClasses/mangledSamWrappersOld.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BytecodeTextTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBytecodeTextTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
This PR removes an outdated workaround for inline class mangling in `FunctionReferenceLowering`. Before 4f171a9eb511823f5f3507d335dc3cb0d2d913c5 this lowering ran after inline class lowering and had to produce mangled function names for `invoke`. After the commit in question we were mangling the same function twice. This never caused any problems since these functions were only called through bridge methods.
> JVM IR: Avoid double mangling of function reference invoke methods

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/transformers/irToJs/SwitchOptimizer.kt
- compiler/testData/codegen/box/when/switchOptimizationMultipleMixedConditions.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
Recursive results from checkForPrimitiveOrPattern were ignored. If it found a case/condition that could not be optimized the resulting "false" was [not propagated](https://github.com/JetBrains/kotlin/blob/276ffd5a4becd3742d8f2a1f51e3d3c0396f9a0d/compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/transformers/irToJs/SwitchOptimizer.kt#L73). This would lead to a "optimized" when without all conditions.
- see [KT-45738](https://youtrack.jetbrains.com/issue/KT-45738)
- The `return` is now lifted out of the when to make it more obvious what is going on.
- New test for mixed multiple conditions in when
> KJS IR: Fix KT-45738 - Consider recursive checkForPrimitiveOrPattern during switch optimization

- compiler/backend/src/org/jetbrains/kotlin/codegen/coroutines/CoroutineTransformerMethodVisitor.kt
- compiler/testData/codegen/bytecodeText/coroutines/debug/thisAndResultInLvt.kt
- compiler/testData/codegen/bytecodeText/coroutines/varValueConflictsWithTableSameSort.kt
- compiler/testData/debug/localVariables/suspend/completion/staticStateMachineReceiver.kt
The coroutine transformation would leave locals in the local
variable table across the code that reloads local variables from
the continuation on reentry. However, when reentering the function
the local has no value until after the reloads from the
continuation.
This change splits the locals in the local variable table to
avoid such uninitialized locals. A local alive across a
suspension point has its range split in two. One that goes
from the original start to the state label for the restart
after the suspension. The other goes from after the local
has been reloaded from the continuation until the previous
end of the local.
> [JVM] Fix uninitialized locals after coroutine transformation.

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/FunctionNVarargBridgeLowering.kt
- compiler/testData/codegen/box/inlineClasses/kt45084.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
FunctionNVarargBridgeLowering checked the name of the method instead
of whether the method overrides an invoke method. That doesn't work
when the name of the function gets mangled because of inline class
arguments.
Fixed KT-45084.
> [JVM_IR] Deal with inline-class arguments in large arity lambdas.

- plugins/uast-kotlin-fir/build.gradle.kts
- plugins/uast-kotlin/build.gradle.kts
As per https://github.com/JetBrains/kotlin/pull/4312#discussion_r628215916, "IDEA" sounds like IntelliJ, while FIR UAST depends on some of `idea-frontend*` modules. According to the origin of this comment (https://github.com/JetBrains/kotlin/commit/06af2a88f0f5860bebc45f0b366c0a7665912a03), the clearer target to mention in the comment is `:idea:idea-core`
> FIR/UAST: clarify what module we should not depend on

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/optimizations/FoldConstantLowering.kt
- compiler/testData/codegen/box/fullJdk/kt46540.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
> [JVM IR] Fix constant folding to use basic types always.

- plugins/uast-kotlin-fir/build.gradle.kts
- plugins/uast-kotlin/build.gradle.kts
When running IDEA > IDEA (No ProcessCanceledException), we'll see:
```
java.lang.NoClassDefFoundError: org/jetbrains/uast/kotlin/ConverterUtilsKt
at org.jetbrains.uast.kotlin.KotlinUastLanguagePlugin.convertElementWithParent(KotlinUastLanguagePlugin.kt:92)
at org.jetbrains.uast.UastFacade.convertElementWithParent(UastContext.kt:64)
at org.jetbrains.uast.UastContextKt.toUElement(UastContext.kt:111)
at com.intellij.codeInsight.daemon.impl.IconLineMarkerProvider.getLineMarkerInfo(IconLineMarkerProvider.java:40)
at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:163)
at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:88)
at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoo …
```
> FIR/UAST: make a fat jar with the base module

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/SharedVariablesLowering.kt
- compiler/testData/codegen/box/enum/kt46605.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
[KT-46605](https://youtrack.jetbrains.com/issue/KT-46605) was caused by 2fa04af, which added a condition that incorrectly skipped over enum entries when looking for shared variables. The code in question comes with a "TODO remove this condition", which is what this PR does.
Unfortunately, I don't know why this condition was there in the first place. From my local testing, it looks like nothing breaks without it. If it turns out that this is still necessary it would also be possible to add another case for `IrEnumEntry` in `SharedVariablesLowering.lower`.
> IR: Lower shared variables in enum entries (KT-46605)

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/codegen/box/coroutines/kt46813.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
This fixes the issue in KT-46813, but it feels like we're playing a game of whack-a-mole. The `unboxResultIfNeeded` function essentially has to identify every compiler generated "bridge" method that may take boxed `Result` arguments and this PR just adds another case (suspend lambda `invoke` methods which bridge to `invokeSuspend`).
There has to be a better way to do this.
> JVM IR: Do not unbox Results in suspend lambda invoke methods (KT-46813)

- compiler/backend/src/org/jetbrains/kotlin/codegen/coroutines/CoroutineCodegen.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/AnonymousObjectTransformer.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/CapturedParamDesc.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/LambdaInfo.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/PsiInlineCodegen.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/coroutines/CoroutineTransformer.kt
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxInlineCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrInlineCodegen.kt
- compiler/testData/codegen/boxInline/suspend/inlineClass/returnBoxedFromLambda.kt
- compiler/testData/codegen/boxInline/suspend/inlineClass/returnUnboxedFromLambda.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/JvmIrAgainstOldBoxInlineTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/JvmOldAgainstIrBoxInlineTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenInlineES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java
The call site inside the inline function expects them to return a boxed value, like FunctionN.invoke would.
#KT-46915 Fixed
> JVM_IR: box inline class values returned by suspend inline lambdas

- compiler/backend/src/org/jetbrains/kotlin/codegen/optimization/boxing/PopBackwardPropagationTransformer.kt
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/testData/codegen/box/optimizations/kt46921.kt
- compiler/testData/codegen/bytecodeText/boxedNotNumberTypeOnUnboxing.kt
- compiler/testData/codegen/bytecodeText/boxingOptimization/casts.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
1. if an argument of a `pop` cannot be removed, then all other potential arguments of that `pop` can't be removed either, and the same applies to other `pop`s that touch them;
2. the same is true for primitive conversions, but this is even trickier to implement correctly, so I simply did the same thing as with boxing operators: replace the conversion itself with a `pop` and keep the argument as-is.
Somehow this actually removes *more* redundant primitive type conversions than the old code in a couple bytecode text tests, so I've patched them to kind of use the value, forcing the instructions to stay.
#KT-46921 Fixed
> JVM: be more careful when removing unused constants 

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LocalDeclarationsLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/inlineclasses/MemoizedInlineClassReplacements.kt
- compiler/testData/codegen/box/extensionProperties/kt46952.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- core/compiler.common/src/org/jetbrains/kotlin/name/Name.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
> [JVM_IR] Avoid using special names in static inline class replacements.

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSymbols.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/PromisedValue.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/SuspendLambdaLowering.kt
- compiler/testData/codegen/box/coroutines/inlineClasses/kt47129.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
> JVM_IR: fix Result types in continuations & remove more codegen hacks

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/debug/localVariables/tryFinally11.kt
- compiler/testData/debug/localVariables/tryFinally12.kt
- compiler/testData/debug/localVariables/tryFinally13.kt
- compiler/testData/debug/localVariables/tryFinally7.kt
This ensures that catch variables are not visible in duplicated
finally blocks generated at an exit within the catch variable
scope.
^KT-46449 Fixed
> [JVM_IR] Keep track of catch variable gaps.

- kotlin-native/backend.native/tests/build.gradle
- kotlin-native/backend.native/tests/runtime/text/parse0.kt
- kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/FloatingPointParser.kt
Fixing: https://youtrack.jetbrains.com/issue/KT-47662
- Fixed incorrect logic of String.toFloat() and String.toDouble().
Long string without any digits were treated as Float or Double:
"this string is not a numb3r, am I right?????????????".toFloat() == Float("Infinity").
- Fixed incorrect parsing of floating point constants "NaN" and "Infinity":
String values like "NaNPICEZy" or "InfinityN" were treated as valid numbers.
- Merged parsing logic for Double and Float:
Removed the code duplication, unified methods, made the code more Kotlin-like, not C++-like.
- Updated tests:
Removed useless tests that checked nothing, updated tests with real regression scenarios.
> [Native, All platforms] HotFix of the incorrect parsing of long strings to Float and Double

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/JvmInlineClassLowering.kt
- compiler/testData/codegen/box/inlineClasses/kt47762.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
The inline class lowering would attempt to lower a companion object
property backing field.
^KT-47762 Fixed.
> [JVM_IR] Fix check for inline class property backing in lowering.

- compiler/testData/diagnostics/foreignAnnotationsTests/java8Tests/jspecify/strictMode/Captured.fir.kt
- compiler/testData/diagnostics/foreignAnnotationsTests/java8Tests/jspecify/strictMode/Captured.fir.txt
- compiler/testData/diagnostics/foreignAnnotationsTests/java8Tests/jspecify/strictMode/Captured.kt
- compiler/testData/diagnostics/foreignAnnotationsTests/java8Tests/jspecify/strictMode/Captured.txt
- compiler/testData/diagnostics/foreignAnnotationsTests/java8Tests/jspecify/warnMode/Captured.fir.kt
- compiler/testData/diagnostics/foreignAnnotationsTests/java8Tests/jspecify/warnMode/Captured.fir.txt
- compiler/testData/diagnostics/foreignAnnotationsTests/java8Tests/jspecify/warnMode/Captured.kt
- compiler/testData/diagnostics/foreignAnnotationsTests/java8Tests/jspecify/warnMode/Captured.txt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/ForeignAnnotationsCompiledJavaTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/ForeignAnnotationsCompiledJavaWithPsiClassReadingTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/ForeignAnnotationsSourceJavaTestGenerated.java
- core/descriptors.jvm/src/org/jetbrains/kotlin/load/java/typeEnhancement/typeEnhancement.kt
- core/descriptors/src/org/jetbrains/kotlin/types/TypeWithEnhancement.kt
Fixes KT-47854, but I'm not sure the root cause is addressed. If it was possible to create a `CapturedType(*)?` (not `CapturedType(*)..CapturedType(*)?`) with an enhancement of `CapturedType(*)`, the type approximator would still break.
> FE: small cleanup of enhancement-wrapped types

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/IrInlineCodegen.kt
- compiler/testData/codegen/box/callableReference/kt47988.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
The lambda generated for inlining does not have an extension
receiver. Therefore, update the function type of the inline
function argument so that the inliner does not expect an extension
receiver.
^ KT-47988 Fixed.
> [JVM_IR] Fix inlining of callable references to extension methods.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/debug/localVariables/tryFinally.kt
- compiler/testData/debug/localVariables/tryFinally11.kt
- compiler/testData/debug/localVariables/tryFinally12.kt
- compiler/testData/debug/localVariables/tryFinally2.kt
This ensures that the debugger always has a bytecode offset for
the line number of a break/continue so that you step there and
so that you can set breakpoints there.
The `nop` instruction is optimized out if it has no line number
information.
^KT-46450 Fixed
> [JVM IR] Ensure an instruction for the line number for a break.

- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/InlineCallableReferenceToLambda.kt
- compiler/testData/codegen/box/callableReference/arrayConstructor.kt
Basically the same thing as #4418.
#KT-48267 Fixed
> JVM_IR: use substituted return type when lowering inline references

- compiler/resolution.common/src/org/jetbrains/kotlin/resolve/calls/inference/components/ConstraintIncorporator.kt
This should slightly mitigate the UI freezes caused by [KT-47545](https://youtrack.jetbrains.com/issue/KT-47545).
> Check for cancelation during type inference

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxInlineCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrUtils.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/lower/StaticCallableReferenceLowering.kt
- compiler/testData/codegen/boxInline/reified/singletonLambda.kt
- compiler/testData/codegen/boxInline/reified/singletonLambda.txt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrSerializeCompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/JvmIrAgainstOldBoxInlineTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/JvmOldAgainstIrBoxInlineTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenInlineES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenInlineTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenInlineTestGenerated.java
The inliner supports that, we just need to generate the reification markers on GETFIELD to instance fields.
> JVM_IR: generate instance fields even when reification is needed

- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ParcelizeDeclarationChecker.kt
- plugins/parcelize/parcelize-compiler/testData/box/valueClassWrapper.kt
- plugins/parcelize/parcelize-compiler/tests/org/jetbrains/kotlin/parcelize/test/ParcelizeBoxTestGenerated.java
- plugins/parcelize/parcelize-compiler/tests/org/jetbrains/kotlin/parcelize/test/ParcelizeIrBoxTestGenerated.java
While Parcelize supports value classes in the backend, there was still an issue with frontend diagnostics, reported [here](https://issuetracker.google.com/197890119). This PR addresses the frontend diagnostics by not unfolding inline classes before checking whether they are parcelable.
> Parcelize: Fix diagnostics for parcelable value classes

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/FunctionGenerator.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/ConstantValueGenerator.kt
- compiler/testData/codegen/box/arrays/constantArrayOfAny.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsLegacyPrimitiveArraysBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
While annotations restrict the set of allowed types to a few final built-ins, in arbitrary constants we can have array elements that are some subtype of the array's element type.
#KT-48671 Fixed
> IR: do not infer array element types for non-annotation constants

- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ir/AndroidIrBuilder.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ir/AndroidSymbols.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ir/IrParcelSerializerFactory.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ir/IrParcelSerializers.kt
- plugins/parcelize/parcelize-compiler/testData/codegen/classLoaderValues.ir.txt
- plugins/parcelize/parcelize-compiler/testData/codegen/classLoaderValues.kt
- plugins/parcelize/parcelize-compiler/testData/codegen/classLoaderValues.txt
- plugins/parcelize/parcelize-compiler/tests/org/jetbrains/kotlin/parcelize/test/ParcelizeBytecodeListingTestGenerated.java
- plugins/parcelize/parcelize-compiler/tests/org/jetbrains/kotlin/parcelize/test/ParcelizeIrBytecodeListingTestGenerated.java
In `readBundle`, `readPersistableBundle`, and `readValue`.
> Parcelize: Use the class loader of the Parcelable class for deserialization

- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/JvmOptimizationLowering.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/IrInlineReferenceLocator.kt
- compiler/testData/codegen/bytecodeText/kt3845.kt
```
class A {
val x = 1
fun foo() {
x // getfield x
run { x } // should also be getfield x
privateFun()
}
private inline fun privateFun() = x // should also be getfield x
}
```
> JVM_IR: optimize property accesses in inline lambdas and private funs

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/PropertyReferenceLowering.kt
- compiler/testData/codegen/box/delegatedProperty/optimizedDelegatedProperties/kt48825.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
before checking whether they use the KProperty parameter. (Otherwise the body is empty and the check always says that the parameter is unused.)
^KT-48825 Fixed
> JVM_IR: resolve fake overrides of inline delegated property operators

- compiler/ir/backend.jvm/entrypoint/src/org/jetbrains/kotlin/backend/jvm/FacadeClassSourceShimForFragmentCompilation.kt
- compiler/ir/backend.jvm/entrypoint/src/org/jetbrains/kotlin/backend/jvm/JvmGeneratorExtensionsImpl.kt
- compiler/ir/backend.jvm/entrypoint/src/org/jetbrains/kotlin/backend/jvm/JvmIrCodegenFactory.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/Psi2IrTranslator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/CallGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/GeneratorContext.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ModuleGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/EvaluatorFragmentInfo.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentCompilerSymbolTableDecorator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentContext.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentDeclarationGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentModuleGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/intermediate/VariableLValue.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DeclarationStubGenerator.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/StubGeneratorExtensions.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/SymbolTable.kt
- compiler/ir/serialization.common/src/org/jetbrains/kotlin/backend/common/serialization/DescriptorByIdSignatureFinder.kt
- core/deserialization.common.jvm/src/org/jetbrains/kotlin/load/kotlin/FacadeClassSource.kt
- core/deserialization.common.jvm/src/org/jetbrains/kotlin/load/kotlin/JvmPackagePartSource.kt
This commit introduces a new entrypoint for the IR backend, and starts
the work of accomoding the evaluator in psi2ir.
The evaluator expects a certain class and method structure of the
compiled fragment, but PSI is only supplied for the actual fragment.
So, to that end, this commit introduces a new "front end" of psi2ir
that "synthesizes" the module, class and method structure around the
fragment before calling into the existing psi2ir pipeline to obtain
the IR for the fragment.
The primary complication so far is handling the captured variables of
the fragment: they are mapped to parameters of the method surrounding
the fragment, and passed as arguments on evaluation. Hence, the IR
translation of the fragment needs to remap captured variables to the
appropriate parameter, in essentially …
> [EE-IR] Fragment Compiler Entrypoint in IR Backend

- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ir/AndroidSymbols.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ir/IrParcelSerializerFactory.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ir/IrParcelSerializers.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/serializers/ParcelSerializer.kt
- plugins/parcelize/parcelize-compiler/testData/box/shortArray.kt
- plugins/parcelize/parcelize-compiler/testData/box/unsignedArrays.kt
- plugins/parcelize/parcelize-compiler/testData/codegen/primitiveArrays.ir.txt
- plugins/parcelize/parcelize-compiler/testData/codegen/primitiveArrays.kt
- plugins/parcelize/parcelize-compiler/testData/codegen/unsignedPrimitiveArrays.ir.txt
- plugins/parcelize/parcelize-compiler/testData/codegen/unsignedPrimitiveArrays.kt
- plugins/parcelize/parcelize-compiler/tests/org/jetbrains/kotlin/parcelize/test/ParcelizeBoxTestGenerated.java
- plugins/parcelize/parcelize-compiler/tests/org/jetbrains/kotlin/parcelize/test/ParcelizeBytecodeListingTestGenerated.java
- plugins/parcelize/parcelize-compiler/tests/org/jetbrains/kotlin/parcelize/test/ParcelizeIrBoxTestGenerated.java
- plugins/parcelize/parcelize-compiler/tests/org/jetbrains/kotlin/parcelize/test/ParcelizeIrBytecodeListingTestGenerated.java
- There was an error with `ShortArray`s, which failed with a frontend exception.
- Added support for unsigned arrays, since we already support unsigned types.
As an aside, it would be really nice to have access to symbols for unsigned types and arrays in the IR backend, but I found no easy way to add support for that. Instead the parcelize plugin has to work with stubs for the unsigned array types.
> Parcelize: Support short and unsigned arrays

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/BridgeLowering.kt
- compiler/testData/codegen/box/bridges/kt46389.kt
- compiler/testData/codegen/box/bridges/kt46389_jvmDefault.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/es6/semantics/IrJsCodegenBoxES6TestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/semantics/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/semantics/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
This PR makes the JVM IR backend match the behavior of the JVM backend, which apparently never generates bridges for default argument stubs. There are problems with this choice (see the comments in the code), but I don't see a great solution here until we use JVM default methods everywhere.
Meanwhile, the JS backend has the (imo) nicer behavior in cases where it does work (`testKt46389_jvmDefault`), but also suffers from `KT-46389` (`testKt46389`) when inline functions are involved.
> JVM IR: Don't generate bridges for default argument stubs (KT-46389)

- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ParcelizeDeclarationChecker.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ParcelizeResolveExtension.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/diagnostic/DefaultErrorMessagesParcelize.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ir/ParcelizeIrTransformer.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ir/irUtils.kt
- plugins/parcelize/parcelize-compiler/testData/box/sealedClass2.kt
- plugins/parcelize/parcelize-compiler/testData/box/sealedInterface.kt
- plugins/parcelize/parcelize-compiler/tests/org/jetbrains/kotlin/parcelize/test/ParcelizeBoxTestGenerated.java
- plugins/parcelize/parcelize-compiler/tests/org/jetbrains/kotlin/parcelize/test/ParcelizeIrBoxTestGenerated.java
See https://issuetracker.google.com/177856520
This is essentially syntactic sugar. A `@Parcelize` annotation on a `sealed class` just propagates this annotation to all direct subclasses.
> Parcelize: Allow Parcelize annotation on sealed classes

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBytecodeTextTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LocalDeclarationsLowering.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/SuspendLambdaLowering.kt
- compiler/testData/codegen/bytecodeListing/annotations/localClassWithCapturedParams_ir.txt
- compiler/testData/codegen/bytecodeText/fieldsForCapturedValues/constructorOnly.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BytecodeTextTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBytecodeTextTestGenerated.java
I.e. those only used in constructors, where parameters with the same values are also present.
One exception is captured inline parameters on the JVM backend, as the bytecode inliner uses field assignment instructions (setfield) to locate them; removing the field is thus not possible:
```
inline fun baz(crossinline f: () -> String) =
object {
init { println(f()) } // *has* to create a field called `$f`...
}
fun main() {
val ok = "OK"
println(baz { ok }) // ...otherwise the inliner won't create a field for `ok`.
}
```
TODO: fix the inliner? Even so, removing the field would be a backwards-incompatible change.
^KT-48784 Fixed
> IR: do not create unused capture fields

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBytecodeTextTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
- compiler/testData/codegen/bytecodeListing/delegatedProperty/delegatedPropertiesInCompanionObject_ir.txt
- compiler/testData/codegen/bytecodeListing/fileClassWithPrivateDeclarationsOnly_after.txt
- compiler/testData/codegen/bytecodeListing/fileClassWithPrivateDeclarationsOnly_before.txt
- compiler/testData/codegen/bytecodeListing/noReceiverInCallableReferenceClasses_ir.txt
- compiler/testData/codegen/bytecodeText/outerClass/classInClinit.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BytecodeTextTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBytecodeTextTestGenerated.java
The JVM and newer Android runtimes treats that the same as if
there is no enclosing method. However, older Android runtimes
for Android 5 and 6 throw exceptions on reflective access
and even older runtimes have different behavior. To avoid
those issues, exclude <clinit> from enclosing method attributes.
^ KT-48754 Fixed
> [JVM IR] Do not generate clinit as enclosing method.

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/MemoizedInlineClassReplacements.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/testData/codegen/box/inlineClasses/kt48993.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
> JVM_IR: do not move receivers on functions with inline class parameters

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/AddContinuationLowering.kt
- compiler/testData/codegen/box/jvm8/defaults/noDefaultImpls/suspendSuperCall.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
The visibility was the cause of KT-44533; not generating `$suspendImpl` at all makes `super` calls impossible.
^KT-49106 Fixed
> JVM_IR: generate `$suspendImpl` in interfaces as public

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/dsl/KotlinProjectExtension.kt
Fixes this error: `Unknown value for parameter -Xexplicit-api: 'disabled'. Value should be one of {disable, strict, warning}
when using
```kotlin
kotlin {
explicitApi = ExplicitApiMode.Disabled
}
```
> Fix ExplicitApiMode.Disabled

- kotlin-native/shared/src/main/kotlin/org/jetbrains/kotlin/konan/util/DependencyProcessor.kt
Previously initializing the DependencyProcessor will result in file IO.
In a fully-hermetic environment where all dependencies are local, this IO is redundant and may require the build system (e.g. Bazel) to do extra setup to ensure there is a local writable directory specified for these directories. This change will instead cause the dependency processor to bail early and skip downloading dependencies if all are local anyway.
Prior to this change kicking off a clean build with local dependencies would result in:
```
rm -rf ~/.konan/cache; fswatch -ax ~/.konan
~/.konan/cache Created IsDir
~/.konan/cache/.lock Created IsFile
```
After the change no FS operations are performed.
> [Native] Lazily create dependency & cache directories.

- libraries/kotlinx-metadata/jvm/src/kotlinx/metadata/jvm/JvmFlag.kt
- libraries/kotlinx-metadata/jvm/src/kotlinx/metadata/jvm/impl/JvmMetadataExtensions.kt
- libraries/kotlinx-metadata/jvm/src/kotlinx/metadata/jvm/impl/jvmExtensionNodes.kt
- libraries/kotlinx-metadata/jvm/src/kotlinx/metadata/jvm/jvmExtensionVisitors.kt
- libraries/kotlinx-metadata/jvm/src/kotlinx/metadata/jvm/jvmExtensions.kt
- libraries/kotlinx-metadata/jvm/test/kotlinx/metadata/test/MetadataSmokeTest.kt
Right now, `kotlinx-metadata-jvm` does not handle the `jvmClassFlags` extension, which is used to record the new jvm-default modes on interfaces. This means that we currently loose the extension when we process metadata using `kotlinx-metadata`, which in turn breaks `jvm-abi-gen` on targets compiled with `jvm-default=all` or `all-compatibility`.
> kotlinx-metadata-jvm: Handle the jvmClassFlags extension

- compiler/config.jvm/src/org/jetbrains/kotlin/config/JvmTarget.kt
In the detekt project we show valid values for various Kotlin compiler flags on the detekt CLI. The CLI library we're using uses `toString` to enumerate values for enums and display when run with the `--help` flag.
There's a `toString` override on `LanguageVersion` which allows us to display all values that can be parsed successfully with `LanguageVersion.fromVersionString(...)`, so it would be great to have the same for `JvmTarget`, which would allow us to show all valid values that can be parsed by `JvmTarget.fromString(...)`.
> Add readable toString for JvmTarget

- compiler/ir/backend.jvm/entrypoint/src/org/jetbrains/kotlin/backend/jvm/JvmIrCodegenFactory.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/ReflectiveAccess.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmGeneratorExtensions.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSymbols.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/IrIntrinsicMethods.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/intrinsics/JvmDebuggerInvokeSpecial.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/CallGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/GeneratorExtensions.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentCompilerSymbolTableDecorator.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/IrStatementOrigin.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/StubGeneratorExtensions.kt
- Refactor JvmIrCodegenFactory to allow for caller's choice of
lowerings.
- Refactor of SyntheticAccessorLowering to expose the accessibility
check used to determine the need for accessors.
- Replacement of field, method and constructor uses with corresponding
java.lang.reflection API via additional lowering running _before_
the existing IR pipeline.
- Emulating super calls in the context of class methods via new
compiler intrinsic.
- psi2ir: Add support for `_field` suffix on properties in the
evaluator for accessing underlying fields when applicable.
- Add `JvmGeneratorExtensions` point for determining whether a
property accessor has a user-supplied body in order to predict how
they are ultimately compiled for the JVM.
> [EE-IR] Use reflection to avoid the need for accessors when compiling fragments

- kotlin-native/Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/jvm/CommandLine.kt
- kotlin-native/Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/jvm/ToolConfig.kt
- kotlin-native/Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/jvm/main.kt
This aligns with the flag added to kotlinc in:
https://youtrack.jetbrains.com/issue/KT-40670
Hermetic builds would benefit from being able to override dependency paths or airplaneMode using this mechanism:
```
$ bin/cinterop -Xoverride-konan-properties "apple-llvm-20200714-macos-x64-essentials.default=/tmp/llvm;airplaneMode=true" -def foo.def
```
> [Native] Add -Xoverride-konan-properties to cinterop.

- libraries/kotlinx-metadata/jvm/test/kotlinx/metadata/test/MetadataSmokeTest.kt
- libraries/kotlinx-metadata/src/kotlinx/metadata/impl/readers.kt
- libraries/tools/kotlinp/testData/ValueClass.kt
- libraries/tools/kotlinp/testData/ValueClass.txt
There are two problems with how `kotlinx-metadata` handles inline class representations.
First, there is a bug, where the flags of the underlying type are incorrect. The code uses `type.flags` instead of `type.typeFlags`, which seems a bit error prone. :-|
Second, the class reader would always visits the `inlineClassUnderlyingType` field, even if it wasn't present in the metadata. This was clearly intentional, but I think it's problematic, since there is now no way to tell whether the metadata contained this field to begin with. Just copying metadata using `kotlinx-metadata` would quietly add the field to the result.
I can think of two alternatives here if we want to keep the current behavior. First we could visit the underlying type field with an additional `isDefault` flag. That's not …
> kotlinx-metadata: Fix parsing of inlineClassUnderlyingType

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/ir/SharedVariablesManager.kt
- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/JsSharedVariablesManager.kt
- compiler/ir/backend.jvm/entrypoint/src/org/jetbrains/kotlin/backend/jvm/JvmIrCodegenFactory.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/FragmentSharedVariablesLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmSharedVariablesManager.kt
- compiler/ir/backend.wasm/src/org/jetbrains/kotlin/backend/wasm/lower/WasmSharedVariablesManager.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/EvaluatorFragmentInfo.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentCompilerSymbolTableDecorator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentDeclarationGenerator.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/declarations/IrDeclarationOrigin.kt
- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/descriptors/KonanSharedVariablesManager.kt
- box captured variables using `Ref`s, the same mechanism that's used
for shared variables in closures.
From the doc of the lowering at the center of this PR:
```
// This lowering is a preprocessor for IR in order to support the compilation
// scheme used by the "Evaluate Expression..." mechanism of the IntelliJ plug-in
// for Kotlin debugging.
//
// Fragments are compiled as the body of an enclosing function that close the free
// variables of the fragment as parameters. The values of these are then extracted
// from the stack at the current breakpoint, and the fragment code is invoked with
// these values to evaluate the expression.
//
// If the parameter is a shared variable, e.g. `IntRef` (the same mechanism used to
// implement captures of lambdas) the value extracted from the stack …
```
> [EE-IR] Support mutations by evaluator fragments

- compiler/frontend/src/org/jetbrains/kotlin/resolve/BindingContext.java
- compiler/frontend/src/org/jetbrains/kotlin/resolve/bindingContextUtil/BindingContextUtils.kt
- compiler/frontend/src/org/jetbrains/kotlin/util/slicedMap/Slices.java
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/BranchingExpressionGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ModuleGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentModuleGenerator.kt
This PR is split in two commits for ease of reviewing:
1) Refactor the binding context to use a "basic slice" for `USED_AS_EXPRESSION` - see the commit message for explanation.
2) Change the fragment entrypoint in psi2ir to handle multiple inputs to support inline functions in the fragment.
> [EE-IR] Support Inline functions 

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/codegen/CoroutineCodegen.kt
- compiler/testData/codegen/box/coroutines/kt49645.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- native/native.tests/tests-gen/org/jetbrains/kotlin/konan/blackboxtest/NativeExtBlackBoxTestGenerated.java
Do not coroutine transform static inline class replacements that
forward to a default interface suspend method. No boxing has to
take place on return (as the default interface method always
boxes) so we can simply forward the call.
^KT-49645 Fixed
> [JVM_IR] Fix inline class default method codegen.

- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ParcelizeAnnotationChecker.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ParcelizeDeclarationChecker.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ParcelizeNames.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/diagnostic/DefaultErrorMessagesParcelize.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/fir/diagnostics/FirParcelizeClassChecker.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/fir/diagnostics/FirParcelizeConstructorChecker.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/fir/diagnostics/FirParcelizePropertyChecker.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/fir/diagnostics/KtDefaultErrorMessagesParcelize.kt
- plugins/parcelize/parcelize-compiler/src/org/jetbrains/kotlin/parcelize/ir/ParcelizeIrTransformerBase.kt
- plugins/parcelize/parcelize-compiler/testData/box/constructorWithoutValOrVar.kt
- plugins/parcelize/parcelize-compiler/testData/box/customParcelerChecks.kt
- plugins/parcelize/parcelize-compiler/testData/box/ignoredOnParcel.kt
- plugins/parcelize/parcelize-compiler/testData/diagnostics/ignoredOnParcelDefaultValues.kt
- plugins/parcelize/parcelize-compiler/testData/diagnostics/ignoredOnParcelUnsupportedType.kt
- plugins/parcelize/parcelize-compiler/tests-gen/org/jetbrains/kotlin/parcelize/test/runners/FirParcelizeDiagnosticTestGenerated.java
- plugins/parcelize/parcelize-compiler/tests-gen/org/jetbrains/kotlin/parcelize/test/runners/ParcelizeBoxTestGenerated.java
- plugins/parcelize/parcelize-compiler/tests-gen/org/jetbrains/kotlin/parcelize/test/runners/ParcelizeDiagnosticTestGenerated.java
- plugins/parcelize/parcelize-compiler/tests-gen/org/jetbrains/kotlin/parcelize/test/runners/ParcelizeFirBoxTestGenerated.java
- plugins/parcelize/parcelize-compiler/tests-gen/org/jetbrains/kotlin/parcelize/test/runners/ParcelizeIrBoxTestGenerated.java
- Allow `@IgnoredOnParcel` annotations on constructor parameters with default values. See https://issuetracker.google.com/177850560
- Don't check constructors if there is a custom `Parceler` - the checks are there to ensure that we can generate correct code, but with a custom Parceler that's not really necessary. See https://issuetracker.google.com/177850558
> Parcelize: More permissive constructor diagnostics

- libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/testing/karma/KotlinKarma.kt
Without this, one has to define a file like `karma.config.d/karma.conf.js`
with contents:
```js
config.set({
browsers: ['ChromeHeadlessNoSandbox'],
customLaunchers: {
ChromeHeadlessNoSandbox: {
base: 'ChromeHeadless',
// Needed to work on Jenkins. Otherwise, there's an error:
// 'Running as root without --no-sandbox is not supported. See https://crbug.com/638180.'
flags: ['--no-sandbox'],
}
}
});
```
This change allows staying 100% in Gradle config for such configuration.
With growing usage of Kubernetes, this flag becomes more and more
popular.
Ideally the Karma config API in Gradle could be more flexible, so that
e.g. someone that uses Chromium could also use `--no-sandbox` flag.
However, it's some bigger change that influnces the API, so I want this
change to be simple.
Related Slack …
> Allow running Chrome headless with '--no-sandbox' flag

- plugins/jvm-abi-gen/src/org/jetbrains/kotlin/jvm/abi/JvmAbiMetadataProcessor.kt
This does not affect compilation, but it causes problems in IntelliJ.
> jvm-abi-gen: Do not write kotlin.Metadata default values (KT-39492)

- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/EvaluatorFragmentInfo.kt
Part of migration to new constructor signature.
Unblocked by intellij-community#1839.
> [EE-IR] Minor: Refactor EvaluatorFragmentInfo

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/FunctionReferenceLowering.kt
- compiler/testData/codegen/box/casts/kt48987.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
Fixes [KT-48987](https://youtrack.jetbrains.com/issue/KT-48987), which looks similar to [KT-47449 ](https://youtrack.jetbrains.com/issue/KT-47449)
> JVM_IR: handle star projection arguments in smart casts (KT-48987)

- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/CAdapterGenerator.kt
This previously failed if the module name contaned dots or dashes, e.g.
```
kotlinc-native ~/test.kt -produce static -module-name="foo-bar.baz"
```
This change espaces `-` and `.` similar to `ObjCExportNamer`'s `abbreviate`.
> [Native] Escape the module name in the C adapter.

- plugins/atomicfu/atomicfu-compiler/src/org.jetbrains.kotlinx.atomicfu.compiler/extensions/AtomicfuTransformer.kt
- plugins/atomicfu/atomicfu-compiler/test/org/jetbrains/kotlinx/atomicfu/AtomicfuJsIrTestGenerated.java
- plugins/atomicfu/atomicfu-compiler/testData/box/TraceTest.kt
Support [tracing](https://github.com/Kotlin/kotlinx.atomicfu#tracing-operations) for the kotlinx.atomicfu compiler plugin.
These transformer changes erase trace invocations from the JS/IR:
```
val trace = Trace(size)
fun update(x: Int): Int {           
// custom trace message
trace { "calling update($x)" }
// appending multiple arguments to the trace
trace.append(x, "CAS", current.value)
}
```
> kotlinx.atomicfu compiler plugin (JS): tracing supported.

- plugins/atomicfu/atomicfu-compiler/src/org.jetbrains.kotlinx.atomicfu.compiler/extensions/AtomicfuTransformer.kt
- plugins/atomicfu/atomicfu-compiler/src/org.jetbrains.kotlinx.atomicfu.compiler/extensions/TransformerUtil.kt
- plugins/atomicfu/atomicfu-compiler/test/org/jetbrains/kotlinx/atomicfu/AtomicfuJsIrTestGenerated.java
- plugins/atomicfu/atomicfu-compiler/testData/box/DelegatedPropertiesTest.kt
Support delegated properties for the kotlinx.atomicfu compiler plugin.
[kotlinx.atomicfu](https://github.com/Kotlin/kotlinx.atomicfu) library supports declaration of properties delegated to atomics:
```
private val _a = atomic(42)
var a: Int by _a
```
For JS backend this should be transformed to:
```
private val _a = 42
var a: Int
get() = _a
set(value) = { _a = value }
```
> kotlinx.atomicfu compiler plugin (JS): delegated properties supported

- compiler/ir/backend.jvm/entrypoint/src/org/jetbrains/kotlin/backend/jvm/JvmIrCodegenFactory.kt
Generalize the config specific to evaluator fragment compilation for wider
applicability.
---
I am getting the strangest runtime exception which I have been unable to create a useful repro for: intellij-community/kt-212-master (879c6d432b4ce0051eb3204e674bd0cc86ff5661) _builds_ against this change, but I get a `RuntimeException` reporting that the new constructor does not exist for any code that relies on the presence of the default value for the new constructor parameter:
```
Caused by: java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.<init>(org.jetbrains.kotlin.config.CompilerConfiguration, org.jetbrains.kotlin.backend.common.phaser.PhaseConfig, org.jetbrains.kotlin.ir.backend.jvm.serialization.JvmDescriptorMangler, …
```
> [IR] Generalize fragment generation logic for wider use

- plugins/android-extensions/android-extensions-compiler/src/org/jetbrains/kotlin/android/synthetic/codegen/AndroidIrExtension.kt
- plugins/android-extensions/android-extensions-compiler/testData/codegen/android/singleFile/0.kt
In general, calling open methods in open class constructors is unsafe because their overrides will see an uninitialized instance. This change makes it at least possible to use the view cache in such cases.
(See also: #4654)
^KT-50627 Fixed
> IR/Android: initialize the findViewById cache before `super()`

- libraries/stdlib/jvm/src/kotlin/util/MathJVM.kt
Replace `Float.NIN_VALUE` with `Float.MIN_VALUE`.
> Fix typo in description of Float.ulp

- compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/KotlinCliJavaFileManagerImpl.kt
- compiler/tests/org/jetbrains/kotlin/cli/JavaSourceClassInClassPathTest.kt
If the class `A` is in a jar `previous.jar`, the following CLI
invocation will take that class instead of the `A` class
defined in `A.java`:
kotlinc -cp previous.jar A.java B.kt
This is problematic for build tools that put the jar for a
previous build on the classpath when recompiling some of the
files.
^KT-51025 Fixed.
> [JVM CLI] Prefer source over classpath.

- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentDeclarationGenerator.kt
Testing revealed buggy generation of classes: the prior code is
rejected by the JVM verifier due to missing call to `this()` or
`super()`.
> [EE-IR] Minor: Generate valid bytecode for Fragment Class in PSI2IR

- core/descriptors/src/org/jetbrains/kotlin/resolve/inlineClassesUtils.kt
- core/deserialization/src/org/jetbrains/kotlin/serialization/deserialization/descriptors/DeserializedClassDescriptor.kt
- plugins/jvm-abi-gen/test/org/jetbrains/kotlin/jvm/abi/CompileAgainstJvmAbiTestGenerated.java
- plugins/jvm-abi-gen/test/org/jetbrains/kotlin/jvm/abi/IrCompileAgainstJvmAbiTestGenerated.java
- plugins/jvm-abi-gen/test/org/jetbrains/kotlin/jvm/abi/LegacyCompileAgainstJvmAbiTestGenerated.java
- plugins/jvm-abi-gen/testData/compile/privateValueClassConstructor/app/app.kt
- plugins/jvm-abi-gen/testData/compile/privateValueClassConstructor/lib/lib.kt
`DeclarationDescriptor.isInlineClass` misidentifies inline classes without constructors. This can happen for the ABI of inline classes with private constructors.
---
Additionally, we should probably try to deserialize the `inlineClassUnderlyingRepresentation` for both inline and value classes. Just doing this would fix the issue for the JVM IR backend, but the JVM backend still relies on the behavior of `isInlineClass`.
The behavior was changed in e69a973b07c4a990f992e0e568248cb4de1a18ff.
> inlineClassUtils: Fix handling of inline classes without constructors (KT-50992)

- compiler/cli/src/org/jetbrains/kotlin/cli/common/messages/AnalyzerWithCompilerReport.kt
- compiler/tests/org/jetbrains/kotlin/cli/AnalysisHandlerExtensionTest.kt
ExperimentalUsageChecker.checkCompilerArguments() will crash if there was an error running analyze().
This checks for the error first so it can be properly reported.
> Check analysis error before checking compiler args

- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExport.kt
This enables using exported Frameworks with `-fmodules-decluse`.
One use-case for this is ensuring that distributed builds are
explicitly providing all required modules, which is important for
reproducibility.
For more background on `use` declarations, see:
https://clang.llvm.org/docs/Modules.html#use-declaration
The easiest way to reproduce this locally is by compiling a framework,
and emitting a pcm file with `swiftc`. Note that this requires a
pcm for `Foundation`, which can be found in the clang ModuleCache. e.g.
```
kotlin-native/dist/bin/kotlinc-native ~/test.kt -produce framework -o /tmp/TestFramework.framework
swiftc -emit-pcm -module-name TestFramework -o /tmp/TestFramework.pcm /tmp/TestFramework.framework/Modules/module.modulemap -Xcc -fmodules-decluse -Xcc …
```
> [Native] Explicitly use Foundation in ObjC export.

- compiler/testData/codegen/box/reflection/callBy/inlineClassFunctionsAndConstructors.kt
- core/reflection.jvm/src/kotlin/reflect/jvm/internal/KDeclarationContainerImpl.kt
- core/reflection.jvm/src/kotlin/reflect/jvm/internal/KFunctionImpl.kt
Partial fixes have been made for the following ticket.
Please see the code and comments for the fix.
- ["KotlinReflectionInternalError" when using \`callBy\` on constructor that has inline class parameters : KT\-27598](https://youtrack.jetbrains.com/issue/KT-27598)
Note that even with this fix, the call will still fail due to another bug in `InlineClassAwareCaller`.
I am in the process of checking for that bug.
> Partial fix for KT-27598

- compiler/ir/ir.interpreter/src/org/jetbrains/kotlin/ir/interpreter/proxy/reflection/KFunctionProxy.kt
Replace `eqaulsByAdapteeCall` with `equalsByAdapteeCall`
> Fix typo in KFunctionProxy.kt

- plugins/kotlin-serialization/kotlin-serialization-compiler/test/org/jetbrains/kotlinx/serialization/SerializationPluginDiagnosticTestGenerated.java
This test is a leftover from the original implementation of #4583 which was updated. This test is redundant now.
> Remove redundant MetaSerializable test

- compiler/backend-common/src/org/jetbrains/kotlin/backend/common/CodegenUtil.kt
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.js/src/org/jetbrains/kotlin/ir/backend/js/utils/misc.kt
- compiler/testData/codegen/box/dataClasses/kt49715.kt
- compiler/testData/codegen/box/dataClasses/kt49715.txt
- compiler/testData/codegen/box/dataClasses/kt49715_behaviorChange.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/testOld/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
- native/native.tests/tests-gen/org/jetbrains/kotlin/konan/blackboxtest/NativeCodegenBoxTestGenerated.java
issue: https://youtrack.jetbrains.com/issue/KT-49715
----
As far as I know, the method `getMemberToGenerate` is used to: 
1. generate `toString`, `hashCode`, `equals` methods for data class
2. generate `serialize`, `deserialize`, `childSerializers`, `typeParametersSerializers` methods  in `serialization-compiler-plugin`
Not pretty sure if this change breaks semantics/purpose of  method `getMemberToGenerate`, but it is safe for now because all those methods above are not extension methods.
#KT-49715 Fixed
----
It passed `jvmCompilerTest` but I haven't run many tests for `jsBackend` or `nativeBackend`
> JVM_IR: Handle methods descriptor clash in data class

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirLocalVariableTestGenerated.java
- compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/testData/checkLocalVariablesTable/underscoreNames.kt
- compiler/testData/debug/localVariables/doWhile.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrLocalVariableTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/LocalVariableTestGenerated.java
Locals introduced in the body of a do-while loop are not
necessarily live at the do-while condition. For example,
if there is a continue in the body before the declaration:
do {
if (shouldContinue(x))
continue
val y = 32  // not always defined in the condition
doSomething(y)
} while (x < 2)
For locals referenced in the condition such code is rejected
by the frontend because a local referenced in the condition
must be always defined when you get there.
However, locals that are not used in the condition were always
put in the local variable table. This leads to invalid locals
information which can trip of debuggers and other build tools
such as the D8 dexer.
This patch only puts in locals information for locals actually
referenced in the local variable table for the condition.
^Fixes …
> [JVM IR] Limit local variables in do-while conditions.

- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/ReflectiveAccess.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
An evaluator fragment is considered a member of the `root` package.
When evaluating fragments that call `protected` members at a breakpoint in a file that is also in the `root` package, the logic from synthetic accessor lowering declares the access for legal: the JVM allows protected access within the same package...
... unless the call and the callee live on different class loaders, as may be the case when the evaluator uses the "compiling evaluator" mechanism, where the code for the fragment is loaded and run on the JVM being debugged, rather than interpret the code using eval4j.
This PR lets the fragment lowering tell the logic from synthetic accessor lowering to consider the access as across class loader boundaries.
This will unmute a test (superMembers.kt) in the evaluator suite in …
> [EE-IR] Add "different classloader" check to synthetic accessor lowering

- compiler/backend/src/org/jetbrains/kotlin/codegen/state/GenerationState.kt
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirLocalVariableTestGenerated.java
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirSteppingTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/LocalDeclarationsLowering.kt
- compiler/ir/backend.jvm/entrypoint/src/org/jetbrains/kotlin/backend/jvm/JvmIrCodegenFactory.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/FragmentLocalFunctionPatchLowering.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/ReflectiveAccess.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendContext.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/GeneratorContext.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentCompilerSymbolTableDecorator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/fragments/FragmentModuleGenerator.kt
- compiler/testData/debug/localVariables/constructors/multipleConstructors.kt
- compiler/testData/debug/localVariables/constructors/property.kt
- compiler/testData/debug/stepping/kt15259.kt
- compiler/testData/debug/stepping/kt29179.kt
- compiler/testData/debug/stepping/nullcheck.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrLocalVariableTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrSteppingTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/LocalVariableTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/SteppingTestGenerated.java
This commit introduces support for calling and referencing local functions and
objects in evaluate expression on the IR backend.
The primary incision is a lowering inserted after Local Declaration Lowering,
that uses the intermediate data structures recorded by LDL to rewrite calls to
local functions to the appropriate function in the binary, instead of predicting
the compilation strategy. The required changes to the rest of the pipeline
facilitate piping the required data around.
The key to this transformation is that _captures by the local function_ must be
introduced as _captures by the fragment function_, such that the evaluator
infrastructure can find the appropriate values at run-time. This is necessary
due to the strategy of compiling local functions to static functions instead of …
> [EE-IR] Support Local Functions

- analysis/low-level-api-fir/tests/org/jetbrains/kotlin/analysis/low/level/api/fir/diagnostic/compiler/based/DiagnosisCompilerTestFE10TestdataTestGenerated.java
- compiler/fir/analysis-tests/tests-gen/org/jetbrains/kotlin/test/runners/FirOldFrontendDiagnosticsTestGenerated.java
- compiler/fir/analysis-tests/tests-gen/org/jetbrains/kotlin/test/runners/FirOldFrontendDiagnosticsWithLightTreeTestGenerated.java
- compiler/frontend/cfg/src/org/jetbrains/kotlin/cfg/pseudocode/instructions/special/InlinedLocalFunctionDeclarationInstruction.kt
- compiler/testData/diagnostics/tests/controlFlowAnalysis/kt52131.kt
- compiler/testData/diagnostics/tests/controlFlowAnalysis/kt52131.txt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/DiagnosticTestGenerated.java
The body of the InlinedLocalFunctionDeclarationInstruction was
not copied. That confuses the information on the exceptional edge
with the information on the normal edge.
^KT-52131 Fixed
> [FE1.0] Fix CFG for inline function calls in finally blocks.

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/AnonymousObjectTransformer.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/InlineCodegen.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/MethodInliner.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/SMAP.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/inlineCodegenUtils.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/optimization/OptimizationMethodVisitor.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/optimization/boxing/StackPeepholeOptimizationsTransformer.kt
- compiler/backend/src/org/jetbrains/kotlin/codegen/optimization/common/FastMethodAnalyzer.kt
- compiler/testData/codegen/bytecodeText/coercionToUnitOptimization/nopInlineFuns.kt
- compiler/testData/codegen/bytecodeText/inline/linenumberForOneParametersArgumentCall.kt
- compiler/testData/debug/stepping/functionCallWithInlinedLambdaParam.kt
- compiler/testData/debug/stepping/inTheEndOfLambdaArgumentOfInlineCall.kt
- compiler/testData/debug/stepping/inlineCallableReference.kt
- compiler/testData/debug/stepping/inlineNamedCallableReference.kt
- compiler/testData/debug/stepping/inlineSimpleCall.kt
- compiler/testData/debug/stepping/lambdaStepInline.kt
- compiler/testData/debug/stepping/lambdaStepInlineWithDefaults.kt
- compiler/testData/debug/stepping/linenumberForOneParametersArgumentCall.kt
- compiler/testData/debug/stepping/nestedInline.kt
- compiler/testData/debug/stepping/noParametersArgumentCallInExpression.kt
- compiler/testData/debug/stepping/simpleSmap.kt
E.g. in `x + f()` where `f` is an inline lambda, the instructions for `+` should have the line number of that expression (while previously they instead had the line number of the last line of the lambda).
Since this generates many more line numbers, nops, and corresponding labels, this PR also includes a memory optimization in FastMethodAnalyzer to avoid constructing Frame objects for such instructions.
The changes in stepping tests are consistent with how non-inline lambdas behave, i.e. "force step into" at the end of a lambda brings you back to the call even if the result is discarded.
Note that although this change adds fake line numbers to single-line inline functions with default lambda arguments, this does not fix KTIJ-21440; apparently, extra support from IntelliJ is required. …
> JVM: restore call site line number after inlining lambdas

- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/FragmentLocalFunctionPatchLowering.kt
Sequence Debugger test suite revealed the need for rewriting calls to local functions in _lambdas_ occuring in the fragment.
> [EE-IR] Minor: run local function patching on all fragment code

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/TailRecursionCallsCollector.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/TailrecLowering.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/ir/builders/IrBuilders.kt
- compiler/ir/backend.jvm/entrypoint/src/org/jetbrains/kotlin/backend/jvm/JvmGeneratorExtensionsImpl.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/FunctionGenerator.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/GeneratorExtensions.kt
This makes the debugger update the values when entering a recursive call, and also uses fewer variable slots.
This may also work on the JS backend, but Native would probably require something else.
^KT-47203 Fixed
> JVM: write back to tailrec function parameters if possible

- compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/KotlinCliJavaFileManagerImpl.kt
- compiler/tests/org/jetbrains/kotlin/cli/JavaSourceInnerClassInClassPathTest.kt
Also when searching for inner classes.
^Fixes KT-51025
> Always take java source before class files.

- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/FragmentLocalFunctionPatchLowering.kt
> [EE-IR] Anticipate fake overrides in fragment lowerings

- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/BinaryOptions.kt
- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/KonanConfig.kt
- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/ObjCExportSuspendFunctionLaunchThreadRestriction.kt
- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/IrToBitcode.kt
- kotlin-native/backend.native/tests/build.gradle
- kotlin-native/backend.native/tests/objcexport/coroutines.swift
- kotlin-native/runtime/src/main/cpp/CompilerConstants.cpp
- kotlin-native/runtime/src/main/cpp/CompilerConstants.hpp
- kotlin-native/runtime/src/main/cpp/ObjCExportCoroutines.mm
This patch adds a binary compiler argument to allow not crashing if a
suspend function is called from a non-Main dispatcher from ObjC or
Swift. This is relevant for people using the new memory model, in which
this restriction may be relaxed.
> KT-51297: Allow suspend from any thread from ObjC

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxInlineCodegenTestGenerated.java
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirLightTreeBlackBoxInlineCodegenTestGenerated.java
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirSerializeCompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/FunctionCodegen.kt
- compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/IrSourceCompilerForInline.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/RecordEnclosingMethodsLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/JvmBackendContext.kt
- compiler/testData/codegen/box/sam/kt52417.kt
- compiler/testData/codegen/boxInline/enclosingInfo/kt52417.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxInlineCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/CompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxInlineCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrCompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrSerializeCompileKotlinAgainstInlineKotlinTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/JvmIrAgainstOldBoxInlineTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/JvmOldAgainstIrBoxInlineTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
This is what Java 15+ does, and it permits accessing captured type parameters via reflection. The alternative is to emit generic signatures on the lambda methods, but that was disabled and I have no clue why.
^KT-52417 Fixed
> JVM_IR: skip SAM lambdas when computing enclosing method of objects

- compiler/backend/src/org/jetbrains/kotlin/codegen/inline/LambdaInfo.kt
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/testData/codegen/box/defaultArguments/kt52702.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/testOld/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
- native/native.tests/tests-gen/org/jetbrains/kotlin/konan/blackboxtest/NativeCodegenBoxTestGenerated.java
> JVM IR: Start fake variables for default lambdas after initialization

- compiler/backend/src/org/jetbrains/kotlin/codegen/coroutines/CoroutineTransformerMethodVisitor.kt
- compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/K2JVMCompilerArguments.kt
- compiler/cli/src/org/jetbrains/kotlin/cli/jvm/jvmArguments.kt
- compiler/config.jvm/src/org/jetbrains/kotlin/config/JVMConfigurationKeys.java
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/CoroutineCodegen.kt
- compiler/testData/cli/jvm/extraHelp.out
- compiler/testData/codegen/box/coroutines/varSpilling/debugMode/backEdge.kt
- compiler/testData/codegen/box/coroutines/varSpilling/debugMode/if.kt
- compiler/testData/codegen/box/coroutines/varSpilling/debugMode/nullCleanup.kt
- compiler/testData/codegen/box/coroutines/varSpilling/debugMode/nullNotSpill.kt
- compiler/testData/codegen/box/coroutines/varSpilling/debugMode/simple.kt
- compiler/testData/codegen/box/coroutines/varSpilling/debugMode/twoRefs.kt
- compiler/testData/codegen/box/coroutines/varSpilling/debugMode/unusedParamNotSpill.kt
- compiler/testData/codegen/box/coroutines/varSpilling/debugMode/when.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests/org/jetbrains/kotlin/test/directives/JvmEnvironmentConfigurationDirectives.kt
- compiler/tests-common-new/tests/org/jetbrains/kotlin/test/runners/codegen/AbstractJvmBlackBoxCodegenTestBase.kt
- compiler/tests-common-new/tests/org/jetbrains/kotlin/test/services/configuration/JvmEnvironmentConfigurator.kt
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/testOld/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
- native/native.tests/tests-gen/org/jetbrains/kotlin/konan/blackboxtest/NativeCodegenBoxTestGenerated.java
This commit adds a new key that will allow users to enhance their
debugging experience in suspending contexts when using the IR backend.
After the key is enabled, the following things are changed:
1. All variables in a suspending context are spilled regardless their
liveness.
2. Their LVT records are not shrunk.
3. ACONST_NULL is not spilled to dead variables.
I would be very thankful if you told me how it would be best to cover this key with tests.
The drawback of the current implementation is that `shouldOptimiseUnusedVariables` affects three different places in `CoroutineTransformerMethodVisitor` as described above. They may seem random at a first glance, however I thought that it is better than if I refactored a large amount of a very important code.
I also consciously named the key …
> Add a key to enable spilling of all variables in a suspending context

- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/JvmLower.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/ReflectiveAccess.kt
Title says it all.
ReflectAccessLowering was making incorrect assumptions on the shape of the IR due to running _before_ lowering of calls with "unsaturated" default arguments.
Moving the lowerings later in the sequence resolves this.
Resolves KTIJ-21963. Tests in [intellij-community#2046](https://github.com/JetBrains/intellij-community/pull/2046)
> [KTIJ-21963] Move reflective access after default args lowerings

- libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/targets/js/npm/resolver/KotlinRootNpmResolverStateHolder.kt
make `state` in `KotlinRootNpmResolverStateHolder` public so I can manually try and work around this annoying bug and set the state manually
https://youtrack.jetbrains.com/issue/KT-52647
> KT-52647 make `state` in `KotlinRootNpmResolverStateHolder` public

- compiler/testData/diagnostics/nativeTests/objCName.kt
- compiler/testData/diagnostics/nativeTests/objCName.txt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/DiagnosticsNativeTestGenerated.java
- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/KonanFqNames.kt
- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExportHeaderGenerator.kt
- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExportNamer.kt
- kotlin-native/backend.native/tests/objcexport/expectedLazy.h
- kotlin-native/backend.native/tests/objcexport/expectedLazyLegacySuspendUnit.h
- kotlin-native/backend.native/tests/objcexport/expectedLazyNoGenerics.h
- kotlin-native/backend.native/tests/objcexport/objCName.swift
- kotlin-native/backend.native/tests/objcexport/objCNameA.kt
- kotlin-native/backend.native/tests/objcexport/objCNameB.kt
- kotlin-native/runtime/src/main/kotlin/kotlin/native/Annotations.kt
- libraries/stdlib/api/js-v1/kotlin.experimental.kt
- libraries/stdlib/api/js/kotlin.experimental.kt
- libraries/stdlib/src/kotlin/annotations/NativeAnnotations.kt
- libraries/stdlib/src/kotlin/experimental/ExperimentalObjCName.kt
- libraries/tools/binary-compatibility-validator/reference-public-api/kotlin-stdlib-runtime-merged.txt
- native/frontend/src/org/jetbrains/kotlin/resolve/konan/diagnostics/DefaultErrorMessagesNative.kt
- native/frontend/src/org/jetbrains/kotlin/resolve/konan/diagnostics/ErrorsNative.kt
- native/frontend/src/org/jetbrains/kotlin/resolve/konan/diagnostics/NativeObjCNameChecker.kt
- native/frontend/src/org/jetbrains/kotlin/resolve/konan/platform/NativePlatformConfigurator.kt
Relates to [KT-42297](https://youtrack.jetbrains.com/issue/KT-42297), [KT-50767](https://youtrack.jetbrains.com/issue/KT-50767), [KT-48076](https://youtrack.jetbrains.com/issue/KT-48076), [KT-48072](https://youtrack.jetbrains.com/issue/KT-48072), [KT-43087](https://youtrack.jetbrains.com/issue/KT-43087) and [KT-40796](https://youtrack.jetbrains.com/issue/KT-40796).
```kotlin
@ObjCName(swiftName = "MySwiftArray")
class MyKotlinArray {
@ObjCName(swiftName = "index")
fun indexOf(@ObjCName(swiftName = "of") element: String): Int = TODO()
}
```
```swift
// Current usage without the ObjCName annotations
let array = MyKotlinArray()
let index = array.indexOf(element: "element")
// Usage with the ObjCName annotations
let array = MySwiftArray()
let index = array.index(of: "element")
```
The …
> ObjCName annotation

- compiler/backend.common.jvm/src/org/jetbrains/kotlin/resolve/jvm/AsmTypes.java
https://youtrack.jetbrains.com/issue/KT-48822
We catch a flaky build crash with the following stacktrace:
```
Caused by: java.util.ConcurrentModificationException
at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
at org.jetbrains.kotlin.resolve.jvm.AsmTypes.getType(AsmTypes.java:133)
at org.jetbrains.kotlin.codegen.AsmUtil.wrapJavaClassesIntoKClasses(AsmUtil.java:443)
```
Presumably, AsmTypes#getType() could be called from multiple threads during build process, which causes CME sometimes.
Can't reproduce steps to get a crash, that might be a hint to concurrent nature of problem as well.
Solution: make TYPES_MAP modification safe.
> KT-48822: Fixes ConcurrentModificationException in AsmTypes

- compiler/fir/checkers/checkers-component-generator/src/org/jetbrains/kotlin/fir/checkers/generator/diagnostics/FirNativeDiagnosticsList.kt
- compiler/fir/checkers/checkers.native/gen/org/jetbrains/kotlin/fir/analysis/diagnostics/native/FirNativeErrors.kt
- compiler/fir/checkers/checkers.native/src/org/jetbrains/kotlin/fir/analysis/diagnostics/native/FirNativeErrorsDefaultMessages.kt
- compiler/fir/checkers/checkers.native/src/org/jetbrains/kotlin/fir/analysis/native/checkers/FirNativeObjCNameChecker.kt
- compiler/testData/diagnostics/nativeTests/objCName.fir.kt
- compiler/testData/diagnostics/nativeTests/objCName.kt
- compiler/testData/diagnostics/nativeTests/objCName.txt
- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/objcexport/ObjCExportNamer.kt
- native/frontend/src/org/jetbrains/kotlin/resolve/konan/diagnostics/DefaultErrorMessagesNative.kt
- native/frontend/src/org/jetbrains/kotlin/resolve/konan/diagnostics/ErrorsNative.kt
- native/frontend/src/org/jetbrains/kotlin/resolve/konan/diagnostics/NativeObjCNameChecker.kt
Empty names aren't handled correctly in the ObjC export and should be prohibited (for now).
cc @SvyatoslavScherbina
> [K/N] Prohibit empty ObjCNames

- libraries/stdlib/jvm/src/kotlin/reflect/TypesJVM.kt
The correct return type of getAnnotatedBounds is Array\<AnnotatedType\>. This fact causes some problems now that kotlin-stdlib is targeting JDK 1.8:
* the compiler generates a bridge to the incorrect "override" that attempts to cast an empty Array\<Annotation\> into the correct type, which fails because those two types are unrelated;
* on Android, touching this method in any way (via reflection) on any API version causes a ClassNotFoundException;
* tools that validate references in libraries when compiling for Android complain about the bridge because they know the returned type does not exist.
The easiest solution is to simply remove the override and leave getAnnotatedBounds unimplemented, making it throw AbstractMethodError when called. This is the behavior it previously had anyway, as …
> Remove incorrect override in TypeVariableImpl

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/SuspendLambdaLowering.kt
- compiler/testData/codegen/box/annotations/annotatedLambda/lambda.kt
- compiler/testData/codegen/box/annotations/annotatedLambda/suspendLambda.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
For non-suspend lambdas annotations are carried over to the
invoke method so that tooling can find the annotation there.
It seems reasonable that annotations are carried over to
the invoke methods on suspend lambdas as well so that similar
tooling can be built and work for suspend lambdas.
> Add suspend lambda annotations to invokeSuspend.

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/lower/SingleAbstractMethodLowering.kt
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/JvmSingleAbstractMethodLowering.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/ir/JvmIrCoroutineUtils.kt
- compiler/testData/codegen/box/coroutines/featureIntersection/funInterface/kt50950.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/testOld/wasm/semantics/IrCodegenBoxWasmTestGenerated.java
- native/native.tests/tests-gen/org/jetbrains/kotlin/konan/blackboxtest/NativeCodegenBoxTestGenerated.java
If the super class is in a file that has already been lowered, the base method has an extra continuation parameter which breaks things.
Also, SAM wrappers around functional objects are tail-call and do not need continuations ever, so don't even try.
^KT-50950 Fixed
> JVM_IR: unwrap suspend views when generating SAM wrappers

- core/builtins/native/kotlin/Primitives.kt
- generators/builtins/primitives.kt
- generators/builtins/unsignedTypes.kt
- libraries/stdlib/src/kotlin/util/FloorDivMod.kt
- libraries/stdlib/unsigned/src/kotlin/UByte.kt
- libraries/stdlib/unsigned/src/kotlin/UInt.kt
- libraries/stdlib/unsigned/src/kotlin/ULong.kt
- libraries/stdlib/unsigned/src/kotlin/UShort.kt
When reading the [current docs for `mod`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/mod.html), I had to think about "now, which of the two operands is actually called _divisor_", as that term is just used in the second sentence, not in the first one.
> Calculates the remainder of flooring division of this value by the other value.
> 
> The result is either zero or has the same sign as the _divisor_ and has the absolute value less than the absolute value of the divisor.
Now the first sentence includes "(dividend)" and "(divisor)", which makes it clear also for "mathematically challenged people" like me (or rather, people who don't have the English vocabulary for these terms at hand). The same change is done for `rem`.
For consistency, the same change is also done for the signed …
> docs: mod/rem: clarify who is dividend and divisor

- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/CheckIrElementVisitor.kt
- compiler/ir/backend.common/src/org/jetbrains/kotlin/backend/common/phaser/DumperVerifier.kt
- compiler/ir/backend.jvm/entrypoint/src/org/jetbrains/kotlin/backend/jvm/JvmIrCodegenFactory.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/intermediate/PropertyLValue.kt
- compiler/tests-common-new/tests/org/jetbrains/kotlin/test/services/CompilerConfigurationProvider.kt
This PR contains a number of small fixes for invalid IR coming from Psi2Ir.
The background is that I ran into issues with invalid IR (specifically unbound symbols, see 06270dbe2ad4fae95882b24815fdd285ed57959b) in the Compose plugin. After fixing this problem I tried to turn on IR validation and unbound symbol checking in Psi2Ir. I found a couple of smaller issues which are also fixed in this PR, but didn't manage to turn on IR validation by default because of the following issues.
- [KT-54208](https://youtrack.jetbrains.com/issue/KT-54208/Missing-errors-for-unimplemented-interface-delegation-members): This is really a missing frontend error which results in invalid IR. This was apparently already well-known and had been filed as [KT-46120](https://youtrack.jetbrains.com/issue/KT-46120/AME- …
> Psi2Ir: Fix unbound symbols and IrValidation issues

- libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinTargetConfigurator.kt
Gradle's `ArtifactAttributes` class is an internal class which contains only a single field that is [deprecated for removal](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/artifacts/ArtifactAttributes.java).
That single field references the part of the public API that should be referenced directly.  This PR makes that change.
Fixes [#KT-54447](https://youtrack.jetbrains.com/issue/KT-54447/Remove-usage-of-deprecated-internal-Gradle-field-in-Kotlin-Gradle-Plugin-replace-with-equivalent-in-public-API)
> Remove usage of deprecated Gradle field, replace with equivalent

- kotlin-native/Interop/Indexer/src/main/kotlin/org/jetbrains/kotlin/native/interop/indexer/NativeIndex.kt
- kotlin-native/Interop/StubGenerator/src/main/kotlin/org/jetbrains/kotlin/native/interop/gen/jvm/main.kt
- kotlin-native/shared/src/main/kotlin/org/jetbrains/kotlin/konan/exec/ExecuteCommand.kt
Pass in temp-file C sources to clang via stdin instead of by name. This prevents absolute paths of temp files from being encoded in bitcode.
Tested manually via the following on macOS:
```bash
$ kotlin-native/dist/bin/cinterop -def kotlin-native/platformLibs/src/platform/osx/posix.def -o /tmp/a/posix.klib
$ kotlin-native/dist/bin/cinterop -def kotlin-native/platformLibs/src/platform/osx/posix.def -o /tmp/b/posix.klib
$ shasum /tmp/a/posix.klib /tmp/b/posix.klib
c3ae6962ffc0b52d2191eaa02dfd0b94176f98c0  /tmp/a/posix.klib
c3ae6962ffc0b52d2191eaa02dfd0b94176f98c0  /tmp/b/posix.klib
```
> [KT-54284][Native] Produce deterministic klibs from cinterop.

- compiler/backend/src/org/jetbrains/kotlin/codegen/optimization/RedundantCheckCastElimination.kt
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/testData/codegen/box/casts/kt53146.kt
- compiler/testData/codegen/box/casts/kt54581.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
These should only have ever been necessary for field type inference in coroutines, which should have been fixed by 0fc676a20c.
Unlike 903a5d69a4, this time the change is in an optimization pass. Advantage: optimization passes have a closer to the JVM view of the bytecode, which makes this change significantly more likely to be correct. Disadvantage: technically we don't really guarantee optimization passes other than FixStack will run at all. For KT-54581 this is 100% fine since the problem itself is caused by redundant checkcast elimination in the first place (otherwise there would've been a redundant cast to String), but for KT-53146 this means the fix is somewhat incidental and not necessarily guaranteed.
^KT-53146 Fixed
^KT-54581 Fixed
> JVM: consider casts of null to be redundant

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/SyntheticAccessorLowering.kt
- compiler/testData/codegen/box/inlineClasses/kt54656.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
Please correct me if I'm wrong:
In `syntheticAccessorLoweringPhase`, '`hidden constructor`' looks like a concept related to some kind of `sealed classes` & `annotation classes`. A constructor from `Java` doesn't look like one of them and should not add a `constructor marker` argument to its accessor.
Fix [KT-54656](https://youtrack.jetbrains.com/issue/KT-54656/NoSuchMethodError-on-invoking-Java-constructor-which-takes-an-inline-value-class-as-a-parameter)
> JVM_IR: Don't treat java constructor as 'hidden' one in syntheticAccessorLoweringPhase

- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/MoveCompanionObjectFieldsLowering.kt
- compiler/testData/codegen/bytecodeListing/deprecatedConstantPropertyInterfaceCompanion.kt
- compiler/testData/codegen/bytecodeListing/deprecatedConstantPropertyInterfaceCompanion.txt
- compiler/testData/codegen/bytecodeListing/deprecatedConstantPropertyInterfaceCompanion_ir.txt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BytecodeListingTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBytecodeListingTestGenerated.java
Create the field directly and maintain the fact that its corresponding property is the companion object property. That property has the deprecated annotation which puts the deprecated marker on the field when code generating the field.
^KT-54840 Fixed
> [JVM] Retain deprecated status for interface companion const property.

- compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/diagnostics/FirErrorsDefaultMessages.kt
Otherwise it's really not clear what exactly the type is supposed to be.
> FIR: render entire declaration header in *_MISMATCH_ON_OVERRIDE

- core/reflection.jvm/src/kotlin/reflect/jvm/internal/KCallableImpl.kt
Performance improvements have been made to `KCallableImpl.callDefaultMethod` (`KFunction.callBy`).
`KFunction.callBy` is almost always used when function calls are made using `kotlin-reflect`.
Improving this performance will improve the performance of the entire library that depends on `kotlin-reflect`.
The contents of the array used for reflection calls are definitive for the target function.
On the other hand, the current implementation manages arguments dynamically.
In this PR, I have improved performance by caching as much of the processing as possible on the first run, and also by dropping the use of `ArrayList`.
I have created a simple benchmark project to compare 1.7.0-RC with this change.
The content compares the calling process for functions with 0, 1, 5, and 20 arguments, using …
> Performance improvement of KFunction.callBy

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/indy/LambdaMetafactoryArguments.kt
- compiler/testData/codegen/box/extensionFunctions/contextReceivers/contextAndExtensionLambdaIndy.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
KT-53957 Fixed
KT-52874 likely fixed
Parameters were ordered incorrectly: [extension receiver, context receivers, regular parameters] instead of [context receivers, extension receiver, regular parameters].
Wouldn't it be reasonable to have a separate list of context parameters (instead of `contextReceiverParametersCount`), the same as `extensionReceiverParameter` is separate in IR?
> Fix indy lambdas with extension and context receivers

- plugins/kapt3/kapt3-compiler/src/org/jetbrains/kotlin/kapt3/stubs/ClassFileToSourceStubConverter.kt
- plugins/kapt3/kapt3-compiler/testData/converter/errorExtensionReceiver.kt
- plugins/kapt3/kapt3-compiler/testData/converter/errorExtensionReceiver.txt
- plugins/kapt3/kapt3-compiler/tests-gen/org/jetbrains/kotlin/kapt3/test/runners/ClassFileToSourceStubConverterTestGenerated.java
- plugins/kapt3/kapt3-compiler/tests-gen/org/jetbrains/kotlin/kapt3/test/runners/IrClassFileToSourceStubConverterTestGenerated.java
When using correct error types and there is a property setter or
receiver for an unknown type then the parameter type would be `Object` instead
of the error type.
This fixes [KT-46965](https://youtrack.jetbrains.com/issue/KT-46965/Kapt-correctErrorTypes-custom-setter-gets-Object-parameter-type) and [KT-46966](https://youtrack.jetbrains.com/issue/KT-46966/Kapt-correctErrorTypes-receiver-type-is-NonExistentClass).
> KAPT: Fix error types for receivers and property setters in stubs

- core/descriptors/src/org/jetbrains/kotlin/types/TypeSubstitution.kt
- core/descriptors/src/org/jetbrains/kotlin/types/error/ErrorType.kt
- plugins/kapt3/kapt3-compiler/testData/converter/kt43786.kt
- plugins/kapt3/kapt3-compiler/testData/converter/kt43786.txt
- plugins/kapt3/kapt3-compiler/tests-gen/org/jetbrains/kotlin/kapt3/test/runners/ClassFileToSourceStubConverterTestGenerated.java
- plugins/kapt3/kapt3-compiler/tests-gen/org/jetbrains/kotlin/kapt3/test/runners/IrClassFileToSourceStubConverterTestGenerated.java
Error types that are generic could sometimes throw an ISE when generating the stub.
This fixes [KT-43786](https://youtrack.jetbrains.com/issue/KT-43786/KAPT-IllegalStateException-SimpleTypeImpl-should-not-be-created-for-error-type-ErrorScope).
> KAPT: Fix an ISE when processing unresolved generic types

- compiler/backend.common.jvm/src/org/jetbrains/kotlin/types/AbstractTypeMapper.kt
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBytecodeTextTestGenerated.java
- compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/ClassCodegen.kt
- compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/JvmSignatureClashDetector.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/mapping/IrTypeMapper.kt
- compiler/ir/backend.jvm/src/org/jetbrains/kotlin/backend/jvm/mapping/MethodSignatureMapper.kt
- compiler/testData/codegen/bytecodeText/innerClasses/kt56104.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBytecodeTextTestGenerated.java
Inner class attributes should only be recorded for types that are materialized in the result class file. In particular, we should not emit inner classes attributes for types that appear only in fake overrides. We do map these types to track the fake overrides for JVM signature clashes but they are not materialized in the class file.
^KT-56104 Fixed
> [JVM_IR] Limit inner class attributes to types in class file

- kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/ObjCExportUtils.kt
This communicates to runtime tests that calls to `get` are O(1).
> Implement `RandomAccess` on NS(Mutable)Array bridges

- libraries/tools/kotlin-gradle-plugin-api/api/kotlin-gradle-plugin-api.api
- libraries/tools/kotlin-gradle-plugin-api/src/common/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinTargetHierarchyBuilder.kt
- libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/targetHierarchy/buildKotlinTargetHierarchy.kt
- libraries/tools/kotlin-gradle-plugin/src/functionalTest/kotlin/org/jetbrains/kotlin/gradle/unitTests/KotlinTargetHierarchyDslTest.kt
Kotlin 1.8.20-Beta introduced experimental WASM support, though it was missed in introduced in the same version experimental `KotlinTargetHierarchy*` API
> Support WASM in KotlinTargetHierarchyBuilder

- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/JvmLateinitLowering.kt
I recently saw that IR elements' members were generally all made mutable. This is my experiment inspired by that change.
This PR  simply makes so that IrVariable's are modified in place instead of doung a replacement mapping with new objects.
Tests run: `:compiler:tests-common-new:test --tests "org.jetbrains.kotlin.test.runners.codegen.IrBlackBoxCodegenTestGenerated"`
> Simplify and optimize JvmLateinitLowering - make use of now mutable members

- compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/ExpressionCodegen.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ArgumentsGenerationUtils.kt
- compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ClassGenerator.kt
- compiler/ir/ir.tree/gen/org/jetbrains/kotlin/ir/expressions/IrMemberAccessExpression.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/IrExpressions.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/IrMemberAccessExpression.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/impl/IrCallImpl.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/impl/IrConstructorCallImpl.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/impl/IrDelegatingConstructorCallImpl.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/impl/IrEnumConstructorCallImpl.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/impl/IrFunctionReferenceImpl.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/impl/IrLocalDelegatedPropertyReferenceImpl.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/expressions/impl/IrPropertyReferenceImpl.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DataClassMembersGenerator.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/IrUtils.kt
- compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/transform.kt
- compiler/ir/ir.tree/tree-generator/src/org/jetbrains/kotlin/ir/generator/IrTree.kt
- compiler/ir/ir.tree/tree-generator/src/org/jetbrains/kotlin/ir/generator/config/ConfigModel.kt
- compiler/ir/ir.tree/tree-generator/src/org/jetbrains/kotlin/ir/generator/model/Transformations.kt
- compiler/ir/ir.tree/tree-generator/src/org/jetbrains/kotlin/ir/generator/print/Elements.kt
- kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/llvm/IntrinsicGenerator.kt
This PR completes #4560 by generating the last left over element class. That fix allows further bulk operations and experiments involving the whole tree.
Most significantly the `valueArguments` and `typeArguments` lists were converted from arrays to (preallocated) MutableLists.
One outcome is that it's now possible to work with them like with regular lists instead of throught the `getValueArgument`/`putTypeArgument` methods. OOTH the everything  still uses the latter. But it should be possible to inline those methods with a refactoring action for the whole codebase if that's desired.
The other thing is possible performance regression.I have not run any benchamrk but I'm keen on seeing its results.
> Autogenerate IrMemberAccessExpression

- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirLightTreeBlackBoxCodegenTestGenerated.java
- compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirPsiBlackBoxCodegenTestGenerated.java
- compiler/ir/backend.jvm/lower/src/org/jetbrains/kotlin/backend/jvm/lower/StaticInitializersLowering.kt
- compiler/testData/codegen/box/enum/enumEntriesInCompanion.kt
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/BlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenTestGenerated.java
- compiler/tests-common-new/tests-gen/org/jetbrains/kotlin/test/runners/codegen/IrBlackBoxCodegenWithIrInlinerTestGenerated.java
- compiler/tests-gen/org/jetbrains/kotlin/codegen/LightAnalysisModeTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/JsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/fir/FirJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/IrJsCodegenBoxTestGenerated.java
- js/js.tests/tests-gen/org/jetbrains/kotlin/js/test/ir/IrJsES6CodegenBoxTestGenerated.java
- native/native.tests/tests-gen/org/jetbrains/kotlin/konan/blackboxtest/FirNativeCodegenBoxTestGenerated.java
- native/native.tests/tests-gen/org/jetbrains/kotlin/konan/blackboxtest/FirNativeCodegenBoxTestNoPLGenerated.java
- native/native.tests/tests-gen/org/jetbrains/kotlin/konan/blackboxtest/NativeCodegenBoxTestGenerated.java
- native/native.tests/tests-gen/org/jetbrains/kotlin/konan/blackboxtest/NativeCodegenBoxTestNoPLGenerated.java
- wasm/wasm.tests/tests-gen/org/jetbrains/kotlin/wasm/test/IrCodegenBoxWasmTestGenerated.java
In function `<clinit>` , the `$ENTRIES` field should be initialized before it is
used. To ensure this, we insert declarations that generated in enum class
lowering phase to the start of the class.
Fix: [KT-57784](https://youtrack.jetbrains.com/issue/KT-57784)
> JVM: Fix enum entries glitch

- core/descriptors.jvm/src/org/jetbrains/kotlin/load/kotlin/header/ReadKotlinClassHeaderAnnotationVisitor.java
This solves an issue I reported myself: https://youtrack.jetbrains.com/issue/KT-52071
Some environments still use the Java Security Manager (despite its impending deprecation). They're also likely to block reading unknown system variables.
If Kotlin isn't widely used in an organization, then reading `kotlin.ignore.old.metadata` will trigger an `AccessControlException`. In that case, the code should continue as if the variable is unset, not crash.
I've tested this change manually in my own environment, which has a Security Manager that blocks reading system variables.
> KT-52071 Fallback if Security Manager blocks reading system properties

- compiler/ir/backend.wasm/src/org/jetbrains/kotlin/backend/wasm/lower/InvokeOnExportedFunctionExitLowering.kt
- compiler/ir/backend.wasm/src/org/jetbrains/kotlin/backend/wasm/lower/UnhandledExceptionLowering.kt
This fixes a wrong return type (`Boolean`) of some setter functions, currently returning `Unit`.
This issue doesn't affect the code directly because of the `propertyAccessorInlinerLoweringPhase` optimization, which inlines setters and getters, essentially hiding the bug.
Without `propertyAccessorInlinerLoweringPhase`, the resulting Wasm code will not compile because of an illegal cast.
Here is the erroneous Wasm code that will be produced without `propertyAccessorInlinerLoweringPhase`:
```
i32.const 1
call $kotlin.wasm.internal.<set-isNotFirstWasmExportCall>___fun_1534
global.get $kotlin.Unit_instance___g_513
ref.cast $kotlin.Boolean___type_432  ;; <------------  Illegal cast here
struct.get_s $kotlin.Boolean___type_432 4
drop
``` …
> [KT-69003] Correct the return type of setters from `Boolean` to their return type (`Unit`)

- js/ReadMe.md
Fix the link of ReadMe.md for Kotlin Standard Library for JavaScript
> Fix the link of ReadMe.md for Kotlin Standard Library for JavaScript

- compiler/cli/cli-js/src/org/jetbrains/kotlin/cli/js/K2JSCompiler.kt
- compiler/cli/src/org/jetbrains/kotlin/cli/common/CLICompiler.kt
- compiler/cli/src/org/jetbrains/kotlin/cli/jvm/K2JVMCompiler.kt
- compiler/cli/src/org/jetbrains/kotlin/cli/jvm/plugins/PluginCliParser.kt
- compiler/cli/src/org/jetbrains/kotlin/cli/metadata/KotlinMetadataCompiler.kt
- compiler/test-infrastructure-utils/tests/org/jetbrains/kotlin/script/scriptTestUtil.kt
Closes `URLClassLoader` objects upon compilation completion.
See: https://youtrack.jetbrains.com/issue/KT-72172/File-Leak-occurring-in-Kotlin-Daemon
> KT-72172 Dispose URLClassLoader after compilation

- compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/CompileEnvironmentUtil.java
The JAR format has a lot of single int writes. Without buffering, these are very inefficient.
Closes https://youtrack.jetbrains.com/issue/KT-73922
> Buffer CompileEnvironmentUtil.writeToJar
